/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_1_1");
    record0.set("content_body", "Leveraged Lease Mechanics\n\nLeveraged leases represent one of the most sophisticated financing structures in modern leasing. This lesson explores the intricate mechanics of leveraged leases, focusing on the roles of debt providers and equity participants.\n\nDebt Provider vs Equity Participant Roles:\n- Debt providers (lenders) provide non-recourse financing, typically 60-80% of the equipment cost\n- Equity participants (lessors) invest the remaining 20-40% and bear residual value risk\n- Debt providers have priority claim on lease payments; equity participants receive residual cash flows\n- Non-recourse debt means lenders have no claim on lessor's other assets\n\nNon-Recourse Debt Structures:\n- Equipment serves as sole collateral for debt\n- Debt is secured by lease payments and residual value\n- Lenders rely on credit quality of lessee and equipment value\n- Debt-to-equity ratios typically range from 2:1 to 4:1\n- Debt tranches may include senior and subordinated layers\n\nTranche Payment Design:\n- Senior debt receives priority in lease payment allocation\n- Subordinated debt receives payments after senior debt service\n- Equity participants receive residual cash flows after all debt service\n- Waterfall structures ensure predictable payment hierarchy\n- Balloon payments at lease end tied to residual value realization\n\nKey Financial Metrics:\n- Lessor IRR: typically 8-12% after-tax\n- Lessee effective rate: typically 2-4% below unsecured borrowing\n- Debt service coverage ratio (DSCR): typically 1.2x to 1.5x\n- Loan-to-value (LTV): typically 70-85%\n\nTax Considerations:\n- Lessor claims depreciation deductions\n- Investment tax credits (if applicable) flow to lessor\n- Lessee deducts lease payments as operating expense\n- Proper structuring ensures lessor retains tax ownership");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_1_2");
    record1.set("content_body", "Synthetic Leases\n\nSynthetic leases (also called tax leases or off-balance-sheet leases) represent a unique hybrid structure combining tax and accounting treatment.\n\nTax Ownership vs Operating Lease Treatment:\n- For tax purposes: Lessor is treated as owner, claims depreciation and tax credits\n- For accounting purposes: Lessee treats as operating lease (off-balance-sheet)\n- This dual treatment creates significant value for both parties\n- Requires careful structuring to satisfy IRS safe harbor rules\n\nOff-Balance-Sheet Benefits:\n- Lessee avoids balance sheet liability recognition\n- Improves debt-to-equity ratios and financial metrics\n- Enhances return on assets (ROA) and return on equity (ROE)\n- Provides accounting flexibility for financial reporting\n- Particularly valuable for capital-intensive industries\n\nStructuring Requirements:\n- Lease term typically 75-90% of asset useful life\n- Lessee has option to purchase at fair market value at lease end\n- Lessee bears residual value risk through purchase option\n- Lessor retains tax ownership and depreciation benefits\n- Proper documentation essential for IRS compliance\n\nRisk Allocation:\n- Lessor assumes credit risk of lessee\n- Lessee assumes residual value risk\n- Lessor retains tax benefits\n- Both parties benefit from lower overall financing costs\n\nAccounting Implications (Pre-IFRS 16/ASC 842):\n- Operating lease treatment for lessee\n- Lease payments expensed as incurred\n- No balance sheet liability or right-of-use asset\n- Footnote disclosure of future lease obligations\n\nPost-IFRS 16/ASC 842 Considerations:\n- Modern standards require right-of-use asset recognition\n- Synthetic lease benefits reduced under new standards\n- Structuring focus shifted to true operating leases\n- Short-term and low-value lease exemptions remain valuable");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_1_3");
    record2.set("content_body", "Sale and Leaseback (Advanced)\n\nAdvanced sale-and-leaseback transactions represent sophisticated refinancing and capital optimization strategies.\n\nAsset Liquidity Considerations:\n- Sale-and-leaseback converts fixed assets into liquid capital\n- Enables companies to unlock equity trapped in owned assets\n- Provides immediate cash for operations or strategic investments\n- Maintains operational control through lease arrangement\n\nFair Market Value (FMV) Appraisals:\n- Independent appraisals essential for transaction credibility\n- FMV determination affects lease pricing and residual value\n- Appraisals must comply with USPAP (Uniform Standards of Professional Appraisal Practice)\n- Multiple valuation approaches: cost, market, income\n- Appraisal quality impacts lender confidence and financing terms\n\nAdvanced Structuring Techniques:\n- Partial sale-and-leaseback (sale of portion of asset)\n- Leveraged sale-and-leaseback (debt financing of purchase)\n- Cross-border sale-and-leaseback (tax optimization)\n- Sale-leaseback-buyback structures (flexibility)\n\nFinancial Engineering:\n- Lease pricing based on FMV and market conditions\n- Residual value guarantees or purchase options\n- Floating rate structures tied to market indices\n- Escalation clauses for inflation protection\n\nAccounting Treatment:\n- Gain on sale recognition (subject to IFRS 16/ASC 842 rules)\n- Right-of-use asset and lease liability recognition\n- Deferred gain amortization over lease term\n- Disclosure of sale-leaseback transactions\n\nRisk Management:\n- Residual value risk allocation between parties\n- Maintenance and insurance obligations\n- Default and remedies provisions\n- Renewal and extension options\n\nTax Optimization:\n- Timing of gain recognition\n- Depreciation deduction strategies\n- Interest deduction optimization\n- State and local tax considerations");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "lesson_2_1");
    record3.set("content_body", "Jurisdictional Optimization\n\nCross-border lease structuring requires sophisticated understanding of multiple jurisdictions and tax regimes.\n\nSpecial Purpose Vehicles (SPVs):\n- SPVs isolate credit risk and tax exposure\n- Typically incorporated in lessor's home jurisdiction\n- May include intermediate SPVs in treaty jurisdictions\n- Ownership structure optimizes tax efficiency\n- Bankruptcy remoteness protects lenders and equity investors\n\nSPV Jurisdiction Selection:\n- Lessor's home country (simplicity, tax benefits)\n- Treaty jurisdiction (tax treaty benefits)\n- Neutral jurisdiction (Ireland, Luxembourg, Netherlands)\n- Considerations: tax treaties, withholding taxes, regulatory environment\n\nDouble Taxation Treaties (DTTs):\n- Bilateral agreements between countries to prevent double taxation\n- Typically reduce withholding tax rates on lease payments\n- May provide tax credits for foreign taxes paid\n- Treaty benefits require proper documentation and substance\n- Over 3,000 bilateral treaties worldwide\n\nTreaty Benefits Optimization:\n- Proper SPV jurisdiction selection to access treaty benefits\n- Documentation of treaty eligibility and substance requirements\n- Principal purpose test (PPT) compliance under BEPS\n- Beneficial ownership documentation\n\nStructuring Considerations:\n- Lessor SPV in treaty jurisdiction\n- Lessee in another jurisdiction\n- Lease payments subject to reduced withholding taxes\n- Residual value payments optimized\n- Currency and payment timing optimization\n\nCompliance and Documentation:\n- Tax residency certificates\n- Beneficial ownership declarations\n- Treaty eligibility documentation\n- Transfer pricing documentation\n- Substance requirements (management, employees, assets)\n\nRisk Mitigation:\n- Treaty abuse prevention (BEPS Action 6)\n- Principal purpose test compliance\n- Substance-over-form analysis\n- Regular compliance reviews\n- Professional tax advice essential");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "lesson_2_2");
    record4.set("content_body", "Withholding Taxes & VAT\n\nWithholding taxes and value-added taxes represent significant costs in cross-border leasing that require careful management.\n\nWithholding Tax Mechanics:\n- Withholding taxes imposed on lease payments by lessee's jurisdiction\n- Typical rates: 10-30% depending on treaty and jurisdiction\n- Lessee required to withhold and remit to tax authorities\n- Lessor receives net payment after withholding\n- Treaty benefits can reduce or eliminate withholding\n\nGross-Up Clauses:\n- Lessor compensated for withholding taxes through gross-up\n- Lessee pays additional amount to cover withholding\n- Formula: Gross-up = Withholding Tax / (1 - Withholding Rate)\n- Protects lessor's after-tax return\n- Increases lessee's effective lease cost\n\nWithholding Tax Optimization:\n- Treaty jurisdiction selection to minimize withholding\n- Proper documentation of treaty eligibility\n- Timing of payments to optimize withholding\n- Currency selection considerations\n- Coordination with other tax planning strategies\n\nVAT/GST Considerations:\n- VAT/GST typically applies to lease payments\n- Rates vary by jurisdiction: 15-27% typical range\n- Input VAT recovery available in many jurisdictions\n- Cross-border VAT treatment varies\n- Place of supply rules determine VAT jurisdiction\n\nVAT/GST Recovery Strategies:\n- Lessee VAT recovery on lease payments (if eligible)\n- Lessor VAT on equipment acquisition\n- Input tax credit optimization\n- Reverse charge mechanisms\n- VAT-exempt vs taxable treatment analysis\n\nCross-Border VAT Planning:\n- Place of supply determination (lessor or lessee location)\n- Intra-EU VAT rules (if applicable)\n- Third-country VAT treatment\n- Documentation requirements for VAT recovery\n- Compliance with MOSS (Mini One-Stop Shop) if applicable\n\nIntegrated Tax Planning:\n- Withholding tax and VAT coordination\n- Overall effective tax rate optimization\n- Lease pricing adjustments for tax costs\n- Sensitivity analysis for tax rate changes\n- Contingency planning for tax law changes");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "lesson_2_3");
    record5.set("content_body", "Currency & Hedging\n\nCurrency risk management is critical in cross-border leases where payments occur in multiple currencies.\n\nFX Risk Identification:\n- Transaction risk: Exposure on lease payment amounts\n- Translation risk: Exposure on consolidated financial statements\n- Economic risk: Long-term exposure to currency movements\n- Timing risk: Uncertainty in payment dates and amounts\n\nCurrency Exposure in Leases:\n- Lessor exposure: Receives payments in lessee's currency\n- Lessee exposure: Pays in lessor's currency\n- Equipment cost: May be in third currency\n- Residual value: Realized in equipment location currency\n- Financing costs: May be in lessor's home currency\n\nHedging Instruments:\n- Forward contracts: Lock in exchange rate for future date\n- Currency swaps: Exchange principal and interest in different currencies\n- Currency options: Right to exchange at specified rate\n- Money market hedges: Borrow/lend in foreign currency\n- Natural hedges: Match currency inflows and outflows\n\nForward Contract Mechanics:\n- Lessor enters forward contract to sell foreign currency\n- Locks in exchange rate for lease payment dates\n- Eliminates FX uncertainty\n- Costs: Bid-ask spread and counterparty risk\n- Accounting: Hedge accounting treatment under IFRS 9/ASC 815\n\nCurrency Swap Structures:\n- Lessor swaps foreign currency payments for home currency\n- Swap counterparty assumes FX risk\n- Reduces lessor's FX exposure\n- Costs: Swap spread and counterparty risk\n- Accounting: Hedge accounting treatment\n\nNatural Hedging Strategies:\n- Match currency of lease payments with currency of financing\n- Lessor borrows in lessee's currency\n- Reduces need for derivative hedging\n- Lowers hedging costs\n- Simplifies accounting treatment\n\nHedging Decision Framework:\n- Quantify FX exposure\n- Evaluate hedging costs vs benefits\n- Consider accounting implications\n- Assess counterparty credit risk\n- Monitor and rebalance hedges\n\nAccounting for Hedges:\n- Hedge accounting requirements (IFRS 9/ASC 815)\n- Effectiveness testing\n- Gain/loss recognition\n- Disclosure requirements\n- Documentation essential for hedge accounting");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "lesson_3_1");
    record6.set("content_body", "Pricing for Profitability\n\nLease pricing requires sophisticated financial modeling to ensure profitability while remaining competitive.\n\nIRR Calculation Methodology:\n- Internal Rate of Return (IRR) represents lessor's return on investment\n- Calculated as discount rate that equates PV of cash inflows to outflows\n- Cash outflows: Equipment cost, financing costs, transaction costs\n- Cash inflows: Lease payments, residual value, tax benefits\n- Target IRR: Typically 8-12% after-tax depending on risk profile\n\nCash Flow Components:\n- Equipment acquisition cost (negative cash flow)\n- Lease payment receipts (positive cash flows)\n- Residual value realization (positive cash flow)\n- Tax depreciation benefits (positive cash flows)\n- Investment tax credits (positive cash flows)\n- Financing costs and debt service (negative cash flows)\n- Transaction and administrative costs (negative cash flows)\n\nIRR Calculation Process:\n- Project all cash flows over lease term\n- Include residual value assumption\n- Incorporate tax benefits\n- Account for financing structure\n- Solve for discount rate equating NPV to zero\n\nSensitivity Analysis:\n- Evaluate IRR sensitivity to key assumptions\n- Residual value sensitivity: \u00b110-20% variations\n- Lease payment timing: Early vs late payment scenarios\n- Financing costs: Interest rate variations\n- Tax rate changes: Corporate tax rate variations\n- Default scenarios: Lessee default and recovery\n\nSensitivity Analysis Framework:\n- Identify key variables affecting IRR\n- Establish base case assumptions\n- Vary each variable independently\n- Calculate resulting IRR changes\n- Create sensitivity tables and charts\n- Identify critical assumptions\n\nPricing Strategy:\n- Determine target IRR based on risk profile\n- Calculate required lease payment\n- Adjust for market conditions and competition\n- Consider lessee credit quality\n- Factor in residual value risk\n- Account for tax benefits\n\nCompetitive Pricing:\n- Benchmark against market rates\n- Consider lessor's cost of capital\n- Factor in credit spreads\n- Evaluate competitive positioning\n- Balance profitability with market share\n\nRisk-Adjusted Pricing:\n- Higher IRR for higher-risk leases\n- Credit quality adjustments\n- Residual value risk premiums\n- Currency risk adjustments\n- Liquidity risk considerations");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "lesson_3_2");
    record7.set("content_body", "Residual Value Insurance (RVI)\n\nResidual Value Insurance protects lessors against residual value shortfalls at lease end.\n\nRVI Mechanics:\n- Insurance policy covers difference between guaranteed and actual residual value\n- Lessor pays insurance premium (typically 1-3% of equipment cost)\n- Insurer assumes residual value risk\n- Lessor receives payment if residual value falls below guarantee\n- Protects lessor's IRR and return on investment\n\nRVI Coverage:\n- Covers residual value shortfalls due to:\n  - Market value decline\n  - Equipment obsolescence\n  - Technological changes\n  - Supply/demand imbalances\n- Does NOT cover:\n  - Damage from lessee negligence\n  - Extraordinary wear and tear\n  - Unauthorized modifications\n  - Lessee-caused obsolescence\n\nRVI Underwriting:\n- Insurer evaluates equipment type and market\n- Assesses residual value risk\n- Determines insurable residual value\n- Sets insurance premium\n- Establishes coverage limits\n- Requires equipment inspection\n\nRVI Pricing:\n- Premium typically 1-3% of equipment cost\n- Varies by equipment type and market\n- Higher premiums for volatile markets\n- Lower premiums for stable, liquid markets\n- Affects overall lease economics\n\nSecondary Markets for Residuals:\n- Used equipment markets\n- Auction houses and brokers\n- Direct sales to end-users\n- Refurbishment and resale\n- Salvage and recycling\n\nResidual Value Realization:\n- Equipment condition assessment\n- Market timing for sale\n- Pricing strategy\n- Marketing and promotion\n- Negotiation and closing\n\nRVI vs Self-Insurance:\n- RVI provides certainty and risk transfer\n- Self-insurance retains upside potential\n- RVI costs reduce lessor profitability\n- Self-insurance requires capital reserves\n- Decision depends on risk tolerance and capital availability\n\nRVI in Lease Pricing:\n- RVI premium included in lease payment calculation\n- Affects overall lease cost to lessee\n- Reduces lessor's residual value risk\n- Improves lease economics certainty\n- May improve credit rating and financing terms\n\nRVI Claims Process:\n- Equipment inspection at lease end\n- Valuation determination\n- Comparison to guaranteed residual\n- Claim submission to insurer\n- Insurer payment if shortfall exists\n- Documentation and record-keeping");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "lesson_3_3");
    record8.set("content_body", "Lease Modifications (IFRS 16/ASC 842)\n\nLease modifications occur when parties change lease terms, requiring accounting reassessment under modern standards.\n\nIFRS 16 Lease Modification Treatment:\n- Lease modification: Change in scope or consideration of lease\n- Reassessment required when modification occurs\n- Modification accounting depends on whether it increases scope\n- Increases in scope: Separate lease accounting\n- Decreases in scope: Partial or full derecognition\n\nASC 842 Lease Modification Treatment:\n- Similar framework to IFRS 16\n- Modification: Change in lease terms or conditions\n- Reassessment of lease classification\n- Remeasurement of lease liability and ROU asset\n- Effective date of modification\n\nCommon Lease Modifications:\n- Extension or renewal of lease term\n- Change in lease payments\n- Change in residual value guarantee\n- Addition or removal of equipment\n- Change in lessee or lessor\n- Covenant modifications\n\nAccounting for Lease Extensions:\n- Reassess lease term (including extension options)\n- Recalculate lease liability\n- Adjust right-of-use asset\n- Recognize gain or loss if applicable\n- Update depreciation schedule\n\nAccounting for Payment Changes:\n- Modification of lease payment amounts\n- Recalculate present value of lease payments\n- Adjust lease liability\n- Adjust right-of-use asset\n- Recognize gain or loss\n\nAccounting for Scope Changes:\n- Addition of equipment: Separate lease accounting\n- Removal of equipment: Partial derecognition\n- Determine if modification increases scope\n- Allocate consideration to separate components\n- Account for each component separately\n\nModification Accounting Mechanics:\n- Determine modification effective date\n- Remeasure lease liability at modification date\n- Adjust right-of-use asset\n- Calculate gain or loss\n- Update lease accounting going forward\n\nDisclosure Requirements:\n- Describe nature of modification\n- Quantify impact on lease liability and ROU asset\n- Disclose gain or loss recognition\n- Explain changes to lease terms\n- Provide comparative information\n\nPractical Considerations:\n- Documentation of modification agreement\n- Timing of accounting recognition\n- Impact on financial statements\n- Tax implications of modification\n- Communication with auditors and stakeholders");
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("lesson_id", "lesson_4_1");
    record9.set("content_body", "Green Leasing\n\nGreen leasing integrates environmental sustainability into lease structures, creating value for all parties.\n\nSustainability-Linked Leases:\n- Lease payments tied to environmental performance metrics\n- Incentivizes lessee to achieve sustainability targets\n- Lessor benefits from improved asset value and marketability\n- Aligns financial incentives with environmental goals\n- Supports ESG (Environmental, Social, Governance) objectives\n\nPerformance Metrics:\n- Carbon emissions reduction\n- Energy efficiency improvements\n- Renewable energy adoption\n- Water consumption reduction\n- Waste reduction and recycling\n- Certification achievements (LEED, ISO 14001, etc.)\n\nPricing Mechanisms:\n- Base lease payment for standard performance\n- Payment reductions for exceeding sustainability targets\n- Payment increases for underperformance\n- Tiered structures with multiple performance levels\n- Bonus payments for exceptional performance\n\nRenewable Energy Financing:\n- Solar panel leasing\n- Wind turbine leasing\n- Battery storage leasing\n- EV charging infrastructure leasing\n- Renewable energy equipment financing\n\nRenewable Energy Lease Economics:\n- Long-term stable cash flows from power purchase agreements\n- Tax credits and incentives (ITC, PTC)\n- Depreciation benefits\n- Government subsidies and grants\n- Attractive risk-adjusted returns\n\nGreen Building Leasing:\n- HVAC and energy management systems\n- LED lighting and controls\n- Building automation systems\n- Water conservation equipment\n- Sustainable materials and finishes\n\nESG Reporting and Disclosure:\n- Sustainability reporting frameworks (GRI, SASB, TCFD)\n- Carbon accounting and reporting\n- Impact measurement and verification\n- Third-party certification and verification\n- Stakeholder communication\n\nFinancial Benefits:\n- Lower operating costs through efficiency\n- Improved asset value and marketability\n- Access to green financing and incentives\n- Enhanced corporate reputation\n- Investor and customer appeal\n\nRisk Considerations:\n- Technology obsolescence risk\n- Performance guarantee enforcement\n- Measurement and verification challenges\n- Regulatory changes\n- Market acceptance of green assets");
  app.save(record9);

  const record10 = new Record(collection);
    record10.set("lesson_id", "lesson_4_2");
    record10.set("content_body", "Circular Economy Models\n\nCircular economy leasing models emphasize product-as-a-service and end-of-life management.\n\nUsage-Based Leasing:\n- Lease payments based on actual usage (miles, hours, units produced)\n- Lessor retains ownership and residual value risk\n- Lessee pays only for consumption\n- Incentivizes efficient usage\n- Aligns costs with benefits\n\nUsage Measurement:\n- Telematics and IoT sensors for real-time tracking\n- Odometer readings for vehicles\n- Hour meters for equipment\n- Production counters for manufacturing equipment\n- Digital platforms for usage reporting\n\nUsage-Based Pricing:\n- Fixed base payment plus variable usage charges\n- Tiered pricing for volume discounts\n- Peak vs off-peak pricing\n- Seasonal adjustments\n- Performance-based adjustments\n\nProduct-as-a-Service (PaaS):\n- Lessor provides equipment and services\n- Lessee pays for service delivery\n- Lessor responsible for maintenance and optimization\n- Lessor incentivized to maximize equipment efficiency\n- Reduces lessee capital requirements\n\nPaaS Examples:\n- Lighting-as-a-Service (pay per lumen)\n- Cooling-as-a-Service (pay per degree)\n- Printing-as-a-Service (pay per page)\n- Transportation-as-a-Service (pay per mile)\n- Manufacturing-as-a-Service (pay per unit)\n\nEnd-of-Life Management:\n- Lessor responsible for equipment recovery\n- Refurbishment and remanufacturing\n- Component reuse and recycling\n- Proper disposal and environmental compliance\n- Circular supply chain optimization\n\nRefurbishment and Remanufacturing:\n- Equipment inspection and assessment\n- Component replacement and upgrade\n- Testing and quality assurance\n- Cosmetic restoration\n- Resale or re-lease\n\nRecycling and Disposal:\n- Material recovery and separation\n- Hazardous material handling\n- Environmental compliance\n- Waste minimization\n- Circular material flows\n\nCircular Economy Benefits:\n- Resource efficiency and waste reduction\n- Extended product lifecycles\n- New revenue streams from refurbishment\n- Environmental sustainability\n- Regulatory compliance\n- Brand reputation enhancement\n\nFinancial Implications:\n- Higher upfront costs for tracking and management\n- Residual value optimization through refurbishment\n- New revenue from remanufactured products\n- Cost savings from material recovery\n- Long-term profitability improvement");
  app.save(record10);

  const record11 = new Record(collection);
    record11.set("lesson_id", "lesson_5_1");
    record11.set("content_body", "The Big Deal Simulation - $50M Cross-Border Aircraft Lease\n\nCapstone Case Study Scenario:\n\nYou are a lease structuring advisor tasked with structuring a complex international aircraft lease. This comprehensive simulation integrates all concepts from previous modules.\n\nTransaction Overview:\n- Equipment: Boeing 787-9 Dreamliner\n- Lessee: European airline (revenue in EUR)\n- Lessor: US-based leasing company\n- Lease term: 12 years\n- Equipment cost: $50 million\n- Residual value: 15% of original cost ($7.5 million)\n- Tax considerations: US lessor, EU lessee, potential double taxation\n- ESG requirement: Lessee wants sustainability-linked pricing\n\nKey Challenges:\n1. Structuring optimal lease arrangement (leveraged vs synthetic vs traditional)\n2. Managing currency risk (USD lessor, EUR lessee)\n3. Optimizing tax efficiency across jurisdictions\n4. Addressing withholding taxes and VAT\n5. Pricing for profitability while remaining competitive\n6. Managing residual value risk\n7. Incorporating ESG/sustainability requirements\n8. Ensuring IFRS 16/ASC 842 compliance\n\nDeliverables Required:\n\n1. Financial Model:\n   - Calculate lessor IRR with tax benefits\n   - Perform 20% asset value sensitivity analysis\n   - Model cash flows over 12-year lease term\n   - Include residual value scenarios\n   - Incorporate financing structure\n   - Calculate lessee effective rate\n\n2. Risk Assessment:\n   - Identify residual value risk and mitigation\n   - Analyze currency risk and hedging strategies\n   - Assess regulatory and compliance risks\n   - Evaluate credit risk of lessee\n   - Develop contingency plans\n\n3. Structuring Recommendation:\n   - Recommend optimal structure type\n   - Justify SPV jurisdiction choice\n   - Address withholding tax implications\n   - Explain debt/equity allocation\n   - Outline transaction timeline\n\n4. Tax Optimization Strategy:\n   - Optimize using Double Taxation Treaties\n   - Address VAT/GST treatment\n   - Structure gross-up clauses\n   - Minimize overall tax burden\n   - Ensure compliance with BEPS rules\n\n5. Accounting Analysis:\n   - Apply IFRS 16 treatment\n   - Address lease classification\n   - Document lease modifications\n   - Analyze accounting impact\n   - Prepare financial statement disclosures\n\nGrading Criteria:\n- Financial accuracy: 25%\n- Risk analysis: 25%\n- Structuring logic: 25%\n- Tax optimization: 15%\n- Presentation: 10%");
  app.save(record11);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
