/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_2_1");
    record0.set("content_body", "# Leasing for Businesses and Organizations\n\n## Section 1: Why Businesses Lease\n\n### Reason 1: Capital Preservation\nBusinesses lease to avoid large upfront capital investments, preserving cash for growth and other strategic initiatives.\n\n**Example**: A manufacturing company preserves $100,000 in capital by leasing equipment instead of buying it.\n\n### Reason 2: Flexibility\nLeasing provides flexibility to upgrade or change equipment as market conditions and business needs evolve.\n\n**Example**: A growing company can upgrade to larger equipment as the business expands without selling old equipment.\n\n### Reason 3: Cost Predictability\nLease payments are fixed and predictable, making budgeting easier and providing financial certainty.\n\n**Example**: A $5,000/month lease payment is predictable and can be easily included in the budget.\n\n### Reason 4: Technology Access\nLeasing ensures businesses have access to the latest technology, helping them stay competitive.\n\n**Example**: A manufacturing company uses the latest CNC machines to stay ahead of competitors.\n\n### Reason 5: Operational Efficiency\nIn many business leases, the lessor handles maintenance and repairs, allowing the business to focus on core operations.\n\n**Example**: The lessor maintains equipment, freeing the company to focus on production and sales.\n\n### Reason 6: Balance Sheet Impact\nLeasing can improve financial ratios and return on assets by reducing the asset base and improving asset efficiency.\n\n**Example**: Leasing improves the debt-to-equity ratio and return on assets.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_2_1");
    record1.set("content_body", "## Section 2: Business Leasing Applications\n\n### Application 1: Equipment Leasing\nBusinesses lease manufacturing equipment, office equipment, and technology equipment.\n\n**Example**: A manufacturing company leases a CNC machine for production.\n\n### Application 2: Vehicle Leasing\nCompanies lease vehicles for business operations, including company cars, trucks, and vans.\n\n**Example**: A sales company leases vehicles for the sales team.\n\n### Application 3: Real Estate Leasing\nBusinesses lease office space, warehouse space, and retail space for operations.\n\n**Example**: A company leases an office building for headquarters.\n\n### Application 4: Technology Leasing\nCompanies lease computers, servers, and software for IT operations.\n\n**Example**: A company leases IT equipment to support operations.\n\n### Application 5: Specialized Equipment\nBusinesses lease medical equipment, construction equipment, and agricultural equipment.\n\n**Example**: A construction company leases heavy equipment for projects.\n\n## Section 3: Business Size Considerations\n\n### Small Businesses\n- **Capital**: Limited capital available\n- **Needs**: Need flexibility for growth\n- **Leasing**: Ideal for growth and expansion\n\n**Example**: A startup leases equipment to launch operations without large capital investment.\n\n### Medium Businesses\n- **Operations**: Growing operations\n- **Needs**: Need scalability\n- **Leasing**: Supports growth and expansion\n\n**Example**: A growing company leases additional equipment to support expansion.\n\n### Large Businesses\n- **Operations**: Established operations\n- **Strategy**: May buy or lease strategically\n- **Leasing**: Used for flexibility and specialized equipment\n\n**Example**: A large company leases specialized equipment for specific projects.");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_2_1");
    record2.set("content_body", "## Section 4: Industry-Specific Leasing\n\n### Industry 1: Manufacturing\n- **Equipment**: Machinery and production equipment\n- **Leasing**: Equipment leasing is common\n\n**Example**: A manufacturing company leases CNC machines for production.\n\n### Industry 2: Technology\n- **Equipment**: Computers, servers, and software\n- **Leasing**: Common for rapid technology changes\n\n**Example**: A tech company leases servers to support operations.\n\n### Industry 3: Retail\n- **Equipment**: Store equipment and point-of-sale systems\n- **Leasing**: Common for equipment and fixtures\n\n**Example**: A retail company leases POS systems for stores.\n\n### Industry 4: Healthcare\n- **Equipment**: Medical and diagnostic equipment\n- **Leasing**: Common for expensive equipment\n\n**Example**: A hospital leases imaging equipment for diagnostics.\n\n### Industry 5: Transportation\n- **Equipment**: Vehicles and fleet equipment\n- **Leasing**: Common for fleet management\n\n**Example**: A logistics company leases trucks for operations.\n\n## Section 5: Organizational Benefits\n\n### Benefit 1: Financial Benefits\n- **Capital preservation**: No large upfront investment\n- **Cost predictability**: Fixed monthly payments\n- **Tax deductions**: Lease payments are tax deductible\n\n**Example**: A company preserves $100,000 in capital and deducts lease payments from taxes.\n\n### Benefit 2: Operational Benefits\n- **Maintenance included**: Lessor handles maintenance\n- **Reduced burden**: Less operational burden\n- **Focus on core business**: Team focuses on core operations\n\n**Example**: The lessor maintains equipment, freeing the team to focus on production.\n\n### Benefit 3: Strategic Benefits\n- **Technology access**: Access to latest technology\n- **Competitive advantage**: Stay ahead of competitors\n- **Flexibility for growth**: Easy to adapt to growth\n\n**Example**: Access to latest technology provides competitive advantage.\n\n### Benefit 4: Risk Management\n- **Residual value risk**: Lessor bears residual value risk\n- **Obsolescence risk**: No risk of equipment becoming obsolete\n- **Financial risk**: Reduced financial risk\n\n**Example**: No risk of equipment becoming obsolete or losing value.");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "lesson_2_1");
    record3.set("content_body", "## Section 6: Case Study - ManufacturingCorp\n\n### Company Profile\n- **Name**: ManufacturingCorp\n- **Business**: Manufacturing company\n- **Situation**: Need equipment for expansion\n\n### Challenge\n- Need $500,000 in equipment\n- Limited capital available\n- Want latest technology\n- Need flexibility for market changes\n\n### Leasing Solution\n- Lease equipment instead of buying\n- Monthly payment: $10,000\n- Lease term: 5 years\n- Upgrade option available\n\n### Benefits Achieved\n- **Capital preserved**: $500,000 preserved for growth\n- **Predictable costs**: $10,000/month is predictable\n- **Latest technology**: Access to newest equipment\n- **Flexibility**: Can upgrade or change equipment\n- **Operational efficiency**: Lessor maintains equipment\n- **Tax benefits**: Lease payments are tax deductible\n\n### Financial Impact\n- **Capital preserved**: $500,000\n- **Annual lease cost**: $120,000\n- **Tax savings**: $30,000 (at 25% tax rate)\n- **Net annual cost**: $90,000\n\n### Outcome\n- Equipment obtained without capital investment\n- Capital preserved for growth initiatives\n- Positioned for continued expansion and market growth");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "lesson_2_2");
    record4.set("content_body", "# Leasing for Consumers and Individuals\n\n## Section 1: Why Consumers Lease\n\n### Reason 1: No Ownership Burden\nLeasing eliminates the responsibility of ownership. The lessor handles maintenance and repairs.\n\n**Example**: The lessor maintains the car, so the consumer doesn't need to worry about repairs.\n\n### Reason 2: Latest Models\nConsumers can drive the latest car models with the newest technology every few years.\n\n**Example**: Drive a new car every 3 years with the latest features and technology.\n\n### Reason 3: Predictable Costs\nLease payments are fixed and predictable, with maintenance often included.\n\n**Example**: A $400/month payment includes maintenance, making costs predictable.\n\n### Reason 4: No Depreciation Risk\nThe lessor bears the risk of the vehicle losing value. The consumer doesn't lose money if the car depreciates.\n\n**Example**: No loss if the car value drops below expected residual value.\n\n### Reason 5: Warranty Coverage\nLeased vehicles are typically under full warranty, with no repair costs for the consumer.\n\n**Example**: All repairs are covered by warranty, with no out-of-pocket repair costs.\n\n### Reason 6: Flexibility\nConsumers can easily change vehicles as their needs change, such as upgrading to a larger vehicle.\n\n**Example**: Upgrade to a larger vehicle when the family grows.\n\n## Section 2: Consumer Leasing Applications\n\n### Application 1: Car Leasing\nConsumers lease personal vehicles and company cars.\n\n**Example**: A consumer leases a car for personal use.\n\n### Application 2: Equipment Leasing\nConsumers lease tools and appliances for personal use.\n\n**Example**: A consumer leases tools for a home project.\n\n### Application 3: Technology Leasing\nConsumers lease computers and smartphones.\n\n**Example**: A consumer leases a smartphone for personal use.\n\n### Application 4: Furniture Leasing\nConsumers lease home and office furniture.\n\n**Example**: A consumer leases furniture for an apartment.\n\n### Application 5: Specialty Equipment\nConsumers lease musical instruments and sports equipment.\n\n**Example**: A consumer leases a musical instrument for lessons.");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "lesson_2_2");
    record5.set("content_body", "## Section 3: Consumer Leasing Benefits\n\n### Benefit 1: Financial Benefits\n- **Lower monthly payment**: Lease payment is lower than purchase payment\n- **No large upfront cost**: No down payment or large initial investment\n- **Predictable costs**: Fixed monthly payments\n\n**Example**: $400/month lease vs $25,000 purchase price.\n\n### Benefit 2: Convenience Benefits\n- **Maintenance included**: Lessor handles all maintenance\n- **Warranty coverage**: Full warranty coverage included\n- **No repair hassles**: No need to find mechanics or deal with repairs\n\n**Example**: All maintenance is included, with no repair costs.\n\n### Benefit 3: Flexibility Benefits\n- **Easy to change**: Easy to switch to a different vehicle\n- **Upgrade to new models**: Drive the latest models\n- **Adapt to changing needs**: Change vehicles as needs change\n\n**Example**: Upgrade to a larger vehicle when the family grows.\n\n### Benefit 4: Peace of Mind\n- **No depreciation risk**: Lessor bears depreciation risk\n- **No repair costs**: All repairs covered by warranty\n- **Full warranty coverage**: Complete peace of mind\n\n**Example**: No unexpected repair costs or depreciation losses.\n\n## Section 4: Consumer Leasing Considerations\n\n### Consideration 1: Mileage Limits\n- **Typical limit**: 12,000 miles per year\n- **Excess mileage**: Charges for miles over the limit\n- **Cost**: Typically $0.25 per excess mile\n\n**Example**: Driving 15,000 miles/year results in 3,000 excess miles \u00d7 $0.25 = $750 in charges.\n\n### Consideration 2: Wear and Tear\n- **Normal wear**: Normal wear and tear is acceptable\n- **Excess wear**: Charges for excessive wear\n- **Condition**: Vehicle must be returned in good condition\n\n**Example**: Excess wear charges apply for damage beyond normal wear.\n\n### Consideration 3: Early Termination\n- **Early termination fees**: Fees for ending lease early\n- **Remaining payments**: May owe remaining lease payments\n- **Cost**: Can be substantial\n\n**Example**: Early termination fee of $5,000 plus remaining payments.\n\n### Consideration 4: Customization\n- **Limited customization**: Limited ability to customize vehicle\n- **Original condition**: Must return in original condition\n- **Restrictions**: Cannot make permanent modifications\n\n**Example**: Cannot modify the vehicle or paint it a different color.\n\n### Consideration 5: Insurance\n- **Full coverage required**: Full coverage insurance required\n- **Lessor named**: Lessor named as insured\n- **Cost**: Insurance cost is consumer's responsibility\n\n**Example**: Full coverage insurance is required by the lessor.");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "lesson_2_2");
    record6.set("content_body", "## Section 5: Leasing vs Buying for Consumers\n\n### Leasing\n- **Ownership**: No ownership\n- **Monthly payment**: Lower monthly payment\n- **Maintenance**: Maintenance included\n- **Models**: Latest models available\n- **Mileage**: Mileage limits apply\n\n**Example**: Lease car for flexibility and latest models.\n\n### Buying\n- **Ownership**: Full ownership\n- **Monthly payment**: Higher monthly payment\n- **Maintenance**: Owner maintains\n- **Models**: Older models over time\n- **Mileage**: No mileage limits\n\n**Example**: Buy car for long-term use and high mileage.\n\n### When to Lease\n- Want latest models\n- Drive low mileage\n- Prefer predictable costs\n- Don't want maintenance\n\n**Example**: Consumer who drives 10,000 miles/year.\n\n### When to Buy\n- Drive high mileage\n- Want ownership\n- Long-term use\n- Want customization\n\n**Example**: Consumer who drives 20,000 miles/year.\n\n## Section 6: Case Study - JohnDoe Consumer Leasing\n\n### Consumer Profile\n- **Name**: John Doe\n- **Situation**: Need vehicle for personal use\n\n### Challenge\n- Need reliable vehicle\n- Want latest technology\n- Want predictable costs\n- Don't want maintenance hassles\n\n### Leasing Solution\n- Lease new car\n- Monthly payment: $400\n- Lease term: 3 years\n- Mileage limit: 12,000 miles/year\n- Maintenance included\n\n### Benefits Achieved\n- **Latest car**: Drive new car every 3 years\n- **Predictable cost**: $400/month payment\n- **Maintenance included**: No repair costs\n- **Warranty coverage**: Full warranty included\n- **No depreciation risk**: Lessor bears residual value risk\n\n### Comparison: Leasing vs Buying\n- **Leasing**: $400/month \u00d7 36 months = $14,400\n- **Buying**: $25,000 purchase + $200/month maintenance = $32,200\n- **Savings**: $17,800\n\n### Outcome\n- Vehicle obtained with predictable costs\n- Latest technology available\n- No maintenance hassles\n- Significant savings vs buying");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "lesson_2_3");
    record7.set("content_body", "# Leasing Industry Overview and Careers\n\n## Section 1: Leasing Industry Overview\n\n### Industry Size\n- **Market size**: Multi-billion dollar industry\n- **Growth**: Growing rapidly\n- **Scope**: Global market\n\n**Example**: The global leasing market exceeds $1 trillion annually.\n\n### Industry Segments\n\n#### Segment 1: Equipment Leasing\n- Manufacturing equipment\n- Office equipment\n- Technology equipment\n\n**Example**: Equipment leasing companies provide manufacturing equipment.\n\n#### Segment 2: Vehicle Leasing\n- Car leasing\n- Truck leasing\n- Fleet leasing\n\n**Example**: Vehicle leasing companies provide cars and trucks.\n\n#### Segment 3: Real Estate Leasing\n- Office space\n- Warehouse space\n- Retail space\n\n**Example**: Real estate leasing companies provide office buildings.\n\n#### Segment 4: Specialty Leasing\n- Medical equipment\n- Construction equipment\n- Agricultural equipment\n\n**Example**: Specialty leasing companies provide medical equipment.\n\n## Section 2: Leasing Industry Participants\n\n### Participant 1: Lessors\n- Equipment owners\n- Finance companies\n- Banks\n\n**Example**: An equipment finance company is a lessor.\n\n### Participant 2: Lessees\n- Businesses\n- Consumers\n- Organizations\n\n**Example**: A manufacturing company is a lessee.\n\n### Participant 3: Brokers\n- Facilitate leases\n- Match lessors and lessees\n\n**Example**: A leasing broker matches companies with equipment.\n\n### Participant 4: Vendors\n- Equipment manufacturers\n- Dealers\n- Suppliers\n\n**Example**: An equipment manufacturer is a vendor.\n\n### Participant 5: Service Providers\n- Maintenance providers\n- Insurance providers\n- Legal providers\n\n**Example**: A maintenance company provides equipment maintenance.");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "lesson_2_3");
    record8.set("content_body", "## Section 3: Leasing Industry Trends\n\n### Trend 1: Digital Transformation\n- Online leasing platforms\n- Digital documentation\n- Automated processes\n\n**Example**: Online lease applications and digital documentation.\n\n### Trend 2: Sustainability\n- Green equipment\n- Environmental focus\n- Eco-friendly options\n\n**Example**: Leasing electric vehicles for sustainability.\n\n### Trend 3: Flexibility\n- Shorter lease terms\n- More upgrade options\n- Customized terms\n\n**Example**: 2-year lease terms for flexibility.\n\n### Trend 4: Technology Integration\n- IoT monitoring\n- Data analytics\n- Predictive maintenance\n\n**Example**: Real-time equipment monitoring using IoT.\n\n### Trend 5: Customization\n- Tailored lease terms\n- Flexible payment options\n- Custom agreements\n\n**Example**: Custom lease agreements tailored to customer needs.\n\n## Section 4: Career Opportunities\n\n### Career 1: Lease Originator\n- **Responsibilities**: Originate new leases, work with customers, process applications\n- **Skills**: Sales, customer service, financial analysis\n- **Growth**: High demand\n\n**Example**: A lease originator at a finance company originates new equipment leases.\n\n### Career 2: Lease Manager\n- **Responsibilities**: Manage lease portfolio, monitor compliance, handle customer service\n- **Skills**: Portfolio management, compliance, customer service\n- **Growth**: Stable demand\n\n**Example**: A lease manager oversees a portfolio of 100+ leases.\n\n### Career 3: Credit Analyst\n- **Responsibilities**: Analyze credit risk, evaluate applications, make credit decisions\n- **Skills**: Financial analysis, credit analysis, risk assessment\n- **Growth**: Steady demand\n\n**Example**: A credit analyst evaluates customer creditworthiness.\n\n### Career 4: Sales Representative\n- **Responsibilities**: Sell leasing products, build customer relationships, close deals\n- **Skills**: Sales, relationship building, product knowledge\n- **Growth**: High demand\n\n**Example**: A sales rep sells leasing products to businesses.\n\n### Career 5: Operations Manager\n- **Responsibilities**: Manage operations, oversee processes, ensure compliance\n- **Skills**: Operations management, process improvement, compliance\n- **Growth**: Steady demand\n\n**Example**: An operations manager oversees lease processing.\n\n### Career 6: Compliance Officer\n- **Responsibilities**: Ensure regulatory compliance, monitor compliance, implement policies\n- **Skills**: Compliance knowledge, regulatory expertise, policy development\n- **Growth**: Growing demand\n\n**Example**: A compliance officer ensures regulatory compliance.");
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("lesson_id", "lesson_2_3");
    record9.set("content_body", "## Section 5: Industry Skills and Qualifications\n\n### Skill 1: Financial Analysis\n- Analyze financial statements\n- Evaluate credit risk\n- Calculate lease payments\n\n**Example**: Analyze customer financials to evaluate creditworthiness.\n\n### Skill 2: Customer Service\n- Work with customers\n- Resolve issues\n- Build relationships\n\n**Example**: Provide excellent customer service to lease customers.\n\n### Skill 3: Sales Skills\n- Sell leasing products\n- Build relationships\n- Close deals\n\n**Example**: Sell leasing products to business customers.\n\n### Skill 4: Compliance Knowledge\n- Understand regulations\n- Ensure compliance\n- Implement policies\n\n**Example**: Ensure compliance with leasing regulations.\n\n### Skill 5: Technology Skills\n- Use leasing software\n- Data analysis\n- Digital tools\n\n**Example**: Use lease management software for operations.\n\n## Section 6: Case Study - LeasingCorp Industry\n\n### Company Profile\n- **Name**: LeasingCorp\n- **Business**: Equipment leasing company\n- **Founded**: 10 years ago\n- **Employees**: 50\n- **Annual revenue**: $50M\n- **Lease portfolio**: 500 leases\n\n### Growth Strategy\n- Expand customer base\n- Expand product offerings\n- Invest in technology\n- Hire talented staff\n\n### Career Opportunities\n- **Lease originators**: 5 positions\n- **Lease managers**: 3 positions\n- **Credit analysts**: 2 positions\n- **Sales representatives**: 4 positions\n- **Operations managers**: 2 positions\n- **Compliance officers**: 1 position\n\n### Industry Impact\n- Enables business growth\n- Provides equipment access\n- Creates employment\n- Drives innovation\n\n### Outcome\n- Growing leasing business\n- Career opportunities available\n- Industry growth continuing\n- Positioned for continued expansion");
  app.save(record9);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
