/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_lesson_1");
    record0.set("content_body", "# Pre-2019 Lease Accounting Standards\n\n## Section 1: IAS 17 - International Lease Accounting Standard\n\n### What is IAS 17?\n- International Accounting Standard 17\n- Lease accounting standard issued by IASB\n- Effective date: January 1, 1997\n- Replaced by: IFRS 16 (January 1, 2019)\n- Applies to: Public and private companies using IFRS\n\n### IAS 17 Development:\n- Issued by IASB in 1997\n- Revised in 2003\n- Effective until December 31, 2018\n- Replaced by IFRS 16 on January 1, 2019\n\n### Key Principle:\n- Dual lease accounting model\n- Finance leases vs. operating leases\n- Finance leases capitalized (on balance sheet)\n- Operating leases off-balance sheet\n\n## Section 2: IAS 17 Lease Classification\n\n**Finance Lease:**\n- Lease transfers substantially all risks and rewards\n- Lessee recognizes asset and liability\n\n**Operating Lease:**\n- Lease does not transfer substantially all risks and rewards\n- Lessee recognizes lease expense\n- Lessor retains asset\n\n### Classification Criteria:\nLease is Finance Lease if:\n1. Lease transfers ownership\n2. Lease contains purchase option\n3. Lease term \u2265 75% of asset's economic life\n4. PV of lease payments \u2265 90% of asset's fair value\n5. Asset is specialized\n\n## Section 3: IAS 17 Lessee Accounting\n\n**Finance Lease:**\n- Recognize asset at lower of PV of payments or fair value\n- Recognize liability at PV of lease payments\n- Asset depreciated over lease term\n- Liability reduced by lease payments\n\n**Operating Lease:**\n- No asset or liability recognized\n- Lease expense recognized straight-line\n\n## Section 4: IAS 17 Lessor Accounting\n\n**Finance Lease:**\n- Derecognize underlying asset\n- Recognize lease receivable\n- Finance income recognized\n\n**Operating Lease:**\n- Retain underlying asset\n- Asset depreciated over useful life\n- Lease income recognized straight-line");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "pbc_lesson_2");
    record1.set("content_body", "# Evolution to Modern Standards\n\n## Section 1: Why Standards Changed\n\n### Key Drivers of Change:\n\n**1. Off-Balance Sheet Financing:**\n- Operating leases kept off balance sheet\n- Hid true liabilities from investors\n\n**2. Comparability Issues:**\n- Different accounting for similar transactions\n- Finance leases vs. operating leases\n\n**3. Transparency Demands:**\n- Investors wanted full disclosure\n- Regulators demanded transparency\n\n**4. Convergence Efforts:**\n- IASB and FASB working together\n- Align international and US standards\n\n**5. Technology Changes:**\n- New lease arrangements emerging\n- Cloud computing, software leases\n\n## Section 2: IAS 17 to IFRS 16 Transition\n\n**1. Single Lease Accounting Model:**\n- IAS 17: Finance vs. operating distinction\n- IFRS 16: Single model for all leases\n\n**2. Right-of-Use Asset:**\n- IAS 17: Finance leases only\n- IFRS 16: All leases\n\n**3. Lease Liability:**\n- IAS 17: Finance leases only\n- IFRS 16: All leases\n\n**4. Lessor Accounting:**\n- IAS 17: Finance vs. operating distinction\n- IFRS 16: Similar distinction maintained\n\n**5. Exemptions:**\n- IAS 17: Limited exemptions\n- IFRS 16: Short-term and low-value exemptions\n\n## Section 3: ASC 840 to ASC 842 Transition\n\n**ASC 840:**\n- US GAAP lease accounting standard\n- Effective date: January 1, 1977\n- Dual lease accounting model\n\n**ASC 842:**\n- Replaced ASC 840\n- Effective January 1, 2019 (public), 2022 (private)\n- Single lease accounting model\n\n## Section 4: Convergence Journey\n\n**2006:** Joint project initiated\n**2010:** First exposure draft issued\n**2013:** Revised proposal issued\n**2016:** Standards issued (IFRS 16 and ASC 842)\n**2019-2022:** Implementation globally");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
