/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_1_1_id");
    record0.set("content_body", "SECTION 1: WHAT IS LEASING STRATEGY?\n\nDefinition:\n- Long-term plan for leasing business success\n- Aligns resources with market opportunities\n- Creates competitive advantage\n- Guides decision-making\n- Example: Strategy to become market leader in IT equipment leasing\n\nSTRATEGIC PLANNING PROCESS:\n\n1. Vision and Mission:\n   - Vision: Where do we want to be? (5-10 years)\n   - Mission: What is our purpose?\n   - Example: Vision = \"Become top 3 IT leasing provider in region\"\n\n2. Strategic Analysis:\n   - Assess internal strengths and weaknesses\n   - Analyze external opportunities and threats\n   - Identify competitive advantages\n   - Example: Strength = strong credit analysis, Weakness = limited capital\n\n3. Strategy Development:\n   - Define strategic objectives\n   - Develop strategies to achieve objectives\n   - Allocate resources\n   - Example: Objective = grow market share 5%, Strategy = expand sales team\n\n4. Implementation:\n   - Execute strategies\n   - Monitor progress\n   - Adjust as needed\n   - Example: Hire 10 new sales reps, train on new products\n\n5. Evaluation:\n   - Measure results\n   - Compare to objectives\n   - Identify improvements\n   - Example: Achieved 6% growth vs. 5% target\n\nSECTION 2: TYPES OF LEASING STRATEGIES\n\nStrategy 1: Cost Leadership\n- Definition: Compete on lowest cost, achieve economies of scale, reduce operating costs\n- Example: Offer lowest lease payments in market\n- Advantages: Attract price-sensitive customers, high volume/lower margins, difficult for competitors to match\n- Disadvantages: Lower profit margins, requires high volume, vulnerable to price wars");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_1_1_id");
    record1.set("content_body", "Strategy 2: Differentiation\n- Definition: Compete on unique value, offer superior service or features, premium pricing\n- Example: Full-service leases with 24/7 support\n- Advantages: Higher profit margins, customer loyalty, less price competition\n- Disadvantages: Requires continuous innovation, higher costs, smaller market size\n\nStrategy 3: Focus/Niche\n- Definition: Specialize in specific market segment, deep expertise in niche, tailored solutions\n- Example: Specialize in healthcare equipment leasing\n- Advantages: Market leadership in niche, strong customer relationships, premium pricing\n- Disadvantages: Limited market size, vulnerable to market changes, requires specialized expertise\n\nStrategy 4: Growth/Expansion\n- Definition: Expand into new markets or products, increase market share, grow revenue and profit\n- Example: Expand from IT to manufacturing equipment\n- Advantages: Revenue growth, diversification, economies of scale\n- Disadvantages: Higher risk, requires capital, execution challenges\n\nSECTION 3: SWOT ANALYSIS\n\nSWOT Framework:\n- Strengths (Internal): What are we good at? What advantages do we have? What resources do we have?\n- Weaknesses (Internal): What are we not good at? What disadvantages do we have? What resources do we lack?\n- Opportunities (External): What market opportunities exist? What trends favor us? What can we exploit?\n- Threats (External): What market threats exist? What trends hurt us? What can harm us?");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_1_1_id");
    record2.set("content_body", "SWOT Analysis Process:\n1. Identify Strengths: Internal capabilities, competitive advantages, resources and assets\n2. Identify Weaknesses: Internal limitations, competitive disadvantages, resource gaps\n3. Identify Opportunities: Market growth, unmet customer needs, industry trends\n4. Identify Threats: Competitive threats, market changes, economic factors\n5. Develop Strategies: Leverage strengths to exploit opportunities, address weaknesses to mitigate threats\n\nSECTION 4: COMPETITIVE ADVANTAGE\n\nWhat is Competitive Advantage?\n- Unique capability that competitors cannot easily replicate\n- Creates superior customer value\n- Enables premium pricing or lower costs\n- Example: Superior credit analysis = lower default rates = lower costs\n\nTypes of Competitive Advantage:\n1. Cost Advantage: Lower costs than competitors, enables lower pricing\n2. Differentiation Advantage: Unique features or service, enables premium pricing\n3. Speed Advantage: Faster service than competitors, enables faster decision-making\n4. Quality Advantage: Superior quality or reliability, enables premium pricing\n5. Relationship Advantage: Strong customer relationships, enables customer loyalty");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "lesson_1_1_id");
    record3.set("content_body", "Building Competitive Advantage:\n1. Identify Core Competencies: What are we uniquely good at?\n2. Invest in Capabilities: Develop and strengthen core competencies\n3. Protect Advantage: Create barriers to imitation, build switching costs\n4. Sustain Advantage: Continuously improve, innovate and adapt\n\nSECTION 5: CASE STUDY - STRATEGYEASING INC.\n\nSituation: Developing leasing strategy for new company\n\nVision and Mission:\n- Vision: Become top 5 equipment leasing company in region within 10 years\n- Mission: Provide innovative, customer-centric leasing solutions\n\nSWOT Analysis:\nStrengths: Experienced management team (20+ years), strong relationships with equipment manufacturers, access to capital ($50M), proprietary credit model\nWeaknesses: New company (no brand recognition), small sales team (5 people), limited customer base, high cost structure\nOpportunities: Growing IT equipment market (15% annual growth), consolidation trend, underserved mid-market segment, technology disruption\nThreats: Large competitors with scale advantages, economic downturn risk, technology disruption risk, new competitors entering market\n\nCompetitive Advantage: Proprietary credit model = lower default rates, experienced team = better customer relationships, flexibility = faster decision-making\n\nStrategic Objectives:\n1. Build Brand Recognition: Become known in mid-market segment (2 years)\n2. Grow Customer Base: Acquire 500 customers in 3 years\n3. Achieve Profitability: Achieve 10% ROI by year 3\n4. Expand Product Offerings: Offer 5 product types by year 3");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "lesson_1_2_id");
    record4.set("content_body", "SECTION 1: MARKET ANALYSIS FRAMEWORK\n\nMarket Analysis Components:\n\n1. Market Size and Growth:\n   - Total addressable market (TAM)\n   - Market growth rate\n   - Market trends\n   - Example: $100B TAM, 8% annual growth\n\n2. Customer Analysis:\n   - Who are the customers?\n   - What are their needs?\n   - How do they buy?\n   - Example: Mid-market manufacturers, need flexibility, buy through RFP\n\n3. Competitive Analysis:\n   - Who are the competitors?\n   - What are their strengths/weaknesses?\n   - What is their market share?\n   - Example: 5 major competitors, 60% combined market share\n\n4. Industry Trends:\n   - What trends are shaping the market?\n   - What is the direction of the market?\n   - What opportunities/threats exist?\n   - Example: Consolidation trend, technology disruption, sustainability focus\n\n5. Regulatory Environment:\n   - What regulations apply?\n   - How do they impact the market?\n   - What compliance is required?\n   - Example: Accounting standards, consumer protection laws");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "lesson_1_2_id");
    record5.set("content_body", "SECTION 2: COMPETITIVE POSITIONING\n\nWhat is Competitive Positioning?\n- How company is perceived relative to competitors\n- Unique value proposition\n- Target market segment\n- Example: \"Premium service provider for mid-market manufacturers\"\n\nPositioning Strategies:\n\n1. Price-Based Positioning: Position as lowest cost provider, compete on price\n2. Quality-Based Positioning: Position as highest quality provider, compete on quality and reliability\n3. Service-Based Positioning: Position as best service provider, compete on customer service\n4. Innovation-Based Positioning: Position as most innovative provider, compete on innovation\n5. Relationship-Based Positioning: Position as best partner, compete on relationships\n\nPositioning Process:\nStep 1: Identify Target Market - Who do we want to serve?\nStep 2: Understand Customer Needs - What do customers value?\nStep 3: Analyze Competitors - How are competitors positioned?\nStep 4: Identify Differentiation - How can we differentiate?\nStep 5: Develop Positioning Statement - Clear, concise statement of positioning");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "lesson_1_2_id");
    record6.set("content_body", "SECTION 3: MARKET SEGMENTATION\n\nWhat is Market Segmentation?\n- Dividing market into distinct customer groups\n- Each segment has different needs/characteristics\n- Enables targeted strategies\n- Example: Segment by industry (manufacturing, healthcare, IT)\n\nSegmentation Approaches:\n\n1. Geographic Segmentation: Divide by location (North America, Europe, Asia)\n2. Demographic Segmentation: Divide by company size, industry, etc.\n3. Psychographic Segmentation: Divide by values, attitudes, lifestyle\n4. Behavioral Segmentation: Divide by buying behavior, usage, loyalty\n5. Needs-Based Segmentation: Divide by customer needs\n\nSECTION 4: CASE STUDY - MARKETLEASING INC.\n\nSituation: Analyzing market and developing positioning strategy\n\nMarket Analysis:\n\nMarket Size and Growth:\n- Total addressable market: $150B\n- Annual growth rate: 10%\n- Market segments: IT (40%), Manufacturing (35%), Healthcare (15%), Other (10%)\n- IT segment growing 15% annually");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "lesson_1_2_id");
    record7.set("content_body", "Customer Analysis:\n- Primary customers: Mid-market companies ($10M-$500M revenue)\n- Key needs: Flexibility, reliability, cost-effectiveness\n- Buying process: RFP, 3-6 month decision cycle\n- 80% of customers use RFP process\n\nCompetitive Analysis:\n- Major competitors: 5 large national companies\n- Market share: Top 3 = 50%, Others = 50%\n- Competitor positioning: Mix of cost, quality, service\n- Competitor A = low cost (30% market share), Competitor B = premium service (15%)\n\nIndustry Trends:\n- Consolidation: Smaller lessors being acquired\n- Technology: AI, automation, digital platforms\n- Sustainability: Green equipment, ESG focus\n- Flexibility: Shorter terms, upgrade options\n- 20% of new leases include upgrade options");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "lesson_1_2_id");
    record8.set("content_body", "Competitive Positioning:\n\nTarget Market: Mid-market manufacturers ($50M-$200M revenue), need flexibility and reliability, value cost-effectiveness\n\nDifferentiation:\n- Proprietary credit model = faster approvals\n- Flexible lease terms = customized solutions\n- Strong service = 24/7 support\n- 24-hour approval vs. 5-day competitor average\n\nPositioning Statement: \"Flexible, reliable leasing solutions for growing manufacturers\"\n\nCompetitive Advantages:\n- Faster approvals (24 hours vs. 5 days)\n- More flexible terms (customizable)\n- Better service (24/7 support)\n- Competitive pricing (5% below market average)\n\nMarket Entry Strategy:\n- Target underserved mid-market segment\n- Build relationships with equipment dealers\n- Develop reputation for fast approvals and flexibility\n- Partner with 20 equipment dealers in region\n\nExpected Results:\n- Capture 5% market share in 3 years\n- Acquire 300 customers\n- Generate $50M in annual lease revenue\n- Achieve 12% ROI");
  app.save(record8);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
