/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_lesson_5");
    record0.set("content_body", "SECTION 1: Lessee Recognition and Measurement\n\nLessee Recognition:\n\nAt Lease Commencement:\n1. Recognize right-of-use asset\n2. Recognize lease liability\n3. Measure at present value of lease payments\n4. Example: $500K equipment = $500K ROU asset + $450K liability\n\nMeasurement:\n\nRight-of-Use Asset:\n- Measured at cost\n- Cost = Lease liability + Initial direct costs - Lease incentives\n- Example: $450K liability + $5K costs - $0 incentives = $455K ROU asset\n\nLease Liability:\n- Measured at present value of lease payments\n- Discount rate: Implicit rate (if known), otherwise incremental borrowing rate\n- Lease payments: Fixed + variable (linked to index) + residual guarantees\n- Example: PV of $10K/month \u00d7 60 months = $450K\n\nSECTION 2: Subsequent Measurement\n\nROU Asset Amortization:\n\nAmortization Method:\n- Straight-line amortization over lease term\n- Example: $500K / 5 years = $100K/year\n\nLease Liability Interest:\n\nInterest Calculation:\n- Interest = Lease liability \u00d7 Discount rate\n- Example: $450K \u00d7 5% = $22,500 Year 1 interest\n\nLease Payment Allocation:\n\nEach Lease Payment:\n- Principal portion: Reduces lease liability\n- Interest portion: Recognized as interest expense\n- Example: $10K payment = $7,500 principal + $2,500 interest\n\nSECTION 3: Lease Modifications\n\nWhat is a Lease Modification?\n- Change to lease terms or conditions\n- Requires remeasurement of liability and asset\n- Example: Extension of lease term, change in payment\n\nTypes of Modifications:\n\n1. Scope Changes: Addition or removal of equipment\n2. Payment Changes: Change in lease payment amount\n3. Term Changes: Extension or shortening of lease term\n4. Residual Value Changes: Change in residual value guarantee\n\nModification Accounting:\n\nStep 1: Identify Modification\nStep 2: Calculate New Lease Liability\nStep 3: Adjust ROU Asset\nStep 4: Record Adjustment\n\nSECTION 4: Case Study - ASC 842 Lessee Accounting\n\nCompany: LesseeASC842 Inc.\nLease Details:\n- Equipment: Manufacturing equipment\n- Equipment cost: $500,000\n- Lease term: 5 years (60 months)\n- Monthly payment: $10,000\n- Residual value guarantee: $50,000\n- Implicit rate: 5%\n- Initial direct costs: $5,000\n\nLease Liability Calculation:\n- Monthly payment: $10,000\n- Number of payments: 60\n- Monthly discount rate: 0.4167% (5% / 12)\n- PV of payments: $10,000 \u00d7 54.3 = $543,000\n- Residual guarantee: $50,000 \u00d7 (1.05)^-5 = $39,175\n- Total lease liability: $582,175\n\nYear 1 Summary:\n- Total lease payments: $120,000\n- Total interest expense: $23,568\n- Total amortization: $117,432\n- Total lease expense: $141,000");
  app.save(record0);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
