/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_lesson_8");
    record0.set("content_body", "SECTION 1: Implementation Planning\n\nImplementation Phases:\n\nPhase 1: Assessment (Weeks 1-4)\n- Identify all leases\n- Assess current accounting\n- Identify gaps\n- Deliverable: Lease inventory\n\nPhase 2: Design (Weeks 5-8)\n- Design new accounting processes\n- Develop accounting policies\n- Design system changes\n- Deliverable: Accounting policies, system design\n\nPhase 3: Build (Weeks 9-16)\n- Build system changes\n- Develop tools and templates\n- Train team\n- Deliverable: Systems, tools, trained team\n\nPhase 4: Test (Weeks 17-20)\n- Test accounting entries\n- Test system functionality\n- Test disclosures\n- Deliverable: Test results, fixes\n\nPhase 5: Transition (Weeks 21-24)\n- Record transition entries\n- Implement new accounting\n- Prepare financial statements\n- Deliverable: Transition entries, financial statements\n\nPhase 6: Close-out (Weeks 25-26)\n- Final review and audit\n- Document procedures\n- Finalize disclosures\n- Deliverable: Audited financial statements\n\nSECTION 2: Lease Identification and Inventory\n\nLease Identification Steps:\n\nStep 1: Identify Contracts\n- Review all contracts\n- Identify potential leases\n- Example: Equipment, building, vehicle leases\n\nStep 2: Assess Lease Criteria\n- Does contract convey right to use asset?\n- Is there consideration?\n- Example: Equipment lease = lease\n\nStep 3: Document Lease Terms\n- Lease term\n- Lease payments\n- Residual value\n- Example: 5-year lease, $10K/month\n\nStep 4: Create Lease Inventory\n- List all leases\n- Document key terms\n- Example: 100 leases identified\n\nSECTION 3: Accounting Policy Development\n\nPolicy Components:\n\n1. Lease Definition\n2. Recognition Policy\n3. Measurement Policy\n4. Discount Rate Policy\n5. Short-term and Low-Value Lease Policy\n6. Lease Modification Policy\n7. Presentation and Disclosure Policy\n\nSECTION 4: Case Study - Implementation\n\nCompany: ImplementationCorp\nCurrent State:\n- 100 leases across company\n- Operating vs. finance lease distinction\n- Many operating leases off-balance sheet\n\nImplementation Plan:\n- Phase 1: Identify all 100 leases\n- Phase 2: Design new processes\n- Phase 3: Build systems\n- Phase 4: Test accounting\n- Phase 5: Record transition entries\n- Phase 6: Finalize and audit\n\nFinancial Statement Impact:\n- Total assets increase: $50M\n- Total liabilities increase: $45M\n- Equity impact: $5M\n- Year 1 net income impact: -$0.5M");
  app.save(record0);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
