/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_lesson_7");
    record0.set("content_body", "SECTION 1: Similarities Between IFRS 16 and ASC 842\n\nCore Similarities:\n\n1. Single Lease Accounting Model:\n   - Both use single model for all leases\n   - No distinction between finance and operating (for lessees)\n   - All leases recognized on balance sheet\n\n2. Right-of-Use Asset and Lease Liability:\n   - Both recognize ROU asset\n   - Both recognize lease liability\n   - Both measure at present value\n\n3. Lease Definition:\n   - Both define lease similarly\n   - Contract conveying right to use asset\n   - For period of time\n\n4. Lease Payments:\n   - Both include fixed payments\n   - Both include variable payments (linked to index)\n   - Both include residual value guarantees\n\n5. Lease Term:\n   - Both include non-cancellable period\n   - Both include renewal periods (if reasonably certain)\n   - Both include termination penalties\n\n6. Exemptions:\n   - Both have short-term lease exemption (\u2264 12 months)\n   - Both have low-value asset exemption (< $5,000)\n   - Both allow optional exemption election\n\n7. Lessor Classification:\n   - Both classify leases as finance or operating\n   - Both use similar classification criteria\n   - Both recognize finance and operating leases differently\n\nSECTION 2: Key Differences\n\nDifference 1: Transition Approach\n- IFRS 16: Full or modified retrospective\n- ASC 842: Modified retrospective only\n- Example: Different transition approaches\n\nDifference 2: Practical Expedients\n- IFRS 16: Limited practical expedients\n- ASC 842: More practical expedients available\n- Example: Different simplifications\n\nDifference 3: Discount Rate\n- Both use implicit rate if known\n- Both use incremental borrowing rate if not\n- Example: Similar approaches\n\nSECTION 3: Convergence and Divergence Areas\n\nConvergence Areas:\n1. Core Model: Both use right-of-use model\n2. Lease Definition: Both define lease similarly\n3. Measurement: Both measure at present value\n\nDivergence Areas:\n1. Transition: Different approaches\n2. Practical Expedients: Different availability\n3. Implementation: Different timelines\n\nSECTION 4: Case Study - Comparison\n\nCompany: ComparisonCorp\nLease Details:\n- Equipment: Manufacturing equipment\n- Equipment cost: $500,000\n- Lease term: 5 years (60 months)\n- Monthly payment: $10,000\n- Implicit rate: 4%\n- Incremental borrowing rate: 5%\n\nIFRS 16 Accounting:\n- Discount Rate: 4% implicit rate\n- Lease Liability: $589,096\n- ROU Asset: $594,096\n\nASC 842 Accounting:\n- Discount Rate: 4% implicit rate\n- Lease Liability: $589,096\n- ROU Asset: $594,096\n\nComparison:\n- Both standards result in same amounts\n- Because implicit rate is known and used by both\n- If implicit rate unknown, standards would differ");
  app.save(record0);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
