/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("vendor_leasing_case_studies");

  const record0 = new Record(collection);
    record0.set("lessonId", "lesson_5_placeholder");
    record0.set("title", "Accounting for Vendor Lease: Multi-Year Equipment Lease");
    record0.set("scenario", "ABC Manufacturing Company enters into a 5-year lease agreement with XYZ Equipment Leasing for specialized manufacturing equipment. The lease terms include: monthly lease payments of $15,000, the equipment has an estimated useful life of 8 years, the company's incremental borrowing rate is 5% annually, and there is a residual value guarantee of $200,000 at the end of the lease term. The company must maintain the equipment in good condition and carry comprehensive insurance with the lessor named as loss payee.");
    record0.set("requirements", "1. Classify the lease as either operating or finance lease based on ASC 842 criteria\n2. Calculate the Right-of-Use (ROU) asset and lease liability at lease commencement\n3. Prepare the initial journal entries to record the lease\n4. Prepare the journal entries for the first year of the lease (including depreciation and interest)\n5. Analyze the impact on the company's financial statements\n6. Discuss the disclosure requirements for this lease");
    record0.set("analysisFramework", "1. ASC 842 Classification Criteria:\n   - Does the lease transfer ownership? No\n   - Is there a reasonably certain purchase option? No\n   - Is the lease term for the major part of the asset's economic life? 5 years out of 8 years = 62.5% (yes)\n   - Does the PV of payments equal substantially all of fair value? (Calculate)\n   - Is the asset specialized? No\n\n2. ROU Asset Calculation:\n   - Lease liability at commencement\n   - Plus: Lease payments made at or before commencement\n   - Plus: Initial direct costs\n   - Less: Lease incentives received\n\n3. Lease Liability Calculation:\n   - PV of fixed lease payments: $15,000 \u00d7 60 months\n   - PV of residual value guarantee: $200,000\n   - Discount rate: 5% annual (0.4074% monthly)\n\n4. Journal Entries:\n   - Initial recognition of ROU asset and lease liability\n   - Monthly lease payment entries\n   - Depreciation of ROU asset\n   - Interest expense on lease liability\n\n5. Financial Statement Impact:\n   - Balance sheet: ROU asset and lease liability\n   - Income statement: Depreciation and interest expense\n   - Cash flow statement: Operating and financing activities");
    record0.set("expectedOutcome", "Students should be able to: (1) Correctly classify the lease as a finance lease based on the 62.5% lease term criterion; (2) Calculate the lease liability as the PV of payments and residual guarantee; (3) Calculate the ROU asset; (4) Prepare accurate journal entries for lease recognition and subsequent payments; (5) Understand the impact on financial statements and key metrics; (6) Identify required disclosures including lease terms, ROU assets, liabilities, and expense components.");
    record0.set("difficulty", "intermediate");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lessonId", "lesson_6_placeholder");
    record1.set("title", "Managing Vendor Lease Risks: Multi-Vendor Portfolio");
    record1.set("scenario", "DEF Corporation manages a portfolio of 50 equipment leases from 8 different vendors across 5 industries. The portfolio includes: manufacturing equipment (40% of portfolio), transportation equipment (30%), IT equipment (20%), and office equipment (10%). Recent economic downturn has affected several lessees, with 3 lessees showing signs of financial distress. The company needs to assess credit risks, evaluate residual value risks, ensure compliance with all regulations, and develop a comprehensive risk management strategy.");
    record1.set("requirements", "1. Conduct a comprehensive credit risk assessment for the portfolio\n2. Identify and evaluate residual value risks for key asset categories\n3. Develop a compliance checklist and assess current compliance status\n4. Create a risk management strategy addressing identified risks\n5. Establish monitoring procedures and early warning indicators\n6. Develop default management procedures for at-risk leases\n7. Recommend insurance coverage and risk mitigation strategies");
    record1.set("analysisFramework", "1. Credit Risk Assessment:\n   - Analyze financial statements of each lessee\n   - Calculate key financial ratios (debt service coverage, current ratio, debt-to-equity)\n   - Assess industry trends and competitive position\n   - Evaluate management quality and experience\n   - Assign internal credit ratings\n   - Identify concentration risks\n\n2. Residual Value Risk Analysis:\n   - Review residual value estimates for each asset category\n   - Assess technological obsolescence risk\n   - Evaluate market conditions and demand\n   - Consider maintenance and condition monitoring\n   - Analyze historical residual value performance\n\n3. Compliance Framework:\n   - Federal regulations: TILA, ECOA, FCRA, Dodd-Frank, GLBA\n   - State regulations: UCC, state-specific leasing laws\n   - Documentation requirements\n   - Disclosure requirements\n   - Record retention requirements\n\n4. Risk Mitigation Strategies:\n   - Portfolio diversification\n   - Concentration limits\n   - Risk-based pricing\n   - Collateral and guarantees\n   - Insurance coverage\n   - Covenant structure\n\n5. Monitoring Procedures:\n   - Monthly payment monitoring\n   - Quarterly financial review\n   - Annual covenant compliance review\n   - Asset condition inspections\n   - Market value assessments");
    record1.set("expectedOutcome", "Students should be able to: (1) Conduct comprehensive credit assessments using financial analysis and industry evaluation; (2) Identify and quantify residual value risks; (3) Develop compliance procedures and documentation; (4) Create risk management strategies addressing identified risks; (5) Establish monitoring systems with early warning indicators; (6) Develop escalation procedures for at-risk leases; (7) Recommend appropriate insurance coverage and risk mitigation measures; (8) Understand the importance of portfolio diversification and concentration limits.");
    record1.set("difficulty", "advanced");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
