/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_lesson_6");
    record0.set("content_body", "SECTION 1: Lessor Classification\n\nLessor Lease Classification:\n\nFinance Lease:\n- Lease transfers substantially all risks and rewards\n- Lessor recognizes lease receivable\n- Lessor recognizes finance income\n- Example: 5-year lease of 7-year asset = finance lease\n\nOperating Lease:\n- Lease does not transfer substantially all risks and rewards\n- Lessor retains asset\n- Lessor recognizes lease income\n- Example: 2-year lease of 10-year asset = operating lease\n\nClassification Criteria:\n\nLease is Finance Lease if:\n1. Lease transfers ownership\n2. Lease contains purchase option (reasonably certain to exercise)\n3. Lease term \u2265 75% of asset's economic life\n4. PV of lease payments \u2265 90% of asset's fair value\n5. Asset is specialized (no alternative use)\n\nSECTION 2: Finance Lease Accounting\n\nFinance Lease Recognition:\n\nAt Lease Commencement:\n1. Derecognize underlying asset\n2. Recognize lease receivable\n3. Recognize finance income (deferred)\n4. Example: $500K equipment = $500K lease receivable\n\nMeasurement:\n\nLease Receivable:\n- Measured at present value of lease payments\n- Discount rate: Implicit rate in lease\n- Example: PV of $10K/month \u00d7 60 months = $500K\n\nFinance Income:\n- Recognized over lease term\n- Interest on outstanding receivable\n- Example: Year 1 finance income = $25,000\n\nSECTION 3: Operating Lease Accounting\n\nOperating Lease Recognition:\n\nAt Lease Commencement:\n1. Retain underlying asset\n2. No lease receivable\n3. Example: $500K equipment retained on balance sheet\n\nMeasurement:\n\nUnderlying Asset:\n- Measured at cost\n- Depreciated over useful life\n- Example: $500K / 10 years = $50K/year depreciation\n\nLease Income:\n- Recognized over lease term\n- Straight-line basis\n- Example: $10K/month = $120K/year lease income\n\nSECTION 4: Case Study - ASC 842 Lessor Accounting\n\nCompany: LessorASC842 Inc.\n\nLease 1: Finance Lease\n- Equipment: Manufacturing equipment\n- Equipment cost: $500,000\n- Equipment useful life: 7 years\n- Lease term: 5 years\n- Monthly payment: $10,000\n- Implicit rate: 5%\n\nClassification:\n- Lease term: 5 years / 7 years = 71% (not \u2265 75%)\n- PV of payments: $543,000 / $500,000 = 109% (\u2265 90%)\n- Classification: Finance lease (criterion 4 met)\n\nYear 1 Summary:\n- Total lease payments: $120,000\n- Total finance income: $25,000\n- Lease receivable reduction: $108,000");
  app.save(record0);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
