/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("vendor_leasing_glossaries");

  const record0 = new Record(collection);
    record0.set("lessonId", "lesson_4");
    record0.set("termCount", 10);
    record0.set("terms", "Lease Accounting System | Data Abstraction | Lease Register | Compliance Testing | Internal Controls | Segregation of Duties | Audit Trail | System Integration | Data Validation | Lease Reconciliation");
    record0.set("definitions", "Software system designed to manage lease accounting processes and maintain lease data | Process of extracting key lease terms from agreements into standardized format | Centralized record of all organizational leases with key terms and accounting data | Process of verifying that lease accounting complies with applicable standards | Policies and procedures designed to ensure accuracy and prevent errors in lease accounting | Division of responsibilities to prevent fraud and ensure accuracy | Record of all system transactions and changes for audit purposes | Connection of lease accounting system with other financial systems | Process of ensuring lease data is accurate and complete | Comparison of lease accounting records with source documents and calculations");
    record0.set("examples", "System tracks 500+ leases across multiple business units | Lease terms extracted from PDF agreements into standardized database | Register shows all leases with payment amounts, terms, and accounting treatment | Testing confirms all leases properly classified and measured | Controls include approval workflows and monthly reconciliations | Lease negotiation, accounting, and payment processing handled by different people | System logs show who accessed lease data and when changes were made | Lease system feeds data to general ledger and financial reporting system | Validation rules check for required fields and reasonable values | Monthly reconciliation of lease register to general ledger");
    record0.set("crossReferences", "Related to: Lease Implementation, System Selection | Related to: Lease Data, Data Management | Related to: Lease Accounting, Lease Records | Related to: Lease Compliance, Audit Procedures | Related to: Lease Controls, Risk Management | Related to: Lease Controls, Fraud Prevention | Related to: Lease Audit, Audit Evidence | Related to: Lease Systems, System Architecture | Related to: Lease Data, Data Quality | Related to: Lease Accounting, Account Reconciliation");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lessonId", "lesson_4");
    record1.set("termCount", 10);
    record1.set("terms", "Lease Portfolio | Lease Optimization | Lease Renewal Planning | Lease Termination | Lease Modification | Lease Consolidation | Vendor Management | Lease Reporting | Lease Metrics | Lease Compliance");
    record1.set("definitions", "Collection of all leases held by an organization across all business units and asset types | Process of analyzing leases to identify opportunities for cost reduction or improved terms | Proactive planning for lease renewals to negotiate favorable terms | Process of ending a lease before or at the end of the lease term | Change to lease terms after the lease commencement date | Consolidation of multiple leases with same vendor to improve negotiating position | Management of relationships with lease vendors and landlords | Preparation of reports on lease portfolio status and performance | Key performance indicators used to evaluate lease portfolio performance | Adherence to lease accounting standards and internal policies");
    record1.set("examples", "Portfolio of 200 leases totaling $5 million in annual payments | Analysis identifies $500,000 in potential annual savings through renegotiation | Planning begins 6 months before lease expiration to negotiate renewal terms | Lease terminated early with $50,000 penalty due to facility closure | Lease term extended by 2 years with modified payment structure | Consolidating 5 separate equipment leases with one vendor for volume discount | Vendor management includes performance reviews and relationship building | Monthly reports show lease obligations, upcoming renewals, and compliance status | Metrics include cost per unit, lease term, and payment frequency | Compliance verified through quarterly audits and management review");
    record1.set("crossReferences", "Related to: Lease Management, Portfolio Management | Related to: Lease Economics, Cost Reduction | Related to: Lease Planning, Strategic Planning | Related to: Lease Accounting, Lease Termination | Related to: Lease Accounting, Lease Modification | Related to: Lease Negotiation, Vendor Management | Related to: Lease Relationships, Vendor Management | Related to: Lease Accounting, Financial Reporting | Related to: Lease Analysis, Performance Measurement | Related to: Lease Accounting, Compliance");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lessonId", "lesson_4");
    record2.set("termCount", 10);
    record2.set("terms", "ASC 842 | IFRS 16 | Lease Classification | Operating Lease Expense | Finance Lease Interest | Depreciation Expense | Lease Disclosure | Segment Reporting | Related Party Leases | Lease Modifications Accounting");
    record2.set("definitions", "Accounting Standards Codification Topic 842 - the U.S. GAAP standard for lease accounting | International Financial Reporting Standard 16 - the IFRS standard for lease accounting | Determination of whether a lease is classified as operating or finance lease | Expense recognized for operating leases, typically on a straight-line basis | Interest expense component of finance lease payments | Depreciation of the right-of-use asset over the lease term | Required disclosures about lease obligations, terms, and accounting policies | Disclosure of leases by business segment if material | Leases between related parties that require special disclosure | Accounting treatment of changes to lease terms after commencement");
    record2.set("examples", "ASC 842 requires recognition of ROU asset and lease liability for most leases | IFRS 16 similar to ASC 842 with minor differences in measurement | Lease classified as operating if present value of payments less than 90% of asset value | Operating lease expense of $1,000/month recognized on straight-line basis | Finance lease interest expense of $500 in year 1, declining over lease term | ROU asset depreciated over lease term using straight-line method | Disclosures include lease obligations schedule and significant lease terms | Segment reporting shows leases by business unit if material | Related party lease with parent company requires disclosure of terms | Lease modification to extend term by 2 years requires remeasurement of liability");
    record2.set("crossReferences", "Related to: Lease Accounting Standards, Accounting Requirements | Related to: Lease Accounting Standards, International Standards | Related to: Lease Accounting, Lease Classification | Related to: Lease Accounting, Expense Recognition | Related to: Lease Accounting, Interest Expense | Related to: Lease Accounting, Asset Depreciation | Related to: Lease Accounting, Financial Reporting | Related to: Lease Accounting, Segment Reporting | Related to: Lease Accounting, Related Party Transactions | Related to: Lease Accounting, Lease Changes");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
