/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_2_1");
    record0.set("content_body", "# Lease vs. Buy Analysis\n\n## Framework Overview\n\n**Key Considerations:**\n1. **Financial Factors:** Total cost of ownership (TCO), Cash flow impact, Tax implications, Residual value risk\n2. **Operational Factors:** Equipment maintenance, Flexibility and upgrades, Obsolescence risk, Downtime and reliability\n3. **Strategic Factors:** Capital preservation, Balance sheet impact, Accounting treatment, Competitive advantage\n4. **Risk Factors:** Technology risk, Market risk, Operational risk, Financial risk\n\n## Total Cost of Ownership (TCO)\n\n**TCO Components:**\n- **Acquisition:** Equipment + Delivery + Installation + Setup\n- **Operating:** Maintenance + Insurance + Taxes + Utilities\n- **Financing:** Interest on borrowed funds + Opportunity cost\n- **Residual Value:** Estimated value at end of useful life\n- **Tax Impacts:** Depreciation deductions, Lease payment deductions\n\n**Formula:** TCO = Acquisition + Operating + Financing - Residual - Tax Benefits\n\n## Lease vs. Buy Comparison\n\n**Lease Option:**\n- Monthly payment: $2,000\n- Total payments (5 years): $120,000\n- Setup: $3,000\n- Total cost: $123,000\n- Tax savings: $36,900\n- **Net cost: $86,100**\n\n**Buy Option:**\n- Equipment: $100,000\n- Delivery: $5,000\n- Setup: $3,000\n- Maintenance (5 years): $35,000\n- Insurance: $10,000\n- Financing: $30,000\n- Total: $183,000\n- Residual value: $20,000\n- Tax benefits: $30,000\n- **Net cost: $133,000**\n\n**Savings with Lease: $46,900 (35% lower)**\n\n## Qualitative Factors\n\n**Lease Advantages:** Lower upfront capital, Predictable costs, No residual risk, Flexibility, No maintenance burden, Off-balance sheet\n\n**Lease Disadvantages:** No ownership, Usage restrictions, Early termination penalties, Long-term commitment, Less control\n\n**Buy Advantages:** Full ownership, No restrictions, Can modify, No penalties, Potential residual gain\n\n**Buy Disadvantages:** High upfront capital, Maintenance responsibility, Residual risk, Obsolescence risk, Inflexible, On-balance sheet\n\n## Case Study: ManufacturingCorp Inc.\n\n**Lease:** $8,500/month \u00d7 60 = $510K + $10K setup = $520K, Tax deduction $156K, Net $364K\n\n**Buy:** $500K + $25K + $10K + $60K + $30K + $75K = $700K, Residual $100K, Tax $150K, Net $450K\n\n**Savings: $86K (19% lower with lease)**\n\n**Decision:** Lease is better - more cost-effective, flexible, and preserves capital");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_2_2");
    record1.set("content_body", "# ROI Optimization Strategies\n\n## Seven Key Strategies\n\n**Strategy 1 - Increase Revenue:**\n- Increase lease payment\n- Extend lease term\n- Add value-added services\n- Increase equipment utilization\n- Example: $1,500 to $1,550 = 3.3% higher revenue\n\n**Strategy 2 - Reduce Costs:**\n- Negotiate maintenance contracts\n- Reduce insurance costs\n- Improve operational efficiency\n- Reduce overhead\n- Example: $300 to $250/month = $3K savings over 5 years\n\n**Strategy 3 - Improve Residual Value:**\n- Better equipment selection\n- Improved maintenance\n- Accurate estimation\n- Secondary market development\n- Example: 30% vs 25% residual = higher profit\n\n**Strategy 4 - Reduce Cost of Capital:**\n- Improve credit rating\n- Negotiate better rates\n- Increase equity\n- Diversify funding\n- Example: 6% to 5% = 1% higher profit\n\n**Strategy 5 - Improve Credit Quality:**\n- Better credit analysis\n- Reduce default rate\n- Improve collection\n- Reduce loss severity\n- Example: 2% to 1% default = 1% higher ROI\n\n**Strategy 6 - Optimize Portfolio Mix:**\n- Increase high-margin leases\n- Reduce low-margin leases\n- Diversify\n- Balance risk/return\n- Example: 30% premium, 70% standard = higher ROI\n\n**Strategy 7 - Leverage and Scale:**\n- Increase portfolio size\n- Improve operational leverage\n- Reduce per-lease costs\n- Achieve economies of scale\n- Example: Double portfolio = 10% cost reduction\n\n## ROI Optimization Framework\n\n**Step 1 - Baseline Analysis (2 weeks):**\nCalculate current ROI, Identify drivers, Benchmark against industry, Identify opportunities\n\n**Step 2 - Develop Plan (2 weeks):**\nPrioritize opportunities, Set targets, Develop implementation, Estimate impact\n\n**Step 3 - Implement (3-6 months):**\nExecute initiatives, Monitor progress, Adjust as needed\n\n**Step 4 - Measure Results (1 month):**\nCalculate new ROI, Compare to baseline, Assess impact\n\n**Step 5 - Continuous Improvement (Ongoing):**\nIdentify new opportunities, Refine strategies, Maintain improvements\n\n## Case Study: LeaseCorp Portfolio Optimization\n\n**Current State:** 100 leases, $100K average, $1,500/month, 60-month term, 25% residual, $300/month costs, 10% ROI, 2% default\n\n**Initiatives:**\n1. Increase payments $1,500\u2192$1,550: +$300K revenue, +0.5% ROI\n2. Reduce costs $300\u2192$250: +$300K savings, +0.5% ROI\n3. Improve residual 25%\u219228%: +$300K value, +0.5% ROI\n4. Reduce default 2%\u21921%: +$100K savings, +0.2% ROI\n5. Optimize mix 30% premium/70% standard: +0.3% ROI\n\n**Results:** 10% to 11.5% ROI (15% improvement), +$1.15M annual profit on $100M portfolio\n\n**Timeline:** Months 1-2 initiatives 1-3, Months 3-4 initiatives 4-5, Months 5-6 monitor, Month 7+ maintain");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_2_3");
    record2.set("content_body", "# Advanced ROI Metrics and Analysis\n\n## Advanced ROI Metrics\n\n**Return on Assets (ROA):**\n- Formula: Net Income / Total Assets\n- Measures asset efficiency\n- Higher = better utilization\n- Example: $10M / $100M = 10% ROA\n\n**Return on Equity (ROE):**\n- Formula: Net Income / Equity\n- Measures shareholder returns\n- Higher = better returns\n- Example: $10M / $50M = 20% ROE\n\n**Return on Invested Capital (ROIC):**\n- Formula: NOPAT / Invested Capital\n- Measures return on all capital\n- Useful for comparisons\n- Example: $8M / $80M = 10% ROIC\n\n**Economic Value Added (EVA):**\n- Formula: NOPAT - (Invested Capital \u00d7 WACC)\n- Measures value above cost of capital\n- Positive = value creation\n- Example: $8M - ($80M \u00d7 8%) = $1.6M EVA\n\n**Residual Income (RI):**\n- Formula: Net Income - (Equity \u00d7 Cost of Equity)\n- Measures income above cost of equity\n- Positive = value creation\n- Example: $10M - ($50M \u00d7 12%) = $4M RI\n\n## Risk-Adjusted Returns\n\n**Sharpe Ratio:**\n- Formula: (Return - Risk-Free Rate) / Standard Deviation\n- Measures return per unit of risk\n- Higher = better\n- Example: (12% - 3%) / 8% = 1.125\n\n**Sortino Ratio:**\n- Formula: (Return - Risk-Free Rate) / Downside Deviation\n- Focuses on downside risk\n- Higher = better\n- Example: (12% - 3%) / 5% = 1.8\n\n**Information Ratio:**\n- Formula: (Portfolio Return - Benchmark) / Tracking Error\n- Measures excess return vs benchmark\n- Higher = better\n- Example: (12% - 10%) / 3% = 0.67\n\n## Case Study: EquipmentCorp Advanced Metrics\n\n**Portfolio:** $500M assets, $250M equity, $50M net income, $40M NOPAT, $400M invested capital, 8% WACC, 12% cost of equity, 3% risk-free rate, 12% return, 8% std dev, 10% benchmark, 3% tracking error\n\n**Metrics:**\n- **ROA:** $50M / $500M = 10% (good asset efficiency)\n- **ROE:** $50M / $250M = 20% (strong shareholder returns)\n- **ROIC:** $40M / $400M = 10% (good return on capital)\n- **EVA:** $40M - ($400M \u00d7 8%) = $8M (creating value above cost of capital)\n- **RI:** $50M - ($250M \u00d7 12%) = $20M (creating value above cost of equity)\n- **Sharpe:** (12% - 3%) / 8% = 1.125 (good risk-adjusted return)\n- **Sortino:** (12% - 3%) / 5% = 1.8 (excellent risk-adjusted return)\n- **Information:** (12% - 10%) / 3% = 0.67 (outperforming benchmark)\n\n**Conclusion:** Strong absolute returns, good risk-adjusted returns, outperforming benchmark, creating significant value, well-managed portfolio");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
