/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("vendor_leasing_glossaries");

  const record0 = new Record(collection);
    record0.set("lessonId", "lesson_5_placeholder");
    record0.set("termCount", 10);
    record0.set("terms", "Right-of-Use Asset|Lease Liability|ASC 842|IFRS 16|Operating Lease|Finance Lease|Incremental Borrowing Rate|Lease Modification|Residual Value Guarantee|Lease Disclosure");
    record0.set("definitions", "Right-of-Use Asset: The lessee's right to use an underlying asset for the lease term, recognized on the balance sheet as an asset.\n\nLease Liability: The lessee's obligation to make lease payments, measured as the present value of all lease payments discounted at the incremental borrowing rate.\n\nASC 842: The Financial Accounting Standards Board (FASB) standard for lease accounting in the United States, effective for public companies in 2019 and for private companies in 2022.\n\nIFRS 16: The International Financial Reporting Standards equivalent to ASC 842, effective January 1, 2019, requiring recognition of most leases on the balance sheet.\n\nOperating Lease: A lease that does not meet any of the finance lease criteria and is recognized as a single lease expense on a straight-line basis over the lease term.\n\nFinance Lease: A lease that transfers substantially all the risks and rewards of ownership to the lessee, requiring recognition of both a ROU asset and lease liability.\n\nIncremental Borrowing Rate: The rate the lessee would incur to borrow funds to purchase the underlying asset, used to discount lease payments.\n\nLease Modification: A change to the terms and conditions of an existing lease, which may require remeasurement of the ROU asset and lease liability.\n\nResidual Value Guarantee: The lessee's promise to pay the difference if the asset's fair value at lease end is less than the guaranteed residual value.\n\nLease Disclosure: The quantitative and qualitative information required to be disclosed in the financial statements regarding lease arrangements, including ROU assets, liabilities, and lease expenses.");
    record0.set("examples", "Right-of-Use Asset: A company leases manufacturing equipment for 5 years and recognizes a ROU asset representing its right to use the equipment during the lease term.\n\nLease Liability: The present value of all monthly lease payments of $10,000 for 60 months, discounted at the company's incremental borrowing rate of 5%.\n\nASC 842: A US-based company must apply ASC 842 to all leases in its financial statements, recognizing ROU assets and liabilities for most leases.\n\nIFRS 16: A multinational company with operations in Europe applies IFRS 16 to its lease accounting in those jurisdictions.\n\nOperating Lease: A company leases office space for 3 years and recognizes a single annual lease expense rather than depreciation and interest.\n\nFinance Lease: A company leases equipment with a purchase option that it is reasonably certain to exercise, requiring recognition of both asset and liability.\n\nIncremental Borrowing Rate: A company determines its incremental borrowing rate is 6% based on the rate it would pay to borrow funds for a similar term and amount.\n\nLease Modification: A company and lessor agree to extend the lease term by 2 years, requiring recalculation of the ROU asset and lease liability.\n\nResidual Value Guarantee: A company guarantees the leased equipment will be worth at least $50,000 at lease end; if it's worth only $40,000, the company pays the $10,000 difference.\n\nLease Disclosure: The company discloses in its financial statements the total ROU assets of $5 million, lease liabilities of $4.8 million, and annual lease expense of $1.2 million.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lessonId", "lesson_6_placeholder");
    record1.set("termCount", 10);
    record1.set("terms", "Credit Risk|Residual Value Risk|Compliance|Regulatory Framework|Insurance Coverage|Default Management|Covenant|Risk Mitigation|Credit Assessment|Recovery Procedures");
    record1.set("definitions", "Credit Risk: The risk that a lessee will fail to meet its lease payment obligations, representing the primary concern for lessors.\n\nResidual Value Risk: The risk that the actual value of the leased asset at the end of the lease term will be less than the estimated residual value.\n\nCompliance: Adherence to all applicable laws, regulations, and standards governing lease transactions and financial reporting.\n\nRegulatory Framework: The set of federal, state, and industry regulations that govern lease transactions, including TILA, ECOA, UCC, and GLBA.\n\nInsurance Coverage: Protection against financial loss through various insurance policies, including property, liability, credit, and equipment insurance.\n\nDefault Management: The process of identifying, monitoring, and managing lease defaults, including escalation procedures and recovery actions.\n\nCovenant: A restriction or obligation imposed on the lessee in the lease agreement to protect the lessor's interests and ensure payment capacity.\n\nRisk Mitigation: Strategies and actions taken to reduce or manage identified risks, including diversification, pricing, and monitoring.\n\nCredit Assessment: The process of evaluating a lessee's creditworthiness and ability to meet lease payment obligations.\n\nRecovery Procedures: The steps taken to recover funds or assets following a lessee default, including repossession, asset sale, and collection efforts.");
    record1.set("examples", "Credit Risk: A lessor assesses that a lessee with declining revenues and increasing debt levels presents high credit risk.\n\nResidual Value Risk: Equipment estimated to be worth $100,000 at lease end is actually worth only $70,000 due to technological obsolescence.\n\nCompliance: A lessor ensures all lease agreements include required TILA disclosures and maintains records for the required retention period.\n\nRegulatory Framework: A lessor must comply with TILA requirements for disclosure of APR and finance charges in all lease agreements.\n\nInsurance Coverage: The lessor requires the lessee to maintain property insurance with the lessor named as loss payee and liability insurance with minimum limits.\n\nDefault Management: When a lessee misses a payment, the lessor initiates contact, provides notice of default, and follows escalation procedures.\n\nCovenant: The lease agreement includes a covenant requiring the lessee to maintain a minimum debt service coverage ratio of 1.25x.\n\nRisk Mitigation: The lessor diversifies its portfolio across multiple industries and limits exposure to any single lessee to 5% of total assets.\n\nCredit Assessment: The lessor reviews the lessee's financial statements, analyzes key ratios, and checks credit references before approving the lease.\n\nRecovery Procedures: Following default, the lessor repossesses the equipment, sells it for $60,000, and pursues collection of the $40,000 deficiency.");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
