/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "Lesson 3.1: Value Creation and Win-Win Solutions");
    record0.set("content_body", "# Value Creation and Win-Win Solutions\n\n## Understanding Value in Lease Sales\nValue extends beyond monthly payments to include financial, service, flexibility, relationship, and strategic value. Different customers prioritize different aspects: cost-conscious focus on total cost, service-oriented on support, growth-focused on flexibility, risk-averse on stability.\n\n## Value Creation Strategies\n**Customized Solutions**: Flexible payment structures, bundled services, upgrade pathways\n**Enhanced Services**: Proactive maintenance, 24/7 support, training, performance monitoring\n**Strategic Partnerships**: Vendor relationships, technology integration, industry expertise\n**Financial Optimization**: Tax efficiency, cash flow management, ROI enhancement\n\n## Win-Win Negotiation Principles\n- Separate people from problems\n- Focus on interests, not positions\n- Generate multiple options\n- Use objective criteria\n- Create mutual gains through trade-offs, bundling, timing adjustments\n\n## Creative Problem-Solving\nBrainstorm framework: Define problem \u2192 Generate ideas \u2192 Evaluate and refine. Common solutions: phased implementation, performance-based pricing, shared risk models, contingent agreements, hybrid arrangements.\n\n## Case Study: Value Creation\nManufacturer needed 50 machines. Instead of price reduction, offered: graduated payments aligned with seasonal revenue, comprehensive maintenance package, equipment uptime guarantee, upgrade path after 3 years. Result: Customer got lower effective cost and better operations; company increased margins and loyalty.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "Lesson 3.2: Closing Techniques and Deal Finalization");
    record1.set("content_body", "# Closing Techniques and Deal Finalization\n\n## Recognizing Buying Signals\n**Verbal**: \"When would we start?\", \"How quickly can you set up?\", questions about implementation, positive comparisons, concern-based signals\n**Non-Verbal**: Leaning forward, nodding, relaxed posture, increased eye contact, taking notes, requesting proposals\n**Timing**: References to specific dates and deadlines\n\n## Closing Techniques\n1. **Assumptive Close**: Assume decision made, proceed with next steps\n2. **Alternative Close**: Present two positive options (36 vs 48 months)\n3. **Summary Close**: Summarize agreed terms, ask for commitment\n4. **Urgency Close**: Create legitimate time-based reasons (pricing expires, limited inventory)\n5. **Takeaway Close**: Suggest deal might not be right fit\n6. **Question Close**: Ask what prevents moving forward\n\n## Deal Finalization Process\n1. Confirm all terms in writing\n2. Obtain necessary approvals (internal and customer)\n3. Complete all documentation\n4. Establish implementation timeline\n5. Transition to service team\n6. Post-close follow-up (24-48 hours, pre-delivery, post-delivery)\n\n## Case Study: Closing Techniques\nCFO hesitant despite VP enthusiasm. Used question close to uncover real concern (service quality, not price). Provided reassurance with case studies and guarantees. Used summary close, created urgency, then alternative close. Result: 48-month commitment within 48 hours.");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "Lesson 3.3: Post-Negotiation and Relationship Management");
    record2.set("content_body", "# Post-Negotiation and Relationship Management\n\n## Post-Negotiation Follow-Up\n**First 48 Hours**: Thank you communication, confirm details, introduce service team, address concerns\n**First 30 Days**: Monitor delivery/setup, provide training, initial check-in, handoff documentation\n**First 90 Days**: Regular communication, performance monitoring, relationship development, feedback collection\n\n## Relationship Management Principles\n1. **Consistent Communication**: Monthly check-ins, quarterly reviews, annual strategy sessions\n2. **Exceed Expectations**: Faster response, proactive problem-solving, value addition\n3. **Build Trust**: Honest communication, transparency, confidentiality\n4. **Understand Their Business**: Learn industry, understand goals, provide contextual recommendations\n5. **Develop Personal Relationships**: Identify stakeholders, build individual relationships, personal touch\n\n## Upselling and Cross-Selling\n**Upselling**: Service upgrades, equipment additions, extended coverage (after satisfaction)\n**Cross-Selling**: Complementary products, related services, new solutions (based on needs)\n**Retention**: Monitor warning signs, proactive outreach, demonstrate value, strengthen relationships\n\n## Case Study: Relationship Management\nTech company grew 40%, expanding to new office. Congratulated on growth, conducted service review, built relationships with new contacts, proposed comprehensive solution (20 additional workstations + software), facilitated smooth expansion. Result: Secured expansion deal, cross-sold software, moved from vendor to trusted advisor, positioned for future growth.");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
