/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("vendor_leasing_glossaries");

  const record0 = new Record(collection);
    record0.set("lessonId", "lesson_3");
    record0.set("termCount", 10);
    record0.set("terms", "Net Present Value (NPV) | Internal Rate of Return (IRR) | Discount Rate | Sensitivity Analysis | Scenario Planning | Lease Negotiation | Payment Structure | Renewal Option | Termination Clause | Residual Value");
    record0.set("definitions", "The present value of future cash flows discounted at an appropriate rate, used to evaluate lease economics | The discount rate at which the present value of lease payments equals the lease cost, used to compare lease alternatives | The rate used to discount future lease payments to present value, reflecting the time value of money and risk | Analysis of how changes in key assumptions (payment amounts, terms, rates) affect lease economics | Development of multiple lease scenarios with different assumptions to evaluate outcomes | Process of discussing and agreeing upon lease terms between lessor and lessee | Structure of lease payments including amounts, timing, and frequency | Right to renew the lease at the end of the initial term, typically at predetermined rates | Right to terminate the lease before the end of the term, often with penalties | Estimated value of the leased asset at the end of the lease term");
    record0.set("examples", "A lease with $1,000 monthly payments for 5 years has a lower NPV than one with $1,200 payments for 3 years | A lease with an IRR of 8% is more attractive than one with an IRR of 10% | A 5% discount rate reflects lower risk than a 10% rate | Changing the discount rate from 5% to 7% may significantly impact the lease decision | Scenarios might include best case, worst case, and most likely outcomes | Negotiating lower payments, favorable renewal terms, and flexible termination | Payments might be structured as monthly, quarterly, or annual amounts | A renewal option at 50% of original rent provides flexibility and cost savings | A termination clause allowing exit after 3 years limits long-term commitment | A residual value guarantee protects the lessor if asset value declines");
    record0.set("crossReferences", "Related to: Lease Valuation, Financial Analysis | Related to: Lease Comparison, Investment Analysis | Related to: Time Value of Money, Financial Calculations | Related to: Risk Assessment, Decision Making | Related to: Strategic Planning, Lease Strategy | Related to: Vendor Management, Contract Terms | Related to: Cash Flow Management, Financial Planning | Related to: Lease Flexibility, Risk Management | Related to: Lease Exit, Risk Mitigation | Related to: Asset Valuation, Lease Economics");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lessonId", "lesson_3");
    record1.set("termCount", 10);
    record1.set("terms", "Escalation Clause | Variable Lease Payments | Contingent Rentals | Lease Incentives | Subleasing | Lease Modification | Purchase Option | Bargain Purchase Option | Implicit Rate | Incremental Borrowing Rate");
    record1.set("definitions", "Provision in lease agreement that increases payments over time, typically tied to inflation or other indices | Lease payments that vary based on factors such as usage, sales, or index changes | Payments that depend on the occurrence of specified events or conditions | Concessions provided by lessor such as free rent periods or payment reductions | Arrangement where lessee rents the leased asset to another party | Change to lease terms after the lease commencement date | Right to purchase the leased asset at the end of the lease term | Purchase option where the price is so favorable that exercise is reasonably certain | The discount rate implicit in the lease, used if readily determinable | The rate the lessee would incur to borrow funds for a similar term and security");
    record1.set("examples", "A lease with 3% annual escalation increases payments from $1,000 to $1,030 in year 2 | Payments vary based on equipment usage measured in machine hours | Rent is reduced if sales targets are not met | Lessor provides 3 months free rent at the beginning of the lease | Lessee subleases equipment to another company for higher payments | Lease term extended by 2 years with modified payment terms | Option to purchase equipment for $5,000 at end of 5-year lease | Option to purchase for $1,000 when fair value is $50,000 | Lease specifies 6% implicit rate for calculating present value | Lessee's borrowing rate of 7% used to calculate present value");
    record1.set("crossReferences", "Related to: Lease Payments, Payment Terms | Related to: Lease Economics, Cost Analysis | Related to: Lease Accounting, ASC 842 | Related to: Lease Incentives, Lease Costs | Related to: Lease Obligations, Accounting Treatment | Related to: Lease Changes, Accounting Updates | Related to: Lease Options, Lease Terms | Related to: Lease Accounting, Lease Classification | Related to: Discount Rate, Present Value | Related to: Lease Valuation, Discount Rate");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lessonId", "lesson_3");
    record2.set("termCount", 10);
    record2.set("terms", "Right-of-Use Asset (ROU) | Lease Liability | Operating Lease | Finance Lease | Lease Classification | Lease Commencement Date | Lease Term | Lease Payments | Initial Direct Costs | Lease Incentives Received");
    record2.set("definitions", "Asset recognized on balance sheet representing the lessee's right to use the leased asset | Liability recognized on balance sheet representing the lessee's obligation to make lease payments | Lease where the lessor retains substantially all risks and rewards of asset ownership | Lease where the lessee obtains substantially all risks and rewards of asset ownership | Determination of whether a lease is operating or finance lease based on criteria | Date when the lessee obtains the right to use the leased asset | Period during which the lessee has the right to use the leased asset | Consideration paid by the lessee for the right to use the leased asset | Costs incurred by the lessee to obtain the lease, such as legal fees | Payments or concessions received from the lessor to incentivize the lease");
    record2.set("examples", "ROU asset of $50,000 represents the present value of lease payments | Lease liability of $50,000 is reduced as payments are made | Operating lease for office space with no purchase option | Finance lease for equipment with transfer of ownership at end | Lease classified as finance lease if present value of payments exceeds 90% of asset value | Lease commencement date is when lessee takes possession of asset | Lease term of 5 years with option to renew for 2 additional years | Monthly lease payments of $1,000 for 60 months | Legal fees of $500 to negotiate and execute lease agreement | Lessor provides $5,000 rent reduction in first year");
    record2.set("crossReferences", "Related to: Lease Accounting, Balance Sheet | Related to: Lease Accounting, Lease Liability | Related to: Lease Accounting, Expense Recognition | Related to: Lease Accounting, Lease Classification | Related to: Lease Accounting, Lease Recognition | Related to: Lease Accounting, Lease Commencement | Related to: Lease Accounting, Lease Term | Related to: Lease Accounting, Lease Payments | Related to: Lease Accounting, Initial Measurement | Related to: Lease Accounting, Lease Incentives");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
