/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("quiz_performance_tracking");

  const record0 = new Record(collection);
    record0.set("dashboard_id", "demo_student_001");
    record0.set("quiz_number", 1);
    record0.set("lesson_id", "lesson_1");
    record0.set("quiz_score", 45);
    record0.set("quiz_completion_date", "2026-01-28");
    record0.set("quiz_attempts", 1);
    record0.set("total_quizzes_completed", 4);
    record0.set("average_quiz_score", 40);
    record0.set("highest_quiz_score", 48);
    record0.set("lowest_quiz_score", 32);
    record0.set("quiz_completion_rate_percentage", 40);
    record0.set("performance_trend", "Stable");
    record0.set("improvement_rate_percentage", 5);
    record0.set("projected_final_quiz_score", 42);
    record0.set("total_questions_answered", 120);
    record0.set("correct_answers", 96);
    record0.set("incorrect_answers", 20);
    record0.set("skipped_questions", 4);
    record0.set("average_time_per_question_seconds", 45);
    record0.set("easy_questions_correct_percentage", 85);
    record0.set("medium_questions_correct_percentage", 75);
    record0.set("hard_questions_correct_percentage", 60);
    record0.set("difficulty_trend", "Student performing better on easy questions");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("dashboard_id", "demo_student_001");
    record1.set("quiz_number", 2);
    record1.set("lesson_id", "lesson_2");
    record1.set("quiz_score", 48);
    record1.set("quiz_completion_date", "2026-02-01");
    record1.set("quiz_attempts", 1);
    record1.set("total_quizzes_completed", 4);
    record1.set("average_quiz_score", 40);
    record1.set("highest_quiz_score", 48);
    record1.set("lowest_quiz_score", 32);
    record1.set("quiz_completion_rate_percentage", 40);
    record1.set("performance_trend", "Improving");
    record1.set("improvement_rate_percentage", 5);
    record1.set("projected_final_quiz_score", 42);
    record1.set("total_questions_answered", 120);
    record1.set("correct_answers", 96);
    record1.set("incorrect_answers", 20);
    record1.set("skipped_questions", 4);
    record1.set("average_time_per_question_seconds", 45);
    record1.set("easy_questions_correct_percentage", 85);
    record1.set("medium_questions_correct_percentage", 75);
    record1.set("hard_questions_correct_percentage", 60);
    record1.set("difficulty_trend", "Student performing better on easy questions");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("dashboard_id", "demo_student_001");
    record2.set("quiz_number", 3);
    record2.set("lesson_id", "lesson_3");
    record2.set("quiz_score", 38);
    record2.set("quiz_completion_date", "2026-02-04");
    record2.set("quiz_attempts", 2);
    record2.set("total_quizzes_completed", 4);
    record2.set("average_quiz_score", 40);
    record2.set("highest_quiz_score", 48);
    record2.set("lowest_quiz_score", 32);
    record2.set("quiz_completion_rate_percentage", 40);
    record2.set("performance_trend", "Stable");
    record2.set("improvement_rate_percentage", 5);
    record2.set("projected_final_quiz_score", 42);
    record2.set("total_questions_answered", 120);
    record2.set("correct_answers", 96);
    record2.set("incorrect_answers", 20);
    record2.set("skipped_questions", 4);
    record2.set("average_time_per_question_seconds", 45);
    record2.set("easy_questions_correct_percentage", 85);
    record2.set("medium_questions_correct_percentage", 75);
    record2.set("hard_questions_correct_percentage", 60);
    record2.set("difficulty_trend", "Student performing better on easy questions");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("dashboard_id", "demo_student_001");
    record3.set("quiz_number", 4);
    record3.set("lesson_id", "lesson_4");
    record3.set("quiz_score", 32);
    record3.set("quiz_completion_date", "2026-02-08");
    record3.set("quiz_attempts", 3);
    record3.set("total_quizzes_completed", 4);
    record3.set("average_quiz_score", 40);
    record3.set("highest_quiz_score", 48);
    record3.set("lowest_quiz_score", 32);
    record3.set("quiz_completion_rate_percentage", 40);
    record3.set("performance_trend", "Declining");
    record3.set("improvement_rate_percentage", 5);
    record3.set("projected_final_quiz_score", 42);
    record3.set("total_questions_answered", 120);
    record3.set("correct_answers", 96);
    record3.set("incorrect_answers", 20);
    record3.set("skipped_questions", 4);
    record3.set("average_time_per_question_seconds", 45);
    record3.set("easy_questions_correct_percentage", 85);
    record3.set("medium_questions_correct_percentage", 75);
    record3.set("hard_questions_correct_percentage", 60);
    record3.set("difficulty_trend", "Student performing better on easy questions");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("dashboard_id", "demo_student_001");
    record4.set("quiz_number", 5);
    record4.set("lesson_id", "lesson_5");
    record4.set("quiz_score", 0);
    record4.set("quiz_completion_date", null);
    record4.set("quiz_attempts", 0);
    record4.set("total_quizzes_completed", 4);
    record4.set("average_quiz_score", 40);
    record4.set("highest_quiz_score", 48);
    record4.set("lowest_quiz_score", 32);
    record4.set("quiz_completion_rate_percentage", 40);
    record4.set("performance_trend", "Stable");
    record4.set("improvement_rate_percentage", 5);
    record4.set("projected_final_quiz_score", 42);
    record4.set("total_questions_answered", 120);
    record4.set("correct_answers", 96);
    record4.set("incorrect_answers", 20);
    record4.set("skipped_questions", 4);
    record4.set("average_time_per_question_seconds", 45);
    record4.set("easy_questions_correct_percentage", 85);
    record4.set("medium_questions_correct_percentage", 75);
    record4.set("hard_questions_correct_percentage", 60);
    record4.set("difficulty_trend", "Student performing better on easy questions");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("dashboard_id", "demo_student_001");
    record5.set("quiz_number", 6);
    record5.set("lesson_id", "lesson_6");
    record5.set("quiz_score", 0);
    record5.set("quiz_completion_date", null);
    record5.set("quiz_attempts", 0);
    record5.set("total_quizzes_completed", 4);
    record5.set("average_quiz_score", 40);
    record5.set("highest_quiz_score", 48);
    record5.set("lowest_quiz_score", 32);
    record5.set("quiz_completion_rate_percentage", 40);
    record5.set("performance_trend", "Stable");
    record5.set("improvement_rate_percentage", 5);
    record5.set("projected_final_quiz_score", 42);
    record5.set("total_questions_answered", 120);
    record5.set("correct_answers", 96);
    record5.set("incorrect_answers", 20);
    record5.set("skipped_questions", 4);
    record5.set("average_time_per_question_seconds", 45);
    record5.set("easy_questions_correct_percentage", 85);
    record5.set("medium_questions_correct_percentage", 75);
    record5.set("hard_questions_correct_percentage", 60);
    record5.set("difficulty_trend", "Student performing better on easy questions");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("dashboard_id", "demo_student_001");
    record6.set("quiz_number", 7);
    record6.set("lesson_id", "lesson_7");
    record6.set("quiz_score", 0);
    record6.set("quiz_completion_date", null);
    record6.set("quiz_attempts", 0);
    record6.set("total_quizzes_completed", 4);
    record6.set("average_quiz_score", 40);
    record6.set("highest_quiz_score", 48);
    record6.set("lowest_quiz_score", 32);
    record6.set("quiz_completion_rate_percentage", 40);
    record6.set("performance_trend", "Stable");
    record6.set("improvement_rate_percentage", 5);
    record6.set("projected_final_quiz_score", 42);
    record6.set("total_questions_answered", 120);
    record6.set("correct_answers", 96);
    record6.set("incorrect_answers", 20);
    record6.set("skipped_questions", 4);
    record6.set("average_time_per_question_seconds", 45);
    record6.set("easy_questions_correct_percentage", 85);
    record6.set("medium_questions_correct_percentage", 75);
    record6.set("hard_questions_correct_percentage", 60);
    record6.set("difficulty_trend", "Student performing better on easy questions");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("dashboard_id", "demo_student_001");
    record7.set("quiz_number", 8);
    record7.set("lesson_id", "lesson_8");
    record7.set("quiz_score", 0);
    record7.set("quiz_completion_date", null);
    record7.set("quiz_attempts", 0);
    record7.set("total_quizzes_completed", 4);
    record7.set("average_quiz_score", 40);
    record7.set("highest_quiz_score", 48);
    record7.set("lowest_quiz_score", 32);
    record7.set("quiz_completion_rate_percentage", 40);
    record7.set("performance_trend", "Stable");
    record7.set("improvement_rate_percentage", 5);
    record7.set("projected_final_quiz_score", 42);
    record7.set("total_questions_answered", 120);
    record7.set("correct_answers", 96);
    record7.set("incorrect_answers", 20);
    record7.set("skipped_questions", 4);
    record7.set("average_time_per_question_seconds", 45);
    record7.set("easy_questions_correct_percentage", 85);
    record7.set("medium_questions_correct_percentage", 75);
    record7.set("hard_questions_correct_percentage", 60);
    record7.set("difficulty_trend", "Student performing better on easy questions");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("dashboard_id", "demo_student_001");
    record8.set("quiz_number", 9);
    record8.set("lesson_id", "lesson_9");
    record8.set("quiz_score", 0);
    record8.set("quiz_completion_date", null);
    record8.set("quiz_attempts", 0);
    record8.set("total_quizzes_completed", 4);
    record8.set("average_quiz_score", 40);
    record8.set("highest_quiz_score", 48);
    record8.set("lowest_quiz_score", 32);
    record8.set("quiz_completion_rate_percentage", 40);
    record8.set("performance_trend", "Stable");
    record8.set("improvement_rate_percentage", 5);
    record8.set("projected_final_quiz_score", 42);
    record8.set("total_questions_answered", 120);
    record8.set("correct_answers", 96);
    record8.set("incorrect_answers", 20);
    record8.set("skipped_questions", 4);
    record8.set("average_time_per_question_seconds", 45);
    record8.set("easy_questions_correct_percentage", 85);
    record8.set("medium_questions_correct_percentage", 75);
    record8.set("hard_questions_correct_percentage", 60);
    record8.set("difficulty_trend", "Student performing better on easy questions");
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("dashboard_id", "demo_student_001");
    record9.set("quiz_number", 10);
    record9.set("lesson_id", "lesson_10");
    record9.set("quiz_score", 0);
    record9.set("quiz_completion_date", null);
    record9.set("quiz_attempts", 0);
    record9.set("total_quizzes_completed", 4);
    record9.set("average_quiz_score", 40);
    record9.set("highest_quiz_score", 48);
    record9.set("lowest_quiz_score", 32);
    record9.set("quiz_completion_rate_percentage", 40);
    record9.set("performance_trend", "Stable");
    record9.set("improvement_rate_percentage", 5);
    record9.set("projected_final_quiz_score", 42);
    record9.set("total_questions_answered", 120);
    record9.set("correct_answers", 96);
    record9.set("incorrect_answers", 20);
    record9.set("skipped_questions", 4);
    record9.set("average_time_per_question_seconds", 45);
    record9.set("easy_questions_correct_percentage", 85);
    record9.set("medium_questions_correct_percentage", 75);
    record9.set("hard_questions_correct_percentage", 60);
    record9.set("difficulty_trend", "Student performing better on easy questions");
  app.save(record9);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
