/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_1");
    record0.set("content_body", "# Operational Leasing Basics and Business Benefits\n\n## Section 1: What is Operational Leasing\nOperational leasing is a contractual arrangement where a lessor grants a lessee the right to use an asset for a specified period in exchange for periodic lease payments. The lessor retains ownership.\n\nKey Characteristics: Short-term (1-5 years), lessor retains ownership, maintenance included, flexible, off-balance sheet treatment.\n\n## Section 2: Business Benefits\n- **Capital Preservation**: Avoid large upfront capital expenditures, preserve working capital\n- **Flexibility/Scalability**: Easy upgrades, quickly add/reduce equipment as needs change\n- **Cost Predictability**: Fixed payments, simplified budgeting\n- **Technology Access**: Latest equipment without obsolescence risk\n- **Operational Efficiency**: Lessor handles maintenance, quick replacement\n- **Balance Sheet Impact**: Improved financial ratios\n\n## Section 3: Growth Applications\n- **Rapid Expansion**: Quick deployment, new markets with minimal capital\n- **Market Testing**: Low-risk experimentation, minimal commitment\n- **Seasonal Scaling**: Peak season capacity, pay only when needed\n- **Technology Adoption**: Access new technologies without large capital commitments\n- **Geographic Expansion**: Lease equipment in new countries\n\n## Section 4: Operational Leasing vs Ownership\nOperational Leasing: Low initial cost, fixed monthly cost, maintenance included, high flexibility, low technology risk, off-balance sheet.\n\nOwnership: High upfront capital, variable costs, owner maintains, low flexibility, high technology risk, on-balance sheet.\n\n## Section 5: Case Study - GrowthCorp\nManufacturing company needed $5M in equipment for 40% expansion. Chose operational lease at $85K/month vs $5M purchase. Result: $900K savings, $5M cash preserved, 40% revenue growth achieved.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_2");
    record1.set("content_body", "# Operational Leasing vs Capital Leasing and Strategic Alignment\n\n## Section 1: Operational Leasing Characteristics\nShort-term lease (1-5 years), lessor retains ownership and residual value, lessor handles maintenance, includes cancellation clauses, high flexibility. Accounting: Operating expense (off-balance sheet). Tax: 100% lease payments tax-deductible.\n\n## Section 2: Capital Leasing Characteristics\nLong-term lease (75%+ of asset life), lessee has purchase option, lessee handles maintenance, non-cancellable, limited flexibility. Accounting: Asset and liability (on-balance sheet). Tax: Depreciation and interest deductible.\n\n## Section 3: Key Differences\n- **Lease Term**: Operational 1-5 years vs Capital 5-10+ years\n- **Residual Value**: Lessor retains vs Lessee owns\n- **Flexibility**: High vs Low\n- **Maintenance**: Lessor vs Lessee\n- **Accounting**: Off-balance sheet vs On-balance sheet\n\n## Section 4: Strategic Alignment Framework\n1. **Business Growth Stage**: Startup/High Growth \u2192 Operational; Mature \u2192 Capital\n2. **Equipment Life**: Rapid tech changes \u2192 Operational; Stable \u2192 Capital\n3. **Capital Availability**: Limited \u2192 Operational; Abundant \u2192 Capital\n4. **Flexibility Needs**: High \u2192 Operational; Stable \u2192 Capital\n5. **Operational Burden**: Want maintenance included \u2192 Operational\n6. **Technology Changes**: Rapid evolution \u2192 Operational; Stable \u2192 Capital\n\n## Section 5: Decision Framework\nStep 1: Assess business context. Step 2: Analyze equipment characteristics. Step 3: Evaluate financial impact. Step 4: Consider strategic factors. Step 5: Make decision based on flexibility, cost, and strategic alignment.\n\n## Section 6: Case Study - StrategicCorp\nTechnology company needed $2M IT infrastructure. Operational lease: $35K/month vs Capital lease: $2.6M. Decision: Operational leasing. Result: $920K savings, $2M capital preserved, supported 30% growth, enabled Series B funding.");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
