/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_1_risk_identification");
    record0.set("content_body", "Risk Identification Fundamentals\n\nRisk identification is the first critical step in the risk management process. In equipment leasing, understanding and identifying potential risks helps protect your organization from financial losses and operational disruptions.\n\nKey Topics:\n1. Types of Risks in Equipment Leasing\n   - Credit Risk: The risk that the lessee may default on lease payments\n   - Residual Risk: Uncertainty about the equipment's value at lease end\n   - Operational Risk: Risks related to equipment maintenance and usage\n   - Market Risk: Changes in equipment demand and market conditions\n   - Regulatory Risk: Changes in laws and regulations affecting leasing\n\n2. Risk Identification Process\n   - Gather information about the lessee and equipment\n   - Analyze historical data and industry trends\n   - Conduct thorough due diligence\n   - Document all identified risks\n   - Establish risk assessment criteria\n\n3. Common Risk Indicators\n   - Declining financial performance\n   - Industry downturns\n   - Equipment obsolescence\n   - Regulatory changes\n   - Competitive pressures\n\n4. Documentation and Tracking\n   - Maintain comprehensive risk registers\n   - Update risk assessments regularly\n   - Document risk mitigation efforts\n   - Track risk outcomes\n\nLearning Outcomes:\nBy the end of this lesson, you will be able to:\n- Identify different types of risks in equipment leasing\n- Recognize risk indicators and warning signs\n- Document risks systematically\n- Understand the importance of early risk identification");
    record0.set("video_url", null);
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_2_credit_analysis");
    record1.set("content_body", "Credit Analysis Essentials\n\nCredit analysis is fundamental to assessing the lessee's ability to meet lease obligations. A thorough credit analysis helps determine the appropriate lease terms and pricing.\n\nKey Topics:\n1. Financial Statement Analysis\n   - Balance Sheet Analysis: Assess assets, liabilities, and equity\n   - Income Statement Review: Evaluate profitability and cash flow\n   - Cash Flow Analysis: Determine ability to make lease payments\n   - Ratio Analysis: Calculate key financial metrics\n\n2. Key Financial Ratios\n   - Liquidity Ratios: Current ratio, quick ratio\n   - Profitability Ratios: Net profit margin, ROA, ROE\n   - Leverage Ratios: Debt-to-equity, debt service coverage\n   - Efficiency Ratios: Asset turnover, receivables turnover\n\n3. Lessee Evaluation\n   - Industry analysis and competitive position\n   - Management quality and experience\n   - Historical payment performance\n   - Business stability and growth prospects\n   - Collateral and guarantees\n\n4. Credit Scoring and Rating\n   - Develop credit scoring models\n   - Assign credit ratings\n   - Determine appropriate risk premiums\n   - Set lease terms based on credit quality\n\n5. Red Flags and Warning Signs\n   - Deteriorating financial metrics\n   - Missed payments or late payments\n   - Declining market position\n   - Management changes\n   - Regulatory issues\n\nLearning Outcomes:\nBy the end of this lesson, you will be able to:\n- Analyze financial statements effectively\n- Calculate and interpret key financial ratios\n- Assess lessee creditworthiness\n- Identify credit risk factors\n- Make informed credit decisions");
    record1.set("video_url", null);
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_3_risk_mitigation");
    record2.set("content_body", "Risk Mitigation Strategies\n\nOnce risks are identified and assessed, implementing effective mitigation strategies protects your leasing portfolio and ensures sustainable returns.\n\nKey Topics:\n1. Risk Mitigation Techniques\n   - Diversification: Spread risk across different lessees and industries\n   - Collateral and Security: Secure lease agreements with equipment and guarantees\n   - Covenants: Include protective clauses in lease agreements\n   - Insurance: Transfer certain risks through insurance products\n   - Pricing: Adjust lease rates to reflect risk levels\n\n2. Lease Structure Optimization\n   - Appropriate lease terms and conditions\n   - Residual value management\n   - Payment schedules aligned with cash flows\n   - Flexibility clauses for changing circumstances\n   - Default provisions and remedies\n\n3. Portfolio Management\n   - Monitor portfolio composition\n   - Rebalance to maintain risk targets\n   - Track concentration risks\n   - Manage industry and geographic exposure\n   - Regular portfolio reviews\n\n4. Contingency Planning\n   - Develop response plans for various scenarios\n   - Establish escalation procedures\n   - Create workout strategies\n   - Plan for equipment recovery\n   - Manage default situations\n\n5. Continuous Monitoring\n   - Regular financial reviews\n   - Performance tracking\n   - Early warning systems\n   - Proactive communication with lessees\n   - Timely intervention when needed\n\nLearning Outcomes:\nBy the end of this lesson, you will be able to:\n- Implement effective risk mitigation strategies\n- Structure leases to minimize risk\n- Manage portfolio risk\n- Develop contingency plans\n- Monitor and respond to emerging risks");
    record2.set("video_url", null);
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "lesson_4_compliance");
    record3.set("content_body", "Compliance and Documentation\n\nProper compliance and documentation are essential for legal protection, regulatory adherence, and operational efficiency in equipment leasing.\n\nKey Topics:\n1. Regulatory Framework\n   - Equipment leasing regulations\n   - Consumer protection laws\n   - Tax regulations and accounting standards\n   - Industry-specific requirements\n   - International considerations\n\n2. Documentation Requirements\n   - Lease agreements and terms\n   - Credit analysis documentation\n   - Risk assessment records\n   - Collateral documentation\n   - Payment records and statements\n\n3. Compliance Procedures\n   - Know Your Customer (KYC) requirements\n   - Anti-Money Laundering (AML) compliance\n   - Sanctions screening\n   - Data protection and privacy\n   - Record retention policies\n\n4. Audit and Review\n   - Internal audit procedures\n   - Compliance monitoring\n   - Regular policy reviews\n   - Training and awareness programs\n   - Corrective action processes\n\n5. Best Practices\n   - Maintain comprehensive documentation\n   - Establish clear policies and procedures\n   - Ensure staff training and competency\n   - Regular compliance assessments\n   - Continuous improvement\n\n6. Risk Management Documentation\n   - Risk registers and assessments\n   - Mitigation strategy documentation\n   - Monitoring reports\n   - Incident logs\n   - Lessons learned documentation\n\nLearning Outcomes:\nBy the end of this lesson, you will be able to:\n- Understand regulatory requirements\n- Maintain proper documentation\n- Implement compliance procedures\n- Conduct compliance reviews\n- Ensure legal and regulatory adherence");
    record3.set("video_url", null);
  app.save(record3);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
