/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "LESSON_3_ID");
    record0.set("content_body", "NPV ANALYSIS FRAMEWORK: Comprehensive financial comparison of lease vs buy options that calculates present value of all cash flows and compares options on equal basis. Purpose is to determine which option creates more value and quantify financial difference. Key principle: all cash flows discounted to present value using company cost of capital.\n\nLEASE CASH FLOWS: Monthly/annual lease payments are fixed obligations and tax deductible. Tax impact: lease payments reduce taxable income, saving taxes equal to payment \u00d7 tax rate (e.g., $20K \u00d7 25% = $5K savings). No residual value for lessee. Maintenance often included in lease payment. NPV of leasing is negative number representing cash outflow.\n\nBUY CASH FLOWS: Initial purchase price is negative cash flow. Financing includes loan payments with tax-deductible interest. Depreciation is tax deductible, saving taxes equal to depreciation \u00d7 tax rate. Owner responsible for maintenance costs (tax deductible). Equipment has salvage/residual value at end (positive cash flow). NPV of buying includes all these components.\n\nNPV CALCULATION PROCESS: (1) Project lease payments for lease term, (2) Calculate lease tax benefits by multiplying payment by tax rate, (3) Calculate net lease cash flows (payment minus tax benefit), (4) Project all buy cash flows (purchase, loan, maintenance, depreciation, residual), (5) Discount all cash flows to present using cost of capital, (6) Sum present values for each option, (7) Compare NPVs to determine cheaper option.\n\nCASE STUDY - NPVCorp: Equipment $1M, 5-year life. Lease: $20K/month, $1.2M total, $300K tax benefits, NPV = -$900K. Buy: $1M purchase, $18K/month loan, $30K/year maintenance, $160K/year depreciation, $200K residual, NPV = -$600K. Buying is $300K cheaper in NPV terms. Financial analysis favors buying, but other factors must be considered.");
    record0.set("video_url", "");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "LESSON_4_ID");
    record1.set("content_body", "TOTAL COST OF OWNERSHIP (TCO): Sum of all costs associated with equipment ownership including purchase, financing, maintenance, taxes, and residual value. Components: Purchase cost ($1M equipment), Financing cost (interest on loan), Operating costs (maintenance, insurance, utilities), Tax costs/benefits (depreciation and interest deductions), Residual value (salvage value at end). TCO = all costs minus residual value and tax benefits.\n\nCOST COMPARISON ANALYSIS: Lease cost = sum of lease payments minus tax benefits. Buy cost = total cost of ownership. Cost difference = lease cost minus buy cost (positive means buying cheaper, negative means leasing cheaper). Cost per year = total cost divided by years. Cost per unit = total cost divided by usage units. Example: Lease $900K net cost, Buy $1.06M net cost, Leasing is $160K cheaper.\n\nBREAK-EVEN ANALYSIS: Determines point where lease and buy costs are equal. Break-even residual value: if actual residual > break-even, buying cheaper; if < break-even, leasing cheaper. Break-even lease payment: if actual > break-even, buying cheaper; if < break-even, leasing cheaper. Break-even maintenance: if actual > break-even, leasing cheaper; if < break-even, buying cheaper.\n\nSENSITIVITY ANALYSIS: Analyzes impact of assumption changes on decision. Variables to test: residual value (\u00b110-20%), lease payment (\u00b15-10%), maintenance cost (\u00b110-20%), discount rate (\u00b11-2%). Sensitivity table shows NPV for different assumption values. Tornado diagram visually shows which variables have biggest impact on decision.\n\nCASE STUDY - CostCorp: Equipment $1M, 5-year life. Lease cost: $1.2M payments - $300K tax benefits = $900K net ($180K/year). Buy cost: $1M purchase + $150K financing + $150K maintenance - $200K tax benefits - $200K residual = $900K net ($180K/year). Costs equal at current assumptions. Break-even analysis shows decision at break-even point for residual value, lease payment, and maintenance. Sensitivity analysis: residual value \u00b1$50K changes buy cost by $50K; lease payment \u00b1$2K/month changes lease cost by $120K; maintenance \u00b1$10K/year changes buy cost by $50K. Decision depends on other factors.");
    record1.set("video_url", "");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "LESSON_5_ID");
    record2.set("content_body", "TAX TREATMENT OF LEASING: Operating lease payments are tax deductible, reducing taxable income. Tax savings = lease payment \u00d7 tax rate (e.g., $20K \u00d7 25% = $5K). Capital lease: depreciation and interest are deductible, not lease payments. Tax deduction timing: operating lease deduction when payment made; capital lease deduction spread over lease term.\n\nTAX TREATMENT OF BUYING: Depreciation is tax deductible over useful life, reducing taxable income. Depreciation methods: straight-line (equal each year) or accelerated (higher early years). Interest on equipment loan is tax deductible. Maintenance and repair costs are tax deductible. Example: $1M equipment depreciated over 5 years = $200K/year depreciation = $50K/year tax savings at 25% rate.\n\nTAX INCENTIVES: Section 179 deduction allows immediate deduction of equipment cost up to $1.16M limit, accelerating tax benefits. Bonus depreciation allows 100% depreciation in early years. Research and Development (R&D) tax credit available for R&D equipment. Energy efficiency tax credit available for qualifying equipment (e.g., 30% for solar).\n\nTAX IMPACT ON DECISION: Leasing provides consistent tax benefits from lease payment deductions. Buying provides tax benefits from depreciation, interest, and maintenance deductions. Tax comparison: leasing $60K/year tax benefits vs. buying $62.5K/year (depreciation $50K + interest $15K + maintenance $7.5K). Buying provides slightly more tax benefits. With Section 179 or bonus depreciation, buying becomes significantly more attractive.\n\nCASE STUDY - TaxCorp: Equipment $1M, 5-year life, 25% tax rate. Lease: $20K/month = $240K/year, tax deduction $240K, tax savings $60K/year, 5-year total $300K. Buy: Depreciation $200K/year = $50K tax savings; Interest year 1 $60K = $15K tax savings; Maintenance $30K/year = $7.5K tax savings; Total year 1 = $72.5K tax benefits. With Section 179: $1M deduction in year 1 = $250K tax savings. Tax incentives favor buying significantly. Tax savings reduce net cost of buying, making it more attractive than leasing.");
    record2.set("video_url", "");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
