/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "<LESSON_1.1_ID>");
    record0.set("content_body", "**The Psychology of Ownership vs. Access**\n\nClients often view leasing as \"debt\" - a financial burden signaling weakness. Reframe it as \"utility\" - paying for asset benefits rather than ownership burden.\n\n**Ownership Mindset:** \"We own our assets\" = strength, control, permanence\n**Utility Mindset:** \"We use the best equipment\" = competitive advantage, innovation, efficiency\n\n**Real-World Example:** Manufacturing company buying $5M equipment ties up capital and strains cash flow. Leasing preserves capital for R&D and allows upgrades every 5 years to stay competitive.\n\n**Industries Where Ownership is a Liability:**\n1. High-Tech & IT: Technology obsolescence (3-5 year cycles)\n2. Medical & Healthcare: Regulatory changes, complex compliance\n3. Logistics & Transportation: Rapid depreciation, unpredictable maintenance\n4. Construction & Heavy Equipment: Project-specific needs\n5. Retail & Hospitality: Trend-driven equipment needs\n\n**Key Client Pain Points:**\n1. Budget Constraints: Convert Capex to Opex for easier approval\n2. Obsolescence Fear: Built-in upgrade cycles ensure latest technology\n3. Balance Sheet Impact: Operating leases improve financial ratios\n4. Maintenance Burden: Lessor handles maintenance and disposal\n5. Inflexibility: Lease terms match changing business needs\n\n**Reframing Language:**\n- \"Preserves capital for revenue-generating investments\"\n- \"Provides financial flexibility to invest in growth\"\n- \"Optimizes capital structure like leading companies\"\n- \"Avoids obsolescence costs with latest technology\"\n- \"Strategic partnership managing your asset lifecycle\"\n\n**Case Study:** TechCorp shifted from \"debt\" to \"utility\" mindset. Leasing $2M equipment preserved capital for R&D, saved $100K over 5 years, and maintained technology leadership.");
    record0.set("video_url", "");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "<LESSON_1.2_ID>");
    record1.set("content_body", "**Common Psychological Barriers to Leasing**\n\n**Barrier 1: \"Leasing is for weak companies\"**\nReality: Fortune 500 companies lease 30-40% of assets. Counter: Share industry leader examples.\n\n**Barrier 2: \"We lose control by leasing\"**\nReality: Lessees maintain operational control; lessors maintain legal ownership. Counter: Explain operational control remains with lessee.\n\n**Barrier 3: \"Leasing is more expensive\"**\nReality: Total Cost of Ownership (including maintenance, obsolescence, disposal) often favors leasing. Counter: Use TCO analysis.\n\n**Barrier 4: \"We should use our cash to buy\"**\nReality: Cash used for depreciating assets has high opportunity cost. Counter: Highlight opportunity cost of non-core asset investment.\n\n**Barrier 5: \"Leasing is too complicated\"**\nReality: Leasing can be simple and straightforward. Counter: Simplify process and provide clear documentation.\n\n**Strategies to Address Barriers:**\n1. Use Social Proof: Share similar company examples and industry leader case studies\n2. Reframe Conversation: Focus on benefits (flexibility, technology, cash flow) not features\n3. Provide Data: Use TCO analysis, ROI calculations, industry benchmarks\n4. Address Concerns Directly: Acknowledge, explain reality, provide evidence, offer solutions\n5. Build Trust: Establish credibility, listen thoughtfully, be transparent, follow through\n\n**Feature-to-Benefit Conversion:**\n- Non-recourse debt \u2192 Protects credit rating and borrowing capacity\n- Operating lease \u2192 Improves financial ratios and credit rating\n- Maintenance included \u2192 Predictable costs, reduced operational burden\n- Upgrade options \u2192 Latest technology without obsolescence risk\n- Flexible terms \u2192 Scale up/down matching business needs\n\n**Building Confidence:** Deep product knowledge, industry expertise, client success stories, financial analysis, authentic belief in leasing solution.");
    record1.set("video_url", "");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
