/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("vendor_leasing_quizzes");

  const record0 = new Record(collection);
    record0.set("lessonId", "lesson-7");
    record0.set("title", "Vendor Lease Negotiation and Optimization Quiz");
    record0.set("questionCount", 10);
    record0.set("questions", "[{\"id\":1,\"question\":\"What does BATNA stand for in negotiation?\",\"options\":[\"Best Alternative to Negotiated Agreement\",\"Basic Agreement Terms and Negotiations\",\"Bilateral Agreement Negotiation Analysis\",\"Business Alternative to Negotiated Arrangement\"],\"correctAnswer\":\"Best Alternative to Negotiated Agreement\"},{\"id\":2,\"question\":\"Which technique involves setting the initial offer to influence the final outcome?\",\"options\":[\"Anchoring\",\"Framing\",\"Escalation\",\"Bundling\"],\"correctAnswer\":\"Anchoring\"},{\"id\":3,\"question\":\"What is the primary benefit of collaborative negotiation?\",\"options\":[\"Faster resolution\",\"Win-win outcomes\",\"Lower costs\",\"Reduced documentation\"],\"correctAnswer\":\"Win-win outcomes\"},{\"id\":4,\"question\":\"Which of the following is NOT a cost optimization technique?\",\"options\":[\"Volume discounts\",\"Payment term optimization\",\"Vendor relationship termination\",\"Maintenance cost reduction\"],\"correctAnswer\":\"Vendor relationship termination\"},{\"id\":5,\"question\":\"What is a vendor scorecard used for?\",\"options\":[\"Tracking payment history\",\"Measuring vendor performance\",\"Recording lease terms\",\"Documenting negotiations\"],\"correctAnswer\":\"Measuring vendor performance\"},{\"id\":6,\"question\":\"Which clause allows modification of lease terms during the agreement period?\",\"options\":[\"Renewal option\",\"Flexibility clause\",\"Escalation clause\",\"Termination provision\"],\"correctAnswer\":\"Flexibility clause\"},{\"id\":7,\"question\":\"What is residual value in leasing?\",\"options\":[\"The remaining payment balance\",\"The estimated value at lease end\",\"The monthly payment amount\",\"The total lease cost\"],\"correctAnswer\":\"The estimated value at lease end\"},{\"id\":8,\"question\":\"Which benchmarking approach compares your lease terms to competitors?\",\"options\":[\"Historical analysis\",\"Peer comparison\",\"Trend analysis\",\"Market rate analysis\"],\"correctAnswer\":\"Peer comparison\"},{\"id\":9,\"question\":\"What is the primary purpose of mid-lease modifications?\",\"options\":[\"Reduce vendor profits\",\"Adjust to changing business needs\",\"Avoid final payments\",\"Extend lease terms\"],\"correctAnswer\":\"Adjust to changing business needs\"},{\"id\":10,\"question\":\"Which negotiation strategy focuses on multiple issues simultaneously?\",\"options\":[\"Single-issue negotiation\",\"Sequential negotiation\",\"Multi-issue negotiation\",\"Phased negotiation\"],\"correctAnswer\":\"Multi-issue negotiation\"}]");
    record0.set("answers", "[\"Best Alternative to Negotiated Agreement\",\"Anchoring\",\"Win-win outcomes\",\"Vendor relationship termination\",\"Measuring vendor performance\",\"Flexibility clause\",\"The estimated value at lease end\",\"Peer comparison\",\"Adjust to changing business needs\",\"Multi-issue negotiation\"]");
    record0.set("passingScore", 70);
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lessonId", "lesson-8");
    record1.set("title", "Vendor Lease Case Studies and Best Practices Quiz");
    record1.set("questionCount", 10);
    record1.set("questions", "[{\"id\":1,\"question\":\"What is a key benefit of studying real-world case studies?\",\"options\":[\"Reducing documentation\",\"Learning from others experiences\",\"Eliminating vendor relationships\",\"Avoiding all negotiations\"],\"correctAnswer\":\"Learning from others experiences\"},{\"id\":2,\"question\":\"Which is a best practice in lease portfolio management?\",\"options\":[\"Centralizing vendor relationships\",\"Using multiple uncoordinated vendors\",\"Avoiding performance monitoring\",\"Ignoring lease terms\"],\"correctAnswer\":\"Centralizing vendor relationships\"},{\"id\":3,\"question\":\"What is a common pitfall in vendor leasing?\",\"options\":[\"Negotiating too much\",\"Inadequate vendor evaluation\",\"Monitoring performance too closely\",\"Documenting contracts thoroughly\"],\"correctAnswer\":\"Inadequate vendor evaluation\"},{\"id\":4,\"question\":\"How can vendor lock-in be avoided?\",\"options\":[\"Accepting all vendor terms\",\"Building flexibility into contracts\",\"Avoiding long-term relationships\",\"Refusing to negotiate\"],\"correctAnswer\":\"Building flexibility into contracts\"},{\"id\":5,\"question\":\"What emerging trend focuses on environmental responsibility?\",\"options\":[\"Cost reduction only\",\"Sustainability and green leasing\",\"Vendor consolidation\",\"Payment acceleration\"],\"correctAnswer\":\"Sustainability and green leasing\"},{\"id\":6,\"question\":\"Which technology is emerging in vendor leasing for transparency?\",\"options\":[\"Email systems\",\"Spreadsheets\",\"Blockchain\",\"Fax machines\"],\"correctAnswer\":\"Blockchain\"},{\"id\":7,\"question\":\"What is predictive maintenance in leasing?\",\"options\":[\"Guessing equipment failure\",\"Using data to anticipate maintenance needs\",\"Avoiding maintenance\",\"Replacing equipment frequently\"],\"correctAnswer\":\"Using data to anticipate maintenance needs\"},{\"id\":8,\"question\":\"Which approach helps avoid poor contract documentation?\",\"options\":[\"Verbal agreements\",\"Minimal documentation\",\"Contract standardization\",\"Avoiding written terms\"],\"correctAnswer\":\"Contract standardization\"},{\"id\":9,\"question\":\"What is a key element of successful implementation strategy?\",\"options\":[\"Ignoring stakeholders\",\"Avoiding training\",\"Stakeholder engagement\",\"Resisting change\"],\"correctAnswer\":\"Stakeholder engagement\"},{\"id\":10,\"question\":\"How does the circular economy model apply to leasing?\",\"options\":[\"Discarding equipment\",\"Maximizing equipment lifecycle and reuse\",\"Avoiding sustainability\",\"Ignoring environmental impact\"],\"correctAnswer\":\"Maximizing equipment lifecycle and reuse\"}]");
    record1.set("answers", "[\"Learning from others experiences\",\"Centralizing vendor relationships\",\"Inadequate vendor evaluation\",\"Building flexibility into contracts\",\"Sustainability and green leasing\",\"Blockchain\",\"Using data to anticipate maintenance needs\",\"Contract standardization\",\"Stakeholder engagement\",\"Maximizing equipment lifecycle and reuse\"]");
    record1.set("passingScore", 70);
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
