/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "<LESSON_3_1_ID>");
    record0.set("content_body", "**Section 1: Lease Modifications and Remeasurement**\n\nWhat is a Lease Modification?\n- Change to lease terms or conditions\n- Requires remeasurement of liability and asset\n- Example: Extension of lease term, change in payment amount\n\nTypes of Modifications:\n\n1. Scope Changes:\n   - Addition or removal of equipment\n   - Example: Add 10 computers to existing lease\n\n2. Payment Changes:\n   - Change in lease payment amount\n   - Example: Increase payment from $10K to $11K/month\n\n3. Term Changes:\n   - Extension or shortening of lease term\n   - Example: Extend lease from 5 years to 7 years\n\n4. Residual Value Changes:\n   - Change in residual value guarantee\n   - Example: Increase residual guarantee from $50K to $75K\n\nRemeasurement Process:\n\nStep 1: Identify Modification:\n- Determine type of modification\n- Example: Lease term extension\n\nStep 2: Calculate New Lease Liability:\n- Identify new lease payments\n- Discount at appropriate rate\n- Example: New PV = $600,000\n\nStep 3: Adjust ROU Asset:\n- Adjust for change in liability\n- Adjust for any direct costs\n- Example: ROU asset increases by $50,000\n\nStep 4: Record Adjustment:\n- Debit/credit ROU asset and liability\n- Example: Debit ROU asset $50,000, Credit liability $50,000");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "<LESSON_3_1_ID>");
    record1.set("content_body", "**Section 2: Lease Combinations and Separations**\n\nLease Combinations:\n\nDefinition:\n- Multiple leases combined into single lease\n- Treated as one lease for accounting\n- Example: Lease of building + equipment = combined lease\n\nAccounting Treatment:\n- Combine lease payments\n- Combine lease terms\n- Single ROU asset and liability\n- Example: $500K building + $100K equipment = $600K combined\n\nLease Separations:\n\nDefinition:\n- Single lease separated into multiple leases\n- Each treated as separate lease\n- Example: Lease of building with separate equipment lease\n\nAccounting Treatment:\n- Separate lease payments\n- Separate lease terms\n- Multiple ROU assets and liabilities\n- Example: $500K building lease + $100K equipment lease = separate\n\n**Section 3: Variable Lease Payments**\n\nWhat are Variable Lease Payments?\n- Lease payments that vary based on index or rate\n- Example: Lease payment tied to inflation index\n\nTypes of Variable Payments:\n\n1. Index-Linked Payments:\n   - Tied to inflation index (CPI)\n   - Example: Payment = $10,000 + (CPI increase \u00d7 $1,000)\n\n2. Rate-Linked Payments:\n   - Tied to interest rate\n   - Example: Payment = $10,000 + (LIBOR \u00d7 $100,000)\n\n3. Usage-Based Payments:\n   - Tied to usage (miles, hours)\n   - Example: Payment = $0.10 per mile\n\n4. Performance-Based Payments:\n   - Tied to performance metrics\n   - Example: Payment = $10,000 + (revenue increase \u00d7 5%)\n\nAccounting Treatment:\n\nFixed Payments:\n- Included in lease liability\n- Example: $10,000 fixed payment included\n\nVariable Payments:\n- Not included in lease liability (if truly variable)\n- Recognized as expense when incurred\n- Example: CPI increase recognized as expense");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "<LESSON_3_1_ID>");
    record2.set("content_body", "**Section 4: Lease Termination and Buyout**\n\nLease Termination:\n\nDefinition:\n- Early termination of lease\n- May include termination penalty\n- Example: Terminate 5-year lease after 3 years\n\nAccounting Treatment:\n- Derecognize ROU asset\n- Derecognize lease liability\n- Record gain/loss\n- Example: Loss of $50,000 on early termination\n\nCalculation:\n- Carrying value of ROU asset: $200,000\n- Carrying value of liability: $150,000\n- Termination payment: $180,000\n- Loss = $180,000 - $200,000 = -$20,000\n\nLease Buyout:\n\nDefinition:\n- Purchase of equipment at end of lease\n- Exercise of purchase option\n- Example: Buy equipment for $50,000 at lease end\n\nAccounting Treatment:\n- Derecognize ROU asset\n- Derecognize lease liability\n- Capitalize equipment at cost\n- Example: Equipment cost = $50,000 + remaining ROU asset\n\nCalculation:\n- Remaining ROU asset: $50,000\n- Buyout price: $50,000\n- Total equipment cost: $100,000\n\n**Section 5: Case Study - Advanced Lease Analysis**\n\nCompany: AdvancedLeasing Inc.\nSituation: Analyzing complex lease scenarios\n\nScenario 1: Lease Modification\n\nOriginal Lease:\n- Equipment: $500,000\n- Lease term: 5 years\n- Monthly payment: $10,000\n- Lease liability: $450,000\n- ROU asset: $500,000\n\nModification:\n- Extend lease term by 2 years\n- New monthly payment: $8,000 (lower due to longer term)\n- New lease liability: $520,000\n\nRemeasurement:\n- Old liability: $450,000\n- New liability: $520,000\n- Increase: $70,000\n- Adjustment: Debit ROU asset $70,000, Credit liability $70,000\n- New ROU asset: $570,000\n\nScenario 2: Variable Lease Payments\n\nLease Details:\n- Fixed payment: $10,000/month\n- Variable payment: CPI increase \u00d7 $1,000\n- Current CPI increase: 2%\n- Variable payment: 2% \u00d7 $1,000 = $20/month\n\nAccounting:\n- Fixed payment ($10,000) included in liability\n- Variable payment ($20) recognized as expense when incurred\n- Example: Year 1 variable expense = $240\n\nScenario 3: Lease Termination\n\nLease Details:\n- Original lease term: 5 years\n- Termination after: 3 years\n- Remaining ROU asset: $200,000\n- Remaining liability: $150,000\n- Termination payment: $180,000\n\nAccounting:\n- Derecognize ROU asset: $200,000\n- Derecognize liability: $150,000\n- Record termination payment: $180,000\n- Loss = $180,000 - $200,000 = -$20,000");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "<LESSON_3_2_ID>");
    record3.set("content_body", "**Section 1: Lease Disclosure Requirements**\n\nIFRS 16 Disclosures:\n\nLessee Disclosures:\n- Right-of-use assets\n- Lease liabilities\n- Lease payments\n- Lease modifications\n- Short-term and low-value leases\n- Example: Disclose $500K ROU asset, $450K liability\n\nLessor Disclosures:\n- Finance lease receivables\n- Operating lease assets\n- Lease income\n- Example: Disclose $1M finance lease receivables\n\nASC 842 Disclosures:\n\nLessee Disclosures:\n- Right-of-use assets\n- Lease liabilities\n- Lease payments\n- Lease modifications\n- Short-term and low-value leases\n- Example: Disclose $500K ROU asset, $450K liability\n\nLessor Disclosures:\n- Finance lease receivables\n- Operating lease assets\n- Lease income\n- Example: Disclose $1M finance lease receivables\n\n**Section 2: Lease Accounting Policies**\n\nAccounting Policy Components:\n\n1. Lease Definition:\n   - How company defines lease\n   - Example: \"A contract that conveys right to use asset\"\n\n2. Recognition Policy:\n   - When leases are recognized\n   - Example: \"Recognized at lease commencement\"\n\n3. Measurement Policy:\n   - How leases are measured\n   - Example: \"Measured at PV of lease payments\"\n\n4. Discount Rate Policy:\n   - How discount rate is determined\n   - Example: \"Incremental borrowing rate\"\n\n5. Short-term and Low-Value Lease Policy:\n   - Treatment of short-term and low-value leases\n   - Example: \"Leases < 12 months not recognized\"\n\n6. Lease Modification Policy:\n   - How modifications are treated\n   - Example: \"Remeasured when terms change\"");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "<LESSON_3_2_ID>");
    record4.set("content_body", "**Section 3: Audit and Compliance**\n\nAudit Procedures:\n\n1. Lease Identification:\n   - Identify all leases\n   - Review contracts\n   - Example: Identify 50 leases in company\n\n2. Lease Classification:\n   - Verify correct classification\n   - Check against criteria\n   - Example: Verify 40 finance leases, 10 operating leases\n\n3. Lease Measurement:\n   - Verify correct measurement\n   - Check calculations\n   - Example: Verify $500K ROU asset calculation\n\n4. Lease Disclosure:\n   - Verify complete disclosure\n   - Check against standards\n   - Example: Verify all required disclosures included\n\n5. Lease Modifications:\n   - Identify modifications\n   - Verify remeasurement\n   - Example: Identify 5 modifications, verify remeasurement\n\nCompliance Checklist:\n\n- [ ] All leases identified\n- [ ] Leases correctly classified\n- [ ] Lease liability correctly calculated\n- [ ] ROU asset correctly calculated\n- [ ] Lease payments correctly recorded\n- [ ] Lease modifications correctly remeasured\n- [ ] Disclosures complete and accurate\n- [ ] Accounting policies documented\n- [ ] Internal controls in place\n- [ ] Audit procedures completed\n\n**Section 4: Case Study - Compliance and Reporting**\n\nCompany: ComplianceLeasing Inc.\nSituation: Implementing lease accounting compliance\n\nCurrent State:\n- 100 leases across company\n- Mix of finance and operating leases\n- Limited lease accounting expertise\n- No centralized lease management\n\nCompliance Objectives:\n\nObjective 1: Lease Identification\n- Identify all leases\n- Document lease terms\n- Create lease register\n- Timeline: 2 months\n\nObjective 2: Lease Classification\n- Classify all leases\n- Document classification rationale\n- Verify against criteria\n- Timeline: 1 month\n\nObjective 3: Lease Measurement\n- Calculate lease liabilities\n- Calculate ROU assets\n- Verify calculations\n- Timeline: 2 months\n\nObjective 4: Lease Accounting\n- Record lease entries\n- Implement lease accounting\n- Train accounting team\n- Timeline: 1 month\n\nObjective 5: Disclosure and Reporting\n- Prepare lease disclosures\n- Include in financial statements\n- Audit and review\n- Timeline: 1 month");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "<LESSON_3_2_ID>");
    record5.set("content_body", "Implementation Plan:\n\nPhase 1: Lease Identification (Months 1-2)\n- Review all contracts\n- Identify leases\n- Document lease terms\n- Create lease register\n- Deliverable: Lease register with 100 leases\n\nPhase 2: Lease Classification (Month 3)\n- Classify all leases\n- Document classification\n- Verify against criteria\n- Deliverable: Classification summary (80 finance, 20 operating)\n\nPhase 3: Lease Measurement (Months 4-5)\n- Calculate liabilities\n- Calculate ROU assets\n- Verify calculations\n- Deliverable: Lease measurement schedule\n\nPhase 4: Lease Accounting (Month 6)\n- Record lease entries\n- Implement in accounting system\n- Train team\n- Deliverable: Lease accounting entries recorded\n\nPhase 5: Disclosure and Reporting (Month 7)\n- Prepare disclosures\n- Include in financial statements\n- Audit and review\n- Deliverable: Financial statements with lease disclosures\n\nResults:\n\nLease Register:\n- 100 leases identified\n- 80 finance leases\n- 20 operating leases\n- Total lease liability: $50M\n- Total ROU assets: $52M\n\nFinancial Statement Impact:\n- Total assets increase: $52M\n- Total liabilities increase: $50M\n- Net income impact: -$5M (annual lease expense)\n\nCompliance Status:\n- All leases identified: \u2713\n- All leases classified: \u2713\n- All leases measured: \u2713\n- All leases recorded: \u2713\n- All disclosures complete: \u2713");
  app.save(record5);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
