/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("vendor_leasing_glossaries");

  const record0 = new Record(collection);
    record0.set("lessonId", "lesson_1");
    record0.set("termCount", 20);
    record0.set("terms", "Vendor Leasing, Captive Finance, Direct Lease, Equipment Manufacturer, Lessor, Lessee, Lease Payment, Residual Value, Buyout Option, Renewal Option, Vendor Financing, Third-Party Lessor, Intermediary, Broker, Equipment Financing, Lease Term, Fair Value, Depreciation, Interest Rate, Financing Cost");
    record0.set("definitions", "Vendor Leasing: Equipment financing provided directly by the manufacturer or through their captive finance subsidiary. Captive Finance: A subsidiary company of an equipment manufacturer that provides financing for the manufacturer's products. Direct Lease: A lease where the equipment manufacturer directly provides financing to the customer. Equipment Manufacturer: A company that produces equipment and may offer financing through captive finance. Lessor: The company that owns equipment and leases it to customers. Lessee: The customer who leases equipment from a lessor. Lease Payment: The periodic (usually monthly) payment made by the lessee to the lessor. Residual Value: The estimated value of equipment at the end of the lease term. Buyout Option: The right of the lessee to purchase equipment at the end of the lease. Renewal Option: The right of the lessee to extend the lease beyond the initial term. Vendor Financing: Financing provided by equipment vendors for their products. Third-Party Lessor: A company that leases equipment but is not the manufacturer. Intermediary: A company that arranges leases between vendors and customers. Broker: A professional who facilitates lease transactions between parties. Equipment Financing: Financing for equipment purchases or leases. Lease Term: The duration of the lease agreement. Fair Value: The market value of equipment at a specific point in time. Depreciation: The decrease in equipment value over time. Interest Rate: The percentage charged on financed amounts. Financing Cost: The total cost of borrowing in a lease.");
    record0.set("examples", "Vendor Leasing: Ford Credit financing for vehicle leases. Captive Finance: General Motors Financial Company providing GM vehicle financing. Direct Lease: Caterpillar Financial leasing construction equipment directly. Equipment Manufacturer: John Deere producing agricultural equipment. Lessor: Wells Fargo Equipment Finance leasing machinery. Lessee: A manufacturing company leasing production equipment. Lease Payment: $500 monthly payment for equipment lease. Residual Value: Equipment worth $10,000 at lease end. Buyout Option: Purchasing leased equipment for $5,000 at lease end. Renewal Option: Extending lease for additional 2 years. Vendor Financing: Toyota Financial Services financing vehicle purchases. Third-Party Lessor: Hertz Equipment Rental & Sales. Intermediary: Equipment leasing broker arranging deals. Broker: Commercial equipment broker facilitating transactions. Equipment Financing: Financing for manufacturing machinery. Lease Term: 36-month equipment lease. Fair Value: Equipment appraised at $25,000. Depreciation: Equipment value declining 20% annually. Interest Rate: 5% APR on lease financing. Financing Cost: Total interest of $3,000 over lease term.");
    record0.set("crossReferences", "See also: Captive Finance, Lessor, Lessee, Residual Value | See also: Direct Lease, Equipment Manufacturer, Financing Cost | See also: Lease Payment, Lease Term, Buyout Option | See also: Renewal Option, Vendor Financing, Third-Party Lessor | See also: Intermediary, Broker, Equipment Financing | See also: Fair Value, Depreciation, Interest Rate");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lessonId", "lesson_2");
    record1.set("termCount", 20);
    record1.set("terms", "Captive Finance, Vendor Program, Operating Lease, Finance Lease, Sale-Leaseback, Master Lease, Equipment Pool, Promotional Financing, 0% Financing, Deferred Payment, Residual Value, Buyout Option, Renewal Option, Maintenance Lease, Full-Service Lease, Lease Term, Payment Schedule, Interest Rate, APR, Effective Cost");
    record1.set("definitions", "Captive Finance: A subsidiary of an equipment manufacturer providing financing for the manufacturer's products. Vendor Program: A structured financing program offered by equipment vendors. Operating Lease: A short-term lease with maintenance included and no ownership transfer. Finance Lease: A long-term lease with ownership transfer option at end. Sale-Leaseback: Transaction where customer sells equipment to lessor and leases it back. Master Lease: Umbrella agreement covering multiple individual leases. Equipment Pool: Shared equipment available to multiple customers. Promotional Financing: Temporary reduced rates or special terms to promote sales. 0% Financing: Financing with zero percent annual percentage rate. Deferred Payment: Lease payments deferred for initial period. Residual Value: Estimated equipment value at lease end. Buyout Option: Right to purchase equipment at predetermined price. Renewal Option: Right to extend lease beyond initial term. Maintenance Lease: Lease where vendor covers all maintenance. Full-Service Lease: Comprehensive lease including maintenance, insurance, and support. Lease Term: Duration of lease agreement. Payment Schedule: Schedule showing payment amounts and due dates. Interest Rate: Percentage charged on financed amounts. APR: Annual percentage rate charged on financed amount. Effective Cost: Total cost of financing including all fees and interest.");
    record1.set("examples", "Captive Finance: Ford Motor Credit Company. Vendor Program: GM Financial's vehicle lease program. Operating Lease: 3-year vehicle lease with maintenance included. Finance Lease: 5-year equipment lease with buyout option. Sale-Leaseback: Company sells building and leases it back. Master Lease: Corporate umbrella agreement for multiple equipment leases. Equipment Pool: Shared construction equipment available to multiple contractors. Promotional Financing: 0% APR for 24 months on new equipment. 0% Financing: No interest charged on lease payments. Deferred Payment: First 3 months of payments deferred. Residual Value: Equipment worth $15,000 at lease end. Buyout Option: Purchase equipment for $8,000 at lease end. Renewal Option: Extend lease for additional 24 months. Maintenance Lease: Vendor covers all repairs and maintenance. Full-Service Lease: Includes financing, maintenance, insurance, and roadside assistance. Lease Term: 48-month equipment lease. Payment Schedule: Monthly payments of $500 for 48 months. Interest Rate: 4.5% APR on lease. APR: 3.9% annual percentage rate. Effective Cost: Total cost of $24,000 including all fees.");
    record1.set("crossReferences", "See also: Vendor Program, Operating Lease, Finance Lease | See also: Sale-Leaseback, Master Lease, Equipment Pool | See also: Promotional Financing, 0% Financing, Deferred Payment | See also: Residual Value, Buyout Option, Renewal Option | See also: Maintenance Lease, Full-Service Lease, Lease Term | See also: Payment Schedule, Interest Rate, APR, Effective Cost");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
