/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_1_id_placeholder_1");
    record0.set("content_body", "**Section 1: Operating Leases vs. Capital Leases**\n\nOperating Leases:\n- Definition: Short-term lease where lessor retains ownership and risks\n- Characteristics: Typically 1-3 years, lessor handles maintenance, can be cancelled\n- Accounting: Expensed as operating expense, off-balance sheet (under certain conditions)\n- Tax: Lease payments are tax-deductible\n- Best for: Companies wanting flexibility, avoiding obsolescence risk, predictable costs\n- Example: Vehicle leases, equipment rentals for short-term projects\n- Lessor perspective: Retains residual value risk, handles maintenance, higher ongoing costs\n\nCapital Leases (Finance Leases):\n- Definition: Long-term lease where lessee essentially owns the asset\n- Characteristics: Typically 5-10+ years, lessee handles maintenance, non-cancellable\n- Accounting: Capitalized as asset and liability on balance sheet\n- Tax: Depreciation and interest deductions\n- Best for: Companies wanting long-term asset control, building equity\n- Example: Equipment purchases, vehicle fleets, real estate\n- Lessor perspective: Transfers ownership risks to lessee, lower ongoing costs, higher upfront returns");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_1_id_placeholder_1");
    record1.set("content_body", "**Section 2: Lease Structure Components**\n\n1. Equipment/Asset Specification: Detailed description of asset, specifications and features, condition (new, used, refurbished), serial numbers and identification, delivery and installation requirements\n\n2. Lease Term: Primary lease period (e.g., 36 months), renewal options (e.g., 2 additional 12-month periods), early termination options and penalties, extension options and pricing\n\n3. Lease Payments: Monthly/quarterly/annual payment amounts, payment schedule and due dates, late payment penalties and interest, payment method and location, currency and adjustment mechanisms\n\n4. Maintenance and Support: Full-service lease (lessor handles all maintenance), net lease (lessee handles all maintenance), hybrid (shared maintenance responsibilities), warranty coverage and duration, support and technical assistance\n\n5. Insurance and Risk: Insurance requirements and coverage amounts, who carries insurance (lessor or lessee), liability and damage responsibility, loss payee designation, deductibles and co-insurance\n\n6. Residual Value and End-of-Lease: Residual value guarantee (if applicable), purchase option at lease end, return condition requirements, disposition of asset, excess wear and tear charges\n\n7. Default and Remedies: Definition of default (missed payments, breach of terms), notice and cure periods, remedies available to lessor (repossession, acceleration), lessee remedies for lessor breach, dispute resolution procedures");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_1_id_placeholder_1");
    record2.set("content_body", "**Section 3: Lease Accounting Standards (IFRS 16 / ASC 842)**\n\nIFRS 16 (International): All leases recognized on balance sheet as right-of-use (ROU) asset and lease liability. Lease liability = present value of lease payments. ROU asset = lease liability + initial direct costs - incentives. Depreciation of ROU asset + interest on lease liability = total lease expense. Impact: More leases on balance sheet, higher reported liabilities.\n\nASC 842 (US GAAP): Similar to IFRS 16 but with some differences. Operating leases: ROU asset and lease liability on balance sheet. Finance leases: Capitalized as asset and liability. Lessee accounting: Recognize ROU asset and lease liability. Lessor accounting: Sales-type, direct financing, or operating lease.\n\n**Section 4: Lease Types by Industry**\n\nEquipment Leasing: Manufacturing equipment, IT equipment, medical devices. Typically 3-5 year terms. Full-service or net lease structures. Residual value important for lessor.\n\nVehicle Leasing: Cars, trucks, commercial vehicles. Typically 2-4 year terms. Maintenance often included. Mileage limits common. Residual value critical.\n\nReal Estate Leasing: Commercial space, industrial facilities, retail. Typically 5-10+ year terms. Net lease (tenant pays operating costs). Long-term relationships. Renewal options common.\n\nTechnology Leasing: Servers, networking equipment, software. Typically 2-3 year terms. Rapid obsolescence risk. Upgrade options important. Full-service support common.");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "lesson_1_id_placeholder_1");
    record3.set("content_body", "**Section 5: Case Study - Lease Structure Comparison**\n\nCompany: ManufacturingCorp Inc. Situation: Needs $5M manufacturing equipment for 10 years\n\nOption 1: Operating Lease (3-year terms, renewable) - Annual payment: $1.8M, Lessor handles maintenance, Can upgrade every 3 years, Off-balance sheet (potentially), Total 10-year cost: $18M, Flexibility: High, Obsolescence risk: Low\n\nOption 2: Capital Lease (10-year term) - Annual payment: $1.2M, Lessee handles maintenance ($200K/year), Total annual cost: $1.4M, On-balance sheet, Total 10-year cost: $14M, Flexibility: Low, Obsolescence risk: High\n\nOption 3: Purchase with Financing - Equipment cost: $5M, Financing: $5M loan at 5% over 10 years, Annual payment: $647K, Maintenance: $200K/year, Total annual cost: $847K, Total 10-year cost: $8.47M, Flexibility: None, Obsolescence risk: High\n\nDecision: Company chose Option 1 (Operating Lease) because of flexibility to upgrade technology, predictable costs, lessor handles maintenance, off-balance sheet benefits, and lower obsolescence risk.");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "lesson_1_id_placeholder_2");
    record4.set("content_body", "**Section 1: Essential Lease Terms**\n\n1. Lease Payment Terms: Base rent (fixed monthly/quarterly/annual payment), escalation clauses (annual increases e.g., 3% per year), seasonal adjustments (higher payments during peak seasons), step payments (increasing payments over lease term), balloon payments (large payment at lease end). Example: Year 1-2: $10K/month, Year 3-4: $11K/month, Year 5: $12K/month\n\n2. Payment Timing and Conditions: Payment due date (e.g., 1st of each month), grace period for late payments (e.g., 10 days), late payment penalties (e.g., 1.5% per month), payment method (check, ACH, wire transfer), payment location and account information\n\n3. Maintenance and Service Terms: Full-service lease (lessor provides all maintenance, repairs, parts, labor), net lease (lessee responsible for all maintenance), gross lease (lessor handles major maintenance, lessee handles minor), maintenance schedule (preventive maintenance requirements), service level agreements (response times, uptime guarantees), warranty coverage (duration and scope)");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "lesson_1_id_placeholder_2");
    record5.set("content_body", "**Section 2 (continued): Insurance and Liability**\n\n4. Insurance and Liability: Insurance requirements (type and coverage amounts), lessor as loss payee (lessor named on insurance policy), liability limits (general liability, property damage), deductibles (who pays deductibles), waiver of subrogation (insurance company can't sue lessor), additional insured (lessor named as additional insured)\n\n5. Residual Value and Purchase Options: Guaranteed residual value (lessee guarantees minimum value at lease end), estimated residual value (lessor's estimate, no guarantee), purchase option (lessee can buy asset at lease end), fair market value purchase (buy at FMV at lease end), fixed price purchase (buy at predetermined price). Example: $5M equipment, 5-year lease, $1M guaranteed residual value\n\n6. Default and Remedies: Payment default (missed lease payment), material breach (violation of lease terms e.g., failure to maintain insurance), notice period (time to cure default e.g., 10 days), remedies (repossession, acceleration of payments, damages), lessor's right to repossess (can take back asset if default), lessee's remedies (offset, damages, specific performance)");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "lesson_1_id_placeholder_2");
    record6.set("content_body", "**Section 2: Negotiation Points and Trade-offs**\n\nKey Negotiation Areas:\n\n1. Lease Payment Amount: Lessor wants higher payments to maximize return. Lessee wants lower payments to minimize cost. Trade-off: Longer term = lower monthly payment. Trade-off: Larger down payment = lower monthly payment. Trade-off: Residual value guarantee = higher monthly payment\n\n2. Lease Term: Lessor wants shorter term to reduce risk. Lessee wants longer term for stability and lower payments. Trade-off: Longer term = lower monthly payment but higher total cost. Trade-off: Renewal options = flexibility for lessee\n\n3. Maintenance Responsibility: Lessor wants lessee handles maintenance (net lease). Lessee wants lessor handles maintenance (full-service lease). Trade-off: Full-service lease = higher monthly payment. Trade-off: Net lease = lower monthly payment but higher lessee costs");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "lesson_1_id_placeholder_2");
    record7.set("content_body", "**Section 3: Risk Allocation Strategies**\n\nLessor Risk Mitigation:\n\n1. Residual Value Guarantee: Lessee guarantees minimum residual value at lease end. Protects lessor from obsolescence and market risk. Increases monthly payment. Example: $5M equipment, 5-year lease, $1M guaranteed residual\n\n2. Maintenance Requirements: Require lessee to maintain equipment to manufacturer specifications. Regular maintenance schedule and documentation. Protects asset condition and residual value. Reduces lessor's maintenance costs\n\n3. Insurance Requirements: Require lessee to carry comprehensive insurance. Lessor named as loss payee. Protects lessor from loss due to damage or theft. Reduces lessor's insurance costs\n\n4. Default Provisions: Clear definition of default. Right to repossess asset. Acceleration of remaining payments. Damages for breach. Protects lessor's financial position\n\n5. Creditworthiness: Require personal or corporate guarantees. Require financial statements and credit checks. Require security deposits or letters of credit. Protects lessor from lessee default");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "lesson_1_id_placeholder_2");
    record8.set("content_body", "**Section 4: Case Study - Lease Terms Negotiation**\n\nCompany: TechCorp Inc. Situation: Negotiating lease for $2M IT equipment\n\nInitial Lessor Proposal: Monthly payment: $50K, Term: 3 years, Maintenance: Net lease (lessee handles), Residual value: $500K guaranteed, Early termination: Not allowed, Insurance: Lessee carries, lessor named loss payee\n\nNegotiation Process:\n\nRound 1: Lessee proposes $45K/month, full-service lease, early termination option. Lessor responds: $48K/month, gross lease (shared maintenance), early termination with 15% penalty\n\nRound 2: Lessee proposes $46K/month, full-service lease, early termination with 10% penalty. Lessor responds: $47K/month, full-service lease, early termination with 12% penalty, $400K residual guarantee\n\nRound 3 (Final): Agreement: $47K/month, full-service lease, early termination with 12% penalty, $400K residual guarantee. Additional terms: Annual 2% payment increase, renewal option for 2 additional 12-month periods at $48K/month");
  app.save(record8);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
