/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "<LESSON_1_1_ID>");
    record0.set("content_body", "# Introduction to Securitization\n\n## What is Securitization?\nSecuritization is the process of converting illiquid assets (like lease portfolios) into tradeable securities. A pool of 100 leases worth $50M can be converted into ABS securities backed by cash flows.\n\n## Historical Development\n- 1970s: First mortgage-backed securities (MBS)\n- 1980s: Asset-backed securities (ABS) emerge\n- 1990s: Lease securitization grows\n- 2000s: Structured finance expansion\n- 2008: Financial crisis impacts market\n- 2010s: Market recovery and regulation\n\n## Benefits for Originators\n1. **Capital Efficiency**: Frees up $100M capital for new originations\n2. **Funding Diversification**: Reduces bank reliance, accesses capital markets\n3. **Balance Sheet Management**: Improves debt-to-equity ratio\n4. **Risk Transfer**: Transfers credit risk to investors\n\n## Benefits for Investors\n1. **Yield Enhancement**: 4% yield on AAA tranche vs. 2% on Treasury\n2. **Diversification**: Access to lease cash flows\n3. **Structured Returns**: Multiple tranches (AAA, A, BBB)\n4. **Liquidity**: Tradeable securities in secondary market\n\n## Market Participants\n- **Originator**: Originates leases, sells portfolio\n- **Servicer**: Collects lease payments, manages portfolio\n- **Trustee**: Holds assets, distributes cash flows\n- **Rating Agencies**: Moody's, S&P, Fitch rate securities\n- **Underwriter**: Structures deal, sells securities\n- **Investors**: Institutional investors, hedge funds\n\n## Securitization Process Overview\n1. Portfolio Assembly: 100 leases, $50M portfolio\n2. Due Diligence: Verify lease documentation\n3. Structuring: 70% AAA, 20% A, 10% BBB\n4. Rating: AAA rated senior tranche\n5. Marketing: Roadshow to institutional investors\n6. Pricing: AAA at LIBOR + 50 bps\n7. Closing: Assets transferred to SPV\n8. Distribution: Investors receive certificates");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "<LESSON_1_2_ID>");
    record1.set("content_body", "# Securitization Process and Structure\n\n## Legal Structure - Special Purpose Vehicle (SPV)\nA separate legal entity created for securitization that holds lease assets and issues securities. The SPV is bankruptcy remote from the originator, protecting investors if the originator fails.\n\n## Securitization Mechanics\n\n### Asset Transfer\n- Originator sells lease portfolio to SPV\n- SPV pays originator with proceeds\n- Assets transferred to SPV ($50M portfolio)\n\n### Security Issuance\n- SPV issues securities (notes) backed by lease cash flows\n- Multiple tranches: Senior (AAA), Mezzanine (A), Subordinated (BBB)\n- Example: 70% AAA, 20% A, 10% BBB\n\n### Cash Flow Collection & Distribution\n- Servicer collects monthly lease payments ($500,000)\n- Trustee distributes cash per waterfall\n- Senior tranche paid first, then mezzanine, then subordinated\n\n## Cash Flow Waterfall (Monthly Example)\nCollections: $500,000\n- Servicing fee (0.25%): $1,250\n- Trustee fee (0.10%): $500\n- Senior interest (5%): $145,833\n- Mezzanine interest (6%): $50,000\n- Subordinated interest (8%): $40,000\n- Senior principal: $150,000\n- Mezzanine principal: $50,000\n- Subordinated principal: $25,000\n- Excess to originator: $37,417\n\n## Credit Enhancement Mechanisms\n1. **Subordination**: Lower tranches absorb losses first (BBB absorbs first 10%)\n2. **Overcollateralization**: $55M assets for $50M liabilities\n3. **Reserve Accounts**: $2.5M cash reserve for losses\n4. **Excess Spread**: 2% difference between asset yield and liability cost\n\n## Case Study: StructureCorp Securitization\n- Portfolio: 100 leases, $50M, $500K monthly collections\n- SPV: StructureCorp Lease Trust 2024-1\n- Tranches: $35M AAA, $10M A, $5M BBB\n- Outcome: Securities issued, cash flows managed, investors protected");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
