/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "<LESSON_2.1_ID>");
    record0.set("content_body", "**The Three Pillars of Financial Value**\n\n**Pillar 1: Improving Cash Flow**\nLeasing converts large capital expenditures into smaller, predictable operating expenses. Instead of paying $1M upfront, you pay $250K annually. This preserves cash for operations and growth.\n\n**Pillar 2: Preserving Capital**\nLeasing preserves capital for revenue-generating investments. Capital used for depreciating assets has high opportunity cost. Better to invest in R&D, marketing, or expansion.\n\n**Pillar 3: Optimizing WACC**\nLeasing can reduce WACC (Weighted Average Cost of Capital) by optimizing capital structure. Lower debt = lower WACC = higher company valuation.\n\n**Example: Equipment Purchase vs. Lease**\n\nPurchase Option:\n- Upfront cost: $1M\n- Annual depreciation: $200K\n- Annual maintenance: $50K\n- Total Year 1 cost: $1.25M\n\nLease Option:\n- Annual lease payment: $250K (includes maintenance)\n- Total Year 1 cost: $250K\n\nYear 1 Benefit: Lease preserves $750K in cash for operations and growth.\n\n**Preserving Bank Lines**\n\nTraditional debt reduces available credit lines. Leasing preserves debt capacity.\n\nExample: Company with $50M credit line\n\nBuy Equipment:\n- Equipment financing: $8M debt\n- Available credit: $42M\n- Reduced flexibility\n\nLease Equipment:\n- Debt financing: $0\n- Available credit: $50M\n- Full flexibility preserved\n\n**WACC Optimization**\n\nWACC = (E/V \u00d7 Re) + (D/V \u00d7 Rd \u00d7 (1-Tc))\n\nWhere:\n- E/V = Equity ratio\n- Re = Cost of equity\n- D/V = Debt ratio\n- Rd = Cost of debt\n- Tc = Corporate tax rate\n\nLeasing reduces debt (D/V) and preserves capital for higher-return investments, improving overall returns and reducing WACC.\n\n**Case Study: RetailCorp Inc.**\n\nScenario: Equipment cost $20M, useful life 10 years\n\nPurchase Option:\n- Equipment cost: $20M\n- Annual depreciation: $2M\n- Annual maintenance: $500K\n- 10-year TCO: $25M\n- Capital tied up: $20M\n\nLease Option:\n- Annual lease payment: $1.875M (includes maintenance)\n- 10-year TCO: $18.75M\n- Capital preserved: $20M\n\nCapital Allocation:\n- $20M preserved capital invested at 12% ROI = $24M return\n- Net benefit of leasing: $5.25M ($24M return - $18.75M lease cost)\n\nConclusion: Leasing provides superior financial value through capital preservation and higher-return investments.");
    record0.set("video_url", "");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "<LESSON_2.2_ID>");
    record1.set("content_body", "**The Asset Lifecycle**\n\nAssets go through five stages:\n\n1. **Acquisition**: Selecting, purchasing, and financing equipment\n2. **Installation**: Delivery, setup, and integration\n3. **Operation & Maintenance**: Daily use, preventive maintenance, repairs\n4. **Upgrades**: Technology updates, capacity expansion, improvements\n5. **Disposal**: End-of-life management, recycling, replacement\n\nOwnership requires effort at each stage. Leasing transfers most operational burden to lessor.\n\n**Operational Benefits**\n\n**Benefit 1: Predictable Costs**\n- Ownership: Maintenance unpredictable ($50K-$200K/year)\n- Leasing: Fixed costs ($120K/year)\n- Advantage: Better budgeting and financial planning\n\n**Benefit 2: Reduced Operational Burden**\n- Ownership: Requires 200+ hours/year management\n- Leasing: Requires 20 hours/year management\n- Advantage: Staff can focus on core business\n\n**Benefit 3: Access to Expertise**\n- Lessor provides trained technicians\n- Compliance expertise and regulatory support\n- Advantage: Better maintenance and compliance\n\n**Benefit 4: Flexibility and Scalability**\n- Easy to add equipment during growth\n- Easy to remove equipment during downturns\n- Advantage: Match equipment to business needs\n\n**Benefit 5: Technology Refresh**\n- Regular upgrades ensure latest technology\n- No obsolescence risk\n- Advantage: Competitive advantage maintained\n\n**Lifecycle Management Strategies**\n\n1. **Preventive Maintenance**: Regular maintenance prevents breakdowns\n2. **Condition Monitoring**: Track equipment health and predict failures\n3. **Utilization Optimization**: Maximize equipment usage and ROI\n4. **Upgrade Planning**: Plan technology upgrades strategically\n5. **Disposal and Recycling**: Responsible end-of-life management\n\n**Case Study: HealthcareCorp Inc.**\n\nScenario: 50 hospitals managing medical equipment\n\nCurrent State (Owned Equipment):\n- Annual cost: $8M\n- Staff required: 100+ FTE\n- Equipment uptime: 95%\n- Compliance: Manual, time-consuming\n- Technology: Mixed ages, some outdated\n\nProposed State (Leased Equipment):\n- Annual cost: $6M\n- Staff required: 10 FTE\n- Equipment uptime: 99%\n- Compliance: Automatic, handled by lessor\n- Technology: Latest, automatic upgrades\n\n10-Year Impact:\n- Cost savings: $20M\n- Staff reduction: 90 FTE freed for patient care\n- Uptime improvement: 4% (significant for healthcare)\n- Compliance: 100% automated\n- Technology: Always current\n\nConclusion: Leasing provides superior operational value through cost reduction, staff efficiency, and improved reliability.");
    record1.set("video_url", "");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "<LESSON_2.3_ID>");
    record2.set("content_body", "**Strategic Benefits of Leasing**\n\n**Benefit 1: Scalability**\nLeasing enables easy equipment adjustment to match business growth. Add equipment as you grow, remove as you contract. No capital constraints.\n\n**Benefit 2: Agility and Flexibility**\nEasy to adapt to market changes. Respond quickly to competitive threats. Adjust capacity to demand fluctuations.\n\n**Benefit 3: Risk Mitigation**\nLessor bears many risks: obsolescence, maintenance, residual value. Lessee focuses on core business.\n\n**Benefit 4: Competitive Advantage**\nAccess to latest technology. Regular upgrades maintain competitive edge. Technology leadership attracts customers and talent.\n\n**Benefit 5: Capital Allocation for Growth**\nCapital available for higher-return investments: R&D, marketing, expansion. Better ROI on capital.\n\n**Scaling Strategies**\n\n**Strategy 1: Rapid Expansion**\nLease equipment to support rapid growth without capital constraints. Example: Retail chain expanding from 10 to 50 stores. Lease POS systems, shelving, equipment. Preserve capital for store buildout and inventory.\n\n**Strategy 2: Seasonal Scaling**\nLease additional equipment during peak seasons. Example: Logistics company leases additional trucks during holiday season. Remove after peak. Avoid idle assets.\n\n**Strategy 3: Market Testing**\nLease equipment to test new markets with minimal risk. Example: Manufacturing company tests new market with leased equipment. If successful, expand. If not, return equipment. Minimal loss.\n\n**Agility Advantages**\n\n**Advantage 1: Technology Refresh**\nRegular upgrades maintain competitive advantage. Stay ahead of competitors. Attract tech-savvy customers and employees.\n\n**Advantage 2: Market Adaptation**\nQuick response to market changes. Pivot business model without capital constraints. Adapt to new customer needs.\n\n**Advantage 3: Capacity Flexibility**\nMatch capacity to demand. Avoid over-investment in slow periods. Maximize utilization in peak periods.\n\n**Case Study: TechStartup Inc.**\n\nScenario: Founded 2 years ago, $50M revenue, 100% YoY growth\n\nChallenge:\n- Scale equipment rapidly\n- Preserve capital for R&D and marketing\n- Stay competitive with technology leaders\n- Maintain growth trajectory\n\nLeasing Strategy:\n- Lease all equipment (servers, workstations, networking)\n- Upgrade every 2 years\n- Scale with growth\n- Preserve capital for strategic investments\n\nFinancial Impact:\n- Equipment cost if owned: $10M\n- Lease cost: $2M/year\n- Capital preserved: $10M\n- Capital allocation: $5M R&D, $5M marketing\n\nStrategic Impact:\n- Achieved 100% YoY growth for 3 years\n- Maintained technology leadership\n- Became market leader in segment\n- Attracted top talent (modern equipment)\n- Attracted customers (technology leadership)\n\nConclusion: Leasing enabled rapid scaling, capital preservation, and strategic growth. Company became market leader through agility and technology leadership.");
    record2.set("video_url", "");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
