/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "LESSON 1.1: Lease Structure Basics and Components");
    record0.set("content_body", "SECTION 1: WHAT IS LEASE STRUCTURE?\n\nDefinition:\n- Framework for lease transaction\n- Defines roles and relationships\n- Specifies terms and conditions\n- Example: Equipment lease structure\n\nKey Elements:\n- Lessor and lessee\n- Equipment and specifications\n- Lease term and payment\n- Residual value and risk allocation\n- Example: Complete lease structure\n\nPurpose:\n- Achieve financial objectives\n- Manage risks\n- Optimize tax treatment\n- Ensure compliance\n- Example: Tax-efficient lease structure\n\nSECTION 2: LEASE STRUCTURE COMPONENTS\n\nComponent 1: Parties\n- Lessor (owner)\n- Lessee (user)\n- Broker/intermediary\n- Example: Equipment finance company and manufacturing company\n\nComponent 2: Equipment\n- Equipment description\n- Specifications\n- Condition\n- Location\n- Example: CNC manufacturing machine\n\nComponent 3: Lease Term\n- Commencement date\n- End date\n- Duration\n- Renewal options\n- Example: 5-year lease term\n\nComponent 4: Lease Payments\n- Payment amount\n- Payment frequency\n- Payment schedule\n- Escalation provisions\n- Example: $10,000 monthly payment\n\nComponent 5: Residual Value\n- Expected value at end\n- Residual value guarantee\n- Residual value risk allocation\n- Example: $50,000 residual value\n\nComponent 6: Maintenance and Insurance\n- Maintenance responsibility\n- Insurance requirements\n- Coverage amounts\n- Example: Lessor maintains equipment\n\nComponent 7: Default and Remedies\n- Default definition\n- Notice and cure period\n- Remedies available\n- Example: 10-day notice and cure period\n\nComponent 8: Termination\n- Early termination options\n- Termination fees\n- Equipment return conditions\n- Example: Early termination with $10,000 fee");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "LESSON 1.1: Lease Structure Basics and Components");
    record1.set("content_body", "SECTION 3: LEASE STRUCTURE TYPES\n\nType 1: Simple Lease\n- Basic structure\n- Lessor and lessee only\n- Standard terms\n- Example: Equipment lease\n\nType 2: Leveraged Lease\n- Multiple investors\n- Debt financing\n- Complex structure\n- Example: Large equipment lease with debt\n\nType 3: Sale-Leaseback\n- Asset sale and leaseback\n- Seller becomes lessee\n- Example: Company sells building and leases back\n\nType 4: Syndicated Lease\n- Multiple lessors\n- Shared ownership\n- Example: Large equipment lease with multiple lessors\n\nType 5: Cross-Border Lease\n- International transaction\n- Multiple jurisdictions\n- Example: Equipment lease across countries\n\nSECTION 4: STRUCTURAL OBJECTIVES\n\nObjective 1: Financial Optimization\n- Maximize returns\n- Minimize costs\n- Optimize cash flow\n- Example: Maximize lessor returns\n\nObjective 2: Risk Management\n- Allocate risks appropriately\n- Mitigate risks\n- Manage residual value risk\n- Example: Manage equipment obsolescence risk\n\nObjective 3: Tax Efficiency\n- Minimize tax liability\n- Maximize tax benefits\n- Optimize tax treatment\n- Example: Maximize depreciation deductions\n\nObjective 4: Accounting Treatment\n- Achieve desired accounting treatment\n- Optimize balance sheet impact\n- Example: Operating lease accounting treatment\n\nObjective 5: Regulatory Compliance\n- Ensure regulatory compliance\n- Meet legal requirements\n- Example: Comply with lease accounting standards");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "LESSON 1.1: Lease Structure Basics and Components");
    record2.set("content_body", "SECTION 5: STRUCTURAL CONSTRAINTS\n\nConstraint 1: Regulatory Constraints\n- Lease accounting standards (ASC 842, IFRS 16)\n- Tax regulations\n- Securities regulations\n- Example: ASC 842 lease classification rules\n\nConstraint 2: Financial Constraints\n- Lessor capital requirements\n- Lessee credit quality\n- Financing availability\n- Example: Lessor capital constraints\n\nConstraint 3: Market Constraints\n- Market rates and terms\n- Competitive environment\n- Example: Market lease rates\n\nConstraint 4: Operational Constraints\n- Equipment availability\n- Delivery timelines\n- Example: Equipment delivery constraints\n\nConstraint 5: Legal Constraints\n- Lease agreement requirements\n- Documentation requirements\n- Example: Lease agreement legal requirements\n\nSECTION 6: CASE STUDY - LEASE STRUCTURE BASICS\n\nCompany: StructureCorp\nBusiness: Equipment leasing company\nSituation: Structure equipment lease\n\nLease Structure:\n\nParties:\n- Lessor: StructureCorp (equipment finance company)\n- Lessee: ManufacturingCorp (manufacturing company)\n\nEquipment:\n- CNC Manufacturing Machine\n- Model: Advanced CNC-5000\n- Serial: #12345\n- Condition: New\n\nLease Term:\n- Commencement: January 1, 2024\n- End: December 31, 2028\n- Duration: 5 years\n- Renewal: Not available\n\nLease Payments:\n- Monthly payment: $10,000\n- Payment frequency: Monthly\n- Total payments: $600,000\n- Escalation: None\n\nResidual Value:\n- Expected residual: $50,000\n- Residual guarantee: None\n- Risk allocation: Lessor bears risk\n\nMaintenance:\n- Responsibility: Lessor maintains\n- Insurance: Lessee insures\n- Coverage: $1,000,000 liability\n\nDefault:\n- Definition: Failure to pay or breach\n- Notice period: 10 days\n- Cure period: 10 days\n- Remedies: Repossession, damages\n\nTermination:\n- Early termination: Not available\n- Equipment return: Required\n- Condition: Normal wear and tear\n\nOutcome:\n- Lease structure defined\n- All components specified\n- Roles and responsibilities clear\n- Ready for execution");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "LESSON 1.2: Lessor and Lessee Perspectives");
    record3.set("content_body", "SECTION 1: LESSOR PERSPECTIVE\n\nLessor Objectives:\n\nObjective 1: Return on Investment\n- Maximize return on capital\n- Achieve target yield\n- Example: 8% target yield\n\nObjective 2: Risk Management\n- Manage credit risk\n- Manage residual value risk\n- Manage operational risk\n- Example: Manage equipment obsolescence risk\n\nObjective 3: Capital Efficiency\n- Minimize capital requirements\n- Maximize leverage\n- Example: Minimize capital invested\n\nObjective 4: Portfolio Management\n- Diversify portfolio\n- Manage portfolio risk\n- Example: Diversify across industries\n\nObjective 5: Competitive Positioning\n- Maintain market share\n- Competitive pricing\n- Example: Competitive lease rates\n\nLessor Concerns:\n\nConcern 1: Credit Risk\n- Lessee default risk\n- Payment default risk\n- Example: Lessee bankruptcy risk\n\nConcern 2: Residual Value Risk\n- Equipment value decline\n- Obsolescence risk\n- Example: Equipment becomes obsolete\n\nConcern 3: Operational Risk\n- Equipment damage\n- Maintenance issues\n- Example: Equipment failure\n\nConcern 4: Market Risk\n- Interest rate risk\n- Refinancing risk\n- Example: Interest rate increases\n\nConcern 5: Regulatory Risk\n- Accounting treatment changes\n- Tax treatment changes\n- Example: Lease accounting standard changes\n\nSECTION 2: LESSEE PERSPECTIVE\n\nLessee Objectives:\n\nObjective 1: Cost Minimization\n- Minimize lease costs\n- Minimize total cost of ownership\n- Example: Minimize monthly payment\n\nObjective 2: Flexibility\n- Maintain operational flexibility\n- Easy to upgrade or change\n- Example: Upgrade option available\n\nObjective 3: Capital Preservation\n- Preserve capital for growth\n- Minimize capital investment\n- Example: Preserve $100,000 capital\n\nObjective 4: Accounting Treatment\n- Achieve desired accounting treatment\n- Minimize balance sheet impact\n- Example: Operating lease treatment\n\nObjective 5: Operational Efficiency\n- Reduce operational burden\n- Maintenance included\n- Example: Lessor maintains equipment\n\nLessee Concerns:\n\nConcern 1: Payment Obligations\n- Fixed payment obligations\n- Cash flow impact\n- Example: $10,000 monthly payment\n\nConcern 2: Equipment Availability\n- Equipment availability\n- Delivery timelines\n- Example: Equipment delivery delays\n\nConcern 3: Flexibility Limitations\n- Limited upgrade options\n- Limited termination options\n- Example: No early termination option\n\nConcern 4: Residual Value Risk\n- Residual value guarantee\n- Excess wear and tear charges\n- Example: Residual value guarantee\n\nConcern 5: Compliance Obligations\n- Maintenance obligations\n- Insurance obligations\n- Example: Maintain equipment properly");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "LESSON 1.2: Lessor and Lessee Perspectives");
    record4.set("content_body", "SECTION 3: ALIGNMENT STRATEGIES\n\nStrategy 1: Balanced Risk Allocation\n- Allocate risks appropriately\n- Balance lessor and lessee interests\n- Example: Lessor bears residual value risk\n\nStrategy 2: Flexible Payment Structures\n- Offer flexible payment options\n- Accommodate lessee needs\n- Example: Offer escalating payment option\n\nStrategy 3: Upgrade and Renewal Options\n- Provide upgrade options\n- Provide renewal options\n- Example: Upgrade option after 3 years\n\nStrategy 4: Maintenance and Support\n- Include maintenance in lease\n- Provide support services\n- Example: Lessor maintains equipment\n\nStrategy 5: Transparent Pricing\n- Clear pricing structure\n- No hidden costs\n- Example: All-inclusive lease payment\n\nSECTION 4: STRUCTURAL TRADE-OFFS\n\nTrade-off 1: Payment vs Residual\n- Higher payments, lower residual\n- Lower payments, higher residual\n- Example: $10,000/month vs $50,000 residual\n\nTrade-off 2: Flexibility vs Cost\n- More flexibility, higher cost\n- Less flexibility, lower cost\n- Example: Upgrade option increases cost\n\nTrade-off 3: Risk Allocation\n- Lessor bears more risk, higher cost\n- Lessee bears more risk, lower cost\n- Example: Lessor bears residual risk\n\nTrade-off 4: Term Length\n- Shorter term, higher payment\n- Longer term, lower payment\n- Example: 3-year vs 5-year term\n\nTrade-off 5: Maintenance\n- Lessor maintains, higher cost\n- Lessee maintains, lower cost\n- Example: Lessor maintains equipment\n\nSECTION 5: NEGOTIATION FRAMEWORK\n\nFramework Element 1: Lessor Requirements\n- Minimum return on investment\n- Maximum credit risk\n- Example: 8% minimum return\n\nFramework Element 2: Lessee Requirements\n- Maximum payment\n- Minimum flexibility\n- Example: $10,000 maximum monthly payment\n\nFramework Element 3: Market Conditions\n- Market lease rates\n- Market terms\n- Example: Market rates 8-10%\n\nFramework Element 4: Negotiation Range\n- Lessor floor\n- Lessee ceiling\n- Example: $9,000-$11,000 monthly payment\n\nFramework Element 5: Value Creation\n- Identify mutual benefits\n- Create win-win solutions\n- Example: Upgrade option benefits both parties");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "LESSON 1.2: Lessor and Lessee Perspectives");
    record5.set("content_body", "SECTION 6: CASE STUDY - LESSOR AND LESSEE PERSPECTIVES\n\nLessor: LessorCorp\nLessee: LesseeCorp\nEquipment: Manufacturing equipment\nValue: $500,000\n\nLessor Perspective:\n\nObjectives:\n- Achieve 8% return on investment\n- Manage credit risk\n- Manage residual value risk\n- Maintain market competitiveness\n\nConcerns:\n- Lessee credit quality\n- Equipment obsolescence\n- Interest rate risk\n- Regulatory changes\n\nRequirements:\n- Minimum 8% return\n- Maximum 5% credit risk\n- Residual value guarantee\n- Maintenance by lessee\n\nLessee Perspective:\n\nObjectives:\n- Minimize lease costs\n- Preserve capital\n- Maintain flexibility\n- Achieve operating lease treatment\n\nConcerns:\n- Monthly payment amount\n- Equipment availability\n- Upgrade options\n- Maintenance obligations\n\nRequirements:\n- Maximum $10,000 monthly payment\n- Upgrade option after 3 years\n- Lessor maintains equipment\n- Operating lease treatment\n\nNegotiation:\n\nInitial Offer:\n- Lessor: $11,000/month, 5-year term, lessee maintains\n- Lessee: $9,000/month, 3-year term, lessor maintains\n\nNegotiated Agreement:\n- Payment: $10,000/month\n- Term: 5 years\n- Upgrade option: After 3 years\n- Maintenance: Lessor maintains\n- Return: 8.5% (lessor satisfied)\n- Cost: Acceptable to lessee\n\nOutcome:\n- Win-win agreement reached\n- Both parties satisfied\n- Lease structured successfully");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "LESSON 1.3: Structuring Objectives and Constraints");
    record6.set("content_body", "SECTION 1: PRIMARY STRUCTURING OBJECTIVES\n\nObjective 1: Financial Optimization\n- Maximize lessor returns\n- Minimize lessee costs\n- Optimize cash flow\n- Example: Maximize 8% return\n\nObjective 2: Risk Management\n- Allocate risks appropriately\n- Mitigate key risks\n- Manage residual value risk\n- Example: Manage equipment obsolescence\n\nObjective 3: Tax Efficiency\n- Minimize tax liability\n- Maximize tax benefits\n- Optimize tax treatment\n- Example: Maximize depreciation deductions\n\nObjective 4: Accounting Treatment\n- Achieve desired accounting classification\n- Optimize balance sheet impact\n- Minimize income statement impact\n- Example: Operating lease classification\n\nObjective 5: Regulatory Compliance\n- Ensure regulatory compliance\n- Meet legal requirements\n- Comply with accounting standards\n- Example: Comply with ASC 842\n\nSECTION 2: SECONDARY STRUCTURING OBJECTIVES\n\nObjective 1: Competitive Positioning\n- Maintain market share\n- Competitive pricing\n- Differentiated offerings\n- Example: Competitive lease rates\n\nObjective 2: Operational Efficiency\n- Streamline processes\n- Reduce administrative burden\n- Automate workflows\n- Example: Automated lease management\n\nObjective 3: Flexibility and Scalability\n- Flexible structures\n- Scalable solutions\n- Adaptable to market changes\n- Example: Flexible payment options\n\nObjective 4: Relationship Building\n- Build customer relationships\n- Long-term partnerships\n- Customer satisfaction\n- Example: Excellent customer service\n\nObjective 5: Innovation\n- Innovative structures\n- New product offerings\n- Market differentiation\n- Example: Innovative lease products\n\nSECTION 3: REGULATORY CONSTRAINTS\n\nConstraint 1: Lease Accounting Standards\n- ASC 842 (US GAAP)\n- IFRS 16 (IFRS)\n- Lease classification rules\n- Example: Operating vs finance lease classification\n\nConstraint 2: Tax Regulations\n- Tax lease requirements\n- Depreciation rules\n- Investment tax credits\n- Example: Tax lease classification requirements\n\nConstraint 3: Securities Regulations\n- Securitization requirements\n- Disclosure requirements\n- Example: Securitization disclosure requirements\n\nConstraint 4: Consumer Protection Laws\n- Truth in Leasing Act\n- Disclosure requirements\n- Example: Lease disclosure requirements\n\nConstraint 5: Environmental Regulations\n- Environmental compliance\n- Equipment disposal\n- Example: Equipment disposal requirements");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "LESSON 1.3: Structuring Objectives and Constraints");
    record7.set("content_body", "SECTION 4: FINANCIAL CONSTRAINTS\n\nConstraint 1: Lessor Capital Requirements\n- Minimum capital requirements\n- Capital adequacy ratios\n- Example: Minimum 10% capital ratio\n\nConstraint 2: Lessee Credit Quality\n- Minimum credit score\n- Maximum debt-to-equity ratio\n- Example: Minimum 700 credit score\n\nConstraint 3: Financing Availability\n- Debt financing availability\n- Interest rates\n- Example: 5% financing rate available\n\nConstraint 4: Market Conditions\n- Market lease rates\n- Market terms\n- Example: Market rates 8-10%\n\nConstraint 5: Pricing Constraints\n- Minimum pricing\n- Maximum pricing\n- Example: Minimum 8% return\n\nSECTION 5: OPERATIONAL CONSTRAINTS\n\nConstraint 1: Equipment Availability\n- Equipment availability\n- Delivery timelines\n- Example: 30-day delivery timeline\n\nConstraint 2: Vendor Relationships\n- Vendor availability\n- Vendor pricing\n- Example: Vendor pricing constraints\n\nConstraint 3: Administrative Capacity\n- Processing capacity\n- Documentation capacity\n- Example: Process 100 leases/month\n\nConstraint 4: Technology Limitations\n- System capabilities\n- Integration limitations\n- Example: System integration limitations\n\nConstraint 5: Staffing Constraints\n- Available staff\n- Expertise requirements\n- Example: Limited lease structuring expertise");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "LESSON 1.3: Structuring Objectives and Constraints");
    record8.set("content_body", "SECTION 6: CASE STUDY - STRUCTURING OBJECTIVES AND CONSTRAINTS\n\nCompany: ObjectivesCorp\nBusiness: Equipment leasing company\nSituation: Structure complex equipment lease\n\nStructuring Objectives:\n\nPrimary Objectives:\n1. Achieve 8% return on investment\n2. Manage credit risk (maximum 5%)\n3. Minimize tax liability\n4. Achieve operating lease treatment\n5. Ensure regulatory compliance\n\nSecondary Objectives:\n1. Maintain competitive positioning\n2. Streamline processes\n3. Provide flexible options\n4. Build customer relationships\n5. Innovate lease products\n\nConstraints:\n\nRegulatory Constraints:\n- ASC 842 lease classification rules\n- Tax lease requirements\n- Consumer protection laws\n- Environmental compliance\n\nFinancial Constraints:\n- Lessor capital: $500,000 available\n- Lessee credit: 750+ credit score\n- Financing: 5% available\n- Market rates: 8-10%\n- Pricing: Minimum 8% return\n\nOperational Constraints:\n- Equipment delivery: 30 days\n- Processing capacity: 100 leases/month\n- System integration: Limited\n- Staffing: 5 lease professionals\n\nStructuring Solution:\n\nLease Structure:\n- Equipment: Manufacturing equipment\n- Value: $500,000\n- Term: 5 years\n- Payment: $10,000/month\n- Return: 8.5% (meets objective)\n\nRisk Management:\n- Credit risk: 3% (within constraint)\n- Residual value: $50,000 (managed)\n- Operational risk: Lessor maintains\n\nTax Treatment:\n- Tax lease classification\n- Depreciation deductions: $100,000/year\n- Tax savings: $25,000/year\n\nAccounting Treatment:\n- Operating lease classification\n- ROU asset: $500,000\n- Lease liability: $500,000\n\nCompliance:\n- ASC 842 compliant\n- Tax lease compliant\n- Consumer protection compliant\n- Environmental compliant\n\nOutcome:\n- All objectives achieved\n- All constraints satisfied\n- Lease structured successfully\n- Ready for execution");
  app.save(record8);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
