/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_3963162141");
    record0.set("content_body", "IFRS 16 vs ASC 842 - Comparative Analysis\n\n1. LEASE DEFINITION\nBoth standards: Control-based approach, apply to all leases except short-term (<12 months) and low-value assets\nKey Difference: Minimal; both substantially aligned\n\n2. LESSEE ACCOUNTING\nIFRS 16: All leases on balance sheet (ROU asset and lease liability)\nASC 842: All leases on balance sheet (ROU asset and lease liability)\nKey Difference: Substantially aligned\n\n3. LESSOR ACCOUNTING\nIFRS 16: Two lease types (Operating and Finance)\nASC 842: Three lease types (Operating, Sales-Type, Direct Financing)\nKey Difference: ASC 842 distinguishes sales-type from direct financing leases\n\n4. DISCOUNT RATE\nIFRS 16: Implicit rate (primary); incremental borrowing rate (secondary)\nASC 842: Implicit rate if readily determinable (primary); incremental borrowing rate (secondary)\nKey Difference: ASC 842 adds \"readily determinable\" criterion\n\n5. LEASE TERM\nIFRS 16: Non-cancellable period + periods with significant economic incentive\nASC 842: Non-cancellable period + periods reasonably certain to be exercised\nKey Difference: Different threshold for including renewal/termination options\n\n6. LEASE PAYMENTS\nBoth include: Fixed payments, variable (index-linked), residual guarantees, termination penalties\nBoth exclude: Variable (non-index), service costs, taxes\nKey Difference: Substantially aligned\n\n7. DISCLOSURES\nIFRS 16: Key metrics (maturity analysis, depreciation, expense by type)\nASC 842: More detailed quantitative disclosures\nKey Difference: ASC 842 requires more extensive schedules\n\n8. CONVERGENCE\nBoth standards converged on control-based lessee accounting\nLessor accounting remains divergent\nOngoing IASB/FASB discussions on alignment\n\n9. MULTINATIONAL IMPLICATIONS\n- Separate tracking for US (ASC 842) and international (IFRS 16) operations\n- Lessor accounting differences require jurisdiction-specific treatment\n- Discount rate determination may differ\n- Lease term calculations may differ\n- Consolidation requires reconciliation\n\n10. TRANSITION STRATEGY\n- Phased implementation by jurisdiction\n- Configure systems for both standards\n- Maintain separate calculation modules\n- Train staff on key differences\n- Document assumptions and judgments");
  app.save(record0);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
