/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "<LESSON_3_1_ID>");
    record0.set("content_body", "# Risk Management in Securitization\n\n## Types of Risks\n\n### Credit Risk\n- Risk of lessee default and loss on defaulted leases\n- Example: 2% default rate, 15% loss severity\n- Mitigation: Portfolio diversification, subordination (30%), reserve accounts\n\n### Prepayment Risk\n- Risk of early lease termination, shortens WAL\n- Example: Lessee pays off lease early\n- Mitigation: Prepayment penalties (1%), diversified profiles, scenario modeling\n\n### Interest Rate Risk\n- Risk of rising interest rates affecting floating rate tranches\n- Example: LIBOR increases, coupon increases\n- Mitigation: Interest rate swaps, fixed rate tranches, hedging\n\n### Liquidity Risk\n- Risk of inability to sell securities in secondary market\n- Example: Limited buyer demand\n- Mitigation: Diversified investor base, liquidity facilities ($5M)\n\n### Operational Risk\n- Risk of servicer failure or process failures\n- Example: Servicer bankruptcy, data errors\n- Mitigation: Servicer oversight (monthly), backup servicer, strong controls\n\n### Model Risk\n- Risk of model errors or incorrect assumptions\n- Example: Default rate assumption incorrect\n- Mitigation: Annual validation, quarterly sensitivity analysis, conservative assumptions\n\n## Risk Assessment Process\n\n1. **Risk Identification**: Identify all risks, document, assess likelihood\n2. **Risk Quantification**: Quantify impact, model scenarios (2%, 5%, 10% defaults)\n3. **Risk Prioritization**: Prioritize risks, focus on material risks\n4. **Risk Mitigation**: Develop strategies, implement controls\n5. **Risk Monitoring**: Monitor indicators, track performance, adjust as needed\n\n## Stress Testing\n\n**Default Rate Stress:**\n- Base (2%): All tranches protected\n- Stress (5%): Mezzanine at risk\n- Severe (10%): Senior at risk\n\n**Loss Severity Stress:**\n- Base (15%): All tranches protected\n- Stress (25%): Mezzanine at risk\n- Severe (35%): Senior at risk\n\n**Prepayment Stress:**\n- Increase prepayment to 5%, 10%, 20%\n- Shorter WAL, reduced returns, reinvestment risk\n\n## Case Study: RiskManagementCorp\n\n**Portfolio:** $50M, 2% default, 15% loss severity, 5% prepayment\n\n**Risk Mitigation:**\n- Credit: 30% subordination, 10% OC, 5% reserve\n- Prepayment: 1% penalties, diversified profiles\n- Interest rate: 50% swap, 30% fixed tranches\n- Liquidity: Investor diversification, $5M facility\n- Operational: Monthly oversight, backup servicer\n- Model: Annual validation, quarterly sensitivity\n\n**Outcome:** Comprehensive risk management framework with strong mitigation strategies.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "<LESSON_3_2_ID>");
    record1.set("content_body", "# Regulatory and Accounting Considerations\n\n## Regulatory Framework\n\n### Dodd-Frank Act\n- Risk retention: 5% of deal (originator retains)\n- Disclosure requirements\n- Investor protection\n- Impact: Increased compliance costs, enhanced protection, reduced leverage\n\n### SEC Regulations\n- Registration requirements (Form S-3)\n- Detailed disclosure requirements\n- Investor suitability verification\n- Impact: Increased disclosure, enhanced transparency, investor protection\n\n### Rating Agency Regulations\n- Rating methodology disclosure\n- Conflict of interest management\n- Quarterly surveillance reports\n- Impact: Enhanced rating quality, improved transparency, better protection\n\n## Accounting Treatment\n\n### Originator Accounting\n- Lease portfolio derecognized ($50M)\n- Gain/loss on sale recognized ($2M gain)\n- Servicing asset/liability recognized ($1M)\n- Impact: Removes assets from balance sheet, improves ROA and ROE\n\n### Investor Accounting\n- Securities recognized as investment\n- Interest income recognized quarterly\n- Amortization of premium/discount\n- Impact: Recognizes investment income, reflects fair value changes\n\n### Servicer Accounting\n- Servicing fees recognized monthly ($125K/month)\n- Servicing asset/liability recognized ($500K)\n- Impairment testing quarterly\n- Impact: Recognizes servicing income, reflects asset value\n\n## Disclosure Requirements\n\n**Portfolio Characteristics:**\n- Lease count: 100\n- Portfolio balance: $50M\n- Geographic: 45 states\n- Industry: 18 industries\n- Credit quality: Average FICO 750\n\n**Performance Metrics:**\n- Default rate: 2%\n- Loss severity: 15%\n- Prepayment rate: 5%\n- Delinquency rate: 1%\n\n**Structural Features:**\n- Senior: $35M (70%, AAA)\n- Mezzanine: $10M (20%, A)\n- Subordinated: $5M (10%, BBB)\n- Subordination: 30%\n\n**Risk Factors:**\n- Credit risk: Moderate\n- Prepayment risk: Moderate\n- Interest rate risk: Moderate\n- Liquidity risk: Moderate\n\n## Case Study: ComplianceCorp\n\n**Regulatory Compliance:**\n- Dodd-Frank: 5% retention (BBB tranche)\n- SEC: Form S-3 registration, detailed prospectus\n- Rating Agencies: Methodology disclosed, quarterly surveillance\n\n**Accounting Treatment:**\n- Originator: $50M derecognized, $2M gain, $1M servicing asset\n- Investor: $50M investment, quarterly income\n- Servicer: $125K/month fees, $500K servicing asset\n\n**Outcome:** Full regulatory compliance, correct accounting, comprehensive disclosures.");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "<LESSON_3_3_ID>");
    record2.set("content_body", "# Case Studies and Market Trends\n\n## Case Studies\n\n### Equipment Lease Securitization\n- Portfolio: 500 leases, $250M\n- Structure: 75% AAA, 15% A, 10% BBB\n- Pricing: AAA at LIBOR + 40 bps\n- Outcome: Successful, strong investor demand\n- Lesson: Large portfolios attract investors, strong credit supports AAA\n\n### Vehicle Lease Securitization\n- Portfolio: 1,000 leases, $100M\n- Structure: 70% AAA, 20% A, 10% BBB\n- Pricing: AAA at LIBOR + 60 bps\n- Outcome: Successful, good investor demand\n- Lesson: Higher prepayment risk, pricing reflects risk\n\n### Technology Equipment Lease Securitization\n- Portfolio: 200 leases, $50M\n- Structure: 65% AAA, 20% A, 15% BBB\n- Pricing: AAA at LIBOR + 80 bps\n- Outcome: Successful, moderate investor demand\n- Lesson: Higher obsolescence risk, smaller deals have higher costs\n\n## Market Trends\n\n**Growth in Lease Securitization:**\n- 2015: $30B annual\n- 2018: $50B annual\n- 2021: $60B annual\n- 2024: $70B annual\n- Driver: 5% annual growth\n\n**Collateral Diversification:**\n- Equipment leases: 40%\n- Vehicle leases: 35%\n- Technology leases: 15%\n- Other leases: 10%\n\n**Investor Demand:**\n- Institutional investors: 60%\n- Insurance companies: 20%\n- Banks: 15%\n- Other: 5%\n\n**Enhanced Transparency:**\n- Detailed disclosures: 100%\n- Performance reporting: Monthly\n- Investor communication: Regular\n\n## Future Outlook\n\n**Market Growth:**\n- 2025: $75B annual\n- 2026: $80B annual\n- 2027: $85B annual\n\n**Technology Integration:**\n- Blockchain for settlement\n- AI-powered underwriting\n- Real-time reporting\n\n**ESG Considerations:**\n- ESG-focused securitizations\n- Sustainable equipment leases\n- Green financing\n\n## Case Study: MarketTrendsCorp\n\n**Current Market:** $70B annual, 5% growth, strong demand, competitive pricing\n\n**Trends:** Growing securitization, diversifying collateral, increasing demand, enhancing transparency\n\n**Opportunities:** Technology integration (blockchain, AI), ESG focus, new asset classes, international expansion\n\n**Outcome:** Market trends understood, future opportunities identified, strategic positioning developed.");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
