/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "LESSON_1_ID");
    record0.set("content_body", "# Lease vs Buy Overview and Key Concepts\n\n## What is Lease vs Buy Decision?\nThe lease vs buy decision is the process of evaluating whether to lease (rent) or purchase an asset. This fundamental financial choice affects capital allocation, cash flow, and operational flexibility.\n\n## Leasing Option\n**Operating Lease**: Short-term rental, asset remains with lessor, treated as expense\n**Capital Lease**: Long-term commitment, effectively transfers ownership, capitalized on balance sheet\n\nAdvantages: Lower upfront costs, predictable payments, maintenance included, flexibility, no residual risk\nDisadvantages: Long-term cost may be higher, usage limits, wear and tear charges, no ownership\n\n## Buying Option\n**Cash Purchase**: Full payment upfront, immediate ownership\n**Financed Purchase**: Loan arrangement, gradual equity buildup\n\nAdvantages: Full ownership, long-term savings, customization, no usage limits, equity buildup\nDisadvantages: High upfront cost, maintenance responsibility, obsolescence risk, residual value risk\n\n## Key Decision Drivers\n**Financial**: Cost comparison, cash flow impact, financing considerations\n**Operational**: Asset utilization, operational control, maintenance requirements\n**Strategic**: Business strategy alignment, risk management, core competency\n**Market**: Interest rates, inflation, industry trends, technological change\n\n## Decision Framework\n1. Define requirements and specifications\n2. Gather lease and purchase quotes\n3. Perform quantitative analysis (NPV, IRR, cost analysis)\n4. Evaluate qualitative factors (flexibility, technology, risk)\n5. Make decision and implement\n\n## Case Study: DecisionCorp Manufacturing\nDecisionCorp needed 5 CNC machines ($500,000 total). Lease cost: $300,000 over 5 years. Buy cost: $443,500. Decision: Lease (saved $143,500, provided flexibility, included maintenance).");
    record0.set("video_url", "");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "LESSON_2_ID");
    record1.set("content_body", "# Financial Analysis Fundamentals\n\n## Time Value of Money\nMoney today is worth more than money tomorrow due to earning potential, inflation, risk, and opportunity cost.\n\n**Present Value (PV)**: Current value of future cash flow. Formula: PV = FV / (1 + r)^n\n**Future Value (FV)**: Value of investment at future date. Formula: FV = PV \u00d7 (1 + r)^n\n**Discount Rate**: Interest rate used to calculate present value, reflects time value and risk\n**Compounding**: Earning returns on returns, accelerates growth over time\n\n## Net Present Value (NPV)\nNPV is the sum of present values of all cash flows, discounted at cost of capital.\n\nFormula: NPV = \u03a3 [CF_t / (1 + r)^t] - Initial Investment\n\nInterpretation:\n- NPV > 0: Accept investment (creates value)\n- NPV = 0: Indifferent (breaks even)\n- NPV < 0: Reject investment (destroys value)\n\n## Cost of Capital\n**Cost of Debt**: Interest rate on borrowed funds, tax-adjusted\n**Cost of Equity**: Return required by equity investors\n**WACC**: Weighted average cost of all capital sources\n\nFormula: WACC = (E/V \u00d7 Cost of Equity) + (D/V \u00d7 Cost of Debt \u00d7 (1 - Tax Rate))\n\n## Cash Flow Analysis\nIdentify all cash flows: initial investment, operating cash flows, terminal cash flows\nDetermine timing, quantify amounts, discount to present value\n\n## Sensitivity Analysis\nDetermine how changes in key assumptions affect outcomes.\n\n**One-Way**: Change one variable at a time\n**Two-Way**: Change two variables simultaneously\n**Scenario**: Analyze best case, base case, worst case\n\n## Case Study: FinancialCorp\nFinancialCorp needed servers ($1,000,000). Lease NPV: -$738,287. Buy NPV: -$1,658,674. Decision: Lease (saved $920,387, provided technology flexibility, included maintenance).");
    record1.set("video_url", "");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
