/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("student_progress_dashboards");

  const record0 = new Record(collection);
    record0.set("student_id", "student_001");
    record0.set("course_id", "tax-optimization-leasing");
    record0.set("dashboard_title", "Tax Optimization & Leasing - Progress Dashboard");
    record0.set("dashboard_type", "course_progress");
    record0.set("purpose", "Track student progress through Tax Optimization & Leasing course");
    record0.set("overall_progress_percentage", 65);
    record0.set("overall_performance_score", 72);
    record0.set("target_score", 80);
    record0.set("performance_trend", "Improving");
    record0.set("current_grade", "B");
    record0.set("total_hours_spent", 28);
    record0.set("average_daily_engagement_minutes", 45);
    record0.set("last_activity", "2024-01-15");
    record0.set("engagement_trend", "Increasing");
    record0.set("lessons_completed", 5);
    record0.set("quizzes_completed", 4);
    record0.set("study_guides_completed", 3);
    record0.set("case_studies_completed", 2);
    record0.set("capstone_progress_percentage", 25);
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("student_id", "student_002");
    record1.set("course_id", "tax-optimization-leasing");
    record1.set("dashboard_title", "Tax Optimization & Leasing - Progress Dashboard");
    record1.set("dashboard_type", "course_progress");
    record1.set("purpose", "Track student progress through Tax Optimization & Leasing course");
    record1.set("overall_progress_percentage", 52);
    record1.set("overall_performance_score", 58);
    record1.set("target_score", 80);
    record1.set("performance_trend", "Improving");
    record1.set("current_grade", "C");
    record1.set("total_hours_spent", 18);
    record1.set("average_daily_engagement_minutes", 32);
    record1.set("last_activity", "2024-01-14");
    record1.set("engagement_trend", "Stable");
    record1.set("lessons_completed", 3);
    record1.set("quizzes_completed", 2);
    record1.set("study_guides_completed", 2);
    record1.set("case_studies_completed", 1);
    record1.set("capstone_progress_percentage", 10);
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("student_id", "student_003");
    record2.set("course_id", "tax-optimization-leasing");
    record2.set("dashboard_title", "Tax Optimization & Leasing - Progress Dashboard");
    record2.set("dashboard_type", "course_progress");
    record2.set("purpose", "Track student progress through Tax Optimization & Leasing course");
    record2.set("overall_progress_percentage", 78);
    record2.set("overall_performance_score", 85);
    record2.set("target_score", 80);
    record2.set("performance_trend", "Improving");
    record2.set("current_grade", "A");
    record2.set("total_hours_spent", 42);
    record2.set("average_daily_engagement_minutes", 78);
    record2.set("last_activity", "2024-01-16");
    record2.set("engagement_trend", "Increasing");
    record2.set("lessons_completed", 7);
    record2.set("quizzes_completed", 6);
    record2.set("study_guides_completed", 5);
    record2.set("case_studies_completed", 4);
    record2.set("capstone_progress_percentage", 45);
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("student_id", "student_004");
    record3.set("course_id", "tax-optimization-leasing");
    record3.set("dashboard_title", "Tax Optimization & Leasing - Progress Dashboard");
    record3.set("dashboard_type", "course_progress");
    record3.set("purpose", "Track student progress through Tax Optimization & Leasing course");
    record3.set("overall_progress_percentage", 45);
    record3.set("overall_performance_score", 52);
    record3.set("target_score", 80);
    record3.set("performance_trend", "Improving");
    record3.set("current_grade", "D");
    record3.set("total_hours_spent", 12);
    record3.set("average_daily_engagement_minutes", 22);
    record3.set("last_activity", "2024-01-13");
    record3.set("engagement_trend", "Stable");
    record3.set("lessons_completed", 3);
    record3.set("quizzes_completed", 2);
    record3.set("study_guides_completed", 1);
    record3.set("case_studies_completed", 0);
    record3.set("capstone_progress_percentage", 5);
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("student_id", "student_005");
    record4.set("course_id", "tax-optimization-leasing");
    record4.set("dashboard_title", "Tax Optimization & Leasing - Progress Dashboard");
    record4.set("dashboard_type", "course_progress");
    record4.set("purpose", "Track student progress through Tax Optimization & Leasing course");
    record4.set("overall_progress_percentage", 88);
    record4.set("overall_performance_score", 92);
    record4.set("target_score", 80);
    record4.set("performance_trend", "Improving");
    record4.set("current_grade", "A");
    record4.set("total_hours_spent", 50);
    record4.set("average_daily_engagement_minutes", 95);
    record4.set("last_activity", "2024-01-16");
    record4.set("engagement_trend", "Increasing");
    record4.set("lessons_completed", 8);
    record4.set("quizzes_completed", 7);
    record4.set("study_guides_completed", 6);
    record4.set("case_studies_completed", 5);
    record4.set("capstone_progress_percentage", 60);
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("student_id", "student_006");
    record5.set("course_id", "tax-optimization-leasing");
    record5.set("dashboard_title", "Tax Optimization & Leasing - Progress Dashboard");
    record5.set("dashboard_type", "course_progress");
    record5.set("purpose", "Track student progress through Tax Optimization & Leasing course");
    record5.set("overall_progress_percentage", 62);
    record5.set("overall_performance_score", 68);
    record5.set("target_score", 80);
    record5.set("performance_trend", "Improving");
    record5.set("current_grade", "B");
    record5.set("total_hours_spent", 32);
    record5.set("average_daily_engagement_minutes", 55);
    record5.set("last_activity", "2024-01-15");
    record5.set("engagement_trend", "Increasing");
    record5.set("lessons_completed", 5);
    record5.set("quizzes_completed", 4);
    record5.set("study_guides_completed", 3);
    record5.set("case_studies_completed", 2);
    record5.set("capstone_progress_percentage", 30);
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("student_id", "student_007");
    record6.set("course_id", "tax-optimization-leasing");
    record6.set("dashboard_title", "Tax Optimization & Leasing - Progress Dashboard");
    record6.set("dashboard_type", "course_progress");
    record6.set("purpose", "Track student progress through Tax Optimization & Leasing course");
    record6.set("overall_progress_percentage", 72);
    record6.set("overall_performance_score", 78);
    record6.set("target_score", 80);
    record6.set("performance_trend", "Improving");
    record6.set("current_grade", "B");
    record6.set("total_hours_spent", 38);
    record6.set("average_daily_engagement_minutes", 68);
    record6.set("last_activity", "2024-01-16");
    record6.set("engagement_trend", "Increasing");
    record6.set("lessons_completed", 6);
    record6.set("quizzes_completed", 5);
    record6.set("study_guides_completed", 4);
    record6.set("case_studies_completed", 3);
    record6.set("capstone_progress_percentage", 40);
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("student_id", "student_008");
    record7.set("course_id", "tax-optimization-leasing");
    record7.set("dashboard_title", "Tax Optimization & Leasing - Progress Dashboard");
    record7.set("dashboard_type", "course_progress");
    record7.set("purpose", "Track student progress through Tax Optimization & Leasing course");
    record7.set("overall_progress_percentage", 55);
    record7.set("overall_performance_score", 62);
    record7.set("target_score", 80);
    record7.set("performance_trend", "Improving");
    record7.set("current_grade", "C");
    record7.set("total_hours_spent", 22);
    record7.set("average_daily_engagement_minutes", 38);
    record7.set("last_activity", "2024-01-14");
    record7.set("engagement_trend", "Stable");
    record7.set("lessons_completed", 4);
    record7.set("quizzes_completed", 3);
    record7.set("study_guides_completed", 2);
    record7.set("case_studies_completed", 1);
    record7.set("capstone_progress_percentage", 15);
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("student_id", "student_009");
    record8.set("course_id", "tax-optimization-leasing");
    record8.set("dashboard_title", "Tax Optimization & Leasing - Progress Dashboard");
    record8.set("dashboard_type", "course_progress");
    record8.set("purpose", "Track student progress through Tax Optimization & Leasing course");
    record8.set("overall_progress_percentage", 95);
    record8.set("overall_performance_score", 98);
    record8.set("target_score", 80);
    record8.set("performance_trend", "Improving");
    record8.set("current_grade", "A");
    record8.set("total_hours_spent", 48);
    record8.set("average_daily_engagement_minutes", 120);
    record8.set("last_activity", "2024-01-16");
    record8.set("engagement_trend", "Increasing");
    record8.set("lessons_completed", 8);
    record8.set("quizzes_completed", 7);
    record8.set("study_guides_completed", 6);
    record8.set("case_studies_completed", 5);
    record8.set("capstone_progress_percentage", 75);
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("student_id", "student_010");
    record9.set("course_id", "tax-optimization-leasing");
    record9.set("dashboard_title", "Tax Optimization & Leasing - Progress Dashboard");
    record9.set("dashboard_type", "course_progress");
    record9.set("purpose", "Track student progress through Tax Optimization & Leasing course");
    record9.set("overall_progress_percentage", 68);
    record9.set("overall_performance_score", 75);
    record9.set("target_score", 80);
    record9.set("performance_trend", "Improving");
    record9.set("current_grade", "B");
    record9.set("total_hours_spent", 35);
    record9.set("average_daily_engagement_minutes", 62);
    record9.set("last_activity", "2024-01-15");
    record9.set("engagement_trend", "Increasing");
    record9.set("lessons_completed", 6);
    record9.set("quizzes_completed", 5);
    record9.set("study_guides_completed", 4);
    record9.set("case_studies_completed", 3);
    record9.set("capstone_progress_percentage", 35);
  app.save(record9);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
