/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_lesson_1");
    record0.set("content_body", "SECTION 1: IFRS 16 Introduction and Background\n\nWhat is IFRS 16?\n- International Financial Reporting Standard 16\n- Lease accounting standard issued by IASB\n- Effective date: January 1, 2019\n- Replaces: IAS 17 (Leases)\n- Applies to: Public and private companies using IFRS\n\nKey Principle:\n- Single lease accounting model\n- All leases recognized on balance sheet\n- Right-of-use asset and lease liability\n\nSECTION 2: IFRS 16 Scope and Applicability\n\nApplies To:\n- All leases (except specific exemptions)\n- Lessees and lessors\n- Public and private companies\n- All industries\n\nExemptions:\n\nShort-term Leases:\n- Lease term \u2264 12 months\n- No purchase option\n- Lessee accounting: Optional exemption\n\nLow-Value Assets:\n- Asset value < $5,000\n- Lessee accounting: Optional exemption\n\nSECTION 3: Key Definitions and Concepts\n\nLease Definition:\n- Contract that conveys right to use asset\n- For period of time\n- In exchange for consideration\n\nKey Components:\n\n1. Right-of-Use Asset:\n   - Lessee's right to use underlying asset\n   - Recognized on balance sheet\n   - Depreciated over lease term\n\n2. Lease Liability:\n   - Lessee's obligation to pay lease payments\n   - Recognized on balance sheet\n   - Discounted at incremental borrowing rate\n\n3. Lease Payments:\n   - Fixed payments\n   - Variable payments (linked to index or rate)\n   - Residual value guarantees\n\n4. Lease Term:\n   - Non-cancellable period\n   - Plus renewal periods (if reasonably certain)\n   - Plus periods covered by termination penalties\n\n5. Incremental Borrowing Rate:\n   - Rate to borrow funds for asset\n   - Used to discount lease payments\n\n6. Implicit Rate:\n   - Rate built into lease by lessor\n   - If known, use instead of incremental borrowing rate\n\nSECTION 4: IFRS 16 Principles and Framework\n\nCore Principles:\n\nPrinciple 1: Right-of-Use Model\n- Lessee recognizes right to use asset\n- Lessee recognizes obligation to pay\n\nPrinciple 2: Single Lease Accounting Model\n- No distinction between finance and operating leases\n- All leases recognized on balance sheet\n\nPrinciple 3: Consistent Measurement\n- ROU asset measured at cost\n- Lease liability measured at PV of payments\n\nPrinciple 4: Transparent Disclosure\n- Comprehensive disclosures required\n- Information about lease obligations");
  app.save(record0);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
