/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_3963162141");
    record0.set("content_body", "**Section 1: Balance Sheet Analysis**\n\nBalance Sheet Structure:\n- Assets = Liabilities + Equity\n- Shows financial position at a point in time\n- Key for assessing financial strength and leverage\n\nAsset Analysis:\n\n1. Current Assets (Liquid within 1 year):\n   - Cash and cash equivalents: Most liquid, immediate payment capacity\n   - Accounts receivable: Collectible within 30-90 days\n   - Inventory: Convertible to cash through sales\n   - Prepaid expenses: Non-cash but reduce future cash needs\n   - Example: Strong current assets = good liquidity\n\n2. Fixed Assets (Long-term):\n   - Property, plant, equipment: Core operating assets\n   - Intangible assets: Patents, trademarks, goodwill\n   - Long-term investments: Strategic investments\n   - Example: Modern, well-maintained equipment = lower obsolescence risk\n\n3. Asset Quality Assessment:\n   - Age and condition of assets\n   - Depreciation and accumulated depreciation\n   - Obsolescence risk\n   - Liquidity of assets\n   - Example: Newer equipment = lower replacement risk");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "pbc_3963162141");
    record1.set("content_body", "Liability Analysis:\n\n1. Current Liabilities (Due within 1 year):\n   - Accounts payable: Trade payables to suppliers\n   - Short-term debt: Current portion of long-term debt\n   - Accrued expenses: Wages, taxes, interest payable\n   - Example: High current liabilities = near-term cash needs\n\n2. Long-term Liabilities:\n   - Long-term debt: Bonds, mortgages, long-term loans\n   - Deferred taxes: Future tax obligations\n   - Other long-term obligations: Pensions, leases\n   - Example: High long-term debt = high leverage\n\n3. Liability Quality Assessment:\n   - Debt maturity schedule: When debt is due\n   - Interest rates: Cost of debt\n   - Covenants: Restrictions on borrowing\n   - Example: Debt concentrated in near-term = refinancing risk\n\nEquity Analysis:\n\n1. Equity Components:\n   - Common stock: Ownership stake\n   - Retained earnings: Accumulated profits\n   - Additional paid-in capital: Premium on stock sales\n   - Example: Strong retained earnings = profitable history\n\n2. Equity Quality Assessment:\n   - Equity growth over time\n   - Dividend policy\n   - Share dilution\n   - Example: Growing equity = building financial strength");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "pbc_3963162141");
    record2.set("content_body", "**Section 2: Income Statement Analysis**\n\nIncome Statement Structure:\n- Revenue - Expenses = Net Income\n- Shows profitability over a period\n- Key for assessing earnings quality and sustainability\n\nRevenue Analysis:\n\n1. Revenue Trends:\n   - Year-over-year growth rate\n   - Growth sustainability\n   - Revenue concentration (customer, product, geography)\n   - Example: Consistent 10% annual growth = stable revenue\n\n2. Revenue Quality:\n   - Recurring vs. one-time revenue\n   - Customer concentration\n   - Contract terms and duration\n   - Example: Long-term contracts = stable revenue\n\n3. Revenue Drivers:\n   - Volume growth vs. price increases\n   - New products/services\n   - Market share gains\n   - Example: Volume growth = sustainable growth");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "pbc_3963162141");
    record3.set("content_body", "Expense Analysis:\n\n1. Cost of Goods Sold (COGS):\n   - Direct costs of producing goods/services\n   - COGS as % of revenue (gross margin)\n   - Trends in COGS\n   - Example: Stable COGS % = pricing power\n\n2. Operating Expenses:\n   - Selling, general, administrative (SG&A)\n   - Research and development (R&D)\n   - Depreciation and amortization\n   - Example: Declining SG&A % = improving efficiency\n\n3. Interest Expense:\n   - Cost of debt financing\n   - Interest coverage ratio\n   - Debt service burden\n   - Example: High interest expense = high leverage\n\nProfitability Analysis:\n\n1. Gross Profit:\n   - Revenue - COGS\n   - Gross margin = Gross profit / Revenue\n   - Indicates pricing power and cost control\n   - Example: 40% gross margin = strong pricing power\n\n2. Operating Income (EBIT):\n   - Gross profit - Operating expenses\n   - Operating margin = EBIT / Revenue\n   - Indicates operational efficiency\n   - Example: 15% operating margin = efficient operations\n\n3. Net Income:\n   - Operating income - Interest - Taxes\n   - Net margin = Net income / Revenue\n   - Bottom-line profitability\n   - Example: 10% net margin = profitable operations");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "pbc_3963162141");
    record4.set("content_body", "**Section 3: Cash Flow Statement Analysis**\n\nCash Flow Statement Structure:\n- Operating cash flow + Investing cash flow + Financing cash flow = Net change in cash\n- Shows actual cash generation and usage\n- Key for assessing cash generation ability\n\nOperating Cash Flow (OCF):\n\n1. Definition:\n   - Cash generated from core business operations\n   - Most important cash flow for credit analysis\n   - Indicates ability to pay obligations from operations\n\n2. Calculation:\n   - Net income + Depreciation/Amortization - Changes in working capital\n   - Or: Cash collected from customers - Cash paid for expenses\n\n3. Analysis:\n   - OCF > Net income = high quality earnings\n   - OCF < Net income = earnings quality concerns\n   - OCF trends = sustainability of cash generation\n   - Example: Growing OCF = improving cash generation");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "pbc_3963162141");
    record5.set("content_body", "Investing Cash Flow (ICF):\n\n1. Definition:\n   - Cash used for capital expenditures and investments\n   - Indicates growth investments and asset replacement\n\n2. Components:\n   - Capital expenditures (CapEx): Equipment, facilities\n   - Acquisitions: Business purchases\n   - Investments: Strategic investments\n   - Example: High CapEx = growth investments\n\n3. Analysis:\n   - CapEx as % of revenue: Capital intensity\n   - CapEx vs. depreciation: Asset replacement needs\n   - Example: CapEx > Depreciation = growing asset base\n\nFinancing Cash Flow (FCF):\n\n1. Definition:\n   - Cash from debt and equity financing\n   - Indicates financing activities and shareholder returns\n\n2. Components:\n   - Debt issuance/repayment: Borrowing and debt paydown\n   - Equity issuance: Stock sales\n   - Dividends: Shareholder distributions\n   - Example: Debt repayment = deleveraging\n\n3. Analysis:\n   - Debt trends: Increasing or decreasing leverage\n   - Dividend policy: Shareholder returns\n   - Example: Declining debt = improving financial position");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "pbc_3963162141");
    record6.set("content_body", "Free Cash Flow (FCF):\n\n1. Definition:\n   - Operating cash flow - Capital expenditures\n   - Cash available for debt service and dividends\n\n2. Calculation:\n   - FCF = OCF - CapEx\n\n3. Analysis:\n   - FCF > 0 = cash available for obligations\n   - FCF < 0 = cash deficit, requires financing\n   - FCF trends = sustainability of cash generation\n   - Example: Growing FCF = improving financial position\n\n**Section 4: Case Study - Financial Statement Analysis**\n\nCompany: ManufacturingCorp Inc.\nSituation: Analyzing financial statements for $500K lease\n\nBalance Sheet Analysis (Year 2):\n- Current assets: $15M (cash $3M, receivables $8M, inventory $4M)\n- Fixed assets: $30M (net of depreciation)\n- Total assets: $45M\n- Current liabilities: $8M (payables $5M, short-term debt $3M)\n- Long-term debt: $12M\n- Equity: $25M\n- Assessment: Solid balance sheet, moderate leverage (debt-to-equity 0.6x)");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "pbc_3963162141");
    record7.set("content_body", "Income Statement Analysis (Year 2):\n- Revenue: $50M\n- COGS: $30M (60% of revenue)\n- Gross profit: $20M (40% margin)\n- Operating expenses: $12M\n- EBIT: $8M (16% margin)\n- Interest expense: $1M\n- Net income: $5.6M (11.2% margin)\n- Assessment: Strong profitability, improving margins\n\nCash Flow Analysis (Year 2):\n- Operating cash flow: $7M\n- Capital expenditures: $2M\n- Free cash flow: $5M\n- Debt repayment: $1M\n- Assessment: Strong cash generation, improving financial position\n\nOverall Assessment:\n- Financial strength: Strong\n- Profitability: Strong and improving\n- Cash generation: Strong\n- Leverage: Moderate\n- Lease decision: Approve with standard terms");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "pbc_3963162141");
    record8.set("content_body", "**Section 1: Liquidity Ratios**\n\nCurrent Ratio:\n- Formula: Current assets / Current liabilities\n- Measures ability to pay short-term obligations\n- Interpretation: > 1.5 = good, 1.0-1.5 = adequate, < 1.0 = poor\n- Example: $15M current assets / $8M current liabilities = 1.88x (good)\n\nQuick Ratio (Acid Test):\n- Formula: (Current assets - Inventory) / Current liabilities\n- More conservative than current ratio (excludes inventory)\n- Interpretation: > 1.0 = good, 0.8-1.0 = adequate, < 0.8 = poor\n- Example: ($15M - $4M) / $8M = 1.38x (good)\n\nCash Ratio:\n- Formula: Cash / Current liabilities\n- Most conservative liquidity measure\n- Interpretation: > 0.5 = good, 0.2-0.5 = adequate, < 0.2 = poor\n- Example: $3M / $8M = 0.38x (adequate)\n\nWorking Capital:\n- Formula: Current assets - Current liabilities\n- Absolute measure of liquidity\n- Interpretation: > 0 = positive, indicates cushion\n- Example: $15M - $8M = $7M (positive, good)");
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("lesson_id", "pbc_3963162141");
    record9.set("content_body", "**Section 2: Profitability Ratios**\n\nGross Profit Margin:\n- Formula: Gross profit / Revenue\n- Measures pricing power and cost control\n- Interpretation: Higher is better, compare to industry\n- Example: $20M / $50M = 40% (strong)\n\nOperating Margin (EBIT Margin):\n- Formula: EBIT / Revenue\n- Measures operational efficiency\n- Interpretation: Higher is better, compare to industry\n- Example: $8M / $50M = 16% (strong)\n\nNet Profit Margin:\n- Formula: Net income / Revenue\n- Measures bottom-line profitability\n- Interpretation: Higher is better, compare to industry\n- Example: $5.6M / $50M = 11.2% (strong)\n\nReturn on Assets (ROA):\n- Formula: Net income / Total assets\n- Measures asset efficiency\n- Interpretation: Higher is better, typically 5-15%\n- Example: $5.6M / $45M = 12.4% (strong)\n\nReturn on Equity (ROE):\n- Formula: Net income / Equity\n- Measures return to shareholders\n- Interpretation: Higher is better, typically 10-20%\n- Example: $5.6M / $25M = 22.4% (strong)");
  app.save(record9);

  const record10 = new Record(collection);
    record10.set("lesson_id", "pbc_3963162141");
    record10.set("content_body", "**Section 3: Leverage Ratios**\n\nDebt-to-Equity Ratio:\n- Formula: Total debt / Equity\n- Measures financial leverage\n- Interpretation: < 1.0 = low leverage, 1.0-2.0 = moderate, > 2.0 = high\n- Example: $15M / $25M = 0.6x (low leverage, good)\n\nDebt-to-Assets Ratio:\n- Formula: Total debt / Total assets\n- Measures proportion of assets financed by debt\n- Interpretation: < 0.5 = low leverage, 0.5-0.7 = moderate, > 0.7 = high\n- Example: $15M / $45M = 0.33 (low leverage, good)\n\nEquity Multiplier:\n- Formula: Total assets / Equity\n- Measures financial leverage\n- Interpretation: < 2.0 = low leverage, 2.0-3.0 = moderate, > 3.0 = high\n- Example: $45M / $25M = 1.8x (low leverage, good)\n\nInterest Coverage Ratio:\n- Formula: EBIT / Interest expense\n- Measures ability to pay interest\n- Interpretation: > 3.0 = strong, 2.0-3.0 = adequate, < 2.0 = weak\n- Example: $8M / $1M = 8.0x (strong)\n\nDebt Service Coverage Ratio (DSCR):\n- Formula: Net operating income / Total debt service\n- Measures ability to service all debt\n- Interpretation: > 1.5 = strong, 1.25-1.5 = adequate, < 1.25 = weak\n- Example: $8M / $4M = 2.0x (strong)");
  app.save(record10);

  const record11 = new Record(collection);
    record11.set("lesson_id", "pbc_3963162141");
    record11.set("content_body", "**Section 4: Efficiency Ratios**\n\nAsset Turnover:\n- Formula: Revenue / Total assets\n- Measures asset efficiency\n- Interpretation: Higher is better, compare to industry\n- Example: $50M / $45M = 1.11x\n\nInventory Turnover:\n- Formula: COGS / Inventory\n- Measures inventory management\n- Interpretation: Higher is better, compare to industry\n- Example: $30M / $4M = 7.5x (inventory turns 7.5 times per year)\n\nReceivables Turnover:\n- Formula: Revenue / Accounts receivable\n- Measures collection efficiency\n- Interpretation: Higher is better, compare to industry\n- Example: $50M / $8M = 6.25x (collects receivables 6.25 times per year)\n\nDays Sales Outstanding (DSO):\n- Formula: 365 / Receivables turnover\n- Measures average collection period\n- Interpretation: Lower is better, compare to industry\n- Example: 365 / 6.25 = 58 days (collects in ~2 months)");
  app.save(record11);

  const record12 = new Record(collection);
    record12.set("lesson_id", "pbc_3963162141");
    record12.set("content_body", "**Section 5: Case Study - Ratio Analysis and Benchmarking**\n\nCompany: TechCorp Inc.\nSituation: Evaluating creditworthiness using ratio analysis\n\nFinancial Data (Year 2):\n- Revenue: $100M\n- EBIT: $20M\n- Net income: $14M\n- Total assets: $80M\n- Current assets: $30M\n- Inventory: $10M\n- Accounts receivable: $15M\n- Current liabilities: $15M\n- Total debt: $20M\n- Equity: $60M\n- Interest expense: $1.5M\n- COGS: $60M\n\nRatio Calculations:\n\nLiquidity Ratios:\n- Current ratio: $30M / $15M = 2.0x (good)\n- Quick ratio: ($30M - $10M) / $15M = 1.33x (good)\n- Cash ratio: $5M / $15M = 0.33x (adequate)");
  app.save(record12);

  const record13 = new Record(collection);
    record13.set("lesson_id", "pbc_3963162141");
    record13.set("content_body", "Profitability Ratios:\n- Gross margin: ($100M - $60M) / $100M = 40% (strong)\n- Operating margin: $20M / $100M = 20% (strong)\n- Net margin: $14M / $100M = 14% (strong)\n- ROA: $14M / $80M = 17.5% (strong)\n- ROE: $14M / $60M = 23.3% (strong)\n\nLeverage Ratios:\n- Debt-to-equity: $20M / $60M = 0.33x (low leverage)\n- Debt-to-assets: $20M / $80M = 0.25 (low leverage)\n- Interest coverage: $20M / $1.5M = 13.3x (strong)\n- DSCR: $20M / $2M = 10.0x (very strong)\n\nEfficiency Ratios:\n- Asset turnover: $100M / $80M = 1.25x\n- Inventory turnover: $60M / $10M = 6.0x\n- Receivables turnover: $100M / $15M = 6.67x\n- DSO: 365 / 6.67 = 54.7 days\n\nBenchmarking (vs. Industry Average):\n- Current ratio: 2.0x vs. 1.5x industry = better\n- Net margin: 14% vs. 10% industry = better\n- Debt-to-equity: 0.33x vs. 0.8x industry = better\n- ROE: 23.3% vs. 15% industry = better\n\nOverall Assessment:\n- Liquidity: Strong\n- Profitability: Strong and above industry average\n- Leverage: Low and below industry average\n- Efficiency: Good\n- Credit rating: A (Prime)\n- Default risk: Very low\n- Lease decision: Approve with favorable terms");
  app.save(record13);

  const record14 = new Record(collection);
    record14.set("lesson_id", "pbc_3963162141");
    record14.set("content_body", "**Section 1: Industry-Specific Metrics and Benchmarks**\n\nManufacturing Industry:\n\nKey Metrics:\n- Gross margin: 25-40% (varies by product)\n- Operating margin: 8-15%\n- Asset turnover: 0.8-1.5x\n- Debt-to-equity: 0.5-1.5x\n- Current ratio: 1.2-1.8x\n\nIndustry Risks:\n- Cyclicality: Sensitive to economic cycles\n- Commodity prices: Raw material cost volatility\n- Capacity utilization: Fixed cost burden\n- Competition: Intense competition, price pressure\n- Technology: Rapid obsolescence of equipment\n\nCredit Considerations:\n- Equipment quality and age\n- Production capacity and utilization\n- Customer concentration\n- Supply chain stability\n- Environmental compliance");
  app.save(record14);

  const record15 = new Record(collection);
    record15.set("lesson_id", "pbc_3963162141");
    record15.set("content_body", "Technology/Software Industry:\n\nKey Metrics:\n- Gross margin: 60-80% (high margin)\n- Operating margin: 15-30%\n- Asset turnover: 1.5-3.0x (asset-light)\n- Debt-to-equity: 0.1-0.5x (low leverage)\n- Current ratio: 1.5-2.5x\n\nIndustry Risks:\n- Rapid obsolescence: Technology changes quickly\n- Competition: Intense competition from startups\n- Customer concentration: Reliance on few large customers\n- Talent retention: Key person risk\n- Regulatory: Data privacy and security regulations\n\nCredit Considerations:\n- R&D spending and innovation\n- Customer retention and churn\n- Recurring revenue model\n- Management team stability\n- Intellectual property protection\n\nHealthcare Industry:\n\nKey Metrics:\n- Gross margin: 40-60%\n- Operating margin: 10-20%\n- Asset turnover: 0.8-1.2x\n- Debt-to-equity: 0.3-1.0x\n- Current ratio: 1.2-1.8x");
  app.save(record15);

  const record16 = new Record(collection);
    record16.set("lesson_id", "pbc_3963162141");
    record16.set("content_body", "Industry Risks:\n- Regulatory: Healthcare regulations and compliance\n- Reimbursement: Insurance reimbursement rates\n- Litigation: Medical malpractice and liability\n- Technology: Rapid equipment obsolescence\n- Consolidation: Industry consolidation pressure\n\nCredit Considerations:\n- Regulatory compliance and licensing\n- Reimbursement rates and contracts\n- Malpractice insurance and claims\n- Equipment quality and maintenance\n- Patient volume and demographics\n\nRetail Industry:\n\nKey Metrics:\n- Gross margin: 20-40%\n- Operating margin: 2-8% (thin margins)\n- Asset turnover: 1.5-3.0x\n- Debt-to-equity: 0.5-2.0x\n- Current ratio: 1.0-1.5x\n\nIndustry Risks:\n- Cyclicality: Sensitive to consumer spending\n- Competition: Intense competition, e-commerce disruption\n- Inventory: Inventory obsolescence and markdowns\n- Real estate: Lease obligations and location risk\n- Consumer trends: Changing consumer preferences\n\nCredit Considerations:\n- Store locations and lease terms\n- Inventory management and turnover\n- Customer traffic and sales trends\n- E-commerce presence and digital strategy\n- Debt service from operations");
  app.save(record16);

  const record17 = new Record(collection);
    record17.set("lesson_id", "pbc_3963162141");
    record17.set("content_body", "**Section 2: Industry-Specific Risk Assessment**\n\nCyclical Industries (Manufacturing, Retail, Construction):\n\nCharacteristics:\n- Revenue and profitability fluctuate with economic cycles\n- Sensitive to interest rates and consumer spending\n- Asset-heavy with high fixed costs\n- Inventory and receivables management critical\n\nCredit Analysis Approach:\n- Analyze through-cycle performance (multiple cycles)\n- Stress test for recession scenarios\n- Assess cost structure and flexibility\n- Evaluate debt maturity and refinancing risk\n- Example: Require higher DSCR (1.5x+) for cyclical businesses\n\nCounter-Cyclical Industries (Discount retail, debt collection, funeral services):\n\nCharacteristics:\n- Revenue and profitability increase during downturns\n- Benefit from economic weakness\n- More stable and predictable cash flows\n- Lower default risk during recessions\n\nCredit Analysis Approach:\n- Analyze performance during downturns\n- Assess customer base and demand stability\n- Evaluate competitive position\n- Lower DSCR requirements acceptable\n- Example: Can accept lower DSCR (1.25x) for counter-cyclical businesses");
  app.save(record17);

  const record18 = new Record(collection);
    record18.set("lesson_id", "pbc_3963162141");
    record18.set("content_body", "Growth Industries (Technology, renewable energy, healthcare):\n\nCharacteristics:\n- Rapid revenue growth\n- High profitability potential\n- Significant capital requirements\n- High competition and disruption risk\n\nCredit Analysis Approach:\n- Focus on growth sustainability and market position\n- Assess competitive advantages and barriers to entry\n- Evaluate management team and execution capability\n- Stress test for slower growth scenarios\n- Example: Require strong management and market position\n\nMature/Declining Industries (Coal, print media, traditional retail):\n\nCharacteristics:\n- Slow or negative revenue growth\n- Stable but declining profitability\n- Asset-heavy with high fixed costs\n- Limited growth opportunities\n\nCredit Analysis Approach:\n- Focus on cash generation and cost management\n- Assess competitive position and market share\n- Evaluate ability to adapt and transform\n- Higher default risk\n- Example: Require higher DSCR and guarantees");
  app.save(record18);

  const record19 = new Record(collection);
    record19.set("lesson_id", "pbc_3963162141");
    record19.set("content_body", "**Section 3: Case Study - Industry-Specific Credit Analysis**\n\nCompany: HealthcareTech Inc.\nSituation: Evaluating creditworthiness in healthcare technology industry\n\nCompany Profile:\n- Healthcare IT software company\n- Revenue: $50M, growing 25% annually\n- Founded: 8 years ago\n- Customers: 500+ hospitals and clinics\n- Market position: #3 in market segment\n\nFinancial Analysis:\n- Gross margin: 75% (typical for software)\n- Operating margin: 18% (strong)\n- Net margin: 12%\n- Debt-to-equity: 0.2x (low leverage)\n- Current ratio: 2.0x (strong liquidity)\n- DSCR: 3.0x (very strong)\n\nIndustry-Specific Considerations:\n\n1. Recurring Revenue Model:\n   - 80% of revenue from recurring subscriptions\n   - Positive: Stable, predictable revenue\n   - Assessment: Reduces default risk");
  app.save(record19);

  const record20 = new Record(collection);
    record20.set("lesson_id", "pbc_3963162141");
    record20.set("content_body", "2. Customer Concentration:\n   - Top 10 customers = 30% of revenue\n   - Positive: Diversified customer base\n   - Assessment: Acceptable concentration\n\n3. Regulatory Compliance:\n   - HIPAA compliant\n   - FDA cleared for certain products\n   - Positive: Regulatory barriers to entry\n   - Assessment: Competitive advantage\n\n4. Technology and Innovation:\n   - R&D spending: 15% of revenue\n   - Recent product launches: 3 new products in past year\n   - Positive: Continuous innovation\n   - Assessment: Maintains competitive position\n\n5. Management Team:\n   - CEO: 20 years healthcare IT experience\n   - CFO: 15 years healthcare finance experience\n   - Positive: Experienced management\n   - Assessment: Strong execution capability\n\n6. Market Dynamics:\n   - Market growing 20% annually\n   - Consolidation among competitors\n   - Positive: Growing market, consolidation opportunity\n   - Assessment: Favorable market conditions\n\nCredit Decision:\n- Credit rating: A (Prime)\n- Default probability: < 1%\n- Lease decision: Approve\n- Lease terms: Favorable rates, minimal restrictions\n- Rationale: Strong financial position, favorable industry dynamics, experienced management, recurring revenue model");
  app.save(record20);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
