/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "LESSON_6_ID");
    record0.set("content_body", "# Value Creation and Win-Win Solutions\n\n## Understanding Value in Lease Sales\n\n**What is Value**: Benefit received by client - can be financial or non-financial. Example: Lower cost, better service, faster approval.\n\n**Types of Value**:\n- Financial: Lower lease rate, flexible payment terms, tax benefits\n- Non-Financial: Better service, faster approval, equipment quality\n- Perceived: What client thinks is valuable (may differ from actual)\n\n## Value Creation Strategies\n\n**Strategy 1: Expand the Pie** - Look for additional value, don't just split existing value. Add service package to lease.\n\n**Strategy 2: Identify Interests** - Understand what client really wants beyond stated positions. Client wants flexibility, not just low rate.\n\n**Strategy 3: Create Options** - Develop multiple solutions and offer choices. 3 different lease structures.\n\n**Strategy 4: Use Objective Criteria** - Base decisions on objective standards. Market rate is 4.5%.\n\n## Win-Win Negotiation\n\n**Definition**: Both parties benefit, not zero-sum game. Client gets good rate, lessor gets good deal.\n\n**Principles**:\n1. Separate people from problem - Focus on issue, not person\n2. Focus on interests, not positions - Understand underlying interests\n3. Generate options - Create multiple solutions\n4. Use objective criteria - Base decisions on standards\n\n## Creative Problem-Solving\n\n**Brainstorming**: Generate ideas without judgment, encourage wild ideas\n\n**Lateral Thinking**: Think outside the box, challenge assumptions\n\n**Analogies**: Use examples from other industries, apply to lease situation\n\n**Reframing**: Look at problem differently, change perspective\n\n## Case Study: Value Creation\n\n**Initial Positions**: Lessor wants 5% rate/5 years/monthly; Client wants 3.5% rate/3 years/quarterly\n\n**Value Creation**: Add service package, equipment upgrade option, flexible payment terms\n\n**Options Created**:\n- Option 1: 4.5%, 5 years, monthly, basic service\n- Option 2: 4.25%, 4 years, quarterly, premium service\n- Option 3: 4%, 3 years, flexible, premium + upgrade\n\n**Final Agreement**: 4.25% rate, 4-year term, quarterly payments, premium service, upgrade option. Both parties satisfied with value created.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "LESSON_7_ID");
    record1.set("content_body", "# Closing Techniques and Deal Finalization\n\n## Recognizing Buying Signals\n\n**Definition**: Signs that client is ready to buy, indicates willingness to move forward.\n\n**Verbal Signals**: \"This looks good\", \"When can we start?\", \"What's the next step?\"\n\n**Non-Verbal Signals**: Nodding head, leaning forward, smiling\n\n**Questions**: \"What are payment terms?\", \"How long does approval take?\", \"What documents needed?\"\n\n## Closing Techniques\n\n**Assumptive Close**: Assume they're buying, move forward as if agreed. Use when buying signals present and objections addressed.\n\n**Alternative Close**: Offer two options, both lead to agreement. \"Would you prefer quarterly or monthly payments?\"\n\n**Summary Close**: Summarize what was agreed, confirm understanding. \"So we've agreed to 4.25% for 4 years\"\n\n**Urgency Close**: Create sense of urgency, limited time offer. \"This rate available through Friday\"\n\n**Takeaway Close**: Suggest removing something, client realizes they want it. \"If cost is concern, we could remove service package\"\n\n## Deal Finalization Process\n\n**Step 1: Confirm Terms** - Review all agreed terms, confirm in writing\n\n**Step 2: Prepare Documents** - Prepare lease agreement, supporting documents\n\n**Step 3: Obtain Signatures** - Get all required signatures, ensure proper authorization\n\n**Step 4: Obtain Approvals** - Get internal and client approvals\n\n**Step 5: Finalize Details** - Confirm equipment details, delivery date, payment setup\n\n**Step 6: Document Everything** - Keep records of all agreements, document changes\n\n## Case Study: Closing Techniques\n\n**Negotiation Summary**: 4.25% rate, 4-year term, quarterly payments, premium service\n\n**Buying Signals Recognized**: Client says \"This looks good\", \"When can we start?\", asks about payment terms and approval timeline\n\n**Closing Applied**: Assumptive close - \"Let's get paperwork started\"; Summary close - Confirm all terms\n\n**Deal Finalization**: Confirm terms, prepare documents, obtain signatures (CFO, Operations Manager), obtain approvals (credit, legal), finalize details (equipment, delivery, payment), document everything\n\n**Outcome**: Lease agreement signed, equipment approved, payment process set up, client satisfied, successful deal closure");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "LESSON_8_ID");
    record2.set("content_body", "# Post-Negotiation and Relationship Management\n\n## Post-Negotiation Follow-Up\n\n**Immediate (Within 24 Hours)**:\n- Send confirmation email with all agreed terms\n- Send lease agreement and documents\n- Assign account manager and provide contact info\n- Set timeline for approval and delivery\n\n**Short-Term (1-2 Weeks)**:\n- Check on approvals progress\n- Answer any questions\n- Prepare for equipment delivery\n- Prepare payment setup and instructions\n\n## Relationship Management Principles\n\n**Deliver on Promises**: Do what you said, meet deadlines. Deliver equipment on time.\n\n**Communicate Regularly**: Keep client informed, provide updates. Monthly check-in calls.\n\n**Provide Excellent Service**: Go above and beyond, solve problems quickly. 24/7 support.\n\n**Show Appreciation**: Thank client for business, recognize milestones. Anniversary gift.\n\n**Seek Feedback**: Ask for feedback, make improvements. Annual satisfaction survey.\n\n## Upselling and Cross-Selling\n\n**Upselling**: Sell higher-value version, upgrade existing lease. Upgrade to premium service.\n\n**Cross-Selling**: Sell additional products, complement existing lease. Sell maintenance package.\n\n## Case Study: Relationship Management\n\n**Post-Negotiation**: Confirmation email, documents sent, account manager assigned, timeline set\n\n**Relationship Building**: Deliver on promises, communicate regularly, provide excellent service, show appreciation, seek feedback\n\n**Long-Term Growth**:\n- Year 2: Client needs additional equipment, offer lease and premium service upgrade\n- Year 3: Client needs maintenance, offer maintenance and insurance packages\n- Year 5: Original lease ending, offer renewal and equipment upgrade\n\n**Outcome**: Strong client relationship, multiple leases, high satisfaction, repeat business, referrals, successful long-term partnership");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
