/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_3963162141");
    record0.set("content_body", "**Section 1: Credit Risk Fundamentals**\n\nDefinition of Credit Risk:\n- The risk that a borrower (lessee) will fail to meet their financial obligations\n- Includes failure to pay principal, interest, or lease payments\n- Can result in partial or total loss of investment\n- Primary concern for lessors in lease transactions\n\nTypes of Credit Risk:\n\n1. Default Risk:\n   - Risk that lessee fails to pay lease payments\n   - Most direct and measurable credit risk\n   - Can result in repossession and loss of residual value\n   - Example: Lessee misses 3 consecutive monthly payments\n\n2. Counterparty Risk:\n   - Risk that lessee's financial condition deteriorates\n   - May not result in immediate default but increases risk\n   - Requires monitoring and potential intervention\n   - Example: Lessee's revenue declines 30%, cash flow tightens\n\n3. Concentration Risk:\n   - Risk from over-exposure to single lessee, industry, or geography\n   - Diversification reduces concentration risk\n   - Portfolio-level risk management concern\n   - Example: 20% of portfolio with single customer\n\n4. Residual Value Risk:\n   - Risk that asset value at lease end is lower than estimated\n   - Affects lessor's recovery if lessee defaults\n   - Related to obsolescence and market conditions\n   - Example: Equipment worth $50K instead of estimated $100K\n\n5. Covenant Risk:\n   - Risk that lessee violates lease covenants\n   - Covenants are contractual obligations (e.g., maintain insurance)\n   - Breach may trigger default\n   - Example: Lessee fails to maintain required insurance");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "pbc_3963162141");
    record1.set("content_body", "**Section 2: Creditworthiness Assessment**\n\nWhat is Creditworthiness?\n- Ability and willingness of lessee to meet financial obligations\n- Combination of financial capacity and character/integrity\n- Assessed through multiple factors and metrics\n- Determines credit decision and lease terms\n\nThe Five C's of Credit:\n\n1. Character (Integrity and Willingness to Pay):\n   - Lessee's payment history and track record\n   - Management quality and reputation\n   - Industry experience and expertise\n   - Indicators: Payment history, references, management background\n   - Example: Company with 10-year history of on-time payments\n\n2. Capacity (Ability to Pay):\n   - Lessee's financial ability to meet obligations\n   - Cash flow generation and liquidity\n   - Debt service coverage ratio\n   - Indicators: Revenue, EBITDA, cash flow, debt levels\n   - Example: Company with strong cash flow and low debt\n\n3. Capital (Financial Strength):\n   - Lessee's equity and net worth\n   - Balance sheet strength and asset base\n   - Debt-to-equity ratio and leverage\n   - Indicators: Equity, net worth, asset base, leverage ratios\n   - Example: Company with strong balance sheet and low leverage\n\n4. Collateral (Security):\n   - Assets available to secure the lease\n   - Residual value of leased equipment\n   - Other assets available as security\n   - Indicators: Equipment value, other assets, liens\n   - Example: Equipment with strong residual value and secondary market\n\n5. Conditions (External Factors):\n   - Industry conditions and trends\n   - Economic conditions and outlook\n   - Regulatory environment\n   - Competitive landscape\n   - Indicators: Industry growth, economic outlook, regulations\n   - Example: Growing industry with favorable economic outlook");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "pbc_3963162141");
    record2.set("content_body", "**Section 3: Credit Risk Factors**\n\nQuantitative Risk Factors:\n\n1. Financial Metrics:\n   - Debt-to-equity ratio (leverage)\n   - Current ratio (liquidity)\n   - Debt service coverage ratio (ability to pay)\n   - Return on assets (profitability)\n   - Example: Debt-to-equity > 2.0 indicates higher risk\n\n2. Trend Analysis:\n   - Revenue growth or decline\n   - Profitability trends\n   - Cash flow trends\n   - Debt trends\n   - Example: Declining revenue for 3 consecutive years = higher risk\n\n3. Liquidity Position:\n   - Cash and cash equivalents\n   - Working capital\n   - Current assets vs. current liabilities\n   - Example: Low cash position and negative working capital = higher risk\n\n4. Debt Levels:\n   - Total debt outstanding\n   - Debt maturity schedule\n   - Debt service requirements\n   - Example: High debt with near-term maturities = higher risk\n\nQualitative Risk Factors:\n\n1. Management Quality:\n   - Experience and track record\n   - Industry expertise\n   - Decision-making quality\n   - Succession planning\n   - Example: Experienced management team = lower risk\n\n2. Business Model:\n   - Revenue stability and predictability\n   - Customer concentration\n   - Competitive position\n   - Market share\n   - Example: Diversified customer base = lower risk\n\n3. Industry Dynamics:\n   - Industry growth and maturity\n   - Competitive intensity\n   - Regulatory environment\n   - Technology disruption risk\n   - Example: Growing industry with low competition = lower risk\n\n4. Economic Sensitivity:\n   - Cyclicality of business\n   - Economic sensitivity\n   - Recession resilience\n   - Example: Counter-cyclical business = lower risk");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "pbc_3963162141");
    record3.set("content_body", "**Section 4: Credit Rating and Classification**\n\nCredit Rating Scale:\n\nInvestment Grade (Lower Risk):\n- AAA/Aaa: Highest credit quality, minimal risk\n- AA/Aa: High credit quality, very low risk\n- A/A: Upper-medium credit quality, low risk\n- BBB/Baa: Medium credit quality, moderate risk\n\nSpeculative Grade (Higher Risk):\n- BB/Ba: Lower-medium credit quality, elevated risk\n- B/B: Speculative, significant risk\n- CCC/Caa: Highly speculative, high risk\n- CC/Ca: Very high risk, near default\n- C/C: Imminent default risk\n- D: In default\n\nCredit Classification for Leasing:\n\n1. Prime (A+ to A):\n   - Excellent creditworthiness\n   - Strong financial position\n   - Minimal default risk\n   - Lease terms: Standard rates, minimal restrictions\n   - Example: Fortune 500 company\n\n2. Good (A- to BBB+):\n   - Good creditworthiness\n   - Solid financial position\n   - Low default risk\n   - Lease terms: Standard rates, standard restrictions\n   - Example: Mid-size established company\n\n3. Fair (BBB to BBB-):\n   - Acceptable creditworthiness\n   - Adequate financial position\n   - Moderate default risk\n   - Lease terms: Slightly higher rates, additional restrictions\n   - Example: Smaller company with adequate financials\n\n4. Subprime (BB+ to BB):\n   - Below-average creditworthiness\n   - Weak financial position\n   - Elevated default risk\n   - Lease terms: Higher rates, significant restrictions, guarantees\n   - Example: Startup or company with weak financials\n\n5. High Risk (BB- and below):\n   - Poor creditworthiness\n   - Very weak financial position\n   - High default risk\n   - Lease terms: Very high rates, extensive restrictions, guarantees, collateral\n   - Example: Company near default or in distress");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "pbc_3963162141");
    record4.set("content_body", "**Section 5: Case Study - Creditworthiness Assessment**\n\nCompany: ManufacturingCorp Inc.\nSituation: Applying for $500K equipment lease\n\nAssessment Using Five C's:\n\n1. Character:\n   - Payment history: 10 years, no late payments\n   - Management: Founder/CEO with 20 years industry experience\n   - References: Excellent references from suppliers and customers\n   - Assessment: Strong character, high willingness to pay\n\n2. Capacity:\n   - Revenue: $50M annually, growing 10% per year\n   - EBITDA: $8M (16% margin)\n   - Cash flow: $6M annually\n   - Debt service coverage: 2.5x (strong)\n   - Assessment: Strong capacity to pay\n\n3. Capital:\n   - Equity: $15M\n   - Total assets: $40M\n   - Debt-to-equity: 1.0 (moderate)\n   - Net worth: $15M\n   - Assessment: Solid capital position\n\n4. Collateral:\n   - Equipment residual value: $150K (30% of lease cost)\n   - Other assets: $40M in total assets\n   - Assessment: Adequate collateral\n\n5. Conditions:\n   - Industry: Manufacturing (stable, mature)\n   - Economic outlook: Favorable\n   - Competitive position: Strong market share\n   - Assessment: Favorable external conditions\n\nOverall Assessment:\n- Credit rating: A (Prime)\n- Default risk: Low\n- Lease decision: Approve\n- Lease terms: Standard rates, minimal restrictions");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "pbc_3963162141");
    record5.set("content_body", "**Section 1: Credit Analysis Frameworks**\n\nFramework 1: The Five C's Framework (Covered in Lesson 1.1)\n- Character, Capacity, Capital, Collateral, Conditions\n- Comprehensive assessment of creditworthiness\n- Combines quantitative and qualitative factors\n- Best for: Overall creditworthiness assessment\n\nFramework 2: The CAMEL Framework (Bank Regulatory Framework)\n\nC - Capital Adequacy:\n- Lessee's equity and net worth\n- Ability to absorb losses\n- Debt-to-equity ratio\n- Example: Equity > 30% of assets = adequate capital\n\nA - Asset Quality:\n- Quality of lessee's assets\n- Liquidity of assets\n- Asset composition\n- Example: Liquid assets > 20% of current liabilities = good quality\n\nM - Management Quality:\n- Experience and competence\n- Decision-making quality\n- Strategic planning\n- Example: Experienced management team = strong management\n\nE - Earnings Quality:\n- Profitability and sustainability\n- Earnings stability\n- Return on assets\n- Example: Consistent profitability = strong earnings\n\nL - Liquidity Position:\n- Cash and liquid assets\n- Working capital\n- Ability to meet short-term obligations\n- Example: Current ratio > 1.5 = adequate liquidity");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "pbc_3963162141");
    record6.set("content_body", "Framework 3: The DuPont Analysis Framework\n\nBreaks down Return on Equity (ROE) into components:\n- ROE = Net Profit Margin \u00d7 Asset Turnover \u00d7 Equity Multiplier\n- Identifies sources of profitability and leverage\n- Useful for understanding financial performance drivers\n- Example: High ROE from high leverage = higher risk\n\nFramework 4: The Altman Z-Score Framework\n\nPredicts bankruptcy risk using five financial ratios:\n- Z = 1.2X1 + 1.4X2 + 3.3X3 + 0.6X4 + 1.0X5\n- X1 = Working Capital / Total Assets\n- X2 = Retained Earnings / Total Assets\n- X3 = EBIT / Total Assets\n- X4 = Market Value of Equity / Book Value of Liabilities\n- X5 = Sales / Total Assets\n\nZ-Score Interpretation:\n- Z > 2.99: Safe zone (low bankruptcy risk)\n- 1.81 < Z < 2.99: Gray zone (moderate risk)\n- Z < 1.81: Distress zone (high bankruptcy risk)\n\nExample: Company with Z-score of 3.2 = low bankruptcy risk\n\nFramework 5: The Debt Service Coverage Ratio (DSCR) Framework\n\nDSCR = Net Operating Income / Total Debt Service\n- Measures ability to service debt from operations\n- Key metric for lease payment capacity\n- Typical minimum: 1.25x (can service debt 1.25x over)\n- Example: DSCR of 2.0x = strong ability to pay");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "pbc_3963162141");
    record7.set("content_body", "**Section 2: Credit Analysis Methodologies**\n\nMethodology 1: Ratio Analysis\n\nKey Ratios:\n1. Liquidity Ratios:\n   - Current ratio = Current assets / Current liabilities\n   - Quick ratio = (Current assets - Inventory) / Current liabilities\n   - Cash ratio = Cash / Current liabilities\n\n2. Profitability Ratios:\n   - Gross profit margin = Gross profit / Revenue\n   - Operating margin = Operating income / Revenue\n   - Net profit margin = Net income / Revenue\n   - Return on assets (ROA) = Net income / Total assets\n   - Return on equity (ROE) = Net income / Equity\n\n3. Leverage Ratios:\n   - Debt-to-equity = Total debt / Equity\n   - Debt-to-assets = Total debt / Total assets\n   - Equity multiplier = Total assets / Equity\n   - Interest coverage = EBIT / Interest expense\n\n4. Efficiency Ratios:\n   - Asset turnover = Revenue / Total assets\n   - Inventory turnover = Cost of goods sold / Inventory\n   - Receivables turnover = Revenue / Accounts receivable");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "pbc_3963162141");
    record8.set("content_body", "Methodology 2: Trend Analysis\n\nSteps:\n1. Collect historical financial data (3-5 years)\n2. Calculate key metrics for each period\n3. Analyze trends (improving, declining, stable)\n4. Project future performance\n5. Assess sustainability of trends\n\nExample:\n- Year 1: Revenue $40M, EBITDA $6M (15% margin)\n- Year 2: Revenue $45M, EBITDA $7M (15.6% margin)\n- Year 3: Revenue $50M, EBITDA $8M (16% margin)\n- Trend: Improving revenue and profitability = positive\n\nMethodology 3: Peer Comparison Analysis\n\nSteps:\n1. Identify peer companies (similar size, industry, business model)\n2. Calculate key metrics for peers\n3. Compare lessee metrics to peer averages\n4. Assess relative position (above/below average)\n5. Identify outliers and investigate\n\nExample:\n- Lessee debt-to-equity: 1.5x\n- Industry average: 1.2x\n- Lessee is above average = higher leverage than peers\n\nMethodology 4: Scenario Analysis\n\nSteps:\n1. Develop base case scenario (most likely)\n2. Develop upside scenario (best case)\n3. Develop downside scenario (worst case)\n4. Calculate key metrics for each scenario\n5. Assess risk under different scenarios\n\nExample:\n- Base case: Revenue grows 10%, DSCR = 2.0x\n- Upside case: Revenue grows 15%, DSCR = 2.5x\n- Downside case: Revenue declines 10%, DSCR = 1.2x\n- Risk assessment: Even in downside, DSCR > 1.0x = acceptable");
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("lesson_id", "pbc_3963162141");
    record9.set("content_body", "Methodology 5: Stress Testing\n\nSteps:\n1. Identify key risk factors (revenue decline, cost increase, etc.)\n2. Apply stress scenarios (e.g., 20% revenue decline)\n3. Calculate impact on key metrics\n4. Assess ability to meet obligations under stress\n5. Determine stress tolerance\n\nExample:\n- Stress: 20% revenue decline\n- Impact: DSCR declines from 2.0x to 1.4x\n- Assessment: Still above minimum 1.25x = acceptable stress tolerance\n\n**Section 3: Credit Analysis Process**\n\nStep 1: Information Gathering\n- Request financial statements (3-5 years)\n- Request tax returns\n- Request business plan and projections\n- Conduct industry research\n- Verify references\n- Timeline: 1-2 weeks\n\nStep 2: Financial Statement Analysis\n- Analyze balance sheet (assets, liabilities, equity)\n- Analyze income statement (revenue, expenses, profitability)\n- Analyze cash flow statement (operating, investing, financing)\n- Calculate key ratios and metrics\n- Timeline: 1 week");
  app.save(record9);

  const record10 = new Record(collection);
    record10.set("lesson_id", "pbc_3963162141");
    record10.set("content_body", "Step 3: Qualitative Assessment\n- Assess management quality and experience\n- Evaluate business model and competitive position\n- Analyze industry dynamics and trends\n- Assess economic sensitivity\n- Timeline: 1 week\n\nStep 4: Credit Rating and Decision\n- Assign credit rating (Prime, Good, Fair, Subprime, High Risk)\n- Determine default probability\n- Recommend lease decision (Approve, Conditional, Decline)\n- Recommend lease terms (rates, restrictions, guarantees)\n- Timeline: 1 week\n\nStep 5: Documentation and Approval\n- Document analysis and findings\n- Obtain management approval\n- Communicate decision to sales team\n- Establish monitoring plan\n- Timeline: 1 week\n\n**Section 4: Case Study - Credit Analysis Framework Application**\n\nCompany: TechStartup Inc.\nSituation: Applying for $1M equipment lease\n\nStep 1: Information Gathering\n- Financial statements: 2 years available (startup)\n- Tax returns: 2 years\n- Business plan: Provided\n- Industry research: High-growth tech sector\n- References: Positive from suppliers");
  app.save(record10);

  const record11 = new Record(collection);
    record11.set("lesson_id", "pbc_3963162141");
    record11.set("content_body", "Step 2: Financial Statement Analysis\n- Year 1: Revenue $5M, EBITDA $1M (20% margin), Equity $2M\n- Year 2: Revenue $8M, EBITDA $1.8M (22.5% margin), Equity $3M\n- Debt-to-equity: 0.5x (low leverage)\n- Current ratio: 1.8x (adequate liquidity)\n- DSCR: 2.2x (strong debt service capacity)\n\nStep 3: Qualitative Assessment\n- Management: Experienced founders with 15 years tech industry experience\n- Business model: SaaS with recurring revenue (stable)\n- Competitive position: Growing market share, strong product\n- Industry: High-growth tech sector (favorable)\n- Economic sensitivity: Low (counter-cyclical)\n\nStep 4: Credit Rating and Decision\n- Five C's assessment: Strong across all dimensions\n- CAMEL assessment: Strong capital, assets, management, earnings, liquidity\n- Altman Z-score: 3.5 (safe zone)\n- Credit rating: A (Prime)\n- Default probability: Low (< 1%)\n- Lease decision: Approve\n- Lease terms: Standard rates, minimal restrictions\n\nStep 5: Documentation and Approval\n- Analysis documented in credit memo\n- Approved by credit committee\n- Sales team notified of approval\n- Monitoring plan: Annual financial review, quarterly calls\n- Result: Lease approved and executed");
  app.save(record11);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
