/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "LESSON_1_ID");
    record0.set("content_body", "# Strategic Lease Planning Framework\n\n## Section 1: Strategic Planning Fundamentals\nStrategic planning is the process of defining an organization's direction and making decisions on allocating resources to pursue this strategy.\n\nKey Objectives:\n- Align lease decisions with overall business strategy\n- Optimize capital allocation\n- Manage financial risk\n- Enhance operational flexibility\n- Support long-term growth\n\n## Section 2: Lease Planning Process\nThe 5-phase process includes: (1) Assessment Phase - evaluate current equipment needs, (2) Analysis Phase - conduct financial and strategic analysis, (3) Planning Phase - develop lease strategy, (4) Negotiation Phase - engage with lessors, (5) Implementation Phase - execute lease agreement.\n\nExample: A company planning to acquire $10M in manufacturing equipment follows this process over 6 months, resulting in a 3-year lease agreement with 2 renewal options, saving 15% compared to purchasing.\n\n## Section 3: Strategic Objectives\nFive key objectives guide lease planning:\n1. Cost Optimization - minimize total cost of ownership\n2. Flexibility - maintain ability to upgrade or change equipment\n3. Risk Management - transfer obsolescence and maintenance risk\n4. Cash Flow Management - preserve capital for core operations\n5. Competitive Advantage - enable faster technology adoption\n\n## Section 4: Stakeholder Analysis\nFive stakeholder types must be aligned: Finance (cost and cash flow), Operations (availability and performance), IT (technology currency), Executive Management (strategic alignment), and Legal/Compliance (contract terms).\n\nExample: A $50M equipment lease requires alignment across all stakeholders with different priorities and concerns.\n\n## Section 5: Strategic Decision Framework\nFive decision types guide the process: (1) Equipment Type Decision, (2) Lease vs Buy Decision, (3) Lessor Selection Decision, (4) Term Decision, (5) Renewal Decision.\n\n## Section 6: Case Study - StrategicLeasing Corp\nStrategicLeasing Corp manages a $100M equipment portfolio across 5 facilities. By shifting to 70% leased equipment, the company reduced capital expenditure by $20M annually, improved equipment currency, and enhanced operational flexibility while maintaining cost competitiveness.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "LESSON_2_ID");
    record1.set("content_body", "# Financial Analysis and Lease Evaluation\n\n## Section 1: Lease Evaluation Fundamentals\nLease evaluation is the systematic analysis of lease options to determine if leasing is financially and strategically optimal. Key metrics include NPV, IRR, Payback Period, ROI, and Total Cost of Ownership.\n\nAnalysis Framework: (1) Identify all lease and buy options, (2) Estimate all costs and benefits, (3) Determine appropriate discount rate, (4) Calculate financial metrics, (5) Perform sensitivity analysis, (6) Make recommendation.\n\n## Section 2: NPV Analysis\nNet Present Value is the sum of all discounted cash flows. Formula: NPV = \u03a3(Cash Flow_t / (1 + r)^t) - Initial Investment.\n\nDecision Rule: NPV > 0 means lease is financially attractive; NPV < 0 means buy is better.\n\nExample: $10M Equipment with -$500,000 NPV - Lease option has $200K monthly payments for 60 months. Buy option costs $10M upfront plus $50K annual maintenance. At 10% discount rate, lease NPV is -$500,000 (better than buy's -$8.2M).\n\n## Section 3: IRR Analysis\nInternal Rate of Return is the discount rate that makes NPV equal to zero. Decision Rule: If IRR of lease savings exceeds cost of capital, lease is attractive.\n\nExample: A lease option generates a 6% IRR, which is below the company's 10% cost of capital, suggesting the lease is not financially optimal.\n\n## Section 4: Cash Flow Analysis\nFive components: (1) Lease Payments - regular monthly or annual payments, (2) Maintenance Costs - repairs and servicing (often included), (3) Insurance Costs - equipment insurance (often included), (4) Tax Benefits - deductibility of lease payments, (5) Residual Value - equipment value at end.\n\nExample: $100,000 annual payment with $2,500 annual tax savings (30% rate) results in net annual cost of $5,833.\n\n## Section 5: Sensitivity Analysis\nAnalyze impact of five variables: (1) Discount Rate \u00b12%, (2) Lease Payment \u00b15%, (3) Maintenance Costs \u00b110%, (4) Residual Value \u00b120%, (5) Tax Rate \u00b15%.\n\nExample: Base case NPV of -$500,000 ranges from -$200,000 (best case) to -$800,000 (worst case), showing lease remains better than buy across all scenarios.\n\n## Section 6: Case Study - FinancialAnalysis Corp\nFinancialAnalysis Corp needs $20M in manufacturing equipment. Lease option: $350K monthly for 60 months. Buy option: $20M upfront, $200K annual maintenance.\n\nResults: Lease NPV is -$15.2M vs Buy NPV of -$18.5M. Lease is financially superior by $3.3M. Recommendation: Lease the equipment to preserve capital for other strategic investments.");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "LESSON_3_ID");
    record2.set("content_body", "# Lease vs Buy Decision Framework\n\n## Section 1: Lease vs Buy Fundamentals\nThe lease vs buy decision is a capital budgeting analysis comparing financial and strategic implications. Key factors include financial cost, cash flow impact, balance sheet implications, tax considerations, flexibility, and risk allocation.\n\nDecision Framework: (1) Identify equipment needs, (2) Develop lease and buy options, (3) Estimate all costs and benefits, (4) Calculate financial metrics, (5) Evaluate qualitative factors, (6) Assess risk implications, (7) Make final recommendation.\n\n## Section 2: Financial Comparison\nLease Option: $100,000/month = $1.2M/year, maintenance included, tax benefit of $1.8M over 5 years, net cost $4.2M.\n\nBuy Option: $5M upfront, $50K annual maintenance, $25K annual insurance, depreciation tax benefit $1.5M, residual value $2M, net cost $1.875M.\n\nBreak-Even Analysis: At 5-year mark, buy becomes cheaper. Decision: If equipment needed >5 years, buy; if <5 years, lease.\n\n## Section 3: Qualitative Factors\nFive factors: (1) Flexibility - lease offers high flexibility, buy offers low, (2) Technology Currency - lease keeps current, buy faces obsolescence, (3) Operational Control - lease limited, buy full control, (4) Maintenance Burden - lease included, buy company responsibility, (5) Balance Sheet Impact - lease off-balance sheet, buy on-balance sheet.\n\nTechnology Company Example: Software company prefers leasing $10M servers because technology evolves rapidly, flexibility to scale, maintenance handled by lessor, preserves capital for R&D.\n\n## Section 4: Risk Comparison\nLease Risks: lessor default, obsolescence, residual value, flexibility constraints, cost escalation.\n\nBuy Risks: obsolescence, maintenance, residual value, market risk, liquidity risk.\n\nRisk Mitigation: For lease, negotiate lessor creditworthiness and include upgrade options. For buy, purchase maintenance warranty and plan for technology refresh.\n\n## Section 5: Strategic Considerations\nFive considerations: (1) Capital Preservation - leasing preserves capital for core business, (2) Growth Flexibility - enables rapid scaling, (3) Technology Adoption - enables faster adoption, (4) Financial Leverage - buying increases debt ratios, (5) Tax Efficiency - lease payments fully deductible.\n\n## Section 6: Case Study - LeaseVsBuy Corp\nLeaseVsBuy Corp needs $30M manufacturing facility. Lease: $500K/month for 60 months, net cost $21M. Buy: $30M upfront, net cost $4.25M.\n\nFinancial Analysis: Buy is $16.75M cheaper. Qualitative Factors: Long-term strategic need (10-year plan) justifies ownership, company has financial capacity, full control enables customization.\n\nRecommendation: BUY the facility because financial analysis strongly favors buying, long-term strategic need, company has financial capacity, and full control enables customization for operations.");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
