/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_progress_tracking");

  const record0 = new Record(collection);
    record0.set("dashboard_id", "demo_student_001");
    record0.set("lesson_number", 1);
    record0.set("lesson_title", "Intro to Lease Portfolio Risk");
    record0.set("video_watched", true);
    record0.set("video_completion_percentage", 95);
    record0.set("study_guide_completed", true);
    record0.set("glossary_reviewed", true);
    record0.set("case_study_completed", true);
    record0.set("reading_list_reviewed", true);
    record0.set("overall_lesson_completion_percentage", 92);
    record0.set("quiz_score", 45);
    record0.set("quiz_completion_date", "2026-01-28");
    record0.set("quiz_attempts", 1);
    record0.set("quiz_performance_trend", "Stable");
    record0.set("video_watch_time_minutes", 58);
    record0.set("study_guide_time_minutes", 35);
    record0.set("glossary_review_time_minutes", 15);
    record0.set("case_study_time_minutes", 75);
    record0.set("total_lesson_time_minutes", 183);
    record0.set("average_daily_engagement_minutes", 45);
    record0.set("key_concepts_mastered", "Risk identification, Portfolio assessment");
    record0.set("key_concepts_in_progress", "Advanced modeling");
    record0.set("key_concepts_not_addressed", "Emerging risks");
    record0.set("estimated_mastery_level_percentage", 82);
    record0.set("lesson_status", "Completed");
    record0.set("completion_date", "2026-01-28");
    record0.set("days_to_complete", 2);
    record0.set("on_schedule", true);
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("dashboard_id", "demo_student_001");
    record1.set("lesson_number", 2);
    record1.set("lesson_title", "Credit Risk Modeling");
    record1.set("video_watched", true);
    record1.set("video_completion_percentage", 90);
    record1.set("study_guide_completed", true);
    record1.set("glossary_reviewed", true);
    record1.set("case_study_completed", true);
    record1.set("reading_list_reviewed", false);
    record1.set("overall_lesson_completion_percentage", 85);
    record1.set("quiz_score", 48);
    record1.set("quiz_completion_date", "2026-02-01");
    record1.set("quiz_attempts", 1);
    record1.set("quiz_performance_trend", "Improving");
    record1.set("video_watch_time_minutes", 55);
    record1.set("study_guide_time_minutes", 40);
    record1.set("glossary_review_time_minutes", 18);
    record1.set("case_study_time_minutes", 80);
    record1.set("total_lesson_time_minutes", 193);
    record1.set("average_daily_engagement_minutes", 48);
    record1.set("key_concepts_mastered", "Credit risk assessment, Default probability");
    record1.set("key_concepts_in_progress", "Correlation modeling");
    record1.set("key_concepts_not_addressed", "Systemic risk");
    record1.set("estimated_mastery_level_percentage", 85);
    record1.set("lesson_status", "Completed");
    record1.set("completion_date", "2026-02-01");
    record1.set("days_to_complete", 3);
    record1.set("on_schedule", true);
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("dashboard_id", "demo_student_001");
    record2.set("lesson_number", 3);
    record2.set("lesson_title", "Prepayment Risk");
    record2.set("video_watched", true);
    record2.set("video_completion_percentage", 75);
    record2.set("study_guide_completed", true);
    record2.set("glossary_reviewed", false);
    record2.set("case_study_completed", false);
    record2.set("reading_list_reviewed", false);
    record2.set("overall_lesson_completion_percentage", 65);
    record2.set("quiz_score", 38);
    record2.set("quiz_completion_date", "2026-02-04");
    record2.set("quiz_attempts", 2);
    record2.set("quiz_performance_trend", "Stable");
    record2.set("video_watch_time_minutes", 45);
    record2.set("study_guide_time_minutes", 30);
    record2.set("glossary_review_time_minutes", 0);
    record2.set("case_study_time_minutes", 0);
    record2.set("total_lesson_time_minutes", 75);
    record2.set("average_daily_engagement_minutes", 25);
    record2.set("key_concepts_mastered", "Prepayment basics");
    record2.set("key_concepts_in_progress", "Speed modeling");
    record2.set("key_concepts_not_addressed", "Refinancing incentives");
    record2.set("estimated_mastery_level_percentage", 68);
    record2.set("lesson_status", "In Progress");
    record2.set("completion_date", null);
    record2.set("days_to_complete", 4);
    record2.set("on_schedule", false);
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("dashboard_id", "demo_student_001");
    record3.set("lesson_number", 4);
    record3.set("lesson_title", "Interest Rate Risk");
    record3.set("video_watched", false);
    record3.set("video_completion_percentage", 0);
    record3.set("study_guide_completed", false);
    record3.set("glossary_reviewed", false);
    record3.set("case_study_completed", false);
    record3.set("reading_list_reviewed", false);
    record3.set("overall_lesson_completion_percentage", 0);
    record3.set("quiz_score", 0);
    record3.set("quiz_completion_date", null);
    record3.set("quiz_attempts", 0);
    record3.set("quiz_performance_trend", "Stable");
    record3.set("video_watch_time_minutes", 0);
    record3.set("study_guide_time_minutes", 0);
    record3.set("glossary_review_time_minutes", 0);
    record3.set("case_study_time_minutes", 0);
    record3.set("total_lesson_time_minutes", 0);
    record3.set("average_daily_engagement_minutes", 0);
    record3.set("key_concepts_mastered", "");
    record3.set("key_concepts_in_progress", "Interest rate sensitivity");
    record3.set("key_concepts_not_addressed", "Duration, Convexity");
    record3.set("estimated_mastery_level_percentage", 0);
    record3.set("lesson_status", "Not Started");
    record3.set("completion_date", null);
    record3.set("days_to_complete", 0);
    record3.set("on_schedule", false);
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("dashboard_id", "demo_student_001");
    record4.set("lesson_number", 5);
    record4.set("lesson_title", "Liquidity Risk");
    record4.set("video_watched", false);
    record4.set("video_completion_percentage", 0);
    record4.set("study_guide_completed", false);
    record4.set("glossary_reviewed", false);
    record4.set("case_study_completed", false);
    record4.set("reading_list_reviewed", false);
    record4.set("overall_lesson_completion_percentage", 0);
    record4.set("quiz_score", 0);
    record4.set("quiz_completion_date", null);
    record4.set("quiz_attempts", 0);
    record4.set("quiz_performance_trend", "Stable");
    record4.set("video_watch_time_minutes", 0);
    record4.set("study_guide_time_minutes", 0);
    record4.set("glossary_review_time_minutes", 0);
    record4.set("case_study_time_minutes", 0);
    record4.set("total_lesson_time_minutes", 0);
    record4.set("average_daily_engagement_minutes", 0);
    record4.set("key_concepts_mastered", "");
    record4.set("key_concepts_in_progress", "Market liquidity");
    record4.set("key_concepts_not_addressed", "Bid-ask spreads");
    record4.set("estimated_mastery_level_percentage", 0);
    record4.set("lesson_status", "Not Started");
    record4.set("completion_date", null);
    record4.set("days_to_complete", 0);
    record4.set("on_schedule", false);
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("dashboard_id", "demo_student_001");
    record5.set("lesson_number", 6);
    record5.set("lesson_title", "Portfolio Valuation");
    record5.set("video_watched", false);
    record5.set("video_completion_percentage", 0);
    record5.set("study_guide_completed", false);
    record5.set("glossary_reviewed", false);
    record5.set("case_study_completed", false);
    record5.set("reading_list_reviewed", false);
    record5.set("overall_lesson_completion_percentage", 0);
    record5.set("quiz_score", 0);
    record5.set("quiz_completion_date", null);
    record5.set("quiz_attempts", 0);
    record5.set("quiz_performance_trend", "Stable");
    record5.set("video_watch_time_minutes", 0);
    record5.set("study_guide_time_minutes", 0);
    record5.set("glossary_review_time_minutes", 0);
    record5.set("case_study_time_minutes", 0);
    record5.set("total_lesson_time_minutes", 0);
    record5.set("average_daily_engagement_minutes", 0);
    record5.set("key_concepts_mastered", "");
    record5.set("key_concepts_in_progress", "Valuation methods");
    record5.set("key_concepts_not_addressed", "Mark-to-market");
    record5.set("estimated_mastery_level_percentage", 0);
    record5.set("lesson_status", "Not Started");
    record5.set("completion_date", null);
    record5.set("days_to_complete", 0);
    record5.set("on_schedule", false);
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("dashboard_id", "demo_student_001");
    record6.set("lesson_number", 7);
    record6.set("lesson_title", "Credit Spread Modeling");
    record6.set("video_watched", false);
    record6.set("video_completion_percentage", 0);
    record6.set("study_guide_completed", false);
    record6.set("glossary_reviewed", false);
    record6.set("case_study_completed", false);
    record6.set("reading_list_reviewed", false);
    record6.set("overall_lesson_completion_percentage", 0);
    record6.set("quiz_score", 0);
    record6.set("quiz_completion_date", null);
    record6.set("quiz_attempts", 0);
    record6.set("quiz_performance_trend", "Stable");
    record6.set("video_watch_time_minutes", 0);
    record6.set("study_guide_time_minutes", 0);
    record6.set("glossary_review_time_minutes", 0);
    record6.set("case_study_time_minutes", 0);
    record6.set("total_lesson_time_minutes", 0);
    record6.set("average_daily_engagement_minutes", 0);
    record6.set("key_concepts_mastered", "");
    record6.set("key_concepts_in_progress", "Spread dynamics");
    record6.set("key_concepts_not_addressed", "OAS analysis");
    record6.set("estimated_mastery_level_percentage", 0);
    record6.set("lesson_status", "Not Started");
    record6.set("completion_date", null);
    record6.set("days_to_complete", 0);
    record6.set("on_schedule", false);
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("dashboard_id", "demo_student_001");
    record7.set("lesson_number", 8);
    record7.set("lesson_title", "Portfolio Concentration");
    record7.set("video_watched", false);
    record7.set("video_completion_percentage", 0);
    record7.set("study_guide_completed", false);
    record7.set("glossary_reviewed", false);
    record7.set("case_study_completed", false);
    record7.set("reading_list_reviewed", false);
    record7.set("overall_lesson_completion_percentage", 0);
    record7.set("quiz_score", 0);
    record7.set("quiz_completion_date", null);
    record7.set("quiz_attempts", 0);
    record7.set("quiz_performance_trend", "Stable");
    record7.set("video_watch_time_minutes", 0);
    record7.set("study_guide_time_minutes", 0);
    record7.set("glossary_review_time_minutes", 0);
    record7.set("case_study_time_minutes", 0);
    record7.set("total_lesson_time_minutes", 0);
    record7.set("average_daily_engagement_minutes", 0);
    record7.set("key_concepts_mastered", "");
    record7.set("key_concepts_in_progress", "Concentration risk");
    record7.set("key_concepts_not_addressed", "Diversification");
    record7.set("estimated_mastery_level_percentage", 0);
    record7.set("lesson_status", "Not Started");
    record7.set("completion_date", null);
    record7.set("days_to_complete", 0);
    record7.set("on_schedule", false);
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("dashboard_id", "demo_student_001");
    record8.set("lesson_number", 9);
    record8.set("lesson_title", "Stress Testing");
    record8.set("video_watched", false);
    record8.set("video_completion_percentage", 0);
    record8.set("study_guide_completed", false);
    record8.set("glossary_reviewed", false);
    record8.set("case_study_completed", false);
    record8.set("reading_list_reviewed", false);
    record8.set("overall_lesson_completion_percentage", 0);
    record8.set("quiz_score", 0);
    record8.set("quiz_completion_date", null);
    record8.set("quiz_attempts", 0);
    record8.set("quiz_performance_trend", "Stable");
    record8.set("video_watch_time_minutes", 0);
    record8.set("study_guide_time_minutes", 0);
    record8.set("glossary_review_time_minutes", 0);
    record8.set("case_study_time_minutes", 0);
    record8.set("total_lesson_time_minutes", 0);
    record8.set("average_daily_engagement_minutes", 0);
    record8.set("key_concepts_mastered", "");
    record8.set("key_concepts_in_progress", "Stress scenarios");
    record8.set("key_concepts_not_addressed", "Scenario analysis");
    record8.set("estimated_mastery_level_percentage", 0);
    record8.set("lesson_status", "Not Started");
    record8.set("completion_date", null);
    record8.set("days_to_complete", 0);
    record8.set("on_schedule", false);
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("dashboard_id", "demo_student_001");
    record9.set("lesson_number", 10);
    record9.set("lesson_title", "Advanced Topics");
    record9.set("video_watched", false);
    record9.set("video_completion_percentage", 0);
    record9.set("study_guide_completed", false);
    record9.set("glossary_reviewed", false);
    record9.set("case_study_completed", false);
    record9.set("reading_list_reviewed", false);
    record9.set("overall_lesson_completion_percentage", 0);
    record9.set("quiz_score", 0);
    record9.set("quiz_completion_date", null);
    record9.set("quiz_attempts", 0);
    record9.set("quiz_performance_trend", "Stable");
    record9.set("video_watch_time_minutes", 0);
    record9.set("study_guide_time_minutes", 0);
    record9.set("glossary_review_time_minutes", 0);
    record9.set("case_study_time_minutes", 0);
    record9.set("total_lesson_time_minutes", 0);
    record9.set("average_daily_engagement_minutes", 0);
    record9.set("key_concepts_mastered", "");
    record9.set("key_concepts_in_progress", "Advanced modeling");
    record9.set("key_concepts_not_addressed", "Emerging risks");
    record9.set("estimated_mastery_level_percentage", 0);
    record9.set("lesson_status", "Not Started");
    record9.set("completion_date", null);
    record9.set("days_to_complete", 0);
    record9.set("on_schedule", false);
  app.save(record9);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
