/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("vendor_leasing_case_studies");

  const record0 = new Record(collection);
    record0.set("lessonId", "lesson_3");
    record0.set("title", "TechCorp Equipment Lease Negotiation");
    record0.set("scenario", "TechCorp, a mid-sized technology company, needs to lease 50 servers and networking equipment for their data center expansion. They have received proposals from three vendors with different payment structures, terms, and options. The company needs to evaluate the proposals and negotiate the best terms. Key considerations include: initial payment amounts, escalation clauses, renewal options, termination flexibility, and maintenance responsibilities. The company's CFO wants a comprehensive analysis to support the negotiation strategy.");
    record0.set("requirements", "1) Analyze all three vendor proposals using NPV analysis with 6% discount rate; 2) Perform sensitivity analysis on key assumptions (discount rate, payment amounts, lease term); 3) Develop negotiation strategy for each vendor; 4) Identify key terms to negotiate (payment structure, renewal options, termination clauses); 5) Create financial model comparing all scenarios; 6) Prepare recommendation with supporting analysis; 7) Develop negotiation talking points for each vendor.");
    record0.set("analysisFramework", "Step 1: Gather and organize all vendor proposals with complete terms. Step 2: Calculate NPV for each proposal using base case assumptions. Step 3: Perform sensitivity analysis on discount rate (5%-8%), payment amounts (\u00b110%), and lease term variations. Step 4: Identify negotiation opportunities based on market data and competitive proposals. Step 5: Develop alternative scenarios combining favorable terms from multiple proposals. Step 6: Calculate financial impact of proposed modifications. Step 7: Rank proposals based on financial and strategic criteria. Step 8: Prepare negotiation strategy with fallback positions.");
    record0.set("expectedOutcome", "Students should be able to: 1) Calculate and compare NPV of multiple lease proposals; 2) Identify key value drivers in lease negotiations; 3) Develop data-driven negotiation strategies; 4) Quantify the financial impact of different lease terms; 5) Create comprehensive financial models for lease analysis; 6) Prepare professional recommendations with supporting analysis; 7) Understand how to use financial analysis to strengthen negotiating position.");
    record0.set("difficulty", "intermediate");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lessonId", "lesson_4");
    record1.set("title", "GlobalCorp Lease Accounting System Implementation");
    record1.set("scenario", "GlobalCorp, a multinational corporation with 300+ leases across 15 countries, is implementing a new lease accounting system to comply with ASC 842. The company currently uses spreadsheets and manual processes. The implementation team needs to: assess current state, design new processes, select and configure the system, migrate legacy data, implement controls, and train users. The project has a 6-month timeline and $500,000 budget. Key challenges include data quality issues, multiple currencies, and complex lease terms.");
    record1.set("requirements", "1) Assess current lease accounting processes and identify gaps; 2) Design new processes aligned with ASC 842 requirements; 3) Evaluate and select appropriate lease accounting system; 4) Develop data migration strategy for 300+ existing leases; 5) Design internal controls and approval workflows; 6) Create system configuration specifications; 7) Develop training program for 50+ users; 8) Establish testing and validation procedures; 9) Create implementation timeline and resource plan; 10) Develop post-implementation support plan.");
    record1.set("analysisFramework", "Phase 1: Current State Assessment - Document existing processes, systems, and data quality issues. Phase 2: Design - Define new processes, system requirements, and control framework. Phase 3: System Selection - Evaluate vendors based on functionality, cost, and support. Phase 4: Configuration - Configure system for company's lease portfolio and accounting policies. Phase 5: Data Migration - Extract, transform, and load legacy lease data with validation. Phase 6: Testing - Conduct unit, integration, and user acceptance testing. Phase 7: Training - Provide training to system users and administrators. Phase 8: Go-Live - Transition to new system with parallel run period. Phase 9: Stabilization - Monitor system performance and address issues. Phase 10: Optimization - Identify and implement process improvements.");
    record1.set("expectedOutcome", "Students should be able to: 1) Understand lease accounting system implementation lifecycle; 2) Design processes aligned with accounting standards; 3) Evaluate and select appropriate systems; 4) Develop data migration strategies; 5) Design effective internal controls; 6) Create implementation plans and timelines; 7) Understand change management and training requirements; 8) Identify and mitigate implementation risks; 9) Establish post-implementation support; 10) Optimize lease accounting operations.");
    record1.set("difficulty", "advanced");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
