/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_3963162141");
    record0.set("content_body", "Practical Implementation - Comprehensive Guide\n\n1. JOURNAL ENTRIES FOR LEASE RECOGNITION\n\nAt Lease Commencement:\nDr. Right-of-Use Asset (ROU Asset)          $XXX\n  Cr. Lease Liability                                    $XXX\n\nMonthly/Periodic Lease Payments:\nDr. Lease Liability                         $XXX\nDr. Interest Expense                        $XXX\n  Cr. Cash                                              $XXX\n\nPeriodic Depreciation of ROU Asset:\nDr. Depreciation Expense                    $XXX\n  Cr. Accumulated Depreciation - ROU Asset             $XXX\n\n2. FINANCIAL STATEMENT PRESENTATION\n\nBalance Sheet:\n- ROU Asset: Separate line item or within PP&E\n- Lease Liability: Split into current and non-current portions\n- Current Lease Liability: Due within 12 months\n- Non-Current Lease Liability: Due beyond 12 months\n\nIncome Statement:\n- Operating Leases: Single straight-line lease expense\n- Finance Leases: Depreciation expense + Interest expense (front-loaded)\n\nCash Flow Statement:\n- Operating Activities: Lease payments (operating leases)\n- Financing Activities: Lease payments (finance leases)\n\n3. BALANCE SHEET IMPACT\n\nAssets: ROU Asset recognized; Cash decreases\nLiabilities: Lease Liability recognized\nEquity: No direct impact; indirectly affected through retained earnings\nDebt-to-Equity Ratio: Increases due to new liability\n\n4. INCOME STATEMENT IMPACT\n\nOperating Leases: Straight-line expense = Total payments / Lease term\nFinance Leases: Year 1 higher (depreciation + interest); declining interest thereafter\nLessor: Lease revenue (operating) or Sales revenue + Interest income (sales-type)\n\n5. TRANSITION GUIDANCE\n\nModified Retrospective Approach:\n- Cumulative effect recognized at adoption date\n- Comparative periods NOT restated\n- Practical expedients available\n\nPractical Expedients:\n- Short-term leases (<12 months): Expense as incurred\n- Low-value assets (<$5,000): Expense as incurred\n- Hindsight: Use hindsight in determining lease term\n- Portfolio approach: Apply to similar lease portfolios\n\n6. IMPLEMENTATION TIMELINE\n\nPhase 1 (3-6 months before): Identify leases, assess classification, determine discount rates\nPhase 2 (2-3 months before): Configure systems, develop tracking database, train staff\nPhase 3 (1-2 months before): Calculate ROU assets/liabilities, prepare adjustments\nPhase 4 (At adoption): Record entries, update statements, prepare disclosures\n\n7. COMMON PITFALLS\n\n- Failing to identify embedded leases in contracts\n- Using incorrect incremental borrowing rate\n- Not including renewal options in lease term\n- Omitting residual guarantees from lease payments\n- Not remeasuring for lease modifications\n- Inadequate financial statement disclosures\n- System integration issues and configuration errors");
  app.save(record0);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
