/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_3963162141_1");
    record0.set("content_body", "Section 1: ASC 842 Introduction and Background - What is ASC 842? (Accounting Standards Codification Topic 842, US GAAP lease accounting standard, issued by FASB, effective January 1, 2019 for public companies and January 1, 2022 for private companies, replaces ASC 840). ASC 842 Development (joint project with IASB for convergence, issued February 25, 2016). Key Principle: Single lease accounting model with all leases recognized on balance sheet with Right-of-Use (ROU) asset and lease liability. Section 2: ASC 842 Scope and Applicability - Applies to all US GAAP entities (public companies, private companies, non-profits). Does not apply to IFRS entities, short-term leases (<12 months), or low-value asset leases (<$5,000). Exemptions: Short-term lease exemption (\u226412 months, optional), Low-value asset exemption (<$5,000, optional). Section 3: Key Definitions and Concepts - Lease Definition: contract with identified asset, customer right to control use, for period of time in exchange for consideration. Key Components: Identified Asset (specified and physically distinct), Right to Control (direct use and obtain benefits), Period of Time (non-cancellable), Consideration (lease payments). Lease Term: non-cancellable period plus renewal periods if reasonably certain. Lease Payments: fixed payments, variable payments, residual value guarantees. Discount Rate: implicit rate or incremental borrowing rate. Section 4: ASC 842 Principles and Framework - Core Principles: ROU Asset (lessee right to use), Lease Liability (obligation to pay), Measurement (present value), Subsequent Measurement (depreciation and interest), Lessor Accounting (finance vs operating). Section 5: Case Study - ASC842Corp with manufacturing equipment lease ($500,000 cost, 5-year term, $10,000 monthly payment, $50,000 residual guarantee, 4% implicit rate). Lease identification, term calculation, payment analysis, discount rate selection, ROU asset and liability calculation ($589,096 ROU asset, $584,096 liability).");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "pbc_3963162141_2");
    record1.set("content_body", "Section 1: Lease Definition Under ASC 842 - A contract is a lease if: (1) Identified asset exists or will exist, (2) Customer has right to control use of asset, (3) For period of time in exchange for consideration. Key Elements: Identified Asset (specified, physically distinct, not substitutable), Right to Control (direct use, obtain benefits), Period of Time (specified, non-cancellable), Consideration (lease payments). Section 2: Lease vs Service Contract Distinction - Lease Characteristics: identified asset, control of asset, lease payments. Service Contract Characteristics: no identified asset, no control, service payments. Examples: Equipment lease (lease), Cloud computing (service), Software license (depends on control). Section 3: Control Assessment Framework - Step 1: Identify Asset, Step 2: Assess Direction of Use, Step 3: Assess Benefits, Step 4: Assess Substitution Rights, Step 5: Conclusion. Section 4: Lease Identification Examples - Equipment Lease (5-year, $10,000/month = LEASE), Building Lease (10-year, $50,000/month = LEASE), Cloud Computing (3-year, $5,000/month = NOT A LEASE), Software License (2-year, $100,000/year = depends on control). Section 5: Case Study - IdentificationCorp analyzing 4 contracts: Equipment Lease ($500,000 ROU asset), Building Lease ($5,000,000 ROU asset), Cloud Computing Service ($5,000/month expense), Vehicle Lease ($35,000 ROU asset). Total leases identified: 3 with $5,535,000 total ROU assets. Total non-leases: 1 cloud service.");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
