/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "LESSON_3_ID");
    record0.set("content_body", "# Preparation and Information Gathering\n\n## Pre-Negotiation Preparation\n\n**Why Preparation Matters**: Increases confidence, improves outcomes, reduces surprises. Prepared negotiators close more deals.\n\n**Preparation Timeline**:\n- 2-4 Weeks Before: Research client company, understand industry, identify needs\n- 1-2 Weeks Before: Develop lease proposal, prepare pricing options, identify alternatives\n- 1 Week Before: Prepare presentation materials, anticipate objections, plan responses\n- 1-2 Days Before: Review materials, practice presentation, prepare questions\n- Day Of: Arrive early, set up materials, mental preparation\n\n## Client Research and Analysis\n\n**Company Research Steps**:\n1. Basic Information: Company name, location, industry, size, revenue\n2. Financial Analysis: Financial statements, credit rating, payment history\n3. Industry Analysis: Industry trends, competitive landscape, market conditions\n4. Equipment Needs: What equipment needed, current status, future plans\n5. Decision-Making Process: Who decides, approval process, timeline\n\n## Information Gathering Techniques\n\n**Research**: Company website, financial statements, industry reports, news articles\n\n**Networking**: Talk to industry contacts, learn about company reputation\n\n**Direct Questions**: Ask client directly, listen to answers, take notes\n\n**Observation**: Visit facility, observe operations, understand needs\n\n**Reference Checks**: Talk to other clients, learn about their experience\n\n## Negotiation Strategy Development\n\n**Strategy Components**:\n- Objectives: What do you want to achieve? Ideal outcome?\n- Priorities: What is most important? What can you compromise on?\n- Alternatives: What if negotiation fails? What are your options?\n- Limits: What is your walk-away point? Minimum acceptable outcome?\n- Tactics: What tactics will you use? How will you present your case?\n\n## Case Study: ManufacturingCo Equipment Lease\n\n**Client Profile**: $50M revenue, manufacturing industry, need new equipment, $500K budget, 3-month timeline\n\n**Preparation Process**: Researched company, understood industry, identified equipment needs, developed 3 pricing scenarios (4%, 4.5%, 5%), prepared presentation materials, anticipated objections\n\n**Client Research**: Established manufacturer, strong financial position, growing sector, equipment aging, expansion plans\n\n**Negotiation Strategy**: Objectives - 5-year lease at 4% rate; Priorities - Rate is priority, term flexible; Alternatives - 4.5% rate if needed; Limits - Minimum 4.5% rate; Tactics - Use anchoring, reciprocity, demonstrate expertise");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "LESSON_4_ID");
    record1.set("content_body", "# Negotiation Tactics and Techniques\n\n## Anchoring and Opening Offers\n\n**What is Anchoring**: First number mentioned in negotiation influences final outcome. Example: Start with 4% rate.\n\n**Why Anchoring Works**: Sets reference point, influences perception, anchors expectations\n\n**Anchoring Strategy**:\n1. Make First Offer: Present your opening position\n2. Justify Your Anchor: Explain reasoning, provide supporting data\n3. Be Prepared to Move: Have fallback positions ready\n4. Don't Move Too Much: Small incremental moves (4% to 4.25% to 4.5%)\n\n## Reciprocity and Trading\n\n**What is Reciprocity**: Give something to get something. Creates obligation to return favor.\n\n**Reciprocity Strategy**:\n1. Identify What You Can Offer: Flexible payment terms, quick approval, reduced rates\n2. Identify What You Want: Commitment, longer term, higher volume\n3. Make Trade: Offer something for something (\"If you commit to 5 years, I can offer 4% rate\")\n4. Document Agreement: Confirm what was agreed\n\n## Silence and Patience\n\n**What is Silence**: Pause in conversation, allow other party to speak. Creates pressure to respond.\n\n**Silence Strategy**:\n1. Make Offer: Present your position\n2. Stay Silent: Don't fill the silence, wait for response\n3. Listen Actively: Pay attention to their response\n4. Respond Thoughtfully: Take time to respond\n\n## Reframing and Perspective\n\n**What is Reframing**: Change how issue is viewed, present different perspective. Example: \"This is investment, not expense\"\n\n**Reframing Strategy**:\n1. Identify Objection: What is their concern?\n2. Reframe Issue: Present different perspective\n3. Provide Evidence: Support your reframe\n4. Confirm Understanding: Make sure they understand\n\n## Case Study: ManufacturingCo Negotiation\n\n**Opening Position**: Lessor offers 5%, Client wants 3.5%, Gap is 1.5%\n\n**Anchoring**: Lessor anchors at 5%, justifies with market data (\"Market rate is 4.5-5.5%\")\n\n**Reciprocity**: Lessor offers \"If you commit to 5 years, I can offer 4.5%\"\n\n**Silence**: After making offer, lessor stays silent, client thinks about offer\n\n**Reframing**: Client says \"Rate too high\", Lessor reframes \"This rate includes full service and support\"\n\n**Final Agreement**: 4.25% rate, 4.5-year term, both parties satisfied, win-win outcome");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "LESSON_5_ID");
    record2.set("content_body", "# Handling Objections and Difficult Situations\n\n## Common Lease Sales Objections\n\n**Objection 1: Price/Rate Too High**\n- Response: Acknowledge concern, explain value, offer alternatives\n\n**Objection 2: Don't Need Equipment Now**\n- Response: Understand timeline, offer flexible terms, plan for future\n\n**Objection 3: Prefer to Buy**\n- Response: Explain lease benefits, compare lease vs. buy, offer flexibility\n\n**Objection 4: Concerned About Credit**\n- Response: Explain approval process, offer solutions, build confidence\n\n**Objection 5: Need to Think About It**\n- Response: Respect their process, offer support, follow up\n\n## Objection Handling Framework\n\n**Step 1: Listen** - Let them finish, don't interrupt, take notes\n\n**Step 2: Acknowledge** - Show you understand, validate their concern\n\n**Step 3: Clarify** - Ask questions, understand root cause\n\n**Step 4: Respond** - Address their concern, provide solution\n\n**Step 5: Confirm** - Make sure they're satisfied\n\n## Difficult Situations\n\n**Angry Client**: Stay calm, listen actively, acknowledge emotions, offer solution\n\n**Unrealistic Expectations**: Clarify reality, explain constraints, offer alternatives\n\n**Multiple Competing Offers**: Understand needs, differentiate your offer, emphasize value\n\n**Stalled Negotiation**: Take break, reassess positions, find creative solutions\n\n## Case Study: ManufacturingCo Objections\n\n**Objection 1 - Price Too High**\n- Client: \"Your 5% rate is too high\"\n- Response: Acknowledge, clarify expectations (3.5%), respond with market data (4.5-5.5%), offer 4.5% for 5-year commitment\n\n**Objection 2 - Don't Need Equipment Now**\n- Client: \"We don't need equipment for 6 months\"\n- Response: Acknowledge timeline, clarify exact need, offer flexible lease start, lock in rate now\n\n**Objection 3 - Credit Approval Concern**\n- Client: \"Will we be approved?\"\n- Response: Acknowledge concern, clarify past issues, explain recent strong performance, express confidence in approval\n\n**Outcome**: All objections addressed, lease agreement reached, client satisfied, successful negotiation");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
