/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_1_1");
    record0.set("content_body", "# Understanding ROI in Equipment Leasing\n\n## ROI Fundamentals\nReturn on Investment (ROI) measures the efficiency of an investment: ROI = (Net Profit / Cost of Investment) \u00d7 100%\n\n## Why ROI Matters\n\n**Lessor Perspective:**\n- Revenue generation and risk assessment\n- Portfolio optimization and pricing strategy\n\n**Lessee Perspective:**\n- Cost comparison (lease vs. buy)\n- Cash flow management and asset utilization\n\n**Portfolio Perspective:**\n- Performance benchmarking and risk diversification\n- Capital allocation decisions\n\n## ROI Drivers\n1. Lease terms and pricing\n2. Equipment characteristics (cost, depreciation, maintenance)\n3. Operational factors (utilization, downtime, salvage value)\n4. Financial factors (financing costs, taxes, insurance)\n5. Market factors (equipment conditions, interest rates, residual values)\n\n## ROI Calculation Methods\n\n**Simple ROI:** (Total Lease Payments - Equipment Cost) / Equipment Cost \u00d7 100%\n\n**Annualized ROI:** Simple ROI / Number of Years \u00d7 100%\n\n**Net Present Value (NPV):** Accounts for time value of money\n\n## Industry Benchmarks\n- Equipment leasing average: 8-15% annually\n- High-tech equipment: 12-18%\n- Industrial equipment: 6-10%\n- Vehicles: 5-8%\n\n## Case Study: ManufacturingCorp Inc.\nCNC Machine Lease Analysis:\n- Equipment Cost: $250,000\n- Lease Term: 5 years\n- Monthly Payment: $4,500\n- Total Lease Payments: $270,000\n- Simple ROI: 8% | Annualized: 1.6%\n\nKey insights: Modest returns for lessor, significant capital preservation for lessee. Residual value and maintenance costs are critical factors.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_1_2");
    record1.set("content_body", "# ROI Calculation Methods and Frameworks\n\n## ROI Calculation Methods\n\n**1. Simple ROI:** Easy but ignores time value of money\n**2. Annualized ROI:** Allows comparison across different time periods\n**3. NPV (Net Present Value):** Accounts for time value of money\n**4. IRR (Internal Rate of Return):** Discount rate where NPV = 0\n**5. Profitability Index:** PV of Future Cash Flows / Initial Investment (PI > 1 = good)\n**6. Payback Period:** Time to recover initial investment\n\n## ROI Frameworks\n\n**Lessor Framework:**\nROI = (Lease Payments + Residual Value - Total Costs) / Equipment Cost \u00d7 100%\nFocus: Pricing, residual value, cost control, risk mitigation\n\n**Lessee Framework:**\nROI = (Cost of Ownership - Lease Costs) / Lease Costs \u00d7 100%\nFocus: Lease vs. buy, cash flow, flexibility, technology currency\n\n**Comparative Framework:**\nCompares leasing vs. buying and different lease terms\n\n**Portfolio Framework:**\nWeighted average ROI across multiple leases by equipment type and segment\n\n## ROI Analysis Process (6 Steps)\n1. Define investment scope\n2. Gather financial data\n3. Identify cash flows\n4. Calculate ROI metrics\n5. Sensitivity analysis\n6. Make decision\n\n## Case Study: TechCorp Inc.\nServer Infrastructure Decision:\n\n**Purchase Option:**\n- Equipment Cost: $500,000\n- Maintenance (4 years): $60,000\n- Residual Value: $100,000\n- Net Cost: $460,000\n\n**Lease Option:**\n- Lease Payments (4 years): $528,000\n- Maintenance: $8,000\n- Total Cost: $536,000\n\n**Analysis:** Purchase is $76,000 cheaper, but leasing provides technology flexibility, maintenance coverage, and capital preservation. Recommendation: Lease due to rapid technology evolution and upgrade flexibility.");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
