/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "LESSON_1_ID");
    record0.set("content_body", "# Negotiation Principles and Psychology\n\n## Core Negotiation Principles\n\n**Preparation and Planning**: Research the other party, define your BATNA, set clear objectives, identify common ground, and develop multiple scenarios.\n\n**Active Listening**: Listen to understand, ask clarifying questions, pay attention to verbal and non-verbal cues, and summarize to confirm understanding.\n\n**Interest-Based Negotiation**: Focus on underlying interests rather than positions. Separate people from problems and look for win-win solutions.\n\n**Anchoring and Framing**: The first number mentioned significantly influences outcomes. Make the first offer when you have good information.\n\n**Reciprocity and Concessions**: Make concessions gradually, ask for something in return, and track concessions to ensure balance.\n\n## Negotiation Psychology\n\n**Cognitive Biases**: Anchoring bias, confirmation bias, availability heuristic, sunk cost fallacy, and overconfidence bias all affect negotiations.\n\n**Emotional Dynamics**: Anger, fear, trust, and power dynamics influence negotiation outcomes. Manage emotions through preparation and confidence.\n\n## Emotional Intelligence in Negotiation\n\n**Self-Awareness**: Recognize your emotional patterns, identify your negotiation style, understand your values, and monitor stress levels.\n\n**Self-Regulation**: Stay calm under pressure, control impulses, maintain composure, and use mindfulness techniques.\n\n**Empathy**: Put yourself in their shoes, recognize their concerns, validate their feelings, and build genuine understanding.\n\n**Social Skills**: Communicate clearly, build rapport, manage conflict constructively, and collaborate toward mutual solutions.\n\n**Motivation**: Stay committed to objectives, maintain optimism, persist through difficulties, and focus on creating value.\n\n## Negotiation Styles\n\n- **Competing**: Win at expense of other party (urgent situations)\n- **Collaborating**: Win-win solutions (important relationships)\n- **Compromising**: Both give up something (time-pressured)\n- **Avoiding**: Postpone or sidestep (minor issues)\n- **Accommodating**: Prioritize other party (build goodwill)\n\n## Case Study: Commercial Real Estate Lease\n\nLandlord demanded $50/sq ft, tenant budgeted $40/sq ft. Through preparation, active listening, and collaborative negotiation, they reached $43/sq ft with 2% annual increases and tenant improvement allowance, creating value for both parties.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "LESSON_2_ID");
    record1.set("content_body", "# Lease Sales Process and Stakeholders\n\n## Lease Sales Process Overview\n\n**Stage 1: Prospecting**: Market research, referrals, direct outreach, trade shows, digital marketing, and lead qualification.\n\n**Stage 2: Needs Assessment**: Discovery meeting, open-ended questions, understand pain points, identify budget and timeline, determine decision-makers.\n\n**Stage 3: Solution Development**: Analyze requirements, research options, develop proposals, calculate payments, present with ROI analysis.\n\n**Stage 4: Negotiation**: Address objections, negotiate terms, explore alternatives, build consensus, clarify conditions.\n\n**Stage 5: Documentation**: Prepare agreements, obtain approvals, coordinate with legal, establish schedules.\n\n**Stage 6: Implementation**: Equipment delivery, training, support procedures, payment processing, follow-up.\n\n**Stage 7: Relationship Management**: Regular check-ins, monitor satisfaction, identify opportunities, plan renewal.\n\n## Key Stakeholders\n\n**Primary Decision-Maker** (CFO/Finance Director): Controls budget, focused on ROI and cash flow. Present financial analysis and cost savings.\n\n**Technical Evaluator** (Operations Manager): Assesses specifications and reliability. Provide technical details and references.\n\n**End User** (Production/Office Staff): Uses equipment daily. Involve in demos, address usability, provide training.\n\n**Procurement Manager**: Manages vendor relationships and pricing. Offer competitive pricing and flexible terms.\n\n**Legal/Compliance Officer**: Reviews contracts and ensures compliance. Provide clear terms and address legal concerns.\n\n## Stakeholder Mapping\n\n**High Power, High Interest**: Manage closely with regular communication and detailed information.\n\n**High Power, Low Interest**: Keep satisfied with strategic benefits and executive summaries.\n\n**Low Power, High Interest**: Keep informed by involving in process and gathering feedback.\n\n**Low Power, Low Interest**: Monitor with minimal communication.\n\n## Multi-Stakeholder Negotiation\n\n**Building Consensus**: Understand individual interests, develop inclusive solutions, facilitate group discussions, manage conflicts.\n\n**Communication Strategy**: Tailor messages to each stakeholder (finance, operations, IT, procurement, legal) and use multiple channels.\n\n## Case Study: Manufacturing Equipment Lease\n\nA 500-employee manufacturing company evaluated leasing production equipment. Key stakeholders had different priorities: CFO wanted ROI, Operations wanted reliability, Plant Manager wanted training, Procurement wanted pricing, Legal wanted contract terms. Through individual meetings, group presentations, and collaborative negotiation, they reached agreement on $150,000 annual lease with 5-year warranty, training, and 24/7 support.");
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
