/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_3_id_placeholder_1");
    record0.set("content_body", "**Section 1: Lease Pricing Fundamentals**\n\nKey Pricing Components:\n\n1. Equipment Cost (Capitalized Cost): Acquisition cost of asset, delivery and installation costs, setup and configuration costs, initial training costs. Example: $100K equipment + $5K delivery + $3K setup = $108K capitalized cost\n\n2. Lessor's Cost of Capital: Interest rate lessor pays to finance the lease, typically 4-8% depending on credit quality, affects monthly payment calculation, higher cost of capital = higher lease payment. Example: 6% annual cost of capital\n\n3. Residual Value: Estimated value of asset at lease end, based on depreciation, market conditions, technology, typically 20-40% of original cost for equipment, higher residual value = lower monthly payment. Example: $100K equipment, 5-year lease, $25K residual value\n\n4. Lease Term: Duration of lease (months or years), longer term = lower monthly payment, shorter term = higher monthly payment, affects total interest paid. Example: 36-month lease vs. 60-month lease\n\n5. Lessor's Margin/Profit: Lessor's desired profit on the lease, typically 2-5% of capitalized cost, covers lessor's overhead and profit, competitive market = lower margins. Example: 3% margin on $100K = $3K profit\n\n6. Operating Costs: Maintenance and repairs (if full-service lease), insurance (if lessor carries), property taxes (if applicable), administrative costs. Example: $2K/year maintenance + $1K/year insurance = $3K/year");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_3_id_placeholder_1");
    record1.set("content_body", "**Section 2: Lease Payment Calculation Methods**\n\nMethod 1: Present Value of Annuity (PVA) Method\n\nFormula: Monthly Payment = (Capitalized Cost - Residual Value) / PVA Factor\n\nWhere: PVA Factor = [1 - (1 + r)^-n] / r\n- r = monthly interest rate (annual rate / 12)\n- n = number of months\n\nExample:\n- Capitalized Cost: $100,000\n- Residual Value: $25,000\n- Lease Term: 60 months\n- Annual Interest Rate: 6% (monthly = 0.5%)\n- PVA Factor = [1 - (1.005)^-60] / 0.005 = 51.73\n- Monthly Payment = ($100,000 - $25,000) / 51.73 = $1,451\n\nMethod 2: Money Factor Method (Automotive Industry)\n\nFormula: Monthly Payment = (Capitalized Cost + Residual Value) \u00d7 Money Factor + Residual Value Depreciation\n\nWhere: Money Factor = Annual Interest Rate / 2400\n\nExample:\n- Capitalized Cost: $30,000\n- Residual Value: $15,000\n- Lease Term: 36 months\n- Annual Interest Rate: 6% (Money Factor = 0.0025)\n- Monthly Payment = ($30,000 + $15,000) \u00d7 0.0025 + ($30,000 - $15,000) / 36\n- Monthly Payment = $112.50 + $416.67 = $529.17\n\nMethod 3: Implicit Interest Rate Method\n\nFormula: Solve for interest rate where PV of payments = Capitalized Cost - Residual Value\n\nUsed when lessor wants specific monthly payment and needs to determine implied interest rate.\n\nExample:\n- Capitalized Cost: $100,000\n- Residual Value: $25,000\n- Desired Monthly Payment: $1,500\n- Lease Term: 60 months\n- Solve for interest rate: r \u2248 0.65% monthly (7.8% annual)");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_3_id_placeholder_1");
    record2.set("content_body", "**Section 3: Competitive Pricing Strategies**\n\n1. Cost-Plus Pricing: Calculate all costs (equipment, financing, maintenance, overhead), add desired margin (2-5%), set price based on total cost + margin. Advantage: Ensures profitability. Disadvantage: May not be competitive\n\n2. Market-Based Pricing: Research competitor pricing, price at or below market rates, adjust for differentiation (service, terms, flexibility). Advantage: Competitive and market-driven. Disadvantage: May sacrifice margin\n\n3. Value-Based Pricing: Price based on value delivered to lessee, consider lessee's benefits (flexibility, predictability, technology), price higher for high-value propositions. Advantage: Captures value created. Disadvantage: Requires strong value communication\n\n4. Penetration Pricing: Price low to gain market share, build customer relationships for future business, increase prices after customer acquisition. Advantage: Rapid market penetration. Disadvantage: Lower initial margins\n\n5. Premium Pricing: Price high for premium service/quality, target high-end customers willing to pay more, emphasize superior service and support. Advantage: Higher margins. Disadvantage: Limited market size");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "lesson_3_id_placeholder_1");
    record3.set("content_body", "**Section 4: Case Study - Lease Pricing Calculation**\n\nCompany: EquipmentCorp (Lessor)\nSituation: Pricing a $500K manufacturing equipment lease\n\nCost Analysis:\n- Equipment cost: $500,000\n- Delivery and installation: $25,000\n- Setup and training: $10,000\n- Total capitalized cost: $535,000\n\nFinancing:\n- Cost of capital: 5.5% annual\n- Lessor's desired margin: 3%\n- Effective rate: 8.5% annual\n\nLease Terms:\n- Lease term: 60 months\n- Estimated residual value: $150,000 (28% of cost)\n- Full-service maintenance: $5,000/year\n\nCalculation:\n- PVA Factor at 8.5% for 60 months = 48.32\n- Base monthly payment = ($535,000 - $150,000) / 48.32 = $7,968\n- Maintenance allocation: $5,000 / 12 = $417/month\n- Total monthly payment: $7,968 + $417 = $8,385\n\nPricing Decision:\n- Monthly payment: $8,385\n- Total 5-year revenue: $8,385 \u00d7 60 = $503,100\n- Total costs: $535,000 + ($5,000 \u00d7 5) = $560,000\n- Profit: $503,100 - $560,000 = -$56,900 (Loss!)\n\nAdjustment:\n- Increase residual value assumption to $120,000\n- Recalculate: ($535,000 - $120,000) / 48.32 = $8,577\n- Add maintenance: $8,577 + $417 = $8,994\n- New total revenue: $8,994 \u00d7 60 = $539,640\n- New profit: $539,640 - $560,000 = -$20,360 (Still loss)\n\nFinal Adjustment:\n- Increase monthly payment to $9,500\n- Total revenue: $9,500 \u00d7 60 = $570,000\n- Profit: $570,000 - $560,000 = $10,000 (3.8% margin)\n- Final monthly payment: $9,500");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "lesson_4_id_placeholder_1");
    record4.set("content_body", "**Section 1: Key Financial Metrics**\n\n1. Internal Rate of Return (IRR): Discount rate where NPV of cash flows = 0, measures return on lessor's investment, higher IRR = better return, typical range: 8-15% for equipment leases. Formula: Solve for r where NPV = 0\n\n2. Net Present Value (NPV): Present value of all cash inflows minus outflows, positive NPV = profitable lease, negative NPV = unprofitable lease, discount rate = lessor's cost of capital. Formula: NPV = \u03a3(Cash Flow / (1 + r)^t) - Initial Investment\n\n3. Profitability Index: Ratio of PV of cash inflows to initial investment, PI > 1 = profitable, PI < 1 = unprofitable, useful for comparing leases. Formula: PI = PV of Cash Inflows / Initial Investment\n\n4. Return on Investment (ROI): Percentage return on capital invested, ROI = (Profit / Investment) \u00d7 100%, typical range: 3-8% for equipment leases, useful for comparing to other investments\n\n5. Payback Period: Time to recover initial investment, shorter payback = lower risk, typical range: 2-4 years for equipment leases. Formula: Payback Period = Initial Investment / Annual Cash Flow");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "lesson_4_id_placeholder_1");
    record5.set("content_body", "**Section 2: Lease Financial Analysis**\n\nExample: $100K Equipment Lease Analysis\n\nLease Terms:\n- Capitalized cost: $100,000\n- Monthly payment: $1,800\n- Lease term: 60 months\n- Residual value: $20,000\n- Maintenance cost: $200/month (lessor pays)\n- Insurance cost: $100/month (lessor pays)\n\nCash Flow Analysis:\n- Year 1: 12 \u00d7 $1,800 = $21,600 (revenue)\n- Year 1: 12 \u00d7 ($200 + $100) = $3,600 (costs)\n- Year 1: Net cash flow = $21,600 - $3,600 = $18,000\n\nTotal 5-Year Analysis:\n- Total revenue: $1,800 \u00d7 60 = $108,000\n- Total maintenance: $200 \u00d7 60 = $12,000\n- Total insurance: $100 \u00d7 60 = $6,000\n- Residual value: $20,000\n- Total cash inflows: $108,000 + $20,000 = $128,000\n- Total cash outflows: $100,000 + $12,000 + $6,000 = $118,000\n- Net profit: $128,000 - $118,000 = $10,000\n- ROI: ($10,000 / $100,000) \u00d7 100% = 10%\n- IRR: \u2248 8.5% (calculated using financial calculator)");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "lesson_4_id_placeholder_1");
    record6.set("content_body", "**Section 3: ROI Optimization Strategies**\n\n1. Increase Residual Value Assumption: Higher residual value = lower monthly payment needed, but increases risk if actual residual is lower, balance between profitability and risk. Example: Increase residual from $20K to $25K = lower payment, higher risk\n\n2. Reduce Operating Costs: Negotiate better maintenance contracts, reduce insurance costs through volume discounts, outsource maintenance to reduce overhead. Example: Reduce maintenance from $200 to $150/month = $3,000 savings over 5 years\n\n3. Increase Lease Payment: Higher payment = higher revenue, but may reduce competitiveness, balance between price and market demand. Example: Increase payment from $1,800 to $1,900 = $6,000 additional revenue\n\n4. Reduce Lease Term: Shorter term = higher monthly payment, reduces risk of obsolescence, allows faster equipment refresh. Example: 48-month lease vs. 60-month lease\n\n5. Optimize Portfolio Mix: Mix of high-margin and high-volume leases, balance risk across different equipment types, diversify across industries and customers. Example: 30% high-margin, 70% high-volume leases");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "lesson_4_id_placeholder_1");
    record7.set("content_body", "**Section 4: Case Study - ROI Optimization**\n\nCompany: LeaseCorp (Lessor)\nSituation: Optimizing lease portfolio for better returns\n\nCurrent Portfolio:\n- 100 leases averaging $1,500/month\n- Average lease term: 60 months\n- Average residual value: 25% of cost\n- Average operating costs: $300/month\n- Current average ROI: 6%\n- Current average IRR: 5.5%\n\nAnalysis:\n- Total monthly revenue: 100 \u00d7 $1,500 = $150,000\n- Total monthly costs: 100 \u00d7 $300 = $30,000\n- Monthly profit: $150,000 - $30,000 = $120,000\n- Annual profit: $120,000 \u00d7 12 = $1,440,000\n\nOptimization Strategies:\n\nStrategy 1: Increase Residual Value Assumptions\n- Current: 25% residual value\n- New: 28% residual value\n- Impact: Reduce monthly payment by $50\n- New monthly revenue: 100 \u00d7 $1,450 = $145,000\n- Problem: Revenue decreased, not optimal\n\nStrategy 2: Reduce Operating Costs\n- Current: $300/month per lease\n- New: $250/month per lease (negotiate better maintenance)\n- Impact: Save $50/month per lease\n- New monthly costs: 100 \u00d7 $250 = $25,000\n- New monthly profit: $150,000 - $25,000 = $125,000\n- Annual profit increase: $60,000\n\nStrategy 3: Increase Lease Payments\n- Current: $1,500/month\n- New: $1,550/month (market allows)\n- Impact: Increase revenue by $50/month per lease\n- New monthly revenue: 100 \u00d7 $1,550 = $155,000\n- New monthly profit: $155,000 - $30,000 = $125,000\n- Annual profit increase: $60,000\n\nStrategy 4: Optimize Portfolio Mix\n- Current: All similar leases\n- New: 30% premium leases at $1,800/month, 70% standard at $1,400/month\n- New monthly revenue: (30 \u00d7 $1,800) + (70 \u00d7 $1,400) = $54,000 + $98,000 = $152,000\n- New monthly profit: $152,000 - $30,000 = $122,000\n- Annual profit increase: $24,000\n\nRecommended Approach: Combine Strategies 2 & 3\n- Reduce operating costs by $50/month (Strategy 2)\n- Increase lease payments by $50/month (Strategy 3)\n- New monthly revenue: 100 \u00d7 $1,550 = $155,000\n- New monthly costs: 100 \u00d7 $250 = $25,000\n- New monthly profit: $155,000 - $25,000 = $130,000\n- Annual profit increase: $120,000 (8.3% improvement)\n- New ROI: 7.2% (up from 6%)\n- New IRR: 6.8% (up from 5.5%)");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "lesson_5_id_placeholder_1");
    record8.set("content_body", "**Section 1: Key Lease Risks**\n\n1. Credit Risk (Lessee Default): Risk of lessee unable to pay lease payments. Impact: Loss of revenue, repossession costs, residual value loss. Mitigation: Credit checks, personal guarantees, security deposits. Example: Lessee bankruptcy = loss of remaining payments\n\n2. Residual Value Risk: Risk of asset worth less than estimated at lease end. Impact: Loss on residual value, lower overall return. Mitigation: Conservative residual estimates, residual value insurance. Example: Technology becomes obsolete faster than expected\n\n3. Obsolescence Risk: Risk of asset becomes outdated before lease end. Impact: Reduced residual value, difficulty leasing similar assets. Mitigation: Shorter lease terms, upgrade options, technology monitoring. Example: IT equipment becomes obsolete in 3 years instead of 5\n\n4. Maintenance and Repair Risk: Risk of unexpected maintenance costs exceed estimates. Impact: Reduced profitability, cash flow issues. Mitigation: Detailed maintenance contracts, preventive maintenance, reserves. Example: Major equipment failure costs $50K to repair\n\n5. Market Risk: Risk of market conditions change, affecting lease demand. Impact: Difficulty leasing new equipment, pricing pressure. Mitigation: Diversification, market monitoring, flexible pricing. Example: Economic downturn reduces demand for leases\n\n6. Regulatory Risk: Risk of changes in accounting standards, tax laws, regulations. Impact: Changes to lease accounting, tax treatment, profitability. Mitigation: Legal review, compliance monitoring, flexibility in structures. Example: IFRS 16 changes require balance sheet recognition\n\n7. Operational Risk: Risk of internal processes fail, errors in lease management. Impact: Missed payments, compliance issues, customer disputes. Mitigation: Strong systems, training, quality control, audits. Example: Payment processing error causes late payment");
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("lesson_id", "lesson_5_id_placeholder_1");
    record9.set("content_body", "**Section 2: Risk Assessment Framework**\n\nRisk Assessment Matrix:\n\nCredit Risk: Probability High, Impact High, Risk Score 9, Mitigation: Credit checks, guarantees\nResidual Value: Probability Medium, Impact High, Risk Score 6, Mitigation: Conservative estimates\nObsolescence: Probability Medium, Impact Medium, Risk Score 4, Mitigation: Shorter terms, upgrades\nMaintenance: Probability Low, Impact Medium, Risk Score 2, Mitigation: Maintenance contracts\nMarket: Probability Medium, Impact Medium, Risk Score 4, Mitigation: Diversification\nRegulatory: Probability Low, Impact High, Risk Score 3, Mitigation: Legal review\nOperational: Probability Low, Impact Medium, Risk Score 2, Mitigation: Strong systems\n\nRisk Scoring: Probability (1-3) \u00d7 Impact (1-3) = Risk Score (1-9)\n- 7-9: High risk, requires mitigation\n- 4-6: Medium risk, monitor closely\n- 1-3: Low risk, standard controls");
  app.save(record9);

  const record10 = new Record(collection);
    record10.set("lesson_id", "lesson_5_id_placeholder_1");
    record10.set("content_body", "**Section 3: Risk Mitigation Strategies**\n\n1. Credit Risk Mitigation: Comprehensive credit analysis, personal or corporate guarantees, security deposits or letters of credit, regular financial monitoring, diversified customer base\n\n2. Residual Value Risk Mitigation: Conservative residual value estimates, residual value insurance, shorter lease terms, upgrade options, market monitoring\n\n3. Obsolescence Risk Mitigation: Shorter lease terms for technology, upgrade options built into lease, technology monitoring and forecasting, flexible lease structures, diversified equipment types\n\n4. Maintenance Risk Mitigation: Detailed maintenance contracts with fixed costs, preventive maintenance requirements, maintenance reserves, vendor relationships and negotiations, regular inspections and monitoring\n\n5. Market Risk Mitigation: Diversified customer base across industries, diversified equipment types, flexible pricing strategies, market monitoring and forecasting, hedging strategies\n\n6. Regulatory Risk Mitigation: Legal review of lease structures, compliance monitoring, flexibility in lease structures, professional advisors (legal, accounting), regular updates on regulatory changes\n\n7. Operational Risk Mitigation: Strong systems and processes, employee training and development, quality control and audits, segregation of duties, regular reviews and monitoring");
  app.save(record10);

  const record11 = new Record(collection);
    record11.set("lesson_id", "lesson_5_id_placeholder_1");
    record11.set("content_body", "**Section 4: Case Study - Risk Assessment and Mitigation**\n\nCompany: RiskCorp (Lessor)\nSituation: Assessing risks in new lease portfolio\n\nLease Details:\n- Equipment: Manufacturing equipment\n- Lessee: Small manufacturing company\n- Lease amount: $500,000\n- Lease term: 60 months\n- Residual value: $150,000 (30%)\n- Monthly payment: $6,500\n\nRisk Assessment:\n\n1. Credit Risk: Lessee is small company, 3 years in business, financial condition adequate but not strong, industry is manufacturing (cyclical). Risk score: 7 (High). Mitigation: Personal guarantee from owner, quarterly financial reviews\n\n2. Residual Value Risk: Equipment is manufacturing equipment (moderate obsolescence), market has stable secondary market, residual estimate 30% (reasonable). Risk score: 5 (Medium). Mitigation: Conservative estimate, residual value insurance\n\n3. Obsolescence Risk: Equipment is manufacturing equipment (5-10 year life), technology is stable, not rapidly changing, lease term 60 months (reasonable). Risk score: 3 (Low). Mitigation: Standard monitoring\n\n4. Maintenance Risk: Equipment is robust, well-established design, maintenance included in lease (lessor bears risk), estimated costs $300/month. Risk score: 4 (Medium). Mitigation: Detailed maintenance contract, preventive maintenance\n\n5. Market Risk: Industry is manufacturing (cyclical), market conditions currently stable, diversification is part of larger portfolio. Risk score: 4 (Medium). Mitigation: Diversified portfolio, market monitoring\n\nOverall Risk Assessment: Total risk score 23 (Medium-High). Recommendation: Proceed with mitigation strategies. Key mitigations: Personal guarantee, residual insurance, maintenance contract, quarterly reviews\n\nMitigation Plan:\n1. Obtain personal guarantee from owner\n2. Purchase residual value insurance\n3. Establish detailed maintenance contract with fixed costs\n4. Conduct quarterly financial reviews\n5. Monitor manufacturing industry conditions\n6. Maintain diversified portfolio");
  app.save(record11);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
