/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "<LESSON_2_1_ID>");
    record0.set("content_body", "**Section 1: Lease Valuation Fundamentals**\n\nWhat is Lease Valuation?\n- Determining economic value of lease\n- Present value of future cash flows\n- Discount rate selection\n- Example: $500K equipment lease = $450K present value\n\nValuation Components:\n\n1. Lease Payments:\n   - Fixed monthly/annual payments\n   - Variable payments (linked to index)\n   - Residual value guarantees\n   - Example: $10,000/month fixed + $500/month variable\n\n2. Discount Rate:\n   - Incremental borrowing rate\n   - Implicit rate (if known)\n   - Weighted average cost of capital (WACC)\n   - Example: 5% annual discount rate\n\n3. Lease Term:\n   - Non-cancellable period\n   - Renewal periods (if reasonably certain)\n   - Example: 5-year lease + 2-year renewal = 7-year term\n\n4. Residual Value:\n   - Equipment value at lease end\n   - Guaranteed vs. unguaranteed\n   - Example: $50,000 residual value guarantee\n\n**Section 2: Present Value Calculations**\n\nPresent Value Formula:\n- PV = FV / (1 + r)^n\n- FV = Future value\n- r = Discount rate\n- n = Number of periods\n- Example: $10,000 / (1.05)^1 = $9,524\n\nAnnuity Calculation:\n- PV = PMT \u00d7 [1 - (1 + r)^-n] / r\n- PMT = Payment amount\n- r = Discount rate\n- n = Number of periods\n- Example: $10,000 \u00d7 [1 - (1.05)^-60] / 0.05 = $432,328\n\nLease Liability Calculation:\n\nStep 1: Identify Lease Payments\n- Fixed payments: $10,000/month\n- Variable payments: $500/month\n- Total: $10,500/month\n- Example: 60 months \u00d7 $10,500 = $630,000 total\n\nStep 2: Identify Discount Rate\n- Incremental borrowing rate: 5% annual\n- Monthly rate: 0.4167%\n- Example: 5% / 12 = 0.4167%\n\nStep 3: Calculate PV of Lease Payments\n- Using annuity formula\n- PV = $10,500 \u00d7 [1 - (1.004167)^-60] / 0.004167\n- PV = $10,500 \u00d7 54.3 = $570,150\n- Example: $570,150 present value\n\nStep 4: Calculate PV of Residual Value\n- Residual value: $50,000\n- Discount factor: (1.05)^-5 = 0.7835\n- PV = $50,000 \u00d7 0.7835 = $39,175\n- Example: $39,175 present value\n\nStep 5: Total Lease Liability\n- PV of payments: $570,150\n- PV of residual: $39,175\n- Total: $609,325\n- Example: $609,325 lease liability");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "<LESSON_2_1_ID>");
    record1.set("content_body", "**Section 3: Valuation Methods**\n\nMethod 1: Net Present Value (NPV)\n\nDefinition:\n- Present value of all cash inflows minus outflows\n- Positive NPV = value creation\n- Example: NPV = $450,000 - $400,000 = $50,000\n\nCalculation:\n- NPV = \u03a3 [CF_t / (1 + r)^t] - Initial Investment\n- CF_t = Cash flow in period t\n- r = Discount rate\n- Example: NPV of lease = PV of benefits - PV of costs\n\nMethod 2: Internal Rate of Return (IRR)\n\nDefinition:\n- Discount rate where NPV = 0\n- Represents return on investment\n- Example: IRR = 8% means 8% annual return\n\nCalculation:\n- 0 = \u03a3 [CF_t / (1 + IRR)^t] - Initial Investment\n- Solve for IRR\n- Example: IRR of lease = 8%\n\nMethod 3: Profitability Index\n\nDefinition:\n- PV of future cash flows / Initial investment\n- Index > 1 = profitable\n- Example: $450,000 / $400,000 = 1.125\n\nCalculation:\n- PI = PV of Benefits / PV of Costs\n- Example: PI = $450,000 / $400,000 = 1.125\n\nMethod 4: Payback Period\n\nDefinition:\n- Time to recover initial investment\n- Shorter payback = better\n- Example: 3-year payback period\n\nCalculation:\n- Payback = Initial Investment / Annual Cash Flow\n- Example: $400,000 / $150,000 = 2.67 years\n\n**Section 4: Case Study - Lease Valuation**\n\nCompany: ValuationLeasing Inc.\nSituation: Valuing lease for financial reporting\n\nLease Details:\n- Equipment: Manufacturing equipment\n- Equipment cost: $500,000\n- Lease term: 5 years (60 months)\n- Monthly payment: $10,000\n- Residual value guarantee: $50,000\n- Incremental borrowing rate: 5% annual (0.4167% monthly)\n\nLease Liability Calculation:\n\nStep 1: PV of Lease Payments\n- Monthly payment: $10,000\n- Number of payments: 60\n- Monthly discount rate: 0.4167%\n- Annuity factor: [1 - (1.004167)^-60] / 0.004167 = 54.3\n- PV = $10,000 \u00d7 54.3 = $543,000\n\nStep 2: PV of Residual Value\n- Residual value: $50,000\n- Annual discount rate: 5%\n- Discount factor: (1.05)^-5 = 0.7835\n- PV = $50,000 \u00d7 0.7835 = $39,175\n\nStep 3: Total Lease Liability\n- PV of payments: $543,000\n- PV of residual: $39,175\n- Total: $582,175\n\nROU Asset Calculation:\n\nROU Asset = Lease Liability + Initial Direct Costs\n- Lease liability: $582,175\n- Initial direct costs: $5,000\n- ROU Asset: $587,175\n\nValuation Summary:\n- Lease Liability: $582,175\n- ROU Asset: $587,175\n- Equipment cost: $500,000\n- Valuation difference: $87,175 (includes residual value and initial costs)");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "<LESSON_2_2_ID>");
    record2.set("content_body", "**Section 1: Balance Sheet Impact**\n\nAssets:\n\nRight-of-Use Asset:\n- Recognized on balance sheet\n- Depreciated over lease term\n- Example: $500,000 ROU asset, depreciated over 5 years\n\nImpact on Asset Ratios:\n- Total assets increase\n- Asset turnover decreases\n- Return on assets decreases\n- Example: Total assets increase by $500,000\n\nLiabilities:\n\nLease Liability:\n- Recognized on balance sheet\n- Current and non-current portions\n- Example: $450,000 lease liability\n\nImpact on Liability Ratios:\n- Total liabilities increase\n- Debt-to-equity ratio increases\n- Current ratio decreases\n- Example: Total liabilities increase by $450,000\n\nEquity:\n\nNo Direct Impact:\n- Equity not directly affected by lease recognition\n- Indirectly affected through retained earnings\n- Example: Equity unchanged at lease commencement\n\n**Section 2: Income Statement Impact**\n\nDepreciation Expense:\n\nROU Asset Depreciation:\n- Straight-line depreciation over lease term\n- Example: $500,000 / 5 years = $100,000/year\n\nInterest Expense:\n\nLease Liability Interest:\n- Interest on outstanding lease liability\n- Decreases over time as liability decreases\n- Example: Year 1 interest = $22,500 (5% \u00d7 $450,000)\n\nTotal Lease Expense:\n\nTotal Expense = Depreciation + Interest\n- Year 1: $100,000 + $22,500 = $122,500\n- Example: Total lease expense\n\nImpact on Income:\n\nNet Income:\n- Decreases due to lease expense\n- Example: Net income decreases by $122,500\n\nEarnings Per Share (EPS):\n- Decreases due to lower net income\n- Example: EPS decreases by $0.50");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "<LESSON_2_2_ID>");
    record3.set("content_body", "**Section 3: Cash Flow Statement Impact**\n\nOperating Activities:\n\nLease Payments:\n- Classified as operating activity\n- Includes principal and interest\n- Example: $120,000 annual lease payment\n\nInterest Expense:\n- Included in operating activities\n- Example: $22,500 interest expense\n\nFinancing Activities:\n\nLease Liability Reduction:\n- Principal portion of lease payment\n- Classified as financing activity (some standards)\n- Example: $97,500 principal reduction\n\nInvesting Activities:\n\nNo Direct Impact:\n- ROU asset not classified as investing activity\n- Example: No impact on investing activities\n\n**Section 4: Case Study - Financial Statement Impact**\n\nCompany: ImpactLeasing Inc.\nSituation: Analyzing financial statement impact of lease\n\nLease Details:\n- Equipment: $500,000\n- Lease term: 5 years\n- Monthly payment: $10,000\n- Lease liability: $450,000\n- ROU asset: $500,000\n\nYear 1 Financial Statement Impact:\n\nBalance Sheet (at lease commencement):\n\nAssets:\n- ROU Asset: $500,000\n- Total Assets: +$500,000\n\nLiabilities:\n- Lease Liability (current): $97,500\n- Lease Liability (non-current): $352,500\n- Total Liabilities: +$450,000\n\nEquity:\n- No change at commencement\n\nIncome Statement (Year 1):\n\nDepreciation Expense: $100,000\nInterest Expense: $22,500\nTotal Lease Expense: $122,500\n\nNet Income Impact: -$122,500\n\nCash Flow Statement (Year 1):\n\nOperating Activities:\n- Lease payments: -$120,000\n- Interest expense: -$22,500\n- Total: -$142,500\n\nFinancing Activities:\n- Lease liability reduction: -$97,500\n\nFinancial Ratios Impact:\n\nBefore Lease:\n- Total assets: $1,000,000\n- Total liabilities: $500,000\n- Equity: $500,000\n- Debt-to-equity: 1.0\n- Current ratio: 2.0\n\nAfter Lease (Year 1):\n- Total assets: $1,500,000\n- Total liabilities: $950,000\n- Equity: $500,000\n- Debt-to-equity: 1.9\n- Current ratio: 1.5\n\nImpact:\n- Debt-to-equity increases from 1.0 to 1.9 (90% increase)\n- Current ratio decreases from 2.0 to 1.5 (25% decrease)\n- Asset turnover decreases (more assets, same revenue)");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "<LESSON_2_3_ID>");
    record4.set("content_body", "**Section 1: Lease vs. Buy Analysis Framework**\n\nWhat is Lease vs. Buy Analysis?\n- Comparing financial impact of leasing vs. buying\n- Determining most cost-effective option\n- Considering financial and operational factors\n- Example: Lease $500K equipment vs. buy with financing\n\nAnalysis Components:\n\n1. Equipment Cost:\n   - Purchase price if buying\n   - Lease payments if leasing\n   - Example: $500K purchase vs. $10K/month lease\n\n2. Financing Cost:\n   - Interest on borrowed funds (if buying)\n   - Implicit rate in lease\n   - Example: 5% interest on $500K = $25K/year\n\n3. Operating Costs:\n   - Maintenance, insurance, taxes\n   - Included in lease or paid separately\n   - Example: $5K/year maintenance if buying\n\n4. Tax Benefits:\n   - Depreciation deduction (if buying)\n   - Lease payment deduction (if leasing)\n   - Example: 30% tax rate \u00d7 $100K deduction = $30K tax savings\n\n5. Residual Value:\n   - Equipment value at end (if buying)\n   - Reduces net cost\n   - Example: $100K residual value\n\n6. Time Value of Money:\n   - Discount future cash flows\n   - Present value comparison\n   - Example: Discount at 5% rate\n\n**Section 2: Lease vs. Buy Calculation**\n\nLease Option Analysis:\n\nCosts:\n- Monthly lease payment: $10,000\n- Total lease payments (60 months): $600,000\n- Initial direct costs: $5,000\n- Total lease cost: $605,000\n\nTax Benefits:\n- Lease payments are tax deductible\n- Tax rate: 30%\n- Tax savings: $605,000 \u00d7 30% = $181,500\n- Net lease cost: $605,000 - $181,500 = $423,500\n\nBuy Option Analysis:\n\nCosts:\n- Equipment purchase: $500,000\n- Financing cost (5% annual): $125,000\n- Maintenance (5 years): $25,000\n- Insurance (5 years): $10,000\n- Total cost: $660,000\n\nBenefits:\n- Residual value: $100,000\n- Depreciation tax deduction: $100,000/year \u00d7 30% = $30,000/year \u00d7 5 = $150,000\n- Net cost: $660,000 - $100,000 - $150,000 = $410,000\n\nComparison:\n- Lease cost: $423,500\n- Buy cost: $410,000\n- Difference: $13,500 (buy is cheaper)\n- Decision: Buy is more cost-effective");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "<LESSON_2_3_ID>");
    record5.set("content_body", "**Section 3: Case Study - Lease vs. Buy Analysis**\n\nCompany: DecisionLeasing Inc.\nSituation: Deciding whether to lease or buy manufacturing equipment\n\nEquipment Details:\n- Equipment: Manufacturing equipment\n- Equipment cost: $500,000\n- Equipment useful life: 7 years\n- Lease term: 5 years\n- Monthly lease payment: $10,000\n- Residual value (if buying): $150,000\n- Tax rate: 30%\n- Discount rate: 5%\n\nLease Option:\n\nCosts:\n- Monthly payment: $10,000\n- Total payments (60 months): $600,000\n- Initial direct costs: $5,000\n- Total cost: $605,000\n\nTax Benefits:\n- Lease payments deductible: $600,000\n- Tax savings: $600,000 \u00d7 30% = $180,000\n\nNet Lease Cost:\n- Total cost: $605,000\n- Tax savings: -$180,000\n- Net cost: $425,000\n\nBuy Option:\n\nCosts:\n- Equipment purchase: $500,000\n- Financing (5% annual on $500K): $125,000\n- Maintenance (5 years): $25,000\n- Insurance (5 years): $10,000\n- Total cost: $660,000\n\nBenefits:\n- Residual value: $150,000\n- Depreciation (straight-line): $500,000 / 7 = $71,429/year\n- Depreciation tax deduction: $71,429 \u00d7 30% = $21,429/year \u00d7 5 = $107,145\n- Total benefits: $150,000 + $107,145 = $257,145\n\nNet Buy Cost:\n- Total cost: $660,000\n- Total benefits: -$257,145\n- Net cost: $402,855\n\nComparison:\n- Lease cost: $425,000\n- Buy cost: $402,855\n- Savings with buy: $22,145 (5.2% lower cost)\n- Decision: Buy is more cost-effective\n\nQualitative Factors:\n\nLease Advantages:\n- No maintenance burden\n- Flexibility to upgrade\n- Off-balance sheet (under old standards)\n- Predictable costs\n- Example: No surprise maintenance costs\n\nBuy Advantages:\n- Full ownership\n- No usage restrictions\n- Potential residual value gain\n- Long-term cost savings\n- Example: Can modify equipment as needed\n\nFinal Recommendation:\n- Financial: Buy is $22,145 cheaper (5.2% savings)\n- Operational: Lease provides more flexibility\n- Strategic: Buy provides ownership and control\n- Decision: Buy is recommended based on financial analysis");
  app.save(record5);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
