/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_lesson_1");
    record0.set("content_body", "<h2>Understanding the Shift from Ownership to Access</h2><p>In today's dynamic business environment, companies are increasingly moving away from traditional asset ownership toward an access-based model. This fundamental shift is driven by several key factors:</p><ul><li><strong>Capital Efficiency:</strong> Leasing preserves capital that can be deployed for core business operations and growth initiatives.</li><li><strong>Flexibility:</strong> Businesses can upgrade or change assets as their needs evolve without being locked into long-term ownership.</li><li><strong>Risk Transfer:</strong> Lessors assume the risk of asset obsolescence and residual value, protecting lessees from technological changes.</li><li><strong>Operational Focus:</strong> Companies can focus on their core competencies rather than asset management.</li></ul><p>This shift represents a fundamental change in how businesses think about asset utilization and financial management.</p>");
    record0.set("video_url", "https://example.com/videos/lesson1-ownership-to-access.mp4");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "pbc_lesson_2");
    record1.set("content_body", "<h2>Lessor vs. Lessee and Key Terminology</h2><p>Understanding the key players and terminology in leasing is essential:</p><h3>Key Parties:</h3><ul><li><strong>Lessor:</strong> The owner of the asset who grants the right to use it. Typically a financial institution or equipment company.</li><li><strong>Lessee:</strong> The party who uses the asset under the lease agreement. Pays periodic lease payments.</li></ul><h3>Essential Terms:</h3><ul><li><strong>Lease Term:</strong> The period during which the lessee has the right to use the asset.</li><li><strong>Lease Payment:</strong> The periodic payment made by the lessee to the lessor.</li><li><strong>Residual Value:</strong> The estimated value of the asset at the end of the lease term.</li><li><strong>Incremental Borrowing Rate:</strong> The rate used to discount future lease payments.</li><li><strong>Right-of-Use (ROU) Asset:</strong> The lessee's right to use the underlying asset during the lease term.</li></ul>");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "pbc_lesson_3");
    record2.set("content_body", "<h2>Understanding Leasable Assets</h2><p>A wide variety of assets can be leased in today's marketplace:</p><h3>Common Leasable Assets:</h3><ul><li><strong>Equipment:</strong> Manufacturing equipment, IT hardware, medical devices, construction machinery</li><li><strong>Vehicles:</strong> Cars, trucks, commercial vehicles, fleet management</li><li><strong>Real Estate:</strong> Office space, retail locations, warehouses, industrial facilities</li><li><strong>Technology:</strong> Software licenses, cloud infrastructure, telecommunications equipment</li><li><strong>Specialized Assets:</strong> Aircraft, ships, rail cars, renewable energy equipment</li></ul><h3>Asset Characteristics:</h3><p>Leasable assets typically have:</p><ul><li>Identifiable physical or digital form</li><li>Determinable useful life</li><li>Measurable residual value</li><li>Clear ownership and control mechanisms</li><li>Established market for leasing</li></ul>");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "pbc_lesson_4");
    record3.set("content_body", "<h2>From Application to End of Life (EOL) Options</h2><p>The complete lifecycle of a lease involves several critical stages:</p><h3>Lease Lifecycle Stages:</h3><ol><li><strong>Application & Approval:</strong> Lessee submits application, lessor conducts credit analysis and asset evaluation</li><li><strong>Documentation:</strong> Legal agreements, insurance requirements, and compliance documentation</li><li><strong>Asset Delivery:</strong> Physical delivery and setup of the leased asset</li><li><strong>Active Lease Period:</strong> Regular lease payments, maintenance, and operational use</li><li><strong>End of Life (EOL) Options:</strong> At lease termination, several options are available</li></ol><h3>EOL Options:</h3><ul><li><strong>Return:</strong> Asset returned to lessor in agreed condition</li><li><strong>Renewal:</strong> Extend the lease for an additional term</li><li><strong>Purchase:</strong> Lessee exercises buyout option to purchase the asset</li><li><strong>Upgrade:</strong> Trade in for newer equipment with new lease</li></ul>");
    record3.set("video_url", "https://example.com/videos/lesson4-application-to-eol.mp4");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "pbc_lesson_5");
    record4.set("content_body", "<h2>Comparative Analysis of Cash Flow and Ownership</h2><p>Understanding the financial implications of leasing versus buying is crucial for decision-making:</p><h3>Leasing Advantages:</h3><ul><li>Lower upfront capital requirements</li><li>Predictable monthly expenses</li><li>Off-balance-sheet treatment (under certain conditions)</li><li>Flexibility to upgrade or change assets</li><li>Reduced maintenance and repair costs</li></ul><h3>Buying Advantages:</h3><ul><li>Full ownership and control</li><li>No ongoing lease payments after purchase</li><li>Potential tax depreciation benefits</li><li>Ability to customize the asset</li><li>Long-term cost savings for extended use</li></ul><h3>Financial Comparison:</h3><p>A comprehensive Total Cost of Ownership (TCO) analysis should include:</p><ul><li>Purchase price vs. total lease payments</li><li>Financing costs and interest rates</li><li>Maintenance and repair expenses</li><li>Insurance and registration costs</li><li>Residual value and salvage value</li><li>Tax implications and depreciation benefits</li></ul>");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "pbc_lesson_6");
    record5.set("content_body", "<h2>High Flexibility, Short-Term, Asset Returned at End</h2><p>Operating leases represent the most flexible leasing arrangement:</p><h3>Operating Lease Characteristics:</h3><ul><li><strong>Short-Term Duration:</strong> Typically 1-3 years, much shorter than the asset's useful life</li><li><strong>High Flexibility:</strong> Easy to upgrade, change, or terminate</li><li><strong>Asset Return:</strong> Asset is returned to lessor at end of term in agreed condition</li><li><strong>Lessor Retains Ownership:</strong> Lessor maintains ownership and bears residual value risk</li><li><strong>Maintenance Included:</strong> Often includes maintenance and support services</li></ul><h3>Ideal Use Cases:</h3><ul><li>Technology equipment that becomes obsolete quickly</li><li>Vehicles for short-term projects or seasonal needs</li><li>Equipment for temporary operations or expansion</li><li>Businesses wanting maximum flexibility and minimal commitment</li></ul><h3>Financial Impact:</h3><p>Operating leases provide the most favorable cash flow characteristics with lower monthly payments and minimal long-term obligations.</p>");
    record5.set("video_url", "https://example.com/videos/lesson6-operating-lease.mp4");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "pbc_lesson_7");
    record6.set("content_body", "<h2>Long-Term, Path to Ownership, Transfer of Risk</h2><p>Capital leases (or finance leases) represent a different approach to asset acquisition:</p><h3>Capital Lease Characteristics:</h3><ul><li><strong>Long-Term Duration:</strong> Typically 70-90% of the asset's useful life</li><li><strong>Ownership Transfer:</strong> Lease includes a buyout option or automatic ownership transfer</li><li><strong>Risk Transfer:</strong> Lessee assumes most risks and rewards of ownership</li><li><strong>Lessee Responsibility:</strong> Lessee responsible for maintenance, insurance, and repairs</li><li><strong>Balance Sheet Impact:</strong> Recorded as an asset and liability on the balance sheet</li></ul><h3>Ideal Use Cases:</h3><ul><li>Core business equipment with long useful life</li><li>Assets where ownership is desired at end of term</li><li>Situations where tax depreciation benefits are valuable</li><li>Long-term operational needs</li></ul><h3>Financial Implications:</h3><p>Capital leases result in higher monthly payments but provide a clear path to ownership and potential long-term cost savings.</p>");
    record6.set("video_url", "https://example.com/videos/lesson7-capital-lease.mp4");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "pbc_lesson_8");
    record7.set("content_body", "<h2>Unlocking Capital from Assets You Already Own</h2><p>Sale-leaseback transactions provide a powerful financial strategy:</p><h3>Sale-Leaseback Overview:</h3><p>A sale-leaseback is a transaction where a company sells an asset it owns to a lessor and then leases it back for continued use.</p><h3>Key Benefits:</h3><ul><li><strong>Immediate Capital:</strong> Converts owned assets into cash for business needs</li><li><strong>Improved Liquidity:</strong> Frees up capital tied up in assets</li><li><strong>Balance Sheet Optimization:</strong> Reduces asset base while maintaining operational use</li><li><strong>Tax Efficiency:</strong> Potential tax benefits from lease payments</li><li><strong>Continued Operations:</strong> Business continues using the asset without disruption</li></ul><h3>Common Applications:</h3><ul><li>Real estate (buildings, facilities)</li><li>Equipment and machinery</li><li>Fleet vehicles</li><li>Technology infrastructure</li></ul><h3>Considerations:</h3><p>While sale-leasebacks provide immediate capital, companies should carefully evaluate the long-term cost implications and ensure the transaction aligns with strategic objectives.</p>");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "pbc_lesson_9");
    record8.set("content_body", "<h2>Managing Multiple Assets Under One Contract</h2><p>Portfolio leasing and multi-asset agreements offer significant advantages:</p><h3>Portfolio Leasing Benefits:</h3><ul><li><strong>Simplified Administration:</strong> Single contract for multiple assets reduces paperwork and complexity</li><li><strong>Consolidated Billing:</strong> One invoice for all leased assets simplifies accounting</li><li><strong>Flexible Terms:</strong> Different assets can have different terms within one agreement</li><li><strong>Better Pricing:</strong> Larger portfolios often qualify for better rates and terms</li><li><strong>Easier Upgrades:</strong> Manage asset lifecycle across the entire portfolio</li></ul><h3>Portfolio Management Strategies:</h3><ul><li><strong>Asset Categorization:</strong> Group similar assets for easier tracking</li><li><strong>Staggered Renewals:</strong> Spread lease expirations to manage cash flow</li><li><strong>Centralized Reporting:</strong> Consolidated reporting on all leased assets</li><li><strong>Vendor Consolidation:</strong> Work with fewer lessors for better relationships</li></ul><h3>Implementation Considerations:</h3><p>Effective portfolio management requires clear documentation, regular reviews, and proactive communication with lessors to ensure optimal outcomes.</p>");
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("lesson_id", "pbc_lesson_10");
    record9.set("content_body", "<h2>Understanding Interest Rates, Residuals, and Total Cost of Ownership</h2><p>The financial mechanics of leasing involve several critical components:</p><h3>Interest Rates in Leasing:</h3><ul><li><strong>Implicit Rate:</strong> The rate built into the lease payment calculation</li><li><strong>Incremental Borrowing Rate:</strong> The rate used for accounting purposes under IFRS 16/ASC 842</li><li><strong>Market Rates:</strong> Influenced by credit quality, asset type, and market conditions</li><li><strong>Rate Components:</strong> Base rate + credit spread + lessor margin</li></ul><h3>Residual Value:</h3><ul><li><strong>Definition:</strong> Estimated value of the asset at end of lease term</li><li><strong>Importance:</strong> Directly impacts lease payment calculations</li><li><strong>Risk:</strong> Lessor bears residual value risk in operating leases</li><li><strong>Estimation:</strong> Based on historical data, market trends, and asset condition</li></ul><h3>Total Cost of Ownership (TCO):</h3><p>TCO analysis includes:</p><ul><li>All lease payments over the term</li><li>Maintenance and repair costs</li><li>Insurance and registration</li><li>Taxes and compliance costs</li><li>Residual value (for purchase scenarios)</li><li>Opportunity cost of capital</li></ul>");
  app.save(record9);

  const record10 = new Record(collection);
    record10.set("lesson_id", "pbc_lesson_11");
    record10.set("content_body", "<h2>What Global Lessors Look For in a Lessee</h2><p>Understanding lessor requirements is essential for successful lease applications:</p><h3>Credit Analysis:</h3><ul><li><strong>Financial Statements:</strong> Audited or reviewed financial statements for analysis</li><li><strong>Credit Score:</strong> Personal or business credit rating</li><li><strong>Payment History:</strong> Track record of timely payments</li><li><strong>Debt Ratios:</strong> Leverage and debt service coverage ratios</li><li><strong>Cash Flow:</strong> Ability to make lease payments from operations</li></ul><h3>Business Stability:</h3><ul><li>Industry and market position</li><li>Management experience and stability</li><li>Business plan and growth prospects</li><li>Customer concentration and diversification</li><li>Competitive advantages</li></ul><h3>Operational Factors:</h3><ul><li>Asset utilization and maintenance practices</li><li>Insurance coverage and risk management</li><li>Compliance with regulations</li><li>References from other lessors</li><li>Collateral and guarantees</li></ul><h3>Documentation Requirements:</h3><p>Lessors typically require comprehensive documentation to assess risk and make informed lending decisions.</p>");
    record10.set("video_url", "https://example.com/videos/lesson11-lessor-requirements.mp4");
  app.save(record10);

  const record11 = new Record(collection);
    record11.set("lesson_id", "pbc_lesson_12");
    record11.set("content_body", "<h2>How Leases Appear on Balance Sheets</h2><p>Modern accounting standards require comprehensive lease disclosure:</p><h3>IFRS 16 and ASC 842 Requirements:</h3><ul><li><strong>Right-of-Use (ROU) Asset:</strong> Recognized on the balance sheet as an asset</li><li><strong>Lease Liability:</strong> Recognized as a liability for future lease payments</li><li><strong>Depreciation:</strong> ROU asset is depreciated over the lease term</li><li><strong>Interest Expense:</strong> Lease liability accrues interest expense</li></ul><h3>Balance Sheet Impact:</h3><ul><li>Assets increase (ROU asset)</li><li>Liabilities increase (lease liability)</li><li>Equity may be affected by net income impact</li><li>Key ratios affected: debt-to-equity, asset turnover, ROA</li></ul><h3>Income Statement Impact:</h3><ul><li>Depreciation expense (ROU asset)</li><li>Interest expense (lease liability)</li><li>Total expense similar to operating lease under old standards</li></ul><h3>Disclosure Requirements:</h3><p>Companies must disclose:</p><ul><li>Lease payment schedules</li><li>Weighted average discount rates</li><li>Future minimum lease payments</li><li>Lease-related assets and liabilities</li><li>Lease expense by type</li></ul>");
  app.save(record11);

  const record12 = new Record(collection);
    record12.set("lesson_id", "pbc_lesson_13");
    record12.set("content_body", "<h2>Who is Responsible for What?</h2><p>Clear allocation of responsibilities is critical in lease agreements:</p><h3>Lessor Responsibilities:</h3><ul><li>Ownership and legal title to the asset</li><li>Residual value risk (in operating leases)</li><li>Major structural repairs and replacements</li><li>Property taxes (in some jurisdictions)</li><li>Insurance (in some lease structures)</li></ul><h3>Lessee Responsibilities:</h3><ul><li>Regular maintenance and minor repairs</li><li>Operational use and care of the asset</li><li>Insurance (in most lease structures)</li><li>Timely lease payments</li><li>Compliance with lease terms</li><li>Return of asset in agreed condition</li></ul><h3>Shared Responsibilities:</h3><ul><li>Regulatory compliance</li><li>Environmental compliance</li><li>Safety and security</li><li>Documentation and record-keeping</li></ul><h3>Dispute Resolution:</h3><p>Lease agreements should clearly specify:</p><ul><li>Maintenance standards and schedules</li><li>Condition assessment procedures</li><li>Damage and wear assessment</li><li>Dispute resolution mechanisms</li><li>Remedies for breach</li></ul>");
  app.save(record12);

  const record13 = new Record(collection);
    record13.set("lesson_id", "pbc_lesson_14");
    record13.set("content_body", "<h2>Filtering by Asset Type, Region, and Vendor</h2><p>The global leasing platform provides sophisticated filtering capabilities:</p><h3>Asset Type Filtering:</h3><ul><li><strong>Equipment Categories:</strong> Manufacturing, IT, medical, construction, etc.</li><li><strong>Asset Specifications:</strong> Size, capacity, features, and capabilities</li><li><strong>Condition:</strong> New, refurbished, or used assets</li><li><strong>Availability:</strong> In-stock or made-to-order options</li></ul><h3>Regional Considerations:</h3><ul><li><strong>Geographic Availability:</strong> Assets available in specific regions</li><li><strong>Local Regulations:</strong> Compliance with regional requirements</li><li><strong>Currency:</strong> Lease payments in local or foreign currency</li><li><strong>Shipping and Logistics:</strong> Delivery options and timelines</li><li><strong>Local Support:</strong> Maintenance and service availability</li></ul><h3>Vendor Selection:</h3><ul><li>Lessor reputation and track record</li><li>Pricing competitiveness</li><li>Service quality and responsiveness</li><li>Financial stability</li><li>Specialization in asset type</li><li>Geographic coverage</li></ul><h3>Platform Features:</h3><p>The platform enables efficient comparison of options across multiple vendors and regions to find the best fit for your needs.</p>");
  app.save(record13);

  const record14 = new Record(collection);
    record14.set("lesson_id", "pbc_lesson_15");
    record14.set("content_body", "<h2>Documentation Requirements (KYC/KYB)</h2><p>Proper documentation is essential for lease approval:</p><h3>Know Your Customer (KYC) - Individual Lessees:</h3><ul><li>Government-issued identification</li><li>Proof of address</li><li>Personal financial statements</li><li>Credit authorization</li><li>Tax identification number</li></ul><h3>Know Your Business (KYB) - Corporate Lessees:</h3><ul><li>Business registration and incorporation documents</li><li>Articles of incorporation or bylaws</li><li>Ownership and organizational structure</li><li>Financial statements (audited or reviewed)</li><li>Tax returns (typically 2-3 years)</li><li>Business licenses and permits</li><li>Beneficial ownership documentation</li></ul><h3>Additional Documentation:</h3><ul><li>Bank references</li><li>Trade references</li><li>Insurance certificates</li><li>Lease agreement and terms</li><li>Collateral documentation</li><li>Personal guarantees (if required)</li></ul><h3>Compliance Standards:</h3><p>Documentation requirements comply with:</p><ul><li>Anti-Money Laundering (AML) regulations</li><li>Know Your Customer (KYC) requirements</li><li>Sanctions screening</li><li>Beneficial ownership identification</li><li>Local regulatory requirements</li></ul>");
    record14.set("video_url", "https://example.com/videos/lesson15-kyc-kyb.mp4");
  app.save(record14);

  const record15 = new Record(collection);
    record15.set("lesson_id", "pbc_lesson_16");
    record15.set("content_body", "<h2>How the Platform Streamlines the Closing Process</h2><p>The global leasing platform automates and simplifies lease closing:</p><h3>Platform Features:</h3><ul><li><strong>Digital Documentation:</strong> Upload and manage all documents in one place</li><li><strong>Automated Verification:</strong> Real-time verification of documents and information</li><li><strong>E-Signature Integration:</strong> Secure digital signing of agreements</li><li><strong>Workflow Management:</strong> Automated routing and approval workflows</li><li><strong>Status Tracking:</strong> Real-time visibility into application status</li></ul><h3>Closing Process Steps:</h3><ol><li>Application submission with required documentation</li><li>Automated document verification and validation</li><li>Credit analysis and approval decision</li><li>Lease agreement generation and review</li><li>Digital signature and execution</li><li>Final approval and funding</li><li>Asset delivery coordination</li></ol><h3>Time Savings:</h3><ul><li>Reduced manual processing</li><li>Faster document review</li><li>Quicker approval decisions</li><li>Streamlined communication</li><li>Automated compliance checks</li></ul><h3>Benefits:</h3><p>The platform reduces closing time from weeks to days, improving efficiency for both lessees and lessors.</p>");
  app.save(record15);

  const record16 = new Record(collection);
    record16.set("lesson_id", "pbc_lesson_17");
    record16.set("content_body", "<h2>Dealing with Different Currencies and Jurisdictions</h2><p>Global leasing involves navigating multiple currencies and legal systems:</p><h3>Currency Considerations:</h3><ul><li><strong>Currency Selection:</strong> Lease payments in lessor's currency or lessee's local currency</li><li><strong>Exchange Rate Risk:</strong> Exposure to currency fluctuations</li><li><strong>Hedging Options:</strong> Forward contracts and currency swaps</li><li><strong>Payment Mechanisms:</strong> International wire transfers and settlement</li><li><strong>Reporting:</strong> Multi-currency accounting and consolidation</li></ul><h3>Jurisdictional Issues:</h3><ul><li><strong>Governing Law:</strong> Which jurisdiction's laws apply to the lease</li><li><strong>Tax Treatment:</strong> Different tax implications in different jurisdictions</li><li><strong>Regulatory Compliance:</strong> Local regulations and requirements</li><li><strong>Dispute Resolution:</strong> Arbitration vs. litigation in different venues</li><li><strong>Enforcement:</strong> Ability to enforce lease terms across borders</li></ul><h3>Cross-Border Leasing:</h3><ul><li>Import/export regulations</li><li>Tariffs and duties</li><li>Local content requirements</li><li>Sanctions and trade restrictions</li><li>Insurance and liability coverage</li></ul><h3>Best Practices:</h3><p>When engaging in global leasing:</p><ul><li>Clearly specify currency and payment terms</li><li>Understand local tax implications</li><li>Ensure compliance with all applicable regulations</li><li>Use experienced legal counsel in relevant jurisdictions</li><li>Consider currency hedging strategies</li><li>Maintain clear documentation of all transactions</li></ul>");
  app.save(record16);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
