/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "Practical Implementation");
    record0.set("content_body", "Journal Entries for Lease Recognition: Initial recognition entries record the ROU asset and lease liability at the present value of lease payments. Subsequent measurement entries adjust for depreciation and interest. Lease modification entries remeasure both the ROU asset and lease liability.\n\nFinancial Statement Presentation: Balance sheet presentation of ROU assets and lease liabilities with separate classification of current and non-current portions. Income statement presentation of lease expense including depreciation of ROU asset and interest expense on lease liability. Cash flow statement treatment splits lease payments between operating activities (interest portion) and financing activities (principal portion).\n\nBalance Sheet Impact: ROU asset classification as non-current assets. Lease liability classification with current and non-current portions. Impact on financial ratios including debt-to-equity ratio and asset turnover ratio.\n\nIncome Statement Impact: Lease expense recognition patterns differ between operating and finance leases. Depreciation of ROU asset is recognized over the lease term. Interest expense on lease liability decreases over time. Total expense over the lease term remains consistent.\n\nCash Flow Statement Treatment: Operating activities include the interest portion of lease payments. Financing activities include the principal portion of lease payments. Impact on free cash flow calculations must account for the split treatment.\n\nTransition Guidance: Transition from old lease accounting standards requires cumulative catch-up adjustments. Restatement of prior periods may be necessary. Disclosure of transition impacts is required.\n\nImplementation Timeline: Key dates for adoption must be identified. Phased implementation approach should be planned. System and process changes required for proper accounting.\n\nCommon Pitfalls: Lease identification errors can result in missed leases. Incorrect lease term determination affects the ROU asset and liability amounts. Improper discount rate selection impacts present value calculations. Lease modification accounting mistakes can lead to incorrect adjustments. Inadequate disclosures fail to meet regulatory requirements.\n\nCase Studies: Real-world examples of lease accounting implementation including equipment lease scenarios, real estate lease scenarios, and complex lease arrangements with multiple components.");
  app.save(record0);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
