/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_3963162141");
    record0.set("content_body", "IFRS 16 Fundamentals - Comprehensive Guide\n\n1. LEASE DEFINITION UNDER IFRS 16\n- A contract that conveys the right to use an identified asset for a period of time in exchange for consideration\n- Key elements: identified asset, right to control use, period of time, consideration\n- Applies to all leases except short-term leases (\u226412 months) and low-value assets\n\n2. RECOGNITION CRITERIA\n- Lessee recognizes right-of-use (ROU) asset and lease liability at lease commencement\n- Lessor classifies lease as finance or operating lease\n- Recognition triggers: lease commencement date when asset is available for use\n\n3. RIGHT-OF-USE ASSETS\n- Measured at cost: lease liability + initial direct costs + prepaid lease payments - incentives received\n- Represents lessee's right to use the underlying asset\n- Depreciated over lease term or asset useful life, whichever is shorter\n- Subject to impairment testing\n\n4. LEASE LIABILITIES\n- Present value of lease payments discounted at lease incremental borrowing rate\n- Includes: fixed payments, variable payments linked to index/rate, residual value guarantees, termination penalties\n- Remeasured when lease modifications occur\n\n5. INITIAL MEASUREMENT\n- ROU Asset = Lease Liability + Initial Direct Costs + Prepaid Lease Payments - Lease Incentives\n- Lease Liability = PV of (Fixed Payments + Variable Payments + Residual Guarantees + Termination Penalties)\n- Discount Rate: Incremental borrowing rate (rate lessee would pay to borrow funds)\n\n6. SUBSEQUENT MEASUREMENT\n- ROU Asset: Depreciated on straight-line basis over lease term\n- Lease Liability: Accreted using effective interest method, reduced by lease payments\n- Remeasurement required for: lease modifications, changes in lease term, changes in residual value guarantees\n\n7. LEASE MODIFICATIONS\n- Accounted for as separate lease if: increases scope and consideration reflects standalone price\n- Otherwise: remeasure ROU asset and lease liability\n- Adjustment to ROU asset: increase/decrease based on modification impact\n- Common modifications: extension options exercised, payment term changes, asset substitutions");
  app.save(record0);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
