/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_1_1");
    record0.set("content_body", "# What is Leasing and Why It Matters\n\n## Section 1: What is Leasing?\n\n### Definition\nLeasing is an agreement to use equipment for a specified period. The lessor (owner) retains legal title to the equipment while the lessee (user) has the right to use it. For example, renting a car for a week is a simple form of leasing.\n\n### Key Elements\n- **Lessor**: The owner of the equipment\n- **Lessee**: The user of the equipment\n- **Equipment**: The asset being leased\n- **Time Period**: The duration of the lease\n- **Payment Amount**: The agreed-upon lease payment\n\nExample: A car rental agreement includes all these elements - the rental company (lessor) owns the car, you (lessee) use it, for a specified period, at an agreed price.\n\n### Simple Analogy\nLeasing is like renting an apartment:\n- You use the apartment but don't own it\n- You pay monthly rent to the landlord\n- The landlord maintains the property\n- You can move out when the lease ends\n\nSimilarly, with equipment leasing, you use the equipment but don't own it, pay monthly payments, the lessor maintains it, and you can return it when the lease ends.\n\n## Section 2: Why Leasing Matters\n\n### Reason 1: Access Without Ownership\nLeasing allows you to use equipment without the burden of ownership. You get the benefits of using the equipment without the responsibilities of owning it.\n\n**Example**: Use the latest technology without owning it. A software company can lease high-performance computers instead of buying them.\n\n### Reason 2: Cost Savings\nLeasing typically has lower upfront costs compared to purchasing. You pay predictable monthly payments instead of a large capital investment.\n\n**Example**: A $500/month lease vs. a $10,000 purchase. Over 2 years, the lease costs $12,000 but preserves your $10,000 capital.\n\n### Reason 3: Flexibility\nLeasing provides flexibility to upgrade or change equipment as your business needs evolve. You're not locked into outdated equipment.\n\n**Example**: As your business grows, you can upgrade to larger or more advanced equipment without the hassle of selling old equipment.\n\n### Reason 4: Business Growth\nBy leasing instead of buying, you preserve capital that can be invested in business growth and expansion.\n\n**Example**: A startup can expand operations quickly by leasing equipment instead of spending all capital on purchases.\n\n### Reason 5: Technology Access\nLeasing ensures you always have access to the latest technology without the risk of equipment becoming obsolete.\n\n**Example**: Lease the newest manufacturing equipment to stay competitive without owning outdated machinery.\n\n### Reason 6: Operational Simplicity\nIn many leases, the lessor handles maintenance and repairs, allowing you to focus on your core business.\n\n**Example**: The lessor maintains the equipment, so you don't need to hire maintenance staff or deal with repairs.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_1_1");
    record1.set("content_body", "## Section 3: Leasing vs Buying\n\n### Leasing\n- No ownership of the equipment\n- Lower upfront costs\n- Monthly lease payments\n- Lessor typically handles maintenance\n- Easy to upgrade or change equipment\n- **Example**: Lease equipment for flexibility and lower upfront costs\n\n### Buying\n- Full ownership of the equipment\n- Higher upfront costs\n- One-time or financed payment\n- Owner responsible for maintenance\n- Difficult to upgrade or change\n- **Example**: Buy equipment for long-term, stable use\n\n### When to Lease\n- You need flexibility\n- You want the latest technology\n- You have limited capital\n- You have short-term needs\n- **Example**: A growing business that needs to adapt quickly\n\n### When to Buy\n- You have long-term, stable equipment needs\n- You have abundant capital\n- You want ownership\n- You plan to use equipment for many years\n- **Example**: An established business with stable operations\n\n## Section 4: Key Benefits of Leasing\n\n### Benefit 1: Capital Preservation\nLeasing requires no large upfront investment, preserving your capital for other business needs.\n\n**Example**: Instead of spending $10,000 on equipment, you preserve that capital for marketing, hiring, or other growth initiatives.\n\n### Benefit 2: Predictable Costs\nLease payments are fixed and predictable, making budgeting easier and more certain.\n\n**Example**: A $500/month payment is predictable and can be easily included in your budget.\n\n### Benefit 3: Flexibility\nYou can easily change or upgrade equipment as your business needs evolve.\n\n**Example**: Upgrade to larger equipment as your business grows without selling old equipment.\n\n### Benefit 4: Technology Access\nLeasing ensures you have access to the latest equipment, keeping you competitive.\n\n**Example**: Use the latest technology to stay ahead of competitors.\n\n### Benefit 5: Reduced Risk\nThe lessor bears the risk of equipment becoming obsolete or losing value.\n\n**Example**: You don't risk owning equipment that becomes outdated or loses value.\n\n### Benefit 6: Operational Efficiency\nWith maintenance often included, you can focus on your core business operations.\n\n**Example**: The lessor maintains the equipment, freeing your team to focus on production.");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_1_1");
    record2.set("content_body", "## Section 5: Who Uses Leasing?\n\n### Businesses\n- **Manufacturing companies**: Lease production equipment\n- **Technology companies**: Lease computers and servers\n- **Retail businesses**: Lease store equipment and fixtures\n- **Service companies**: Lease tools and equipment\n\n**Example**: A manufacturing company leases heavy machinery to avoid large capital investments.\n\n### Consumers\n- **Car leasing**: Lease vehicles for personal use\n- **Equipment leasing**: Lease tools and equipment\n- **Technology leasing**: Lease computers and devices\n\n**Example**: A consumer leases a car to drive the latest model without ownership.\n\n### Organizations\n- **Non-profits**: Lease equipment to conserve limited funds\n- **Government agencies**: Lease equipment and vehicles\n- **Educational institutions**: Lease computers and lab equipment\n\n**Example**: A school leases computers to provide students with latest technology.\n\n## Section 6: Case Study - StartupCorp\n\n### Company Profile\n- **Name**: StartupCorp\n- **Business**: Technology startup\n- **Situation**: Need equipment but limited capital\n\n### Challenge\n- Need $50,000 in equipment\n- Limited capital available\n- Want access to latest technology\n- Need flexibility to adapt as business grows\n\n### Leasing Solution\n- Lease equipment instead of buying\n- Monthly payment: $1,000\n- Lease term: 3 years\n- Upgrade option available\n\n### Benefits Achieved\n- **Capital Preserved**: $50,000 preserved for growth\n- **Predictable Costs**: $1,000/month is predictable and budgetable\n- **Latest Technology**: Access to newest equipment\n- **Flexibility**: Can upgrade or change equipment as business grows\n- **Operational Efficiency**: Lessor maintains equipment\n\n### Outcome\n- Equipment obtained without large capital investment\n- Capital preserved for hiring, marketing, and growth\n- Positioned for continued growth and expansion\n- Able to adapt equipment as business needs change");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "lesson_1_2");
    record3.set("content_body", "# Types of Leases and Key Concepts\n\n## Section 1: Operating Leases\n\n### Definition\nAn operating lease is a short-term lease where the lessor retains ownership of the equipment. The lessee has the right to use the equipment but not the benefits of ownership.\n\n**Example**: A 2-3 year equipment lease where the lessor retains ownership and the lessee uses the equipment.\n\n### Characteristics\n- **Short lease term**: Typically 2-5 years\n- **Lessor retains residual value**: Lessor keeps the equipment value at lease end\n- **Lessee has flexibility**: Can upgrade or change equipment\n- **Maintenance often included**: Lessor handles maintenance\n\n**Example**: An equipment lease with maintenance included allows the lessee to focus on operations.\n\n### Benefits\n- **Flexibility**: Easy to upgrade or change equipment\n- **Lower upfront costs**: No large capital investment\n- **Technology access**: Always have latest equipment\n- **Operational efficiency**: Lessor handles maintenance\n\n**Example**: A startup can easily upgrade equipment as the business grows.\n\n### Use Cases\n- **Growing businesses**: Need flexibility to adapt\n- **Technology companies**: Need latest equipment\n- **Seasonal operations**: Need equipment for specific periods\n- **Market testing**: Need equipment to test new markets\n\n**Example**: A startup leases equipment to test a new market without large capital investment.\n\n## Section 2: Capital Leases (Finance Leases)\n\n### Definition\nA capital lease (also called a finance lease) is a long-term lease that transfers the benefits and risks of ownership to the lessee. The lessee has ownership-like rights and responsibilities.\n\n**Example**: A 5-year equipment lease with a purchase option at the end, where the lessee assumes ownership risks.\n\n### Characteristics\n- **Long lease term**: Typically 5+ years\n- **Lessee assumes ownership risks**: Lessee bears residual value risk\n- **Lessee has limited flexibility**: Cannot easily change equipment\n- **Lessee responsible for maintenance**: Lessee handles repairs and upkeep\n\n**Example**: An equipment lease with a purchase option where the lessee is responsible for maintenance.");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "lesson_1_2");
    record4.set("content_body", "### Benefits\n- **Long-term cost certainty**: Fixed payments over long period\n- **Ownership at end**: Option to purchase equipment at lease end\n- **Tax benefits**: May have favorable tax treatment\n- **Financing alternative**: Alternative to traditional financing\n\n**Example**: A company can finance equipment through a capital lease instead of a bank loan.\n\n### Use Cases\n- **Long-term equipment needs**: Equipment needed for many years\n- **Stable operations**: Business with predictable, stable needs\n- **Ownership desired**: Want to own equipment at lease end\n- **Financing needed**: Need alternative financing method\n\n**Example**: An established manufacturing company leases equipment with a purchase option for long-term use.\n\n## Section 3: Consumer Leases\n\n### Definition\nA consumer lease is a lease for personal use, typically short-term. The consumer is the lessee and uses the equipment for personal purposes.\n\n**Example**: A car lease for personal use, typically 2-4 years.\n\n### Characteristics\n- **Short lease term**: Typically 2-4 years\n- **Personal use**: Equipment used for personal purposes\n- **Maintenance often included**: Lessor handles maintenance\n- **Usage limits**: May have mileage or usage limits\n\n**Example**: A car lease with a 12,000 miles/year limit and maintenance included.\n\n### Benefits\n- **No ownership burden**: Don't own the equipment\n- **Maintenance included**: Lessor handles repairs\n- **Latest models**: Always drive the latest car\n- **Predictable costs**: Fixed monthly payments\n\n**Example**: Drive the latest car model without owning it and with maintenance included.\n\n### Use Cases\n- **Car leasing**: Lease vehicles for personal use\n- **Equipment leasing**: Lease tools for personal use\n- **Technology leasing**: Lease computers or devices\n\n**Example**: A consumer leases a car to drive the latest model without ownership.\n\n## Section 4: Key Leasing Concepts\n\n### Concept 1: Lessor\n- **Definition**: The owner of the equipment\n- **Responsibility**: Retains legal title and ownership\n- **Role**: Provides equipment to lessee\n\n**Example**: An equipment finance company is the lessor.\n\n### Concept 2: Lessee\n- **Definition**: The user of the equipment\n- **Responsibility**: Has possession and use rights\n- **Role**: Makes lease payments and uses equipment\n\n**Example**: A manufacturing company is the lessee.");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "lesson_1_2");
    record5.set("content_body", "### Concept 3: Lease Term\n- **Definition**: The period for which equipment is leased\n- **Characteristic**: Fixed duration\n- **Example**: A 3-year lease term\n\n### Concept 4: Lease Payment\n- **Definition**: The monthly or periodic payment\n- **Characteristic**: Fixed amount\n- **Example**: A $1,000 monthly payment\n\n### Concept 5: Residual Value\n- **Definition**: The expected value of equipment at lease end\n- **Ownership**: Lessor retains in operating lease; lessee assumes in capital lease\n- **Example**: Equipment worth $5,000 at lease end\n\n### Concept 6: Default\n- **Definition**: Failure to perform lease obligations\n- **Consequence**: Triggers remedies and penalties\n- **Example**: Failure to make lease payment\n\n### Concept 7: Maintenance\n- **Definition**: Upkeep and repair of equipment\n- **Responsibility**: Lessor or lessee depending on lease type\n- **Example**: Lessor maintains equipment in operating lease\n\n### Concept 8: Insurance\n- **Definition**: Protection against loss or damage\n- **Requirement**: Usually required by lessor\n- **Example**: $1,000,000 liability insurance\n\n## Section 5: Lease Terminology\n\n### Term 1: Lessor\n- Equipment owner who provides the equipment\n- **Example**: Equipment finance company\n\n### Term 2: Lessee\n- Equipment user who makes lease payments\n- **Example**: Manufacturing company\n\n### Term 3: Lease Agreement\n- Legal contract defining terms and conditions\n- **Example**: Written lease agreement signed by both parties\n\n### Term 4: Lease Payment\n- Monthly or periodic payment amount\n- **Example**: $1,000 monthly payment\n\n### Term 5: Lease Term\n- Duration of the lease\n- **Example**: 3-year lease term\n\n### Term 6: Residual Value\n- Expected value at lease end\n- **Example**: $5,000 residual value\n\n### Term 7: Default\n- Breach of lease terms\n- **Example**: Failure to make payment\n\n### Term 8: Maintenance\n- Equipment upkeep and repair\n- **Example**: Lessor maintains equipment");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "lesson_1_2");
    record6.set("content_body", "## Section 6: Case Study - ComparisonCorp\n\n### Company Profile\n- **Name**: ComparisonCorp\n- **Business**: Manufacturing company\n- **Situation**: Need equipment for expansion\n\n### Scenario 1: Operating Lease\n- **Equipment**: Manufacturing machine\n- **Lease term**: 3 years\n- **Monthly payment**: $2,000\n- **Maintenance**: Included\n- **Upgrade option**: Available\n- **Benefits**: Flexibility, latest technology, low upfront cost\n\n### Scenario 2: Capital Lease\n- **Equipment**: Manufacturing machine\n- **Lease term**: 5 years\n- **Monthly payment**: $1,500\n- **Maintenance**: Lessee responsible\n- **Purchase option**: Available at end\n- **Benefits**: Long-term cost certainty, ownership option\n\n### Scenario 3: Consumer Lease\n- **Equipment**: Company vehicles\n- **Lease term**: 3 years\n- **Monthly payment**: $500 per vehicle\n- **Maintenance**: Included\n- **Mileage limit**: 12,000 miles/year\n- **Benefits**: Latest models, maintenance included, predictable costs\n\n### Decision\nComparisonCorp selected the operating lease for manufacturing equipment because:\n- Provides flexibility for growing business\n- Allows technology upgrades\n- Maintenance included\n- Lower upfront costs\n\n### Outcome\n- Equipment obtained through operating lease\n- Flexibility maintained for growth\n- Latest technology available\n- Positioned for continued expansion");
  app.save(record6);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
