/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "pbc_3963162141");
    record0.set("content_body", "**Section 1: Credit Scoring Models**\n\nWhat is Credit Scoring?\n- Quantitative method to assess credit risk\n- Assigns numerical score based on credit factors\n- Predicts probability of default\n- Used to standardize credit decisions\n- Ranges from 0-1000 or 0-100 depending on model\n\nTypes of Credit Scoring Models:\n\n1. Judgmental Scoring:\n   - Expert judgment based on experience\n   - Subjective assessment of credit factors\n   - Flexible but inconsistent\n   - Example: Credit officer assigns score based on experience\n\n2. Statistical Scoring:\n   - Uses historical data to develop scoring model\n   - Identifies factors that predict default\n   - Objective and consistent\n   - Example: Logistic regression model predicting default probability\n\n3. Machine Learning Scoring:\n   - Uses advanced algorithms to identify patterns\n   - Learns from large datasets\n   - Can identify non-obvious relationships\n   - Example: Neural network predicting default risk");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "pbc_3963162141");
    record1.set("content_body", "**Section 2: Credit Scoring Components**\n\nTypical Credit Scoring Model Components:\n\n1. Financial Metrics (40-50% weight):\n   - Debt-to-equity ratio\n   - Current ratio\n   - Debt service coverage ratio\n   - Return on assets\n   - Interest coverage ratio\n   - Example: DSCR > 2.0x = 10 points, 1.5-2.0x = 7 points, < 1.5x = 3 points\n\n2. Profitability Metrics (20-30% weight):\n   - Net profit margin\n   - Operating margin\n   - Return on equity\n   - Trend in profitability\n   - Example: Net margin > 15% = 10 points, 10-15% = 7 points, < 10% = 3 points\n\n3. Liquidity Metrics (10-15% weight):\n   - Current ratio\n   - Quick ratio\n   - Working capital\n   - Cash position\n   - Example: Current ratio > 1.5x = 10 points, 1.0-1.5x = 7 points, < 1.0x = 3 points\n\n4. Industry and Market Factors (10-15% weight):\n   - Industry growth rate\n   - Competitive position\n   - Market share\n   - Industry risk\n   - Example: Growing industry = 10 points, stable = 7 points, declining = 3 points\n\n5. Management and Qualitative Factors (5-10% weight):\n   - Management experience\n   - Business model quality\n   - Customer concentration\n   - Payment history\n   - Example: Experienced management = 10 points, adequate = 7 points, weak = 3 points");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "pbc_3963162141");
    record2.set("content_body", "**Section 3: Credit Scoring Process**\n\nStep 1: Data Collection\n- Gather financial statements (3-5 years)\n- Collect industry and market data\n- Obtain payment history and references\n- Conduct background checks\n- Timeline: 1-2 weeks\n\nStep 2: Calculate Metrics\n- Calculate all financial ratios and metrics\n- Benchmark against industry averages\n- Analyze trends over time\n- Assess qualitative factors\n- Timeline: 1 week\n\nStep 3: Score Each Component\n- Assign points for each metric\n- Weight components according to model\n- Calculate component scores\n- Timeline: 1 week\n\nStep 4: Calculate Total Score\n- Sum weighted component scores\n- Determine credit rating based on score\n- Assess default probability\n- Timeline: 1 day\n\nStep 5: Make Credit Decision\n- Approve, conditional, or decline\n- Determine lease terms based on score\n- Document decision and rationale\n- Communicate to sales team\n- Timeline: 1 week");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "pbc_3963162141");
    record3.set("content_body", "**Section 4: Credit Decision Framework**\n\nCredit Score Ranges and Decisions:\n\nScore 800-1000 (Prime - A):\n- Default probability: < 1%\n- Decision: Approve\n- Lease terms: Standard rates, minimal restrictions\n- Example: Fortune 500 company with strong financials\n\nScore 700-799 (Good - A-/BBB+):\n- Default probability: 1-3%\n- Decision: Approve\n- Lease terms: Standard rates, standard restrictions\n- Example: Established mid-size company with good financials\n\nScore 600-699 (Fair - BBB/BBB-):\n- Default probability: 3-8%\n- Decision: Approve with conditions\n- Lease terms: Slightly higher rates, additional restrictions\n- Example: Smaller company with adequate financials\n\nScore 500-599 (Subprime - BB+/BB):\n- Default probability: 8-15%\n- Decision: Approve with significant conditions\n- Lease terms: Higher rates, significant restrictions, guarantees\n- Example: Startup or company with weak financials\n\nScore < 500 (High Risk - BB- and below):\n- Default probability: > 15%\n- Decision: Decline or require substantial guarantees\n- Lease terms: Very high rates, extensive restrictions, collateral\n- Example: Company near default or in distress");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "pbc_3963162141");
    record4.set("content_body", "**Section 5: Case Study - Credit Scoring Model Application**\n\nCompany: ManufacturingCorp Inc.\nSituation: Applying credit scoring model for $500K lease\n\nData Collection:\n- Financial statements: 3 years available\n- Industry data: Manufacturing sector\n- Payment history: 10 years, no late payments\n- References: Excellent from suppliers and customers\n\nMetric Calculation:\n\nFinancial Metrics (40% weight):\n- Debt-to-equity: 0.6x (score: 9/10)\n- Current ratio: 1.8x (score: 9/10)\n- DSCR: 2.5x (score: 10/10)\n- ROA: 12% (score: 8/10)\n- Interest coverage: 8.0x (score: 10/10)\n- Component score: (9+9+10+8+10)/5 = 9.2/10\n- Weighted score: 9.2 \u00d7 0.40 = 3.68\n\nProfitability Metrics (25% weight):\n- Net margin: 11% (score: 8/10)\n- Operating margin: 16% (score: 9/10)\n- ROE: 22% (score: 9/10)\n- Profitability trend: Improving (score: 9/10)\n- Component score: (8+9+9+9)/4 = 8.75/10\n- Weighted score: 8.75 \u00d7 0.25 = 2.19");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "pbc_3963162141");
    record5.set("content_body", "Liquidity Metrics (15% weight):\n- Current ratio: 1.8x (score: 9/10)\n- Quick ratio: 1.4x (score: 9/10)\n- Working capital: $7M (score: 9/10)\n- Component score: (9+9+9)/3 = 9.0/10\n- Weighted score: 9.0 \u00d7 0.15 = 1.35\n\nIndustry Factors (12% weight):\n- Industry growth: 5% (score: 7/10)\n- Competitive position: Strong (score: 8/10)\n- Market share: 8% (score: 8/10)\n- Component score: (7+8+8)/3 = 7.67/10\n- Weighted score: 7.67 \u00d7 0.12 = 0.92\n\nQualitative Factors (8% weight):\n- Management experience: 20 years (score: 9/10)\n- Business model: Stable (score: 8/10)\n- Customer concentration: Diversified (score: 9/10)\n- Payment history: Excellent (score: 10/10)\n- Component score: (9+8+9+10)/4 = 9.0/10\n- Weighted score: 9.0 \u00d7 0.08 = 0.72\n\nTotal Credit Score:\n- Sum of weighted scores: 3.68 + 2.19 + 1.35 + 0.92 + 0.72 = 8.86\n- Normalized to 1000: 8.86 \u00d7 100 = 886/1000\n\nCredit Decision:\n- Score: 886 (Prime - A)\n- Default probability: < 1%\n- Decision: Approve\n- Lease terms: Standard rates, minimal restrictions\n- Rationale: Excellent financial position, strong management, stable business model");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "pbc_3963162141");
    record6.set("content_body", "**Section 1: Credit Monitoring Framework**\n\nMonitoring Objectives:\n- Track lessee financial condition\n- Identify deterioration early\n- Assess covenant compliance\n- Manage portfolio risk\n- Maximize recovery in default situations\n\nMonitoring Frequency:\n\n1. Prime Credits (Score 800+):\n   - Annual financial review\n   - Quarterly calls/updates\n   - Annual on-site visit\n   - Monitoring cost: Low\n\n2. Good Credits (Score 700-799):\n   - Semi-annual financial review\n   - Quarterly calls/updates\n   - Annual on-site visit\n   - Monitoring cost: Low-Medium\n\n3. Fair Credits (Score 600-699):\n   - Quarterly financial review\n   - Monthly calls/updates\n   - Semi-annual on-site visit\n   - Monitoring cost: Medium\n\n4. Subprime Credits (Score 500-599):\n   - Monthly financial review\n   - Weekly calls/updates\n   - Quarterly on-site visit\n   - Monitoring cost: Medium-High\n\n5. High Risk Credits (Score < 500):\n   - Weekly financial review\n   - Daily calls/updates\n   - Monthly on-site visit\n   - Monitoring cost: High");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "pbc_3963162141");
    record7.set("content_body", "**Section 2: Early Warning Indicators**\n\nFinancial Warning Signs:\n\n1. Deteriorating Profitability:\n   - Declining net margin\n   - Declining operating margin\n   - Declining EBITDA\n   - Indicator: 2+ consecutive quarters of decline\n\n2. Deteriorating Liquidity:\n   - Declining current ratio\n   - Declining quick ratio\n   - Declining cash position\n   - Indicator: Current ratio < 1.0x\n\n3. Increasing Leverage:\n   - Increasing debt-to-equity\n   - Increasing debt-to-assets\n   - Increasing interest expense\n   - Indicator: Debt-to-equity > 2.0x\n\n4. Declining Cash Flow:\n   - Declining operating cash flow\n   - Declining free cash flow\n   - Negative cash flow\n   - Indicator: FCF < 0 for 2+ quarters\n\n5. Covenant Violations:\n   - Failure to maintain minimum DSCR\n   - Failure to maintain maximum leverage\n   - Failure to maintain minimum liquidity\n   - Indicator: Any covenant violation\n\nOperational Warning Signs:\n\n1. Management Changes:\n   - Key executive departures\n   - CEO or CFO turnover\n   - Indicator: Loss of experienced management\n\n2. Customer Concentration:\n   - Loss of major customer\n   - Increasing customer concentration\n   - Indicator: Top customer > 30% of revenue\n\n3. Competitive Pressure:\n   - Loss of market share\n   - New competitors entering market\n   - Price competition intensifying\n   - Indicator: Declining market position\n\n4. Operational Issues:\n   - Production disruptions\n   - Quality problems\n   - Supply chain disruptions\n   - Indicator: Operational challenges\n\n5. Legal/Regulatory Issues:\n   - Litigation or lawsuits\n   - Regulatory violations\n   - Compliance issues\n   - Indicator: Legal or regulatory problems");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "pbc_3963162141");
    record8.set("content_body", "**Section 3: Portfolio Risk Management**\n\nPortfolio Diversification:\n\n1. Customer Diversification:\n   - Limit exposure to single customer\n   - Target: No customer > 5-10% of portfolio\n   - Benefit: Reduces concentration risk\n   - Example: 100 customers with $1M each = well-diversified\n\n2. Industry Diversification:\n   - Spread across multiple industries\n   - Target: No industry > 20-30% of portfolio\n   - Benefit: Reduces industry-specific risk\n   - Example: 30% manufacturing, 25% technology, 20% healthcare, 25% other\n\n3. Geographic Diversification:\n   - Spread across multiple regions/countries\n   - Target: No region > 30-40% of portfolio\n   - Benefit: Reduces geographic/economic risk\n   - Example: 40% North America, 30% Europe, 20% Asia, 10% other\n\n4. Credit Quality Diversification:\n   - Mix of prime, good, fair, and subprime credits\n   - Target: 60% prime/good, 30% fair, 10% subprime\n   - Benefit: Balances risk and return\n   - Example: 60% A-rated, 30% BBB-rated, 10% BB-rated\n\n5. Equipment Type Diversification:\n   - Spread across different equipment types\n   - Target: No equipment type > 20-30% of portfolio\n   - Benefit: Reduces equipment-specific risk\n   - Example: 30% IT equipment, 25% manufacturing, 20% vehicles, 25% other");
  app.save(record8);

  const record9 = new Record(collection);
    record9.set("lesson_id", "pbc_3963162141");
    record9.set("content_body", "Portfolio Metrics:\n\n1. Portfolio Default Rate:\n   - Percentage of portfolio in default\n   - Target: < 2% (varies by credit quality)\n   - Indicator: Portfolio health\n   - Example: 2% default rate = 2 defaults per 100 leases\n\n2. Portfolio Loss Rate:\n   - Percentage of portfolio lost to defaults\n   - Target: < 1% (varies by credit quality)\n   - Indicator: Actual losses\n   - Example: 1% loss rate = $1M loss per $100M portfolio\n\n3. Portfolio Concentration:\n   - Percentage of portfolio in top customers/industries\n   - Target: Top 10 customers < 20%, top industry < 30%\n   - Indicator: Concentration risk\n   - Example: Top 10 customers = 15% of portfolio\n\n4. Portfolio Credit Quality:\n   - Percentage of portfolio in each credit rating\n   - Target: 60% prime/good, 30% fair, 10% subprime\n   - Indicator: Portfolio risk profile\n   - Example: 65% A-rated, 28% BBB-rated, 7% BB-rated");
  app.save(record9);

  const record10 = new Record(collection);
    record10.set("lesson_id", "pbc_3963162141");
    record10.set("content_body", "**Section 4: Case Study - Credit Monitoring and Portfolio Management**\n\nCompany: LeaseCorp (Lessor)\nSituation: Managing credit portfolio of 500 leases\n\nPortfolio Overview:\n- Total portfolio: $500M\n- Number of leases: 500\n- Average lease size: $1M\n- Portfolio default rate: 1.5%\n- Portfolio loss rate: 0.8%\n\nMonitoring Process:\n\nPrime Credits (Score 800+, 60% of portfolio):\n- 300 leases, $300M\n- Annual financial review\n- Quarterly calls\n- Annual on-site visits\n- Monitoring cost: $150K/year\n\nGood Credits (Score 700-799, 30% of portfolio):\n- 150 leases, $150M\n- Semi-annual financial review\n- Quarterly calls\n- Annual on-site visits\n- Monitoring cost: $225K/year\n\nFair Credits (Score 600-699, 8% of portfolio):\n- 40 leases, $40M\n- Quarterly financial review\n- Monthly calls\n- Semi-annual on-site visits\n- Monitoring cost: $120K/year\n\nSubprime Credits (Score 500-599, 2% of portfolio):\n- 10 leases, $10M\n- Monthly financial review\n- Weekly calls\n- Quarterly on-site visits\n- Monitoring cost: $60K/year\n\nTotal Monitoring Cost: $555K/year (0.11% of portfolio)");
  app.save(record10);

  const record11 = new Record(collection);
    record11.set("lesson_id", "pbc_3963162141");
    record11.set("content_body", "Early Warning System:\n\nMonitoring Dashboard:\n- Real-time tracking of key metrics\n- Automated alerts for covenant violations\n- Trend analysis and forecasting\n- Risk scoring updates\n- Example: Alert when DSCR drops below 1.25x\n\nQuarterly Portfolio Review:\n- Review of all credits with score changes\n- Analysis of new defaults and recoveries\n- Portfolio concentration analysis\n- Diversification assessment\n- Recommendations for portfolio adjustments\n\nPortfolio Optimization:\n\nCurrent Portfolio Issues:\n- Top customer: 8% of portfolio (above 5% target)\n- Manufacturing industry: 35% of portfolio (above 30% target)\n- Subprime credits: 2% of portfolio (at 10% target)\n- Geographic concentration: 50% in single region (above 40% target)\n\nOptimization Strategies:\n\n1. Reduce Customer Concentration:\n   - Limit new leases to top customer\n   - Encourage customer to diversify\n   - Target: Reduce to 5% of portfolio over 2 years\n\n2. Reduce Industry Concentration:\n   - Increase focus on technology and healthcare\n   - Reduce manufacturing focus\n   - Target: Reduce manufacturing to 25% over 2 years\n\n3. Increase Subprime Exposure:\n   - Develop subprime lending program\n   - Higher rates to compensate for risk\n   - Target: Increase to 10% of portfolio over 2 years\n\n4. Improve Geographic Diversification:\n   - Expand into new regions\n   - Reduce single-region concentration\n   - Target: Reduce to 40% in single region over 2 years\n\nExpected Results:\n- Reduced portfolio risk\n- Improved portfolio returns\n- Better risk-adjusted returns\n- More resilient portfolio");
  app.save(record11);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
