/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_4.1");
    record0.set("content_body", "# ESG-Linked Leasing: Comprehensive Guide\n\n## Section 1: Introduction to ESG-Linked Leasing\nESG-linked leasing represents a paradigm shift in asset financing, integrating Environmental, Social, and Governance factors directly into lease structures. This innovative approach aligns financial incentives with sustainability performance, creating mutual benefits for lessors and lessees.\n\n## Section 2: ESG-Linked Lease Structures\nESG-linked leases incorporate performance metrics tied to sustainability targets. Key structural elements include:\n- Sustainability-linked pricing mechanisms\n- Performance-based lease adjustments\n- Green certification requirements\n- Carbon footprint reduction targets\n\n## Section 3: Sustainability Metrics & Measurement\nEffective ESG-linked leases require robust measurement frameworks:\n- Environmental metrics (carbon emissions, energy efficiency)\n- Social metrics (workforce diversity, community impact)\n- Governance metrics (compliance, transparency)\n- Third-party verification standards\n\n## Section 4: Green Lease Pricing Models\nPricing mechanisms in ESG-linked leases:\n- Base lease rates with sustainability adjustments\n- Performance-based discounts for exceeding targets\n- Penalty structures for underperformance\n- Dynamic pricing based on ESG ratings\n\n## Section 5: Financial Impact Analysis\nUnderstanding the financial implications:\n- Cost-benefit analysis of ESG compliance\n- ROI calculations for sustainability investments\n- Risk mitigation through ESG alignment\n- Long-term value creation\n\n## Section 6: Case Studies & Best Practices\nReal-world applications and lessons learned from leading organizations implementing ESG-linked leasing strategies.");
    record0.set("video_url", null);
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_4.2");
    record1.set("content_body", "# Usage-Based & As-a-Service Models: Complete Framework\n\n## Section 1: Introduction to Usage-Based Leasing\nUsage-based leasing models shift from ownership to access, aligning costs with actual consumption. This approach provides flexibility and cost optimization for lessees while ensuring predictable revenue streams for lessors.\n\n## Section 2: Pay-Per-Use Lease Models\nCore concepts of usage-based pricing:\n- Metering and monitoring technologies\n- Usage tracking and reporting systems\n- Flexible payment structures\n- Scalability and adaptability\n\n## Section 3: As-a-Service Business Models\nTransforming traditional leasing into service offerings:\n- Equipment-as-a-Service (EaaS)\n- Mobility-as-a-Service (MaaS)\n- Infrastructure-as-a-Service (IaaS)\n- Outcome-based service delivery\n\n## Section 4: Outcome-Based Pricing Mechanisms\nAdvanced pricing strategies:\n- Performance-based pricing\n- Tiered usage pricing\n- Hybrid fixed-variable models\n- Dynamic pricing algorithms\n\n## Section 5: Financial Impact Calculations\nQuantifying the benefits:\n- Cost per unit of usage analysis\n- Total cost of ownership comparisons\n- Revenue optimization strategies\n- Profitability modeling\n\n## Section 6: Implementation & Transition Strategy\nMoving from traditional to usage-based models:\n- Technology infrastructure requirements\n- Customer communication strategies\n- Operational adjustments\n- Risk management considerations");
    record1.set("video_url", null);
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_4.3");
    record2.set("content_body", "# Digital Asset Tracking & IoT: Advanced Technologies\n\n## Section 1: IoT Fundamentals in Leasing\nInternet of Things (IoT) technologies enable real-time visibility and control of leased assets. Understanding IoT architecture and applications is essential for modern leasing operations.\n\n## Section 2: Digital Asset Tracking Technologies\nCore tracking technologies:\n- GPS and location tracking systems\n- RFID and NFC technologies\n- Sensor networks and data collection\n- Cloud-based asset management platforms\n\n## Section 3: Real-Time Telematics\nAdvanced monitoring capabilities:\n- Vehicle and equipment telematics\n- Performance metrics collection\n- Condition monitoring systems\n- Predictive analytics integration\n\n## Section 4: Predictive Maintenance\nLeveraging data for proactive maintenance:\n- Condition-based maintenance triggers\n- Failure prediction algorithms\n- Maintenance scheduling optimization\n- Cost reduction through prevention\n\n## Section 5: Financial Impact of IoT-Enabled Leasing\nQuantifying IoT benefits:\n- Reduced downtime and operational costs\n- Extended asset lifecycle\n- Improved utilization rates\n- Enhanced risk management\n\n## Section 6: Implementation & Future Trends\nDeploying IoT in leasing operations:\n- Technology selection and integration\n- Data security and privacy considerations\n- Scalability and standardization\n- Emerging technologies and innovations");
    record2.set("video_url", null);
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
