/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "[LESSON_2_ID]");
    record0.set("content_body", "INTRODUCTION TO CFO LANGUAGE: Understanding how CFOs think, Financial metrics that matter to CFOs, The language of finance and business strategy, Why salespeople need to speak CFO language\n\nA - CASH FLOW PRESERVATION:\n- Understanding cash flow vs profit\n- Why cash flow is critical to business operations\n- The importance of preserving working capital\n- How leasing preserves cash flow\n- Comparing cash outflows: purchase vs lease\n- Timing of cash payments and their impact\n- Liquidity management through leasing\n- Real-world examples of cash flow preservation\n- How to communicate cash flow benefits to CFOs\n- Case studies showing cash flow improvements\n\nB - SIMPLE ROI VS IRR (A Basic Look at How Equipment Leasing Affects the Internal Rate of Return):\n- Understanding Return on Investment (ROI)\n- What is Internal Rate of Return (IRR)\n- Difference between ROI and IRR\n- Why IRR matters to CFOs\n- How equipment leasing affects IRR calculations\n- Comparing IRR: purchase vs lease scenarios\n- Break-even analysis using IRR\n- Time value of money concepts\n- Discount rates and their impact\n- How to calculate and present IRR to CFOs\n- Real examples of IRR improvements through leasing\n- Tools and methods for IRR analysis\n\nC - INFLATION AS AN ALLY (Explaining How Paying with Tomorrow's Cheaper Dollars Benefits the Client):\n- Understanding inflation and its impact on business\n- How inflation erodes purchasing power\n- The concept of paying with tomorrow's cheaper dollars\n- Real-world inflation examples\n- How fixed lease payments benefit during inflationary periods\n- Comparing fixed lease payments vs variable ownership costs\n- Long-term cost analysis in inflationary environments\n- Hedging against inflation through leasing\n- How to quantify inflation benefits\n- Communicating inflation advantages to CFOs\n- Historical inflation data and projections\n- Case studies of inflation-protected leasing strategies\n\nFINANCIAL MODELING:\n- Building simple financial models to compare scenarios\n- Sensitivity analysis for different economic conditions\n- Scenario planning: best case, worst case, most likely\n- Tools for financial analysis and presentation\n\nOBJECTION HANDLING:\n- Addressing CFO concerns about leasing\n- Overcoming financial objections\n- Presenting data-driven arguments\n- Building credibility with financial decision-makers\n\nSALES MESSAGING FOR CFOs:\n- How to present financial benefits clearly\n- Using metrics and data effectively\n- Creating compelling financial narratives\n- Building trust with financial executives");
  app.save(record0);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
