/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_6_id_placeholder_1");
    record0.set("content_body", "**Section 1: Negotiation Fundamentals**\n\nNegotiation Styles:\n\n1. Competitive (Win-Lose): Goal is to maximize own gains. Approach is aggressive and assertive. Tactics include demands, ultimatums, pressure. Best for one-time transactions with strong position. Risk: Damages relationships, creates resentment\n\n2. Collaborative (Win-Win): Goal is to maximize mutual gains. Approach is cooperative and problem-solving. Tactics include information sharing and creative solutions. Best for long-term relationships and complex deals. Benefit: Builds trust, creates value\n\n3. Compromising (Split-the-Difference): Goal is to find middle ground. Approach is give and take. Tactics include splitting differences and trading concessions. Best for time-constrained negotiations. Risk: Both parties may feel they lost\n\n4. Accommodating (Lose-Win): Goal is to maintain relationship. Approach is cooperative and yielding. Tactics include concessions and flexibility. Best for building relationships and low-stakes issues. Risk: May be taken advantage of\n\n5. Avoiding (Lose-Lose): Goal is to postpone or avoid conflict. Approach is passive and withdrawal. Tactics include delay and avoidance. Best for low-priority issues and cooling off periods. Risk: Issues remain unresolved");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_6_id_placeholder_1");
    record1.set("content_body", "**Section 2: Preparation and Planning**\n\nPre-Negotiation Preparation:\n\n1. Understand Your Position: Know your BATNA (Best Alternative to Negotiated Agreement), your walk-away point (minimum acceptable terms), your ideal outcome, your flexibility and trade-offs. Example: BATNA = lease to another customer at $1,500/month\n\n2. Understand the Other Party: Know their needs and priorities, their constraints and limitations, their alternatives, their decision-making process. Example: Lessee needs flexibility, has budget constraints\n\n3. Identify Common Ground: Find shared interests and goals, areas of agreement, potential win-win solutions. Example: Both want long-term relationship, predictable costs\n\n4. Develop Multiple Options: Create different lease structures, different payment terms, different service levels, different risk allocations. Example: 3-year vs. 5-year lease, full-service vs. net lease\n\n5. Set Negotiation Objectives: Define primary objective (must-have), secondary objectives (nice-to-have), fallback positions, concession strategy. Example: Primary = $1,600/month, Secondary = full-service maintenance");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_6_id_placeholder_1");
    record2.set("content_body", "**Section 3: Negotiation Tactics and Techniques**\n\n1. Anchoring: Make first offer to set negotiation range. Anchor should be ambitious but reasonable. Advantage: Sets favorable starting point. Example: Lessor proposes $1,800/month (higher than expected)\n\n2. Information Gathering: Ask open-ended questions, listen actively to understand needs, identify underlying interests. Example: \"What are your key priorities in this lease?\"\n\n3. Reframing: Present information in favorable light, focus on benefits not features, reframe objections as opportunities. Example: \"Higher payment = better service and support\"\n\n4. Bundling: Package multiple issues together, trade concessions across issues, create value through creative combinations. Example: \"Lower payment + longer term + upgrade option\"\n\n5. Silence: Use silence to create pressure, allow other party to fill silence, avoid rushing to concede. Example: After making offer, stay silent and wait for response\n\n6. Reciprocity: Make concessions to encourage reciprocal concessions, keep concessions small and strategic, track concessions to ensure balance. Example: \"We'll reduce payment by $50 if you extend term by 12 months\"\n\n7. Time Pressure: Create urgency through deadlines, use time constraints strategically, avoid being pressured by artificial deadlines. Example: \"This pricing is available through end of month\"\n\n8. Good Cop / Bad Cop: One negotiator is tough, one is reasonable, creates pressure and relief dynamic, allows flexibility without appearing weak. Example: Manager says \"no,\" salesperson says \"let me see what I can do\"");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "lesson_6_id_placeholder_1");
    record3.set("content_body", "**Section 4: Handling Difficult Negotiations**\n\nCommon Objections and Responses:\n\n1. Objection: \"Your price is too high\"\nResponse: \"Compared to what? Let's look at total value including service, support, and flexibility\"\n\n2. Objection: \"We can get a better deal elsewhere\"\nResponse: \"I understand. What specific terms would make this more attractive?\"\n\n3. Objection: \"We need more flexibility\"\nResponse: \"What flexibility do you need? Let's explore options like early termination or upgrade paths\"\n\n4. Objection: \"We want to own the equipment\"\nResponse: \"I understand. Let's compare the total cost and benefits of ownership vs. leasing\"\n\n5. Objection: \"We need a lower payment\"\nResponse: \"What payment range works for you? Let's explore options like longer term or different service levels\"\n\nDifficult Negotiator Types:\n\n1. The Aggressive Negotiator: Uses demands, ultimatums, pressure. Response: Stay calm, don't match aggression, focus on interests. Example: \"I understand you want the best deal. Let's find a solution that works for both of us\"\n\n2. The Staller: Uses delays, postponements, avoidance. Response: Set deadlines, create urgency, escalate if needed. Example: \"We need a decision by Friday to move forward\"\n\n3. The Unrealistic Negotiator: Makes unreasonable demands and unrealistic expectations. Response: Provide data, educate on market realities, set boundaries. Example: \"Market rates for this equipment are $1,500-$1,800/month\"\n\n4. The Emotional Negotiator: Uses emotional appeals and personal attacks. Response: Stay professional, acknowledge emotions, refocus on issues. Example: \"I understand this is important. Let's focus on finding a solution\"");
  app.save(record3);

  const record4 = new Record(collection);
    record4.set("lesson_id", "lesson_6_id_placeholder_1");
    record4.set("content_body", "**Section 5: Case Study - Advanced Negotiation**\n\nCompany: NegotiationCorp (Lessor)\nSituation: Negotiating complex lease with demanding customer\n\nInitial Proposal (Lessor):\n- Monthly payment: $2,000\n- Lease term: 60 months\n- Maintenance: Net lease (lessee handles)\n- Residual value: $100,000 guaranteed\n- Early termination: Not allowed\n\nCustomer Objections:\n- \"Payment is too high - we can get $1,500 elsewhere\"\n- \"We need full-service maintenance\"\n- \"We need early termination option\"\n- \"We can't guarantee residual value\"\n\nNegotiation Process:\n\nRound 1:\n- Lessor: \"Let's look at total value. Our service and support justify the premium\"\n- Customer: \"We still need lower payment and more flexibility\"\n- Lessor: \"What if we structure this differently? What are your priorities?\"\n\nRound 2:\n- Customer: \"Priority 1: Payment under $1,700. Priority 2: Full-service maintenance. Priority 3: Early termination option\"\n- Lessor: \"I can work with that. Let's explore options\"\n- Lessor proposes: $1,750/month, full-service maintenance, early termination with 10% penalty, $80K residual guarantee\n\nRound 3:\n- Customer: \"Better, but we need $1,650 and 5% early termination penalty\"\n- Lessor: \"I can do $1,700 with 7% penalty if you extend term to 72 months\"\n- Customer: \"Deal - $1,700/month, 72 months, full-service, 7% early termination penalty, $80K residual\"\n\nFinal Agreement:\n- Monthly payment: $1,700\n- Lease term: 72 months\n- Maintenance: Full-service (lessor handles)\n- Residual value: $80,000 guaranteed\n- Early termination: Allowed with 7% penalty\n- Result: Win-win - customer gets flexibility and service, lessor gets longer term and higher total revenue");
  app.save(record4);

  const record5 = new Record(collection);
    record5.set("lesson_id", "lesson_7_id_placeholder_1");
    record5.set("content_body", "**Section 1: Lease Documentation Components**\n\nEssential Lease Agreement Sections:\n\n1. Parties and Definitions: Lessor and lessee identification, equipment description and specifications, key term definitions (capitalized cost, residual value, etc.). Example: \"Lessor: ABC Leasing Corp. Lessee: XYZ Manufacturing Inc.\"\n\n2. Equipment Description: Detailed equipment specifications, serial numbers and identification, condition (new, used, refurbished), delivery and installation terms. Example: \"Caterpillar 320 Excavator, Serial #ABC123, New condition\"\n\n3. Lease Term and Renewal: Primary lease period (e.g., 60 months), renewal options (e.g., 2 additional 12-month periods), renewal pricing (e.g., fair market value), early termination provisions. Example: \"Primary term: 60 months. Renewal: 2 \u00d7 12 months at FMV\"\n\n4. Lease Payments: Monthly/quarterly/annual payment amount, payment schedule and due dates, late payment penalties (e.g., 1.5% per month), payment method and location. Example: \"Monthly payment: $2,000, due 1st of each month\"\n\n5. Maintenance and Service: Maintenance responsibility (full-service, net, gross), maintenance schedule and requirements, service level agreements (response times, uptime), warranty coverage. Example: \"Lessor provides full-service maintenance including parts and labor\"\n\n6. Insurance and Liability: Insurance requirements and coverage amounts, lessor as loss payee, liability limits and deductibles, waiver of subrogation. Example: \"Lessee maintains $500K general liability insurance\"\n\n7. Residual Value and Purchase Options: Guaranteed residual value (if applicable), purchase option at lease end, fair market value purchase option, fixed price purchase option. Example: \"$100K guaranteed residual value at lease end\"\n\n8. Default and Remedies: Definition of default (missed payments, breach), notice and cure periods (e.g., 10 days), remedies (repossession, acceleration, damages), lessor's right to repossess. Example: \"Default if payment 10 days late. Lessor may repossess without notice\"\n\n9. Termination and Return: Early termination provisions and penalties, return condition requirements, excess wear and tear charges, disposition of asset. Example: \"Return in good condition. Excess wear charges apply\"\n\n10. General Provisions: Governing law and jurisdiction, entire agreement clause, amendment procedures, notices and communications, severability clause. Example: \"This agreement constitutes the entire agreement between parties\"");
  app.save(record5);

  const record6 = new Record(collection);
    record6.set("lesson_id", "lesson_7_id_placeholder_1");
    record6.set("content_body", "**Section 2: Legal Compliance and Risk Protection**\n\nKey Legal Considerations:\n\n1. Uniform Commercial Code (UCC): Article 2A governs lease transactions. Defines lessor and lessee rights and obligations. Requires certain disclosures and notices. Affects default and remedies provisions\n\n2. Truth in Leasing Act: Requires clear disclosure of lease terms. Specifies required disclosures (payment, term, residual value, etc.). Applies to consumer leases. Penalties for non-compliance\n\n3. Accounting Standards (IFRS 16 / ASC 842): Affects how leases are recorded and reported. Requires detailed lease accounting. Impacts financial statements and ratios. Requires proper documentation for accounting treatment\n\n4. Tax Considerations: Lease must meet IRS requirements to be treated as lease (not disguised sale). Lessor must retain significant risks and benefits of ownership. Affects depreciation and deduction treatment. Requires proper documentation for tax treatment\n\n5. Consumer Protection Laws: Fair Credit Reporting Act (FCRA), Equal Credit Opportunity Act (ECOA), Fair Debt Collection Practices Act (FDCPA), state-specific consumer protection laws\n\nRisk Protection Strategies:\n\n1. Comprehensive Lease Agreement: Clear and detailed terms, addresses all potential issues, protects lessor's interests, reduces disputes and litigation\n\n2. Personal or Corporate Guarantees: Guarantor liable if lessee defaults, provides additional security, reduces credit risk. Example: Owner personally guarantees lease obligations\n\n3. Security Deposits or Letters of Credit: Provides cash security for performance, covers potential damages or defaults, reduces lessor's risk. Example: $50K security deposit held by lessor\n\n4. Insurance Requirements: Lessee carries comprehensive insurance, lessor named as loss payee, protects lessor from loss. Example: $500K general liability, lessor named loss payee\n\n5. Regular Monitoring and Audits: Monitor lessee's financial condition, conduct equipment inspections, verify insurance coverage, track payment history. Example: Quarterly financial reviews, annual equipment inspections");
  app.save(record6);

  const record7 = new Record(collection);
    record7.set("lesson_id", "lesson_7_id_placeholder_1");
    record7.set("content_body", "**Section 3: Deal Closure Process**\n\nSteps to Close a Lease Deal:\n\n1. Final Negotiation and Agreement: Confirm all terms are agreed, document any last-minute changes, obtain verbal confirmation from decision-makers. Example: \"Let me confirm - $1,700/month, 72 months, full-service maintenance\". Timeline: Immediate\n\n2. Prepare Lease Agreement: Draft comprehensive lease agreement, include all agreed terms, ensure legal compliance, have legal review if needed. Timeline: 2-5 business days\n\n3. Present Agreement for Review: Provide agreement to lessee for review, explain key terms and conditions, address any questions or concerns, allow time for legal review if needed. Timeline: 3-7 business days\n\n4. Obtain Signatures: Lessee signs agreement, lessor signs agreement, obtain required guarantees or security documents, ensure all signatures are authorized. Timeline: 1-3 business days\n\n5. Collect Required Documentation: Financial statements (if required), insurance certificates, security deposits or letters of credit, personal guarantees, equipment specifications and delivery details. Timeline: 1-5 business days\n\n6. Arrange Equipment Delivery: Coordinate delivery with lessee, arrange installation and setup, verify equipment condition and specifications, obtain delivery confirmation. Timeline: 1-4 weeks\n\n7. Activate Lease and Begin Payments: Set up payment processing, send payment instructions to lessee, begin lease accounting and tracking, establish maintenance and support. Timeline: Upon delivery\n\n8. Post-Closing Follow-up: Confirm lessee satisfaction, verify equipment is operating properly, establish ongoing communication, schedule regular reviews. Timeline: Within 2 weeks of delivery");
  app.save(record7);

  const record8 = new Record(collection);
    record8.set("lesson_id", "lesson_7_id_placeholder_1");
    record8.set("content_body", "**Section 4: Case Study - Deal Closure**\n\nCompany: ClosureCorp (Lessor)\nSituation: Closing complex $500K equipment lease\n\nDeal Summary:\n- Equipment: Manufacturing equipment\n- Lessee: Mid-size manufacturing company\n- Monthly payment: $8,500\n- Lease term: 60 months\n- Maintenance: Full-service\n- Residual value: $100K guaranteed\n- Early termination: Allowed with 10% penalty\n\nClosure Timeline:\n\nWeek 1: Final Negotiation - Confirm all terms with lessee, obtain verbal approval from CFO and CEO, document agreed terms\n\nWeek 2: Prepare Documentation - Draft comprehensive lease agreement, include all agreed terms, legal review and revisions, prepare supporting documents (insurance requirements, payment instructions)\n\nWeek 3: Present for Review - Send agreement to lessee, lessee legal team reviews, address questions and concerns, obtain lessee approval\n\nWeek 4: Obtain Signatures - Lessee signs agreement, lessor signs agreement, obtain CFO signature on behalf of lessee, obtain CEO signature on behalf of lessor\n\nWeek 5: Collect Documentation - Receive financial statements, receive insurance certificates, receive security deposit ($50K), receive personal guarantee from owner\n\nWeek 6-8: Arrange Delivery - Coordinate delivery schedule, arrange installation and setup, verify equipment condition, obtain delivery confirmation\n\nWeek 9: Activate Lease - Set up payment processing, send payment instructions, begin lease accounting, establish maintenance support\n\nWeek 10: Post-Closing Follow-up - Confirm lessee satisfaction, verify equipment operation, schedule quarterly reviews, establish ongoing relationship\n\nResult: Successful deal closure with all documentation in place and lease activated");
  app.save(record8);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
