/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("vendor_leasing_quizzes");

  const record0 = new Record(collection);
    record0.set("lessonId", "lesson_5_placeholder");
    record0.set("title", "Lesson 5 Quiz: Vendor Lease Accounting");
    record0.set("questionCount", 10);
    record0.set("questions", "1. Which accounting standard applies to lease accounting in the United States?\na) IFRS 16\nb) ASC 842\nc) ASC 606\nd) FASB 13\n\n2. What is a Right-of-Use (ROU) asset?\na) The residual value of the leased asset\nb) The lessor's ownership interest in the asset\nc) The lessee's right to use the asset over the lease term\nd) The insurance coverage for the leased asset\n\n3. Which of the following is NOT a criterion for classifying a lease as a finance lease?\na) The lease transfers ownership by the end of the term\nb) The lessee has a reasonably certain purchase option\nc) The lease term is for the major part of the asset's economic life\nd) The lease is for a short-term period of less than 12 months\n\n4. How is the lease liability initially measured?\na) The fair value of the leased asset\nb) The present value of lease payments using the incremental borrowing rate\nc) The total of all lease payments without discounting\nd) The residual value of the asset\n\n5. What is the incremental borrowing rate?\na) The rate charged by the lessor\nb) The rate the lessee would pay to borrow funds to purchase the asset\nc) The federal funds rate\nd) The prime lending rate\n\n6. Under ASC 842, how is lease expense recognized for operating leases?\na) As depreciation and interest expense\nb) As a straight-line lease expense\nc) As variable expense based on usage\nd) As a lump sum at lease commencement\n\n7. Which of the following should be included in the lease liability calculation?\na) Only fixed lease payments\nb) Fixed payments, variable payments tied to indices, and residual value guarantees\nc) Only the residual value\nd) Only the purchase option price\n\n8. What is the primary difference between ASC 842 and IFRS 16 regarding lease definitions?\na) IFRS 16 has a more principle-based definition\nb) ASC 842 has a more principle-based definition\nc) They are identical\nd) IFRS 16 only applies to operating leases\n\n9. How should the ROU asset be presented on the balance sheet?\na) Always within property, plant, and equipment\nb) Always as a separate line item\nc) Either separately or within property, plant, and equipment\nd) Only in the notes to the financial statements\n\n10. What is a residual value guarantee?\na) A promise by the lessor to buy back the asset\nb) A promise by the lessee to pay the difference if the asset's value is less than estimated\nc) Insurance coverage for the asset\nd) A guarantee that the asset will not depreciate");
    record0.set("answers", "1. b) ASC 842 - ASC 842 is the FASB standard for lease accounting in the United States, effective for public companies in 2019.\n\n2. c) The lessee's right to use the asset over the lease term - The ROU asset represents the lessee's right to use the underlying asset during the lease term.\n\n3. d) The lease is for a short-term period of less than 12 months - Short-term leases are actually exempt from recognition requirements. The other three are all finance lease criteria.\n\n4. b) The present value of lease payments using the incremental borrowing rate - The lease liability is measured as the PV of all lease payments discounted at the lessee's incremental borrowing rate.\n\n5. b) The rate the lessee would pay to borrow funds to purchase the asset - The incremental borrowing rate is the rate the lessee would incur to borrow the funds needed to purchase the asset.\n\n6. b) As a straight-line lease expense - Operating leases are recognized as a single lease expense on a straight-line basis over the lease term.\n\n7. b) Fixed payments, variable payments tied to indices, and residual value guarantees - The lease liability includes all these components that represent the lessee's payment obligations.\n\n8. a) IFRS 16 has a more principle-based definition - IFRS 16 uses a more principle-based approach to defining leases compared to ASC 842's more rules-based approach.\n\n9. c) Either separately or within property, plant, and equipment - ASC 842 allows flexibility in presentation as long as the ROU asset is clearly identified.\n\n10. b) A promise by the lessee to pay the difference if the asset's value is less than estimated - A residual value guarantee is the lessee's obligation to compensate the lessor if the asset's value falls below the guaranteed amount.");
    record0.set("passingScore", 70);
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lessonId", "lesson_6_placeholder");
    record1.set("title", "Lesson 6 Quiz: Risk Management and Compliance");
    record1.set("questionCount", 10);
    record1.set("questions", "1. What is credit risk in the context of vendor leasing?\na) The risk that the asset will become obsolete\nb) The risk that the lessee will fail to meet lease payment obligations\nc) The risk that interest rates will increase\nd) The risk that the lessor will default\n\n2. Which ratio is most important for assessing a lessee's ability to service debt?\na) Current ratio\nb) Debt service coverage ratio\nc) Inventory turnover\nd) Asset turnover\n\n3. What is residual value risk?\na) The risk that the lessee will not purchase the asset\nb) The risk that the asset's actual value will be less than estimated at lease end\nc) The risk that the lessor will not return the asset\nd) The risk that insurance will not cover the asset\n\n4. Which of the following is NOT a federal regulation affecting lease transactions?\na) Truth in Lending Act (TILA)\nb) Equal Credit Opportunity Act (ECOA)\nc) Uniform Commercial Code (UCC)\nd) Dodd-Frank Act\n\n5. What should be the lessor's primary concern regarding insurance?\na) The lessee has adequate property insurance with the lessor named as loss payee\nb) The lessee has liability insurance\nc) The lessee has credit insurance\nd) The lessee has business interruption insurance\n\n6. Which of the following is a typical default trigger?\na) The lessee's credit rating improves\nb) The lessee makes early payments\nc) Failure to maintain required insurance coverage\nd) The asset increases in value\n\n7. What is the purpose of financial covenants in a lease agreement?\na) To ensure the lessor profits from the lease\nb) To restrict the lessee's financial activities and protect the lessor's interests\nc) To allow the lessee to refinance the lease\nd) To guarantee the residual value\n\n8. Which insurance type protects against the lessee's failure to make lease payments?\na) Property insurance\nb) Liability insurance\nc) Credit insurance\nd) Equipment insurance\n\n9. What is the first step in the default management process?\na) Immediate repossession of the asset\nb) Legal action against the lessee\nc) Early warning system monitoring and initial contact\nd) Acceleration of all remaining payments\n\n10. What is the primary benefit of portfolio diversification in lease management?\na) Increases total lease revenue\nb) Reduces concentration risk and spreads risk across multiple lessees and industries\nc) Eliminates all credit risk\nd) Guarantees profitability");
    record1.set("answers", "1. b) The risk that the lessee will fail to meet lease payment obligations - Credit risk is the primary concern for lessors, representing the risk of lessee default.\n\n2. b) Debt service coverage ratio - This ratio measures the lessee's ability to service debt obligations, which is critical for assessing lease payment capacity.\n\n3. b) The risk that the asset's actual value will be less than estimated at lease end - Residual value risk is the risk that the asset will be worth less than projected when the lease ends.\n\n4. c) Uniform Commercial Code (UCC) - The UCC is a state-level regulation, not a federal regulation. The others are all federal regulations.\n\n5. a) The lessee has adequate property insurance with the lessor named as loss payee - This protects the lessor's interest in the asset and ensures recovery if the asset is damaged.\n\n6. c) Failure to maintain required insurance coverage - This is a typical covenant violation that triggers default. The other options would not trigger default.\n\n7. b) To restrict the lessee's financial activities and protect the lessor's interests - Financial covenants protect the lessor by limiting the lessee's ability to take actions that could impair their ability to pay.\n\n8. c) Credit insurance - Credit insurance specifically protects against the lessee's failure to make payments.\n\n9. c) Early warning system monitoring and initial contact - The default management process should begin with monitoring and early intervention before escalating to more severe actions.\n\n10. b) Reduces concentration risk and spreads risk across multiple lessees and industries - Diversification is a key risk management strategy that reduces exposure to any single lessee or industry.");
    record1.set("passingScore", 70);
  app.save(record1);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
