/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "LESSON_6_ID");
    record0.set("content_body", "OPERATIONAL FACTORS: Equipment usage patterns (frequency and intensity) impact decision - high usage favors buying, low usage favors leasing, variable usage favors leasing flexibility. Maintenance requirements: high maintenance favors leasing (often included), low maintenance favors buying, unpredictable repairs favor leasing certainty. Technology obsolescence: fast change favors leasing flexibility, slow change favors buying, frequent upgrades favor leasing. Flexibility and scalability: high flexibility needs favor leasing, low flexibility needs favor buying, scalability important favors leasing.\n\nSTRATEGIC FACTORS: Capital preservation - critical need favors leasing (preserves capital), excess capital favors buying. Balance sheet management - improve ratios favors operating lease, maintain ratios favors buying, debt concerns favor leasing. Accounting treatment - off-balance sheet preferred favors operating lease, on-balance sheet acceptable favors buying. Risk management - transfer risk favors leasing, retain risk acceptable favors buying, obsolescence risk high favors leasing.\n\nINDUSTRY-SPECIFIC: Manufacturing (equipment-intensive, long life, customization) favors buying. Healthcare (rapid technology, regulatory needs, flexibility) favors leasing. Technology (fast obsolescence, frequent upgrades, scalability) favors leasing. Retail (seasonal variations, flexibility, capital constraints) favors leasing.\n\nCASE STUDY - OperationalCorp: $1M manufacturing equipment. Operational: Daily 24/7 use (buying), high maintenance (leasing), slow technology (buying), low flexibility (buying). Strategic: Abundant capital (buying), strong position (buying), capital lease acceptable (buying), low obsolescence risk (buying). Overall: Operational and strategic factors favor buying. Financial analysis showed buying cheaper. Recommendation: Buy equipment.");
    record0.set("video_url", "");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "LESSON_7_ID");
    record1.set("content_body", "LEASE RISKS: Payment obligation risk - fixed $20K/month for 5 years = $1.2M obligation, cannot terminate early. Mitigation: ensure stable cash flows, build reserves, negotiate termination options. Obsolescence risk - equipment becomes outdated, lessor may not upgrade. Mitigation: negotiate upgrade options, include technology refresh clauses. Lessor default risk - lessor may fail financially, loss of equipment access. Mitigation: assess lessor financial strength, diversify lessors. Residual value risk - excess wear charges, unexpected end-of-lease costs. Mitigation: maintain equipment, document condition, negotiate clear terms.\n\nBUY RISKS: Obsolescence risk - equipment becomes outdated, residual value declines. Mitigation: assess technology trends, plan upgrades, maintain equipment. Maintenance risk - unexpected repair costs, equipment downtime. Mitigation: maintain equipment, purchase warranty, build reserves. Residual value risk - residual value lower than expected. Mitigation: conservative assumptions, maintain equipment, monitor market. Financing risk - interest rates increase, refinancing costs increase. Mitigation: lock in fixed rates, assess trends. Operational risk - equipment downtime, operational disruption. Mitigation: maintain equipment, backup equipment, adequate insurance.\n\nRISK COMPARISON: Lease risks (payment obligation, obsolescence, lessor default, residual value) = moderate profile. Buy risks (obsolescence, maintenance, residual value, financing, operational) = higher profile. Risk mitigation: leasing negotiate terms, buying maintain equipment and build reserves, both assess carefully.\n\nCASE STUDY - RiskCorp: $1M manufacturing equipment. Lease risks: payment obligation (medium, mitigate with stable cash flows), obsolescence (low, slow change), lessor default (low, strong lessor), residual value (medium, maintain equipment). Buy risks: obsolescence (low, slow change), maintenance (medium, preventive maintenance), residual value (medium, conservative assumptions), financing (low, fixed rates), operational (medium, preventive maintenance). Overall: Lease and buy risks moderate, risk mitigation important for both.");
    record1.set("video_url", "");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "LESSON_8_ID");
    record2.set("content_body", "COMPREHENSIVE DECISION FRAMEWORK: Step 1 - Gather information (equipment specs, quotes, financing, taxes, operations, strategy). Step 2 - Financial analysis (NPV leasing/buying, cost comparison, break-even, tax analysis). Step 3 - Operational assessment (usage patterns, maintenance, technology, flexibility). Step 4 - Strategic evaluation (capital preservation, balance sheet, accounting, risk). Step 5 - Risk assessment (identify risks, mitigation, tolerance). Step 6 - Decision matrix (score factors, weight importance, calculate total). Step 7 - Decision and implementation (make decision, implement, monitor).\n\nDECISION MATRIX: Factors weighted: Financial 40%, Operational 30%, Strategic 20%, Risk 10%. Each factor scored 1-10. Weighted scores calculated. Total score determines decision. Example: Leasing 8.2, Buying 7.8.\n\nCASE STUDIES: Manufacturing company ($2M heavy machinery, 24/7 use, slow technology, abundant capital) = Buy. Technology company ($500K IT equipment, variable use, fast technology, limited capital) = Lease. Healthcare facility ($1M medical equipment, daily use, moderate technology, moderate capital) = Lease.\n\nDECISION FRAMEWORK CASE STUDY - DecisionFrameworkCorp: $1M equipment. Information: $20K/month lease, 6% financing, 25% tax, daily 24/7 use, slow technology, abundant capital. Financial: NPV buying -$600K vs leasing -$900K, buying $300K cheaper, score buying 9/10, leasing 6/10. Operational: heavy continuous use (buying 8/10), high maintenance (leasing 6/10), slow technology (buying 8/10), low flexibility (buying 8/10). Strategic: capital not critical (buying 7/10), balance sheet not critical (buying 7/10), accounting not critical (buying 7/10), moderate risk (buying 7/10). Risk: moderate for both (buying 7/10, leasing 7/10). Decision matrix: Financial 3.6 vs 2.4, Operational 2.4 vs 1.8, Strategic 1.4 vs 1.4, Risk 0.7 vs 0.7. Total: Buying 8.1, Leasing 6.3. Recommendation: Buy equipment.");
    record2.set("video_url", "");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
