/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_3_1");
    record0.set("content_body", "# Operational and Strategic Factors\n\n## Operational Considerations\n\n**Equipment Usage Patterns**: Assess full-time vs. part-time usage, peak vs. average demand, utilization rates, and flexibility requirements for scaling.\n\n**Maintenance Requirements**: Understand preventive maintenance needs, breakdown risks, warranty coverage, and service availability.\n\n**Technology Obsolescence**: Determine technology lifecycle, upgrade frequency, compatibility issues, and future-proofing needs.\n\n**Flexibility and Scalability**: Plan for growth, downsizing options, upgrade paths, and equipment portability.\n\n## Strategic Considerations\n\n**Capital Preservation**: Preserve cash for strategic investments, maintain working capital, allocate to higher-return projects, and maintain financial flexibility.\n\n**Balance Sheet Management**: Consider asset valuation impact, debt-to-equity ratios, return on assets, and financial reporting implications.\n\n**Accounting Treatment**: Understand operating vs. capital lease classification, expense recognition timing, balance sheet impact, and tax implications.\n\n**Risk Management**: Transfer operational risk to lessor, manage financial risk, protect against market risk, and ensure regulatory compliance.\n\n## Industry-Specific Considerations\n\n**Manufacturing**: Production continuity critical, customization needs, maintenance intensity, and upgrade cycles.\n\n**Healthcare**: Regulatory compliance required, reliability essential, rapid technology advancement, and specialized maintenance.\n\n**Technology**: Rapid obsolescence, frequent upgrades needed, scalability critical, and system compatibility essential.\n\n**Retail**: Seasonal demand fluctuations, flexibility needed, cost sensitivity, and equipment aesthetics important.\n\n## OperationalCorp Case Study\n\n**Profile**: Manufacturing company, $50M revenue, $2M equipment, 85% current utilization, 15% annual growth.\n\n**Assessment**: Growth requires 20% additional capacity. Lease preserves $5M cash for $3M R&D investment. Maintains debt-to-equity at 0.8 vs. 1.1 with purchase. Lease includes maintenance and technology updates.\n\n**Recommendation**: Lease recommended for capital preservation, financial flexibility, maintenance inclusion, capacity adjustment flexibility, and reduced balance sheet impact.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_3_2");
    record1.set("content_body", "# Risk Assessment and Mitigation\n\n## Lease-Related Risks\n\n**Lease Payment Obligation Risk**: Fixed contractual obligations continue even during business downturns. Mitigation: Negotiate flexible terms, include termination clauses, maintain cash reserves.\n\n**Obsolescence Risk**: Equipment may become outdated before lease ends. Mitigation: Negotiate upgrade options, choose shorter terms, include technology refresh clauses.\n\n**Lessor Default Risk**: Lessor may fail to maintain equipment or go bankrupt. Mitigation: Evaluate lessor stability, negotiate SLAs, maintain backup service providers.\n\n**Residual Value Risk**: May be charged for excess wear and tear at lease end. Mitigation: Define normal wear clearly, negotiate charge caps, document initial condition.\n\n## Purchase-Related Risks\n\n**Obsolescence Risk**: Equipment becomes outdated before end of useful life. Mitigation: Conduct technology assessment, choose proven equipment, plan for upgrades.\n\n**Maintenance and Repair Risk**: Unexpected breakdowns disrupt operations and costs increase with age. Mitigation: Implement preventive maintenance, budget for increases, maintain spare parts.\n\n**Residual Value Risk**: Equipment value declines and disposal costs may apply. Mitigation: Research historical values, maintain equipment condition, plan for replacement.\n\n**Financing Risk**: Rising interest rates increase costs and refinancing may not be available. Mitigation: Lock in fixed-rate financing, maintain credit rating, diversify sources.\n\n**Operational Risk**: Equipment failure causes downtime and fixed capacity limits growth. Mitigation: Implement redundancy, maintain backup equipment, plan for expansion.\n\n## Risk Comparison Matrix\n\n| Risk Factor | Lease | Buy | Mitigation |\n|---|---|---|---|\n| Obsolescence | Low | High | Upgrade options, shorter terms |\n| Maintenance | Low | High | Service contracts, preventive maintenance |\n| Flexibility | High | Low | Flexible terms, upgrade clauses |\n| Residual Value | Low | High | Condition maintenance, market research |\n| Lessor Default | Medium | N/A | Financial evaluation, SLAs |\n| Financing | Low | High | Fixed-rate financing |\n\n## RiskCorp Case Study\n\n**Profile**: Technology services company, $30M revenue, $1.5M server equipment, critical for operations.\n\n**Lease Risk Score: 6.5/10** (Medium Risk)\n- Lessor default risk (medium probability, high impact)\n- Obsolescence risk (high probability, medium impact)\n- Residual value risk (medium probability, low impact)\n\n**Buy Risk Score: 7.5/10** (Higher Risk)\n- Obsolescence risk (high probability, high impact)\n- Maintenance risk (medium probability, high impact)\n- Financing risk (medium probability, medium impact)\n- Operational risk (medium probability, medium impact)\n\n**Recommendation**: Lease recommended due to lower risk profile, rapid technology evolution, flexibility needs, reduced operational risk, and predictable costs.");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_3_3");
    record2.set("content_body", "# Decision Framework and Case Studies\n\n## 7-Step Decision Framework\n\n**Step 1 - Gather Information**: Collect equipment details, company financials, market rates, and industry standards.\n\n**Step 2 - Financial Analysis**: Calculate NPV for lease and buy options, compare total costs, analyze sensitivity.\n\n**Step 3 - Operational Assessment**: Evaluate equipment usage, maintenance needs, obsolescence risk, and operational flexibility.\n\n**Step 4 - Strategic Evaluation**: Assess alignment with business strategy, capital priorities, and risk management approach.\n\n**Step 5 - Risk Assessment**: Identify risks, assess probability and impact, develop mitigation strategies.\n\n**Step 6 - Decision Matrix**: Score options on key factors (cost, flexibility, risk, financial impact, strategic fit, implementation).\n\n**Step 7 - Decision and Implementation**: Make final decision, develop implementation plan, establish monitoring metrics.\n\n## Decision Matrix Approach\n\n**Key Factors and Weights**:\n- Total Cost: 25%\n- Operational Flexibility: 20%\n- Risk Profile: 20%\n- Financial Impact: 15%\n- Strategic Alignment: 10%\n- Implementation Ease: 10%\n\n**Scoring Scale**: 5=Excellent, 4=Good, 3=Neutral, 2=Fair, 1=Poor\n\n**Decision Rules**: 4.0-5.0=Strongly recommended, 3.0-3.9=Recommended with conditions, 2.0-2.9=Consider carefully, 1.0-1.9=Not recommended\n\n## Real-World Case Studies\n\n**Manufacturing Company**: $100M revenue, $5M equipment. Lease Score 4.1, Buy Score 2.9. Lease recommended for lower cost, flexibility, better risk profile.\n\n**Technology Company**: $50M revenue, $2M equipment. Lease Score 4.4, Buy Score 2.8. Lease strongly recommended for rapid technology evolution and upgrade needs.\n\n**Healthcare Facility**: $200M revenue, $3M equipment. Lease Score 3.7, Buy Score 3.4. Lease recommended with conditions for comparable costs and regulatory support.\n\n## DecisionFrameworkCorp Case Study\n\n**Profile**: Business services, $75M revenue, $2.5M equipment, 15% annual growth.\n\n**Financial Analysis**: Lease NPV $1.95M vs. Buy NPV $2.42M. Lease saves $470K (19% lower cost).\n\n**Decision Matrix**: Lease Score 4.3/5.0, Buy Score 2.6/5.0.\n\n**Final Decision: LEASE**\n\n**Rationale**: 19% cost savings, greater flexibility for growth, preserves capital for expansion, lower risk profile, supports 15% annual growth.\n\n**Implementation**: Month 1-4 timeline, finance/operations/IT/HR responsibilities, 30-day deployment target, monthly cost tracking, quarterly reviews, annual technology assessment.\n\n**Conclusion**: Lease strongly recommended based on cost savings, operational flexibility, lower risk, strategic alignment, and capital preservation.");
  app.save(record2);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
