/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = app.findCollectionByNameOrId("lesson_content");

  const record0 = new Record(collection);
    record0.set("lesson_id", "lesson_1_id_placeholder");
    record0.set("content_body", "# Risk Identification & Classification\n\n## Credit Risk\nThe risk that a lessee will default on lease payments. Key components include lessee financial stability, payment history, industry conditions, and economic cycles. Mitigation: thorough credit analysis, ongoing monitoring, diversification, and appropriate lease terms.\n\n## Residual Risk\nUncertainty in equipment value at lease end. Affected by obsolescence, technological advancement, market demand, equipment condition, and supply/demand dynamics. Direct impact on lessor profitability and lease pricing.\n\n## Operational Risk\nRisks from day-to-day lease management including equipment maintenance, insurance gaps, documentation issues, fraud, and regulatory risks. Management: comprehensive documentation, inspections, insurance verification, and compliance monitoring.\n\n## Market Risk\nBroader economic and industry factors affecting equipment values and lease demand. Includes interest rates, economic cycles, industry downturns, competition, and regulatory changes. Requires lease pricing adjustments, portfolio diversification, and scenario analysis.\n\n## Risk Classification Framework\nSystematic approach to identify all relevant risks, assess magnitude and probability, prioritize management efforts, allocate resources, and monitor exposure. Essential for successful equipment leasing operations.");
  app.save(record0);

  const record1 = new Record(collection);
    record1.set("lesson_id", "lesson_2_id_placeholder");
    record1.set("content_body", "# Credit Analysis & Tenant Evaluation\n\n## Financial Statement Analysis\nReview balance sheet (assets, liabilities, working capital, debt, equity), income statement (revenue, expenses, profitability), and cash flow statement (operating, capital, financing activities). Calculate key ratios: liquidity (current, quick), profitability (margins, ROA, ROE), leverage (debt-to-equity, interest coverage), and efficiency (asset turnover).\n\n## Credit Scoring\nQuantitative assessment combining: payment history (35%), amounts owed (30%), credit history length (15%), credit mix (10%), and new credit (10%). Provides standardized risk assessment.\n\n## Tenant Creditworthiness\nQualitative factors: management quality, industry position, business model, growth prospects. Quantitative factors: financial metrics, trend analysis, peer comparison, stress testing.\n\n## Debt-to-Income Ratio\nTotal monthly debt payments divided by gross monthly income. Below 36% acceptable, 36-50% elevated risk, above 50% high risk. Critical for assessing payment capacity.\n\n## Industry-Specific Considerations\nManufacturing (capital intensity, cyclicality), Retail (seasonality, e-commerce), Transportation (fuel volatility, regulation), Healthcare (reimbursement, demographics). Each requires tailored analysis.\n\n## Credit Decision Framework\nGather information, analyze data, make decision (approve/conditions/decline), and monitor performance. Systematic approach minimizes credit risk.");
  app.save(record1);

  const record2 = new Record(collection);
    record2.set("lesson_id", "lesson_3_id_placeholder");
    record2.set("content_body", "# Residual Value Risk Management\n\n## Estimation Methods\nMarket-based: research current prices and recent sales. Depreciation-based: apply depreciation curves to initial cost. Regression analysis: develop predictive models from historical data. Expert opinion: consult specialists and validate with market data.\n\n## Obsolescence Types\nTechnological: newer, more efficient equipment available. Functional: equipment no longer meets needs. Economic: industry decline or competitive displacement. Physical: normal wear, corrosion, component failures.\n\n## Mitigation Strategies\nEquipment selection: choose broad-appeal, proven models. Lease term optimization: match to equipment life cycle. Maintenance requirements: comprehensive programs and inspections. Condition monitoring: regular assessments and documentation.\n\n## Market Volatility Factors\nEconomic cycles (recession, recovery), industry trends (consolidation, disruption), supply/demand dynamics, interest rates, and financing conditions all affect residual values.\n\n## Disposition Strategies\nSell in secondary market (auction, dealer, wholesale), lease extension, refurbishment and resale, or salvage/recycling. Strategy depends on market conditions and equipment condition.\n\n## Risk Management Framework\nForecasting: develop residual curves and scenarios. Pricing: incorporate assumptions and risk premiums. Monitoring: track prices, condition, technology. Adjustment: revise estimates and modify terms.");
  app.save(record2);

  const record3 = new Record(collection);
    record3.set("lesson_id", "lesson_4_id_placeholder");
    record3.set("content_body", "# Risk Mitigation Strategies\n\n## Insurance Products\nEquipment insurance: comprehensive or named-peril coverage. Liability insurance: general and equipment-specific. Lessee requirements: minimum coverage, named insured, waiver of subrogation, proof of payment. Enforcement: regular verification and lapse monitoring.\n\n## Guarantee Structures\nPersonal guarantees: individual commitment from business owners, unconditional and absolute. Corporate guarantees: parent company or affiliate guarantees. Enforcement: clear documentation, proper execution, guarantor monitoring.\n\n## Collateral Strategies\nEquipment as collateral: lessor retains ownership, repossession rights. Additional collateral: cash deposits, accounts receivable, inventory, real estate. Management: regular valuation, inspections, maintenance verification, recovery procedures.\n\n## Diversification\nBy lessee: avoid concentration, establish limits. By industry: spread across sectors. By equipment type: balance specialized vs. general. By geography: regional diversification. Measurement and monitoring essential.\n\n## Hedging Techniques\nInterest rate hedging: swaps, caps, floors. Residual value hedging: insurance or securitization. Protects against rate and value changes.\n\n## Lease Structure Optimization\nTerms: duration, payment structure, balloon payments. Covenants: financial (ratios, debt limits), operational (maintenance, insurance), reporting. Monitoring: lessee performance, equipment condition, market trends. Early warning systems for payment delays, financial deterioration, covenant violations.");
  app.save(record3);
}, (app) => {
  // Rollback: record IDs not known, manual cleanup needed
})
